### ISSUE TITLE
Code of Conduct link returns 404

### ISSUE THREAD

**Issue by Kinrany** [reactjs/reactjs.org#1012]
The [Contribution Guidelines](https://github.com/reactjs/reactjs.org/blob/master/CONTRIBUTING.md) have a link to the code of conduct. The link points to [code.facebook.com/codeofconduct](https://code.facebook.com/codeofconduct), which redirects to [code.fb.com/codeofconduct](https://code.fb.com/codeofconduct), which returns 404.

**Comment by alocke12992** [comment]
You're right. Its the same for all of the fbOpensource projects. I submitted a PR with the fix and emailed (couldn't find a repo I could submit a PR to) the Facebook Open Source Team with the details. 

https://github.com/reactjs/reactjs.org/pull/1011

**Comment by gaearon** [comment]
Raised this internally

**Comment by Kinrany** [comment]
Closing this since #1011 has been merged
