### ISSUE TITLE
JSX syntax highlighting is messed up

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#1014]
Noticed this on https://reactjs.org/docs/add-react-to-a-website.html:

<img width="580" alt="screen shot 2018-06-28 at 00 32 51" src="https://user-images.githubusercontent.com/810438/42005126-db8e9cd4-7a6a-11e8-8b2d-c1d084e92289.png">

I don't know why. Help would be appreciated!

**Comment by KhodorAmmar** [comment]
Looks like an issue in `gatsby-remark-prismjs`. Updating it from `1.2.1` to `1.2.24` does the trick

**Comment by gaearon** [comment]
Thank you for fixing this, it was super annoying
