### ISSUE TITLE
Add-ons-page have wrong links

### ISSUE THREAD

**Issue by VinayakBagaria** [reactjs/reactjs.org#1020]
[Addons page](https://reactjs.org/docs/addons.html) - Clicking of link heads redirect to `Page Not Found`. `Open in New Tab` correctly opens the page.

**Comment by gaearon** [comment]
Thanks for reporting. Looks like a bug. Don't know why this happens.

**Comment by zx6658** [comment]
#1023 i had pr to fix this! :)

**Comment by zx6658** [comment]
@gaearon Can you merge this #1023 ? :) My friend who study react said this problem, and i found this issue. I think it has to fix :) thanks!
