### ISSUE TITLE
Ad Blocker crashes the page

### ISSUE THREAD

**Issue by ahmetcetin** [reactjs/reactjs.org#103]
I'm using an ad blocker called "Stands" in Chrome. It was blocking two scripts on the documentation pages, and whole app crashes, no exception handling here I guess. Ironically, I opened the page about Error Boundaries (https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) after googling and it crashed :) Apparently no Error Boundaries on documentations :)

**Comment by bvaughn** [comment]
This issue overlaps with #14 and #9. Could you add this as a comment to those issues? 😄 

Thanks for pointing this out though! We'll get it fixed. I'm going to close this as a duplicate for now.
