### ISSUE TITLE
Mounting to a non empty DOM node

### ISSUE THREAD

**Issue by nojaf** [reactjs/reactjs.org#1040]
I have a question regarding the [hello world](https://reactjs.org/docs/hello-world.html).
If you have 
```jsx
ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);
```

What happens if the `root` element is an `<h1></h1>` with existing content?
Will the first render do a virtual dom diff with the existing dom?
Or will it override the root?

**Comment by gaearon** [comment]
Existing content will be replaced, yes.

There is a second option (`ReactDOM.hydrate`) which you can use if the existing HTML was *also* generated with React from the same tree. This is how server rendering works in React.
