### ISSUE TITLE
Question: Color scheme used for syntax highlighting

### ISSUE THREAD

**Issue by nicholasodonnell** [reactjs/reactjs.org#1044]
This question has been asked [before](https://github.com/reactjs/reactjs.org/issues/279) but it looks like it may have been updated.

What code theme does reactjs.org use for the code snippets? It's beautiful:

![image](https://user-images.githubusercontent.com/1912717/42398810-5c126226-8139-11e8-88d9-34c196b91ef0.png)

**Comment by alexkrolick** [comment]
It's still the same Oceanic Next

**Comment by alexkrolick** [comment]
For VSCode, the "Gatito" theme seems to be a port of the React colors.

**Comment by enzime4u** [comment]
> The colors don't match with Oceanic Next, only Yellow does. If you inspect the DOM you can find the real ones:
> 
> Color Name	RGB	HEX
> Red	rgb(252, 146, 158)	#FC929E
> Orange	rgb(255, 139, 80)	#FF8B50
> Yellow	rgb(250, 200, 99)	#FAC863
> Green	rgb(141, 200, 145)	#8DC891
> Cyan	rgb(136, 198, 190)	#88C6BE
> Blue	rgb(121, 182, 242)	#79B6F2
> Purple	rgb(197, 165, 197)	#C5A5C5
> Background highlight	rgb(53, 59, 69)	#353B45
> Background dark	rgb(40, 44, 52)	#282C34
> Foregraound	rgb(255, 255, 255)	#FFFFFF
> Grey comments	rgb(178, 178, 178)	#B2B2B2
> I like this version much more then Oceanic Next
> 
> Now after some searching in this repo, I found them in [prism-styles.js](https://github.com/reactjs/reactjs.org/blob/master/src/prism-styles.js)
> But you won't find those colors googling, so we can call it React theme : )

By chance did you find some more info's about the color scheme ?

**Comment by tulushev** [comment]
Nope, everyone says it Oceanic Next and closes discussion, even though it isn't.

**Comment by enzime4u** [comment]
hmm....that's weird then.... found React  Ocean Next Extended ...but I don't know what to say...
