### ISSUE TITLE
Tutorial codepen uses ancient React version (0.14.7)

### ISSUE THREAD

**Issue by HartS** [reactjs/reactjs.org#1055]
When going through the tutorial and attempting things out of scope (such as `React.createContext`) I realized that the version used in the tutorial is ~2.5 years old.

The "External Scripts" used in the tutorial can be updated to the following without consequence:

* https://cdnjs.cloudflare.com/ajax/libs/react/16.4.1/umd/react.development.js
* https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.1/umd/react-dom.development.js

`development.js` can be replaced with `production.min.js` in both URLs if preferred, though some users may want to read the source code of the included libraries.

**Comment by gaearon** [comment]
Woah. This is embarrassing. Thanks.

**Comment by gaearon** [comment]
Fixed
