### ISSUE TITLE
Syntax highlighting works incorrectly

### ISSUE THREAD

**Issue by lex111** [reactjs/reactjs.org#1072]
Page - https://reactjs.org/docs/react-component.html

![image](https://user-images.githubusercontent.com/4408379/42952085-57569ec2-8b80-11e8-8b1e-7829c543ce13.png)

**Comment by AndrewBerry** [comment]
It looks like both the `<pre>` and `<code>` blocks are being given the `gatsby-code-jsx` class name. If you remove the inner `<code>` block, the snippet displays correctly.

![Before](https://user-images.githubusercontent.com/2102593/43059257-f806d146-8e8e-11e8-8596-be3e5a341c1c.png)

![After](https://user-images.githubusercontent.com/2102593/43059270-0df3f11e-8e8f-11e8-8a2f-0a2b4faf8de6.png)

**Comment by giraffesyo** [comment]
@lex111 I don't seem to be having this issue. I'm using chrome on os x. What environment do you notice this on so I can try and reproduce it?

**Comment by AndrewBerry** [comment]
Unable to reproduce the issue - seems to have been solved already.
