### ISSUE TITLE
Pdf/epub/mobi version of documentation.

### ISSUE THREAD

**Issue by ravshansbox** [reactjs/reactjs.org#1079]
Just wondering if it is possible to make pdf/epub/mobi version of documentation, so that anyone can benefit from always up to date, open-source book for free.

**Comment by ravshansbox** [comment]
html version if awesome but sometimes it's better to track reading status, better reading experience on smaller screen sizes.

**Comment by ravshansbox** [comment]
I could generate basic epub format from .md files inside repo with no effort but, it may need some beautifying.

**Comment by threepointone** [comment]
The problem with those versions is they go out of sync very easily, so we probably wouldnt do it on this site. You’re welcome to make your own of course. We’ll soon work on making the site accessible offline.
