### ISSUE TITLE
Indentation is messed up in all inline examples

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#1084]
Don't know when this happened but it looks pretty bad.

https://reactjs.org/docs/introducing-jsx.html

<img width="539" alt="screen shot 2018-07-25 at 1 46 02 am" src="https://user-images.githubusercontent.com/810438/43171854-81f65520-8fac-11e8-90e5-9ae00ac5bddf.png">

I see this everywhere. Did we update to a broken version of something?

**Comment by sophiebits** [comment]
To anyone interested: reproing locally and bisecting might be a good way to start debugging this.

**Comment by Widdershin** [comment]
I'll have a look 😄

**Comment by gaearon** [comment]
(See the latest in https://github.com/reactjs/reactjs.org/pull/1086#issuecomment-407597030)

**Comment by killynathan** [comment]
Hi, this is my first attempt at trying to contribute. I am a little confused as to whether this issue is resolved . If it isn't, I would love to take a stab at it.

**Comment by KhodorAmmar** [comment]
Might this be related to the update I did in #1014 ? I don’t remember it caused any issues back then though

**Comment by maddhruv** [comment]
@gaearon seems the issue is resolved now 
can be closed?
