### ISSUE TITLE
running locally on windows 10 gives errors

### ISSUE THREAD

**Issue by killynathan** [reactjs/reactjs.org#1088]
OS: Windows 10
Node: v8.9.4
yarn: v1.7.0

### in terminal:
GraphQL Error Field "path" must not have a selection since type "String" has no subfields.
file: C:/Users/natha/documents/cs/reactjs.org/src/pages/docs/error-decoder.html.js
```
   1 |
   2 |   query ErrorPageMarkdown($slug: String!) {
   3 |     markdownRemark(fields: {slug: {eq: $slug}}) {
   4 |       html
   5 |       fields {
>  6 |         path {
     |              ^
   7 |           id
   8 |         }
   9 |       }
  10 |       frontmatter {
  11 |         title
  12 |       }
  13 |     }
  14 |     errorCodesJson {
  15 |       internal {
  16 |         contentDigest

```

### in browser:
TypeError: Cannot read property 'code' of undefined
new Home
C:/Users/natha/documents/cs/reactjs.org/src/pages/index.js:27
```
  24 | 
  25 | const {data} = props;
  26 | 
> 27 | const code = data.code.edges.reduce((map, {node}) => {
  28 |   map[node.id] = JSON.parse(node.internal.contentDigest);
  29 | 
  30 |   return map;
```

## Steps to reproduce:
git clone https://github.com/reactjs/reactjs.org.git
cd reactjs.org
yarn
yarn dev
open http://localhost:8000 in chrome
<br><br>
edit: don't know if related, but in #1065 I see changes to error-decoder.html.js of `fields { path { id } }`

edit2:
I am assuming everything in the readme works for windows as it doesn't say otherwise. 

Also, when it says "Node: install version 8.4 or greater" in the readme, does that mean 8.x.x? Inside the package.json, I see:
```
"engines": {
    "node": "^8.4.0",
    "yarn": "^1.3.2"
  },
```
what does that mean for my globally installed node and yarn programs? And should the readme be updated to reflect the contents of the package.json?

**Comment by jalmarazg** [comment]
Hi! 
I reproduced your steps and got no errors on console.

I used the following: 
- OS: Windows 10
- Node 8.11.3
- Yarn 1.9.2

Also, to see those "engines" on `package.json` means that, If you have a version lower than `Node 8.4.0` or `Yarn 1.3.2`, it won't work properly or, at some case, won't work at all if you don't have those or major versions installed. 

I attach an image of the console output after running the command `yarn dev`

<div align = "center" >
<img src = "https://user-images.githubusercontent.com/9245962/43373255-1e0490a2-936e-11e8-84b1-7352ae934715.png" />
</div>
Maybe updating to the newest versions of Node and Yarn and re-reproducing the scenario will make it work.

**Comment by hkniyi** [comment]
Also haviing the same issue here but on windows 8 pro

OS: Windows 8 pro
Node: 8.11.3
Yarn:  1.9.2
->yarn versions
![untitled](https://user-images.githubusercontent.com/42308792/44009988-86f0828a-9ea7-11e8-92b9-a4737663653f.png)

->yarn dev
![untitled2](https://user-images.githubusercontent.com/42308792/44010164-c45775a6-9ea8-11e8-9fee-fbde1cfe7a5e.png)

-> IN Browser
![untitled3](https://user-images.githubusercontent.com/42308792/44010303-77dd422c-9ea9-11e8-8d1b-567b7d406ec6.png)

**Comment by gaearon** [comment]
I had something like this a few times. Removing `.cache` directory in the project root, removing `node_modules` and re-running Yarn solved it.

**Comment by AlmeroSteyn** [comment]
Having the same issue as above.

OS: Windows 10
Node: v8.11.2
Yarn: 1.10.1

![image](https://user-images.githubusercontent.com/5063473/46295616-caa03d00-c598-11e8-8655-d696e60e75b7.png)

Deleting `.cache` and `node-modules` did not work.

Did a clean `git clone` from master and then I first had the first error in this issue. After cleaning I got the second again.

**Comment by gaearon** [comment]
Now Netlify builds have the same issue.
I have no idea what it means.

**Comment by th7nder** [comment]
Got the same issue as @killynathan on Linux (Ubuntu 18.04). 
I've had Node 8.10.0, tried removing .cache and node_modules and the same thing happened. 
Then installed NVM, used node lts/carbon (8.12.0), removed .cache and node_modules and it started to work.

**Comment by DSchau** [comment]
Whoa, _fun_. @th7nder the Node 8.10.0 comment was a helpful one. I am able to semi-reliably reproduce the issue now once I'm using that. I'll take a look at this and report back.

**Comment by DSchau** [comment]
Also @th7nder the issue I solved is slightly different than the issue you ran into. If you run into that again, please open a new issue! Thank you!
