### ISSUE TITLE
Missing docs about Transferring Props in JSX

### ISSUE THREAD

**Issue by hellobrian** [reactjs/reactjs.org#109]
*(Originally opened in https://github.com/facebook/react/issues/11124#event-1282129854)*

I noticed that the latest docs don't talk about [Transferring Props in JSX with rest properties](https://github.com/facebook/react/blob/v15.4.0-rc.3/docs/docs/06-transferring-props.md#transferring-with--in-jsx). 

```jsx
/* for example */
render() {
  const { children, ...other } = this.props;
  return <button {...other}>{children}</button>
}
```

☝️ I felt that this was really useful for building reusable react components and an important concept to surface on the main docs. I was curious if omitting this documentation was intentional? If so, it would be great to understand why (maybe this isn't a good practice anymore?). 

Otherwise, I would be happy to send a PR that adds this back into the docs with any changes you and the community want to see. Overall, I just think this is important info to surface in the current docs. 

Thanks!

**Comment by bvaughn** [comment]
On the [JSX in Depth](https://reactjs.org/docs/jsx-in-depth.html) section of the docs there's a header called [Spread Attributes](https://reactjs.org/docs/jsx-in-depth.html#spread-attributes). It isn't _exactly_ what you mention since it doesn't plug `children` out.

Would you be interested in submitting a PR that adds an additional example to this section?

**Comment by hellobrian** [comment]
Yes, I can send a PR - thanks for the quick response!

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!
