### ISSUE TITLE
Advanced guides order is confusing

### ISSUE THREAD

**Issue by dwfg** [reactjs/reactjs.org#1094]
Why put "forwarding refs" before "refs and dom", also why put topics like context and code-splitting before  more basic topic like "JSX in depth" etc. the ordering is confusing.

**Comment by st-sloth** [comment]
I agree. It's ordered alphabetically and it's understandable for the maintenance reasons, like adding new topics without breaking numeration (if introduced like in the "Main concepts"), but reading it in the current order is frustrating, when the "previous" topics build up on the "next" ones and the reader ends up with stopping reading one topic and navigating to another and then getting back to first one.

**Comment by gaearon** [comment]
I changed Advanced to be alphabetic intentionally at some point to make it clear there’s no particular progression (unlike the Main Concepts). So while this might be annoying in some cases, I hope this makes it more obvious you don’t *have to* read all advanced guides, and instead consult them as you need them.
