### ISSUE TITLE
Please update documentation of componentWillReceiveProps and UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by hajdun** [reactjs/reactjs.org#1116]
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

Documentation did not help me get rid of componentWillReceiveProps/UNSAFE_componentWillReceiveProps

There is a way more easy way to stop using  componentWillReceiveProps/UNSAFE_componentWillReceiveProps than written in docs.

Steps:
Add a nice, unique key to the component which used to receive props.
The key must contain data which supposed to change props (preferably ids)
<ComponentToReceiveProps
key={thing id  that this component depends on + other thing id that this component depends on }
{...props} />

Replace componentWillReceiveProps with componentDidMount in ComponentToReceiveProps.

Use props in ComponentToReceiveProps.

I hope this will help others too.

**Comment by gaearon** [comment]
This part of the section refers to exactly that approach:

> or fully uncontrolled with a key instead.

**Comment by hajdun** [comment]
I think that part could be explained better with some example.

**Comment by gaearon** [comment]
It links to an example.

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key
