### ISSUE TITLE
componentWillReceiveProps to getDerivedStateFromProps

### ISSUE THREAD

**Issue by Statfine** [reactjs/reactjs.org#1119]
if props is not in state, and props is identification marks for certain methods，
```
componentWillReceiveProps(nextProps) {
    if (nextProps.flag !== this.props.flag && nextProps.flag) {
      this.doSomething()
    }
  }
```
what should i do after used getDerivedStateFromProps

**Comment by gaearon** [comment]
>flag is not in state, so i can not used componentDidUpdate to do this.

You can:

```js
componentDidUpdate(prevProps) {
  if (prevProps.flag !== this.props.flag && nextProps.flag) {
    this.doSomething();
  }
}
```

`componentDidUpdate` accepts both `prevProps` and `prevState` as arguments, [as documented](https://reactjs.org/docs/react-component.html#componentdidupdate).

You don't need `getDerivedStateFromProps` for this.

**Comment by Statfine** [comment]
@gaearon    flag is only identification marks，Render action will not be triggered， componentDidUpdate executed？？？

**Comment by gaearon** [comment]
React always calls `componentDidUpdate` unless you bailed out with `shouldComponentUpdate`.

**Comment by Statfine** [comment]
@gaearon  you may not understand what i mean,  flag???
```
import React, { PureComponent } from 'react';
import PropType from 'prop-types';

export default class ExamplePage extends PureComponent {
  componentDidUpdate(prevProps) {
    if (prevProps.flag && this.props.flag !== prevProps.flag) {
      this.handleDoSomething();
    }
  }
  handleDoSomething = () => {
    console.log('handleDoSomething');
  };
  render() {
    const { title } = this.props;
    return (
      <div>
        <p>{title}</p>
      </div>
    );
  }
}

ExamplePage.propTypes = {
  title: PropType.string.isRequired,
  flag: PropType.bool.isRequired,
};
```

**Comment by gaearon** [comment]
I don’t understand your problem. Does this code not work?

**Comment by gaearon** [comment]
Sorry. Please provide an example I can run — I don't understand your problem.

**Comment by Statfine** [comment]
Parent
```
import React from 'react';

import ExamplePage from './ExamplePage';

/* eslint-disable react/prefer-stateless-function */
export class NewPage extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      flag: false,
      title: 'Hello',
    };
  }
  handleClick = () => this.setState({ flag: true });
  render() {
    const { title, flag } = this.state;
    return (
      <div>
        <p onClick={this.handleClick}>Btn</p>
        <ExamplePage flag={flag} title={title} />
      </div>
    );
  }
}

export default NewPage;

```

ExamplePage
```
import React, { PureComponent } from 'react';
import PropType from 'prop-types';

export default class ExamplePage extends PureComponent {
  componentDidUpdate(prevProps) {
    if (prevProps.flag && this.props.flag !== prevProps.flag) {
      this.handleDoSomething();
    }
  }
  handleDoSomething = () => {
    console.log('handleDoSomething');
  };
  render() {
    const { title } = this.props;
    return (
      <div>
        <p>{title}</p>
      </div>
    );
  }
}

ExamplePage.propTypes = {
  title: PropType.string.isRequired,
  flag: PropType.bool.isRequired,
};

```

click Btn change flag,  title not change, so componentDidUpdate executed?
in old version 
```
componentWillReceiveProps(nextProps) {
    if (nextProps.flag !== this.props.flag && nextProps.flag) {
      this.doSomething()
    }
  }
```

**Comment by AliasT** [comment]
@Statfine , may be your problem is:

_Why the child component rerender when parent's state: flag changes, although flag not used in child's render ?_

If so, then the reason is:
when parent rerendered, the process comes to child's shouldComponentUpdate, after the internal `shallowEqual` it gets  true, so rerender, different from Vue's dependencies collection (or mobx?)

That's why we need `shouldComponentUpdate` to optimize our component.

[shallowEqual](https://github.com/facebook/react/blob/b179bae0ae3a9d80bfbe440c8861786b7f928ce1/packages/shared/shallowEqual.js)
[shouldComponentUpdate](https://github.com/facebook/react/blob/b179bae0ae3a9d80bfbe440c8861786b7f928ce1/packages/react-reconciler/src/ReactFiberClassComponent.js#L259)

**Comment by Statfine** [comment]
Thanks， It's my understanding mistake

**Comment by Statfine** [comment]
@AliasT  Thanks,you are right
