### ISSUE TITLE
React-loadable is not FOSS anymore, add a warning?

### ISSUE THREAD

**Issue by tajo** [reactjs/reactjs.org#1146]
React-loadable recently changed its license to blacklist a number of companies. It should probably not be referenced as a go to solution for code splitting. Or there should be an additional warning that the library is not free software.

- [the license](https://github.com/jamiebuilds/react-loadable/blob/master/LICENSE)
- [referenced here](https://github.com/reactjs/reactjs.org/blob/623523131e11a9c08ce01130e612f366d58b5ea1/content/docs/code-splitting.md#libraries)

**Comment by chrisbateman** [comment]
Also, react-loadable doesn't support webpack 4. Might be worth switching to [loadable-components](https://www.npmjs.com/package/loadable-components) for now.

**Comment by gaearon** [comment]
Hmm, we use webpack 4 in CRA@next I think. Happy to take a PR if it's roughly equivalent in functionality.

**Comment by sebmarkbage** [comment]
We’re switch to the React.lazy built in for suspense support regardless. 
https://github.com/facebook/react/pull/13398

**Comment by benweier** [comment]
I consider Jamie Kyle's actions (not just in relation to the recent license changes) to be openly hostile - [disrespectful](https://github.com/palantir/tslint/issues/4132), [absusive](https://github.com/Microsoft/web-build-tools/issues/673#issuecomment-394784311), and [toxic](https://github.com/palantir/tslint/issues/4141) - towards the community. Directly violating the Facebook Open Source [Code of Conduct](https://code.fb.com/codeofconduct/) and ignoring the Open Source Initiative's own guidelines on [restricting use](https://opensource.org/faq#restrict) and ["evil people"](https://opensource.org/faq#evil).

I believe Jamie Kyle is not deserving of having his work mentioned on the React website or featured in any official React community engagement including dependencies, tweets, articles, conference talks, or GitHub issues/pull requests/comments. He is not interested in responsible open source participation and appears to be using his position as contributor/maintainer to further his personal opinions and political agendas at the cost of other entities' freedoms that are expressly permitted.
