### ISSUE TITLE
Guide to install via NPM

### ISSUE THREAD

**Issue by ViggoV** [reactjs/reactjs.org#1152]
Your installation guide seems to completely forget installation through npm. Last time I did it it was something like `npm install react-dom` and the time before that it was just `npm install react`. Since installation methods often change between versions I find it is always a good idea to check the official homepage for the newest way to install. Your page however gives the impression that you can't install with npm (which is untrue) or that it is strongly discouraged.

In fact, the section called Installation doesn't have a single mention of the word *install* except for the title.. 
https://reactjs.org/docs/getting-started.html

**Comment by moumen-soliman** [comment]
It's already here https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

**Comment by ViggoV** [comment]
So is the only recommended way of using React through `create-react-app`? I very much prefer to install my dependencies manually with as little magic as possible..

**Comment by benlaverriere** [comment]
@ViggoV Does [this section](https://reactjs.org/docs/create-a-new-react-app.html#creating-a-toolchain-from-scratch) in that document, particularly [this linked article](https://blog.usejournal.com/creating-a-react-app-from-scratch-f3c693b84658), give the kind of guidance you're thinking of?

**Comment by ViggoV** [comment]
Yes, I guess that about covers it. Thank you!

**Comment by benlaverriere** [comment]
Great! All set to close this issue then?

**Comment by ViggoV** [comment]
Yes :)
