### ISSUE TITLE
Change text color of numbers from white to black in tic-tac-toe game

### ISSUE THREAD

**Issue by ags1773** [reactjs/reactjs.org#1165]
https://reactjs.org/tutorial/tutorial.html#passing-data-through-props
I'm doing the react tutorial in my IDE and came across this issue
- In the assignment 'Passing Data Through Props', the text color of the numbers in the 'Square' component is white
- The numbers get camouflaged with the white background. People following the tutorial might get confused and think that no data is being passed to the component

**Comment by welkin25** [comment]
The background for the code snippets is dark grey, so white text is readable, is that not what you're seeing?

**Comment by welkin25** [comment]
are you saying the text color on the 9 buttons when rendered is white? It should be black and should look like the linked image https://reactjs.org/static/tictac-numbers-685df774da6da48f451356f33f4be8b2-be875.png .

If you're talking about the text in code snippets, code snippets' background is dark grey so white text should be readable.

**Comment by ags1773** [comment]
The text colour of the 9 buttons was white. I added "color: black" to the .square css rule and it worked as shown in the image https://reactjs.org/static/tictac-numbers-685df774da6da48f451356f33f4be8b2-be875.png

**Comment by welkin25** [comment]
That's odd, I copied css from https://codepen.io/gaearon/pen/oWWQNa?editors=0100 and color should default to black (since it's unspecified). What browser do you see it white in? Have you tried a different browser?

**Comment by ags1773** [comment]
Odd indeed. It works correctly in chrome. But in Firefox, it sets the color rgba(255,255,255,0.8)
 using the browser's stylesheet
![tic-tac-toe](https://user-images.githubusercontent.com/27222520/45404613-3f104c00-b67d-11e8-8319-7473148b7170.png)

**Comment by welkin25** [comment]
That shouldn't be the default for Firefox. Did you perhaps edit the Firefox default css settings or used an extension to that effect?

**Comment by ags1773** [comment]
You're correct. It was because of a custom theme I was using for my OS. Works as expected on changing back to the default theme.
I should have researched more before opening the issue, sorry for the inconvenience
