### ISSUE TITLE
docs: remove .bind() in favor of arrow functions w/ implicit bind

### ISSUE THREAD

**Issue by iamclaytonray** [reactjs/reactjs.org#1167]
We could eliminate a lot of verbose code in the docs by removing the `.bind()` calls and replace them with arrow functions, which would implicitly bind. This would probably only take me about 30 minutes to do. 

Also, would you guys consider removing the constructor where it's not really needed? For example, when adding state to a component, could we just take the state out of the constructor and add it as an instance field on the class? 

I'll submit a PR if this is approved

**Comment by gaearon** [comment]
By "arrow functions" you probably mean the class properties transform. It's not standardized yet. We generally avoid using experimental transforms in the docs, even though we widely use them in practice.

**Comment by iamclaytonray** [comment]
Ahh, okay. That makes sense. I'll go ahead and close the issue and the reopen it when both of those land in the spec. Thanks!
