### ISSUE TITLE
Add PrimeReact to the Communty UI Components Page

### ISSUE THREAD

**Issue by cagataycivici** [reactjs/reactjs.org#1179]
I'd appreciate if you could consider adding PrimeReact UI Suite to;

https://reactjs.org/community/ui-components.html

PrimeReact: A rich UI component suite for React featuring 70+ open source components.

https://www.primefaces.org/primereact/

Thank you.

**Comment by Niladri24dutta** [comment]
@cagataycivici add Primereact to the list through PR #1240 . Not sure if it's going to be approved or not.

**Comment by cagataycivici** [comment]
Awesome, thank you.

**Comment by alexkrolick** [comment]
Would you also want to link to the Pro option in the paid components section?

**Comment by cagataycivici** [comment]
PrimeReact is fully open source, there is no paid PRO version with extra features. PrimeReact PRO is simply an optional support service for the library.

**Comment by Niladri24dutta** [comment]
@cagataycivici  I have sorted the list alphabetically
