### ISSUE TITLE
React Js - How to update default text for upload button

### ISSUE THREAD

**Issue by sanketphating** [reactjs/reactjs.org#1192]
![upload button](https://user-images.githubusercontent.com/43408012/45749912-764aa400-bc0d-11e8-9380-55c8a870a943.PNG)

Hello,

I am new to react js can you please guide how to change the default text of upload button.

Here is my code - 

class App extends Component {

  constructor(props) {
    super(props);
    this.state = { value: '' };
    this.handleChange = this.handleChange.bind(this);

  }

  handleChange(event) {
    this.setState({ value: event.target.value });
  }

  render() {
    return (
      <div className="App">
        
        <p className="App-intro">
          <input type='file' 
            id='contactFile'
            multiple='multiple'
            value={this.state.value} onChange={this.handleChange}
          />
         
        </p>
      </div>
    );
  }
}

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bugs in the documentation.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
