### ISSUE TITLE
Usage of componentWillReceiveProps

### ISSUE THREAD

**Issue by lahsivjar** [reactjs/reactjs.org#1193]
I have the following use case:

A react component that takes a list of subscriptions as props and subscribes to these. Whenever the props change (which is seldom) the component checks the current subscriptions with the new ones and does one of the following:

1. If a new subscription is found subscribes to it
2. If an already subscribed topic is not present in the new list unsubscribes from it

Thus, there is only one source of truth.

Current implementation of this is done via `componentWillReceiveProps`.

I was wondering if there is a more proper way of handling it. Any suggestions are welcome.

**Comment by gaearon** [comment]
`componentDidUpdate` is the place to do it.
