### ISSUE TITLE
Name of the first argument of the setState() updater function

### ISSUE THREAD

**Issue by alanyin0322** [reactjs/reactjs.org#1195]
Prior to React 16.4, the first argument is named `prevState` to indicate that we cannot rely on this.state to calculate the property values of the next state.
<img width="951" alt="screen shot 2018-09-21 at 12 17 37 pm" src="https://user-images.githubusercontent.com/25688258/45856894-c7879e80-bd99-11e8-95ef-d4471f81e440.png">

However I realised that from React 16.4 onwards, the name has been changed to `state`. 
<img width="969" alt="screen shot 2018-09-21 at 12 18 09 pm" src="https://user-images.githubusercontent.com/25688258/45859550-47b40100-bda6-11e8-8e3f-96e618451075.png">

I understand that those names are just conventions and you can call them whatever you want. However  I thought the reason to name it `prevState` was not to get confused with `this.state`. I would suggest changing the name from `state` to `curState` to reflect the fact that it's the state at the time setState() gets called.

**Comment by gaearon** [comment]
We've gone back and forth on this a few times. I don't think `curState` is more clear than `state` in this case. You need to understand what it means either way. I see where you're coming from but I think the current name is the best we can do.
