### ISSUE TITLE
Add componentDidCatch to React.Component page

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#120]
Add `componentDidCatch` to https://reactjs.org/docs/react-component.html and link to https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html for a more complete explanation.

**Comment by thomasyimgit** [comment]
Can I try this? I really love this newly brought feature in React16! :)

**Comment by bvaughn** [comment]
Sure! This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by thomasyimgit** [comment]
@bvaughn Hi, thanks for giving me this opportunity. I've added all the necessary document. But right now I'm having a problem on referencing that blog post in the document markdown. Could you please help me with that?

This is how I tried but it redirects to the bottom of the new page.

```
For more details, check [*Error Handling in React 16*](../blog/2017/07/26/error-handling-in-react-16.html).
```

**Comment by bvaughn** [comment]
You should be able to link to `/blog/2017/07/26/error-handling-in-react-16.html` (no leading "../")

**Comment by thomasyimgit** [comment]
Thanks Brian. :smile:

**Comment by bvaughn** [comment]
Closed via #136 
Thanks!

**Comment by merlinpatt** [comment]
I would like to see this expanded to include better docs about info. Came here through a trail from [facebook/react#10461 - decompose info parameter](https://github.com/facebook/react/issues/10461).

I would do it but the only part I am aware of is `componentStack`. Are there more keys?

**Comment by bvaughn** [comment]
`componentStack` is the only current key.

This is mentioned here:
https://reactjs.org/docs/error-boundaries.html#componentdidcatch-parameters

But yea, we should either cross-link or expand in the Component API page too.

**Comment by merlinpatt** [comment]
What future keys do you plan to add to info?

**Comment by bvaughn** [comment]
No plans / unknown
