### ISSUE TITLE
Newbie question. Are React props MEANT to be dynamic or only used at initialization?

### ISSUE THREAD

**Issue by JoeCodeswell** [reactjs/reactjs.org#1213]
Hi folks. I am just coming up to speed with React. So I have a newbie question.

For a child component, are its props MEANT to be dynamic or only used at its initialization?

Should i be  using a child's **state** or **props** to change what it is showing  from say, a button in the parent, i.e. dynamically?

Please answer in class / es6 / create-react-app terms only, since this is my NEWBIE frame of reference.

Thanks in advance.

Love and peace,
Joe

**Comment by gaearon** [comment]
1. Each component receives props from a parent. Props can change over time. For example if parent re-renders, then child receives new props from it. So yes, props are "dynamic" in this sense.

2. Each component is only allowed to change *it own* state. For example, a parent should never try to modify child's state, or vice versa.

3. Components can't change their own props.

4. So how can a child affect what parent is rendering? Parent can pass a callback to the child. The child can call it when it wants to. And in the callback implementation (which lives in the parent), the parent can set its own state. That re-renders both parent and child.

Relevant:

* https://reactjs.org/docs/lifting-state-up.html
* https://reactjs.org/tutorial/tutorial.html#lifting-state-up
* https://reactjs.org/docs/thinking-in-react.html

**Comment by JoeCodeswell** [comment]
Thanks Dan. I will meditate on all this.

:)

Love and peace,

Joe

**Comment by gaearon** [comment]
If this analogy makes sense, you can think of props like function arguments, and state as variables.

**Comment by JoeCodeswell** [comment]
Hi Dan,

Thanks for the analogy.

I hope you will add your words to the React docs. They are really helping
me. I suggest you use them to enhance the
section [A Brief Interlude: Props vs State ](
https://reactjs.org/docs/thinking-in-react.html#a-brief-interlude-props-vs-state
)

I have been thinking about this subject while working on a create-react-app
App that manipulates a Google map.

For this app, sometimes i am a  React Component Creator but mostly i am a
component Consumer.

With regard to your analogy, i am having a bit of trouble squaring the
React docs i have read with who, Component (Creator or Consumer) is in
charge of defining Props == arguments/parameters.

Here is a link to a post by Cuneyt Aliustaoglu that has inspired and
informed me. My relevant question/comment is at the bottom of the post.

[ Using Google Maps in React without custom libraries ](
http://cuneyt.aliustaoglu.biz/en/using-google-maps-in-react-without-custom-libraries/
)

Thanks again, Dan.

Love and peace,
Joe
