### ISSUE TITLE
Is this a situation that need to use getDerivedStateFromProps

### ISSUE THREAD

**Issue by jithender4ever** [reactjs/reactjs.org#1261]
Read the docs https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html and I want to clarify if my situation falls outside the recommended solutions. 

**Goal:** Display a list of filter options ('group 1', 'group 2', 'group 3', etc...) with checkboxes, and when the selections are changed, refresh the list of items displayed to only include the items that belong to the selected groups.
The list of groups is not static and varies by logged on user and is retrieved thru an API.

**Current Implementation:**
I have a container component that interacts with redux middleware and gets the list of groups (as props) from an api call. 
I have in my local state a list of groups set to an empty array - 'groupFilters'.

API call is being made (type - REQUEST) in componentDidMount() and when the response is received, the state change is handled in componentWillReceiveProps(). When the nextProps are not same as current props, I am updating the state by pushing all the groups that I got back from API response to the groups array in my local state. **Reason for local state is that, API response is [{id: 1, group: 'abc'}, {id: 2, group: 'xyz'}, etc ]. But what is displayed as filter options is just group name.

When user changes the filter options, I am handling the change by updating 'selectedGroups' list which is also in my local state. I am using selectedGroups and groupFilters to reconcile and display the checkboxes as checked or `unchecked.`

**Code:**

`

export class MyContainerComponent extends Component {
    state ={
        selectedGroups: [],
        groupFilters: [],
    }

    componentDidMount () {

        const { getGroups } = this.props;

        getGroups(**someparams**); //API call - Redux Action Creator
    }

    componentWillReceiveProps (nextProps) {

        if (nextProps === this.props) return;

        const { data } = nextProps;

        // filter options should only display group names
        filter(data, (item) => options.push(item.groupName));

        this.setState({
            groupFilters: options,
            selectedGroups: options
        });
    }

    handleGroupSelect = groupName => (event, checked) => {
        let selectedGroups = [...this.state.selectedGroups];

        if (checked) {
            selectedGroups = groupName === 'All Groups' ? this.state.groupFilters : selectedGroups.concat(groupName);
        } else {
            if (groupName === 'All Groups') {
                selectedGroups = [];
            } else {
                if(indexOf(selectedGroups, 'All Groups') > -1) {
                    selectedGroups.splice(indexOf(selectedGroups, 'All Groups'), 1);
                }

                if (indexOf(selectedGroups, groupName > -1)) {
                    selectedGroups.splice(indexOf(selectedGroups, groupName), 1);
                }
            }
        }

        this.setState({ selectedGroups });
    }

    render () {
        const { isFetching } = this.props;

        return (
            <div>
                { !isFetching &&
                <MyDisplayComponent
                    groupFilters={ this.state.groupFilters }
                    onGroupSelect={ this.handleGroupSelect }
                    selectedGroups={ this.state.selectedGroups }
                /> }
            </div>
        );
    }
}

const mapStateToProps = ({ api: { userGroups = [] } }) => {
  const { data = [], isFetching = true } = userGroups;

  return { data, isFetching };
};

export default connect(mapStateToProps, Actions)(MyContainerComponent);

`

**Question about Proposed Change:** Can I change this implementation to use getDerivedStateFromProps and componentDidUpdate methods instead? I maybe missing some things here, but memoization and controlled/uncontrolled component options doesn't seem to solve the cases where the props are not being passed from a parent component and are instead received thru redux mapDispatchToProps calls.

Please let me know your thoughts.

**Comment by alexkrolick** [comment]
A good rule of thumb is that if the derived state is a pure function of props and not a mix of the previous state and props, you probably don't need derived state. Instead you can:

- Compute derived values (like transforming data from one shape to another) in `render`. If this is expensive and you need to store old values you might consider using a memoization library like `lodash.memoize` or `memoizeOne` instead of using React state.
- Do the work in the parent component or Redux store. Libraries like `reselect` help with this.

**Comment by alexkrolick** [comment]
> I maybe missing some things here, but memoization and controlled/uncontrolled component options doesn't seem to solve the cases where the props are not being passed from a parent component and are instead received thru redux mapDispatchToProps calls.

In your case the "parent component" is the component created by the Redux `connect` function which transforms Redux state into props for your component. You can use the `mapStateToProps` option to transform the Redux state shape into something else if you need to.: https://redux.js.org/basics/usagewithreact#implementing-container-components
