### ISSUE TITLE
Create guide to create NPM libraries with the REACTJS CLI

### ISSUE THREAD

**Issue by jsnavarroc** [reactjs/reactjs.org#1262]
To help the community to continio generating reusable libraries and make development more agile, I recommend creating a guide that allows to understand how to create NPM libraries using the ReactJS create-react-app (CLI).

**Comment by alexkrolick** [comment]
What is the ReactJS CLI?

**Comment by cijleaf** [comment]
A command line interface tool that seeks to automate some tasks when working on a React.js project.

**Comment by cijleaf** [comment]
Install the react command line tool globally so you can use it from any project directory.

$ npm install -g madebyform/react-cli

**Comment by threepointone** [comment]
Closing since this isn’t relevant as an issue
