### ISSUE TITLE
React.lazy not in documentation 

### ISSUE THREAD

**Issue by karina001** [reactjs/reactjs.org#1275]
We filed [this issue](https://github.com/facebook/react/issues/13907) earlier today and during our investigation, we @rbaheti @sandraattar also found that there is no documentation for React.lazy, although it seems to be referenced as a top-level API.

**Comment by karina001** [comment]
Just found this in the logs, perhaps this could be enough documentation for now, should I submit a pull request? 
![screen shot 2018-10-20 at 2 54 58 pm](https://user-images.githubusercontent.com/29686029/47259519-61fdff00-d478-11e8-954f-57c00bd46685.png)

**Comment by gaearon** [comment]
Master is unstable and contains unreleased features. Please don't expect anything in master to be documented until there is a stable release.
