### ISSUE TITLE
Can a decorator be suggested for method binding instead of arrow functions?

### ISSUE THREAD

**Issue by mbrowne** [reactjs/reactjs.org#1276]
The docs currently mention the use of arrow functions to create bound methods, with a disclaimer that the class properties proposal is not fully standard yet, e.g. https://reactjs.org/docs/handling-events.html.

Unfortunately, using arrow functions for this can have some pretty bad side effects, as described here: https://github.com/mbrowne/bound-decorator/blob/master/MOTIVATION.md.

One of the most salient points for React users is that arrow functions don't play well with some testing tools such as Enzyme.

Could the docs also mention decorators as an alternative solution? I realize that the [decorators proposal](https://github.com/tc39/proposal-decorators) is still in stage 2, but it seems certain at this point that the basic syntax of `@decoratorName` is not going to change, and if there are further changes to the proposal, that would only affect the implementation of the decorator itself, not components that use it. There should of course be a disclaimer that decorators are not yet standard, just like the disclaimer for class properties.

There are good open-source implementations already available, making it easy to use decorators for this purpose. I actually just published a `@bound` decorator compatible with the current decorators proposal implemented in Babel 7:
https://github.com/mbrowne/bound-decorator

And there are existing implementations that work with the legacy decorators proposal as well, meaning this is also an easy and viable option for Babel 6 and TypeScript users, for example:
- https://github.com/brigand/class-bind
- https://github.com/andreypopp/autobind-decorator

In the interest of preventing subtle and confusing bugs, including unexpected issues with Enzyme, I think it would be very helpful for the official docs to suggest decorators as an option.

**Comment by threepointone** [comment]
We wouldn’t recommend unstable proposals in these docs. Closing for now, happy to revisit in the future when they’re shipped.
