### ISSUE TITLE
Preprocessing props with React 16.3+

### ISSUE THREAD

**Issue by pycbouh** [reactjs/reactjs.org#1279]
After reading up on https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html I am left wondering about our most used case for `componentWill*` lifecycle methods. Migration paths mentioned in the article focus entirely on two things: deriving state and causing outer things to happen (async actions, logging, etc). However, we use these methods a lot to preprocess props before rendering a component.

You see, we don't use state for everything. It seems to us, that the state is something that can and is allowed to be changed inside a component. But there are times when you need to store things inside this component that are dependent on props and must not be changed within it.

Say, you have an array of data, and it can be non-uniform data. Maybe something like this:
```javascript
[
  { "type": "flight", "data": { "flightId": "AZ1234", ... } },
  { "type": "stopover", "data": { "stopoverTime": "02:30", ... } },
  { "type": "flight", "data": { ... } },
  ...
]
```
And you want to render this data using different child components, plus maybe prepare some of it beforehand (calculate conditional booleans, format strings, add translations, etc).

Now, you can do all this while in render, but why do it each time if it only depends on props changing? You can also do this preprocessing in a parent component, but most of the time it's the inner logic of the component, not something that a parent should know about. Obvious solution for us was to react on props changing and store the precalculated results in an inner variable of the component class. Turns out, this is not a supported case anymore.

We couldn't work around the new design with the new hooks as well, because `getDerivedStateFromProps` is static and `getSnapshotBeforeUpdate` is probably called too late to change something for the current render. Plus, using them for this would mean that these functions would have unexpected side effects, which is bad.

I guess, HoC is a solution? But I'd rather have the ability to update class properties in between new props and rendering to reduce complexity of hierarchy, at least in some cases. Will it never be possible?

**Comment by alexkrolick** [comment]
It sounds like you are manually memoizing a function of prop values and storing the result on the component instance.

One way to adapt to the new lifecycles would be to extract that code into a separate function, and use a memoization util like https://github.com/alexreardon/memoize-one:

```js
const processResult = memoize(function(x, y) {
   // do something
  return result
})

class MyComp extends React.Component {
  render() {
    const result = processResult(this.props.x, this.props.y)
    return <div>{result}</div>
  }
}
```

**Comment by pycbouh** [comment]
Well, memoization needs to compare inputs on each call, while previously we only acted upon known changes to props via lifecycle hooks. It was simpler and cheaper.

In that case, I actually prefer logic-only HoCs for preprocessing data, as they should not update unless props are believed to be changed. This would mean, however, the need to extend component's interface to a HoC (proptypes, public functions, etc). Shame, we can no longer track prop changes.
