### ISSUE TITLE
React.memo and render prop pattern

### ISSUE THREAD

**Issue by brneto** [reactjs/reactjs.org#1289]
How to use `React.memo` in a render prop pattern? Is it possible? I've noted that HOC, so I suppose it returns some kind of object literal.

Is It right to think that if I want to use render prop pattern I can't use `React.memo`?

**Comment by gaearon** [comment]
Can you be more specific? It's not quite clear what you're asking. An example of what you're trying to do would help.

**Comment by brneto** [comment]
For example:
```
//app.js
<AddTodo render={AddTodoForm} />

//AddTodo.js
class AddTodo extends React.Component {
  static propTypes = {
    render: PropTypes.func.isRequired
  };

  render() {
    const formProps = {
      input: {
        value: this.state.todo,
        onChange: this.handleChange,
        onKeyDown: this.handleNewTodoKeyDown
      }
    };
    return this.props.render(formProps);
  }
}

//AddTodoForm.js
const AddTodoForm = ({ input }) => (
  <header>
    <Title>todos</Title>
    <Input placeholder="What needs to be done?" {...input} />
  </header>
);

AddTodoForm.propTypes = {
  input: PropTypes.object.isRequired
};

export default React.memo(AddTodoForm);
```

**Comment by gaearon** [comment]
No, this won't work. `memo` returns a *component*. You shouldn't assume that you can always call a component as a function.
