### ISSUE TITLE
Ensure Algolia attribution is present on search dropdown

### ISSUE THREAD

**Issue by phrawzty** [reactjs/reactjs.org#130]
Hello!

Just wanted to pop in to mention that the Algolia logo in the search dropdown doesn't appear to be visible in Firefox (oddly enough). Screenshot time!

Firefox 56 (OS X): 
![image](https://user-images.githubusercontent.com/625232/31432857-f8764b22-ae77-11e7-9004-a5019fdb944f.png)

Check that bottom right corner...

Chrome 61 (OS X):
![image](https://user-images.githubusercontent.com/625232/31432887-12f06546-ae78-11e7-9943-c62be25c4ebb.png)

I see that our very own @Haroenv touched this topic in https://github.com/facebook/react/pull/11032. Could be a good place to start looking?

For the sake of completeness, I've also looped in @vjeux via email, which isn't a GitHub Issue but oh well! 😉

**Comment by Haroenv** [comment]
Whoops, I didn't test it in FF, it works in Safari though 😃

**Comment by renatoselenica** [comment]
I am doing some tests on this and it looks like its an svg issue on how firefox detects the svg passed as background img. I am trying to figure it out but do not know enough about svg.

**Comment by Haroenv** [comment]
@renatoselenica, oh good catch! I think we forgot to encode the hash

**Comment by phrawzty** [comment]
Fantastic - thanks everybody!
