### ISSUE TITLE
Cannot write html inside html

### ISSUE THREAD

**Issue by DhakerShiv** [reactjs/reactjs.org#1343]
Hi Team,
I am very new to react, I am just astonished by the fact that I cannot add Html which I receive as text form from the server in JSON(I mean it is not rendered), I googled it and it says we have to use some frameworks like **react-html-parser**, also we can use a property named as **dangerouslySetInnerHTML**. I think react is having some inbuilt support for same otherwise it is very strange to add HTML inside HTML. Let me know if I am missing something here.

**Comment by alexkrolick** [comment]
`dangerouslySetInnerHTML` is the "built-in" support. It's called that because injecting unsanitized HTML can potentially execute untrustworthy code inside your page.

https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
