### ISSUE TITLE
Hooks docs: does an effect run on unmount?

### ISSUE THREAD

**Issue by ranneyd** [reactjs/reactjs.org#1348]
Look at: https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect

It says:
>Passing in an empty array [] of inputs tells React that your effect doesn’t depend on any values from the component, so that effect would run only on mount and unmount, never on updates.

The way I understand effects is the effect runs when the values in that array change, plus when the component mounts. On unmount, react runs the _return values_ of all the effect functions.

This says "that effect would run only on mount and unmount". Does that mean that the effect code, which I would think refers to the first argument to `useEffect`, is run on unmount? That wouldn't really make sense (why would you run the subscriber code on unmount? Then immediately run the clean-up code on it?).

If my understand of what's really going on is true, then this language is a little confusing. I think it would be better to say "so that effect would only run on mount (and the cleanup code on unmount), never on updates", or something like that.

**Comment by sophiebits** [comment]
Thanks!
