### ISSUE TITLE
clarify shallow/deep comparison when firing effects conditionally

### ISSUE THREAD

**Issue by nperichSYKES** [reactjs/reactjs.org#1352]
For example, in this code

`useEffect(
  () => {
    const subscription = props.source.subscribe();
    return () => {
      subscription.unsubscribe();
    };
  },
  [props.source],
);`

if props.source does not change the effect will not run. 

It's clear it will run if `source` is `5` then changes to `6`. But what if props.source is an object or array? 

Like if `source` equals  `{url: 'someUrl', visited: 'false'}` and `visited` changes, does the effect run?

I'm assuming it does a shallow comparison and doesn't track fancy references to check deep equality? So that you should avoid using objects and arrays here? But this is probably worth clarifying explicitly in the docs.

**Comment by nperichSYKES** [comment]
realized it's a duplicate, though phrased differently

**Comment by mukulhase** [comment]
Could you link the duplicate?
