### ISSUE TITLE
no install instructions

### ISSUE THREAD

**Issue by hozefaj** [reactjs/reactjs.org#140]
Surprised to see the homepage or tutorial page of the docs do not contain install instructions. Also would be helpful to have links to pre-compiled JS builds in case there is a use case for non-npm environments.

Info is inside the tutorial: https://reactjs.org/docs/installation.html#installing-react. Does it make sense to have it on the homepage.

**Comment by bvaughn** [comment]
Thanks for the feedback. 😄 

> Surprised to see the homepage or tutorial page of the docs do not contain install instructions

The tutorial links to installation instructions in its "How to Follow Along" section. I don't think they need to be inline. (The tutorial's already pretty long.) It's also nice for them to be discoverable separately from the tutorial for people who don't want to go through the tutorial.

> Does it make sense to have it on the homepage.

I think Docs > Installation is a reasonable location for installation instructions. The home page is focused on giving a summary of _what React is_. If people are interested enough based on that intro, then installation is the top link on the "Docs" section.

I don't think there's any concrete action to be taken here, although I appreciate the feedback. If you do have specific suggestions, please feel free to submit a PR for consideration though! 😄
