### ISSUE TITLE
useCallback should mention that it is disabled on the server

### ISSUE THREAD

**Issue by Zhouzi** [reactjs/reactjs.org#1402]
I observed that `useCallback` returns `undefined` when rendered on the server. I thought it was a bug and reported it here: [react#14241](https://github.com/facebook/react/issues/14241). Apparently, that's the expected behavior. It would be nice to mention that `useCallback` is disabled on the server and returns `undefined`. Also, this note is a bit misleading:

> `useCallback(fn, inputs)` is equivalent to `useMemo(() => fn, inputs)`.

They're not really equivalent since `useMemo` works on the server.

* [Documentation for useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback)

See [this comment](https://github.com/facebook/react/issues/14241#issuecomment-439332739) for more details on how I came to observe this behavior.

**Comment by sophiebits** [comment]
I reopened on the linked issue – I believe this is a bug.
