### ISSUE TITLE
Suspense missing in API documentation

### ISSUE THREAD

**Issue by JonathanStoye** [reactjs/reactjs.org#1424]
Maybe I am completely mistaken and then I want to apologize upfront but it seems to me like there is no exhaustive documentation of Suspense in the API docs. I found the [change log](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#changelog) which e.g. mentions Suspense and the renaming of delayMs to maxDuration and the guide for [code-splitting](https://reactjs.org/docs/code-splitting.html#suspense) but no documentation of Suspense itself. I would expect an section about Suspense with explanation for the maxDuration prop e.g. in https://reactjs.org/docs/react-api.html or am I mistaken?

**Comment by gaearon** [comment]
Yeah the reference is missing, we need to add it.

That said you wouldn’t find anything else there. The `maxDuration` prop has no effect outside of (unstable) concurrent mode, and will not be documented until those parts are released separately.

**Comment by JonathanStoye** [comment]
Okay then, would you like me to open a PR?
