### ISSUE TITLE
React must be in scope when using JSX.

### ISSUE THREAD

**Issue by abrarShariar** [reactjs/reactjs.org#1426]
The [documentation](https://reactjs.org/docs/hooks-intro.html) for using Hooks contains the code snippet - 

```
import { useState } from 'react';

function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
} 
```

But it throws the error: `'React' must be in scope when using JSX`. My react and react-dom versions look like this -

```
  "react": "^16.7.0-alpha.2",
  "react-dom": "^16.7.0-alpha.2"
```

So, 'React' needs to be imported in order to eliminate the error. The first line needs to be modified to -

`import React, { useState } from 'react';`

**Comment by threepointone** [comment]
Fixed separately, thanks!

**Comment by thehcker** [comment]
Always remember to import React at the top of your components. Note: You must always import it as "React" and not "react"
