### ISSUE TITLE
strict-mode documentation

### ISSUE THREAD

**Issue by kcak11** [reactjs/reactjs.org#1434]
In the documentation for strict-mode https://reactjs.org/docs/strict-mode.html
there is a note on the page under the section 
**"Warning about deprecated findDOMNode usage":**

> Note:
> In CSS, the display: contents attribute can be used if you don’t want the node to be part of the layout.
> 

What does this note signify with regards to the strict-mode documentation ? 
It is a bit confusing. It would be helpful if some more information is added here as to how the _**css display property and strict-mode**_  are related.

Thanks in advance.

**Comment by threepointone** [comment]
That note is in context to the workaround for using findDOMNode and adding an additional Dom wrapper.
