### ISSUE TITLE
Best practice to load components in React ?

### ISSUE THREAD

**Issue by pavan2920** [reactjs/reactjs.org#1467]
Hi Team, 

Would like to know the best practice or way to load multiple components in parent component. 

Scenario. 
We are using a parent component where in we have a button, on click of which another component should appear in a Callout. So is it good way to Load child component on load of parent component OR load the child component every time the button is clicked. 

Thanks & Regards, 
Pavan.

**Comment by thchia** [comment]
Normally you start off by just importing the Child as normal and controlling whether it is visible or not in the parent's render. In this sense the Child is 'loaded' from the start.

```jsx
// in <Parent />
render() {
  return { this.state.show ? <Child /> : null }
}
```
If `Child` is a large and complex component that you do not want to load the js for until it is clicked, you can lazy load it. How you do this depends on whether you have support for `React.lazy`, and whether you need server-side rendering. Consider [react-loadable](https://github.com/jamiebuilds/react-loadable) if you don't have access to the latest React features for this.

> with React.lazy
```jsx
// in Parent.js
const Child = React.lazy(() => import('./Child'))

// Use <Child /> in <Parent /> with <Suspense />
```
[More info](https://reactjs.org/docs/code-splitting.html)
