### ISSUE TITLE
Misleading statement regarding using Create-React-App with Typescript

### ISSUE THREAD

**Issue by carpben** [reactjs/reactjs.org#1482]
In _static-type-checking_ -> _Using TypeScript with Create React App_ it says 
> Create React App supports TypeScript out of the box.

Well, it doesn't seem so. 
I followed the instructions for creating a new project. 
`create-react-app my-app --typescript`
I converted App.jsx to App.tsx. There was only 1 error - no types for React. I installed types for React 
`npm i @types/react`
and then run npm start. 
I got the following error: 
![image](https://user-images.githubusercontent.com/13496178/49801243-59c49080-fd52-11e8-8860-f7d93f39f034.png)
While it's perfectly fine to expect a user to install "typescript" and the various type modules, i wouldn't say that it qualifies as "support out of the box" for typescript.

**Comment by liamross** [comment]
If you run `npx create-react-app my-app --typescript` it will generate your entire project using typescript, so the App file will be `App.tsx`, and there should be no reason to have to change it from `.jsx` to `.tsx`. I just attempted this myself and it seems to be the case. I'd recommend you try again with the command and see if you run into the same issues.

To summarize: if you run  `npx create-react-app my-app --typescript` it will generate create-react-app with typescript already set up, no need to install anything further or change any files.

**Comment by carpben** [comment]
This is not my experience. I just tried both `npx create-react-app my-app --typescript` and just `create-react-app my-app --typescript`. In both cases I got the same regular template of create-react-app, with index.js, and app.js. @types/react was not a dependency, and it did not recognize the type of a React component. my react scripts version is `"react-scripts": "2.1.3"`

**Comment by carpben** [comment]
I just updated create-react-app, and it solved the problem. 

The reason I did not update create-react-app in the first place is that I read [here (Create-React-App documenation](https://facebook.github.io/create-react-app/docs/updating-to-new-releases) that : 
> You almost never need to update create-react-app itself: it delegates all the setup to react-scripts.

> When you run create-react-app, it always creates the project with the latest version of react-scripts so you’ll get all the new features and improvements in newly created apps automatically.

I'll close this here, and open an issue on Create-React-App.
