### ISSUE TITLE
WeakMap, WeakSet requirement.

### ISSUE THREAD

**Issue by lili21** [reactjs/reactjs.org#1522]
react-dom@16.7 depends on `WeakMap` and `WeakSet`。

[this page] should mention this.

**Comment by gaearon** [comment]
I only see this:

```js
var PossiblyWeakMap = typeof WeakMap === 'function' ? WeakMap : Map;
```

and this:

```js
var PossiblyWeakSet = typeof WeakSet === 'function' ? WeakSet : Set;
```

So neither dependency is a hard one. React still works without them.
