### ISSUE TITLE
Docs contains npx instead of npm 

### ISSUE THREAD

**Issue by amefoDC** [reactjs/reactjs.org#1566]
![screenshot 195](https://user-images.githubusercontent.com/15066319/51300087-f4d41880-1a2a-11e9-8e27-41a0249da8a1.png)
I noticed this docs contains 'npx' instead of 'npm'.

**Comment by alexkrolick** [comment]
That's correct, `npx` is a command line tool to download and run binaries from npm without globalling installing them 😀

**Comment by amefoDC** [comment]
Thanks. I have just learned something new today.
