### ISSUE TITLE
Building Your Own Hooks out of date, showing v16.8.0-alpha.0 instead of v16.8.0-alpha.1

### ISSUE THREAD

**Issue by dance2die** [reactjs/reactjs.org#1573]
# 🧐 Issue

[Building Your Own Hooks](https://reactjs.org/docs/hooks-custom.html) has description,  
_Source: https://github.com/reactjs/reactjs.org/blob/master/content/docs/hooks-custom.md_

> Hooks are an upcoming feature that lets you use state and other React features without writing a class. They’re currently in React `v16.8.0-alpha.0`.

where `v16.8.0-alpha.0` should be [v16.8.0-alpha.1](https://github.com/facebook/react/releases/tag/v16.8.0-alpha.1), which was released this week..

![chrome_2019-01-18_20-48-10](https://user-images.githubusercontent.com/8465237/51420719-94e08d80-1b62-11e9-9b09-cf19ae69ffa9.png)

# 😃 Suggestion

Update the version to `v16.8.0-alpha.1`.

# ➕ Additional Context

I can tackle on this with a PR if this is indeed an issue 😉

**Comment by odensc** [comment]
Looks like this was fixed with 024b5b61731f267f3eb911c13fdd36e1a11c9d1e.

**Comment by dance2die** [comment]
Thanks @odensc.
Closing 🚪...
