### ISSUE TITLE
[hooks] - edit hooks FAQ , react devtools and flow support react hooks

### ISSUE THREAD

**Issue by Avi98** [reactjs/reactjs.org#1585]
In hooks FAQ [Do Hooks cover all use cases for classes](https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes) says that there is no support for hooks in devtools and flowtype.
But thanks to @bvaughn, he has added hooks support in [react devtools](https://twitter.com/brian_d_vaughn/status/1084944848434524160) and [flowtype](https://github.com/facebook/flow/pull/7149)

**Comment by bvaughn** [comment]
cc @gaearon maybe we can amend this statement as part of writing the blog post for the next release?

**Comment by Avi98** [comment]
I can raise a PR and then it can be merged in the next release if its okay

**Comment by bvaughn** [comment]
Dan was already planning on updating those docs as part of our upcoming release process, so you'll want to coordinate with him to avoid conflicts. 😄 I'll let you two sort it out. Thanks for the offer either way!
