### ISSUE TITLE
[Hooks] - setState should compare setter value for avoid not useful render

### ISSUE THREAD

**Issue by dabretin** [reactjs/reactjs.org#1588]
Hello !
I think `setState` setters must compare value with cached one before _send change modification_ and force not useful rendering...

We can of course do it manually but in some `React.useEffect` (also with `React.useCallback` and `React.useMemo` but it's less severe) it forces to include the _getter_ in `initialState` array...

Sample of pointless rendering in the sample by clicking the **Reset** button with a value already reseted (0):
https://codesandbox.io/embed/py2qo4x1mj

What do you think about it ?

**Comment by gaearon** [comment]
Yeah, it's already how it works in master. (And will work in the stable release.)

**Comment by dabretin** [comment]
Thx for your time :+1: 
So it's normal to not work in v16.8.0-alpha.1 ?
