### ISSUE TITLE
experimental public class fields syntax no longer in TC39

### ISSUE THREAD

**Issue by yinghaochan** [reactjs/reactjs.org#159]
https://github.com/tc39/proposal-class-public-fields

Writing this fat arrow method used to be stage-2, but has since been removed.
```jsx
// https://reactjs.org/docs/handling-events.html
class LoggingButton extends React.Component {
  // This syntax ensures `this` is bound within handleClick.
  // Warning: this is *experimental* syntax.
  handleClick = () => {
    console.log('this is:', this);
  }

  render() {
    return (
      <button onClick={this.handleClick}>
        Click me
      </button>
    );
  }
}
```
Also noticed that js-codemod uses this syntax heavily, but it has been removed from the babel stage 2 preset: https://github.com/babel/babel/pull/6088   so it might cause breaking changes to people updating babel

**Are there any suggestions / ideas on what the path forward will be?**

**Comment by fkling** [comment]
As explained in the link, the proposal has been merged with another proposal. So there is no actual issue?

**Comment by yinghaochan** [comment]
I'm not sure..

The example in the unified proposal uses:
```js
class Counter extends HTMLElement {
  x = 0;

  clicked() {
    this.x++;
    window.requestAnimationFrame(this.render.bind(this));
  }

  constructor() {
    super();
    this.onclick = this.clicked.bind(this);
  }
}
```

instead of
```js
class Counter extends HTMLElement {
  x = 0;

  clicked() {
   ...
  }

  onClick = () => this.clicked()
}
```

**Comment by yinghaochan** [comment]
Also the unified proposal has this example:

https://github.com/tc39/proposal-unified-class-features/blob/master/README.md
## Decorators

ESnext provides decorators to let frameworks and libraries to implement part of the behavior of classes, as seen in the next version of the example:

```js
@defineElement('num-counter')
class Counter extends HTMLElement {
  @observed #x = 0;

  @bound
  #clicked() {
    this.#x++;
  }

  constructor() {
    super();
    this.onclick = this.#clicked;
  }

  connectedCallback() { this.render(); }

  @bound
  render() {
    this.textContent = this.#x.toString();
  }
}
```

Here, decorators are used for:
- `@defineElement` defines the custom element, allowing the name of the element to be at the beginning of the class
- `@bound` makes `#clicked` into an auto-bound method, replacing the explicit `bind` call later
- `@observed` automatically schedules a call to the `render()` method when the `#x` field is changed

**Comment by hzoo** [comment]
@yinghaochan you need to check the original issue in the pr you linked, it just removes it from stage 2 because it moved to stage 3

**Comment by yinghaochan** [comment]
Thanks. I'm happy to be proven wrong here.

**Comment by bvaughn** [comment]
Thanks for the discussion 😄  Sounds like there's no action needed on this issue though, so I'm going to close it.
