### ISSUE TITLE
Reactjs.org won't load due to lifecycle error

### ISSUE THREAD

**Issue by goodbomb** [reactjs/reactjs.org#161]
Hi,

I'm trying to access reactjs.org, but the page won't load because there's a lifecycle error for `docsearch`.

```
react-dom.production.min.js:187
ReferenceError: docsearch is not defined
    at t.componentDidMount (index.js:31)
    at commitLifeCycles (react-dom.production.min.js:169)
    at n (react-dom.production.min.js:180)
    at u (react-dom.production.min.js:183)
    at c (react-dom.production.min.js:184)
    at h (react-dom.production.min.js:188)
    at m (react-dom.production.min.js:187)
    at Object.updateContainer (react-dom.production.min.js:248)
    at react-dom.production.min.js:254
    at Object.unbatchedUpdates (react-dom.production.min.js:190)
```

**Comment by bvaughn** [comment]
Do you, by chance, have some sort of ad blocker (or other extension) that might be preventing docsearch from loading? I'm unable to reproduce the behavior you described when loading reactjs.org.

**Comment by goodbomb** [comment]
I suppose that's possible. You are correct, though. I can see the site fine on my work machine. Not sure why my home machine was having trouble. The page content would appear briefly (flashing in) before displaying a completely blank page. I'll have to check it again at home and see what else is up.

Thanks.

**Comment by bvaughn** [comment]
Thanks! Please let me know.

Also you may be interested in issues like #9 which should hopefully improve the UX for the worst case (total failure due to some kind of error).

**Comment by gaearon** [comment]
This error:

>ReferenceError: docsearch is not defined

was related to Fair Adblocker in the past.

**Comment by bvaughn** [comment]
I've also seen reports of that ^

We recently made some improvements in the UX when ad blockers prevent Babel from loading. (Now we still show the code samples, but instead of the compiled+running code we show an error message about ad blocker whitelists.)

I'm not sure what the UX fix for this is but we should at least handle it gracefully once #9 is resolved.
