### ISSUE TITLE
Suggestion for improving confusing words

### ISSUE THREAD

**Issue by taehwanno** [reactjs/reactjs.org#1653]
Since v16.8.0, [React Hooks](https://reactjs.org/docs/hooks-intro.html) are officially added.

> React is flexible and provides hooks that allow you to interface with other libraries and frameworks.

As you can see [this](https://github.com/reactjs/reactjs.org/blob/master/content/home/examples/a-component-using-external-plugins.md), I think it's not a good idea to use the word "hooks" when describing components that use the external plugin because I think the beginner who listened to React Hooks might be confused.

I hope that the word "hooks" is improved in a way that does not change the meaning of sentences without using "hooks".

**Comment by alexkrolick** [comment]
Fixed by #1655

**Comment by sophiebits-humu** [comment]
Thanks for reporting! Guess we noticed at the same time. 😅

**Comment by taehwanno** [comment]
Ahh, Thanks 👍
