### ISSUE TITLE
Broken link in HOC doc

### ISSUE THREAD

**Issue by tanohzana** [reactjs/reactjs.org#1660]
Redux's connect as an HOC example displays a broken link...

Here's the page where the broken link is :
https://reactjs.org/docs/higher-order-components.html

Here is the broken link :
https://github.com/reduxjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by Lukyhenson** [comment]
Hey @tanohzana i did this PR to solve this :D  => https://github.com/reactjs/reactjs.org/pull/1666

**Comment by tanohzana** [comment]
Perfect ! ;-D

**Comment by Lukyhenson** [comment]
@tanohzana this issue was merged, u can close this issue now :smile:
