### ISSUE TITLE
Link not working in Codebase Overview

### ISSUE THREAD

**Issue by iAziz786** [reactjs/reactjs.org#1669]
On the [Codebase Overview](https://reactjs.org/docs/codebase-overview.html) page, in the [Fiber Reconciler](https://reactjs.org/docs/codebase-overview.html#fiber-reconciler) section, this link is not working.

![image](https://user-images.githubusercontent.com/17024120/52612722-f15c7180-2eb0-11e9-98dc-e45f9e2091fa.png)

**Comment by Lukyhenson** [comment]
Hey @iAziz786 i did this PR to solve this => https://github.com/reactjs/reactjs.org/pull/1673

**Comment by iAziz786** [comment]
Thanks @Lukyhenson, once your PR get merged you can close this issue.

**Comment by saranshkataria** [comment]
Fixed by #1673
