### ISSUE TITLE
Some explicit heading IDs are missing in hooks-faq

### ISSUE THREAD

**Issue by smikitky** [reactjs/reactjs.org#1674]
In `hooks-faq.md`, all explicit heading IDs are missing after "### How do I implement `getDerivedStateFromProps`?".

I believe the cause is this malformed closing of a code block: https://github.com/reactjs/reactjs.org/blame/master/content/docs/hooks-faq.md#L359

**Comment by tesseralis** [comment]
@smikitky PR here: https://github.com/reactjs/reactjs.org/pull/1680
