### ISSUE TITLE
Hook State docs do not tell the true story when comparing to class-based components

### ISSUE THREAD

**Issue by JoshMcCullough** [reactjs/reactjs.org#1677]
https://reactjs.org/docs/hooks-state.html

>We’ll start learning about Hooks by comparing this code to an equivalent class example.

The first code snippet on this page is not equivalent to the second. The first is purposely terse / succinct, while the latter is purposely verbose -- as if one is trying to propose the functional component as much shorter than the non-functional class component.

The class component has unneeded boilerplate which should be removed so the reader can clearly see the differences between the two approaches and decide for themselves which one is easier to understand, write, and use. The constructor is not needed and it is also missing its `import` statement.

The class component example should be this ...

```
import React from 'react';

class Example extends React.Component {
  this.state = {
    count: 0
  };

  render() {
    const { count }  = this.state;

    return (
      <div>
        <p>You clicked {count} times</p>
        <button onClick={() => this.setState({ count: count + 1 })}>
          Click me
        </button>
      </div>
    );
  }
}
```

**Comment by gaearon** [comment]
What you wrote is not valid JavaScript syntax. Did you mean `state = { }`?

Regardless, that's not a valid JavaScript syntax either. It's a syntax *proposal* which has not been standardized yet — and like with any proposals, a subject to change.

In the past when the docs included experimental syntax, people complained about it being confusing. I think it makes sense that we decided the docs should stick to the stable syntax.

**Comment by JoshMcCullough** [comment]
Okay -- fair enough and thanks for the explanation. It's easy to lose site of what is "core ES" nowadays!

**Comment by gaearon** [comment]
For sure! 😄
