### ISSUE TITLE
Document error boundaries

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#17]
Add top-level documentation for the new `componentDidCatch` lifecycle. Please refer to the post:

https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

It describes the behavior in detail. We should just adopt it to the doc format.

This issue has been claimed by @Krizzu

**Comment by lydell** [comment]
This seems to exist now: https://reactjs.org/docs/error-boundaries.html

Question: Should `componentDidCatch` be briefly mentioned in https://reactjs.org/docs/react-component.html and link to the above page?

**Comment by bvaughn** [comment]
Yup! A PR was merged without referencing this issue I guess. Thanks for pointing out the oversight 😄 

I've opened #120 for adding `componentDidCatch` ~ if you want it, leave a comment there and it's all yours :smile:

**Comment by yugandhar-pathi** [comment]
Can some one help me to decipher stack trace. I have stack trace ready but no idea how to actually read that.

Here is the error stack received from production mode..
This error is located at:
    in t
    in RCTSafeAreaView
    in r
    in r
    in Connect(r)
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in RCTView
    in RCTView
    in t
    in RCTView
    in RCTView
    in n
    in t
    in RCTView
    in t
    in r
    in withCachedChildNavigation(r)
    in Unknown
    in n
    in n
    in t
    in t
    in withCachedChildNavigation(t)
    in Unknown
    in n
    in n
    in Unknown
    in Connect(Component)
    in n
    in e
    in t
    in RCTView
    in RCTView
    in t
