### ISSUE TITLE
React Hooks Gradual Adoption Strategy

### ISSUE THREAD

**Issue by VictorChen** [reactjs/reactjs.org#1708]
Curious if these statements are still true in https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy:

> Hooks are very new, and it might be better to wait for more examples and tutorials before considering learning or adopting them.

> We are sharing this **experimental API** ...

Trying to convince the team to use hooks and these statements don't help...

**Comment by gaearon** [comment]
> Hooks are very new, and it might be better to wait for more examples and tutorials before considering learning or adopting them.

That's still true — Hooks being a stable API doesn't mean they're not new, or that there's enough learning materials.

> We are sharing this **experimental API** ...

Will fix that one.

**Comment by VictorChen** [comment]
Thanks! How do we determine when there's enough examples and tutorials (feels like there are a lot already)? Curious when we will start telling people to not wait to learn/adopt hooks.

**Comment by gaearon** [comment]
I can't make these decisions for you. :-) That's up to you and your team.
