### ISSUE TITLE
Main menu is broken

### ISSUE THREAD

**Issue by j-heavy** [reactjs/reactjs.org#1748]
After adding the "Languages" button, the menu broke (1366x768 res) :/

![](https://pbs.twimg.com/media/D0KqXEWX0AAoEp0.jpg)

Without button

![](https://pp.userapi.com/c844416/v844416484/1a43bc/oTYr6nI65xM.jpg)

**Comment by j-heavy** [comment]
https://github.com/reactjs/reactjs.org/pull/1749 solve this

**Comment by tesseralis** [comment]
Resolved in #1749
