### ISSUE TITLE
[Question] React Hooks Docs - Error boundaries

### ISSUE THREAD

**Issue by andre-araujo** [reactjs/reactjs.org#1757]
Is there any way to use the existing hooks to simulate `componentDidCatch` when creating error boundaries?

**Comment by andre-araujo** [comment]
Found into FAQ section, thanks.

**Comment by tobiasbueschel** [comment]
In case anyone is looking for the FAQ section that covers it, you can find it here: https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes
