### ISSUE TITLE
[Documentation] Glossary: Only calss components can have state

### ISSUE THREAD

**Issue by ntishkevich** [reactjs/reactjs.org#1767]
Hey,
I was reviewing a [PR](https://github.com/reactjs/ru.reactjs.org/pull/200) with Russian translation of the article `Glossary of React Terms` and noticed that there is a sentence about class components and state.  

> Only components defined as classes can have state.

You can find it [here](https://reactjs.org/docs/glossary.html#state) in the second paragraph.

React provides a hook `useState` to declare a state for functional components. So I would like to ask, should it be changed after hooks was shipped?

**Comment by alexkrolick** [comment]
Yes, PR welcome to change it 😀
