### ISSUE TITLE
Redux not mentioned in model-management page

### ISSUE THREAD

**Issue by Spacetoaster** [reactjs/reactjs.org#1785]
Redux is mentioned in multiple places on the website, for example [here](https://reactjs.org/docs/faq-state.html#should-i-use-a-state-management-library-like-redux-or-mobx). However in the [overview of model management libraries](https://reactjs.org/community/model-management.html) redux/react-redux is not mentioned and i think this is confusing.

Maybe i am missing something here, but i just stumbled across this and i think it would make the website more consistent to put it there.

**Comment by threepointone** [comment]
I don’t think we have this page anymore? Closing, happy to revisit
