### ISSUE TITLE
Defer window.webpackManifest if possible?

### ISSUE THREAD

**Issue by Daniel15** [reactjs/reactjs.org#179]
https://reactjs.org/ has a 17 KB `window.webpackManifest` in a `<script>` tag in the `<head>`. Since it's in the `<head>`, it's render-blocking and the page can't render until after it loads. Is it possible to move this down underneath the content (eg. to the bottom of the `<body>`) so that it's not render-blocking?

### Edit by @bvaughn:

Once gatsbyjs/gatsby/issues/2541 has been resolved, the resolution to this issue will just be:
* Update to the latest release of Gatsby (`yarn upgrade-interactive`)
* Make sure things still build correctly on a fresh install (`rm -rf ./.cache && rm -rf ./node_modules && yarn install && yarn build`)
* Do quick smoke test to make sure there's no new regression (`yarn dev` and test localhost:8000)

**Comment by bvaughn** [comment]
that manifest comes from [Gatsby's injected `props.headComponents`](https://github.com/gatsbyjs/gatsby/blob/25e3c6aee2f769026df1d2e7a1ec27e9c2d63fc1/packages/gatsby/cache-dir/static-entry.js#L143-L155). Without rendering the injected prop, production builds won't render correctly.

That being said, maybe Gatsby can move this to another injected prop (like `postBodyComponents`)? It looks like @KyleAMathews. [already did this back in March](https://github.com/gatsbyjs/gatsby/commit/4ba57c844d7b8954b529f7503ed9d431b2bb7688) but that change isn't what's in master anymore so maybe it didn't work for some reason?

**Comment by KyleAMathews** [comment]
I vaguely remember it causing some sort of trouble but yeah — we should do this. Created (linked) issue).

**Comment by isaacchien** [comment]
Should this issue be closed now?

**Comment by gaearon** [comment]
I don't think it has been fixed? At least not until we update Gatsby version. 
Wanna send a PR with an update?

**Comment by isaacchien** [comment]
Sure, it'll be my first PR.
