### ISSUE TITLE
Update docs referencing src/

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#181]
I moved everything from `src/` in https://github.com/facebook/react/pull/11252 so we should update the contribution docs and implementation notes.

**Comment by obetomuniz** [comment]
Can I work on it?

**Comment by gaearon** [comment]
Sure!

**Comment by gaearon** [comment]
I updated contribution docs already. For implementation nodes, there is no easy fix since those files are deleted by now. So maybe you could just cut out the paragraph with links to specific files.

**Comment by bvaughn** [comment]
Hello @obetomuniz. Just checking to see if you're still working on this issue. If you are not, no big deal! Please let me know though so I can remove the label in that case and let someone else pick it up. 😄

**Comment by obetomuniz** [comment]
@bvaughn Actually, I'm not working on this PR. My bad! I forgot to update you guys, go ahead and remove the flag.

**Comment by bvaughn** [comment]
No problem 😄 Thanks!

**Comment by ksenna** [comment]
I would like to work on this!

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by ksenna** [comment]
Thank you!

Just submitted PR #291 😄
