### ISSUE TITLE
Restyle logo width to make translations easier

### ISSUE THREAD

**Issue by tesseralis** [reactjs/reactjs.org#1817]
Currently, the width of the logo is fixed at `calc(100% / 6)` so that the nav links are flush with the search bar:

<img width="1280" alt="Screen Shot 2019-03-12 at 7 33 34 PM" src="https://user-images.githubusercontent.com/1278991/54249540-c2f8a300-44fd-11e9-9929-357dcda0453c.png">

Unfortunately, this leads to cut-offs in some translations with longer words in the nav bar:

<img width="1279" alt="Screen Shot 2019-03-12 at 7 38 26 PM" src="https://user-images.githubusercontent.com/1278991/54249698-6d70c600-44fe-11e9-9646-0d83739188f7.png">

We're currently solving this by just adjusting the width of the logo, but it would be nice to have a solution that doesn't require hard-coding the logo width (e.g. just making the nav bar flush against the search bar)

I'll probably fix it myself when I have time but I figured I'd put this up here in case anyone wants to take a look.

**Comment by kevjin** [comment]
Hi, I would be interested in taking a look at this issue. Thanks!

**Comment by kevjin** [comment]
Added PR #1860 for review, thank you!

**Comment by tuantvk** [comment]
same issues repo **vi.reactjs.org**
Text current
![currnet](https://user-images.githubusercontent.com/30563960/59832749-daea8900-936e-11e9-9ec0-67f8877a9994.png)

After translate to vietnamese
![full_content](https://user-images.githubusercontent.com/30563960/59832780-f35aa380-936e-11e9-854d-e4186bb54891.png)

**Comment by nigiiro-taro** [comment]
@tesseralis @tuantvk 
Hello, I would like to work on this issue. This will be my first contribution to oss.
@kevjin 
You have worked on this issue before, would you mind if I took over?

**Comment by akgupta0777** [comment]
@nigiiro-taro go ahead give it a try.

**Comment by nigiiro-taro** [comment]
Thank you. I try it!

**Comment by nigiiro-taro** [comment]
@tesseralis @akgupta0777 
I sent a pull request.
If possible, could you please give me a review or comment?

**Comment by abhay27chauhan** [comment]
is this issue resolved i ? I would like to work on this issue

**Comment by yashbujji** [comment]
is this issue resolved ? . Can i please know the status of the issue so that i can take over it?

**Comment by harish-sethuraman** [comment]
Please note that we're going to replace this site with https://beta.reactjs.org/ soon so we don't really plan to make changes to the old one.
