### ISSUE TITLE
Context reference identity and re-rerenders caveat confusion

### ISSUE THREAD

**Issue by lydell** [reactjs/reactjs.org#1827]
The docs on Context (https://reactjs.org/docs/context.html#caveats) mentions this piece of code as potentially triggering unintentional re-renders:

```js
class App extends React.Component {
  render() {
    return (
      <Provider value={{something: 'something'}}>
        <Toolbar />
      </Provider>
    );
  }
}
```

> For example, the code below will re-render all consumers every time the Provider re-renders because a new object is always created for value

I don't really understand this. Combining React knowledge I already have:

- Context consumers must be (deeply) nested below their Providers.
- When a React component re-renders, it re-renders all child components too.

So if the Provider re-renders, all consumers would re-render anyway?

To me, it feels like some detail is missing from the docs/example regarding this example. Could this be clarified somehow? Thanks!

**Comment by ht254** [comment]
> The docs on Context (https://reactjs.org/docs/context.html#caveats) mentions this piece of code as potentially triggering unintentional re-renders:
> 
> ```js
> class App extends React.Component {
>   render() {
>     return (
>       <Provider value={{something: 'something'}}>
>         <Toolbar />
>       </Provider>
>     );
>   }
> }
> ```
> 
> > For example, the code below will re-render all consumers every time the Provider re-renders because a new object is always created for value
> 
> I don't really understand this. Combining React knowledge I already have:
> 
> * Context consumers must be (deeply) nested below their Providers.
> * When a React component re-renders, it re-renders all child components too.
> 
> So if the Provider re-renders, all consumers would re-render anyway?
> 
> To me, it feels like some detail is missing from the docs/example regarding this example. Could this be clarified somehow? 

> The docs on Context (https://reactjs.org/docs/context.html#caveats) mentions this piece of code as potentially triggering unintentional re-renders:
> 
> ```js
> class App extends React.Component {
>   render() {
>     return (
>       <Provider value={{something: 'something'}}>
>         <Toolbar />
>       </Provider>
>     );
>   }
> }
> ```
> 
> > For example, the code below will re-render all consumers every time the Provider re-renders because a new object is always created for value
> 
> I don't really understand this. Combining React knowledge I already have:
> 
> * Context consumers must be (deeply) nested below their Providers.
> * When a React component re-renders, it re-renders all child components too.
> 
> So if the Provider re-renders, all consumers would re-render anyway?
> 
> To me, it feels like some detail is missing from the docs/example regarding this example. Could this be clarified somehow? Thanks!
I have the same issue too

**Comment by ht254** [comment]
Hi @lydell I have the same issue too.Have you found any solutions on this??

**Comment by alexkrolick** [comment]
```value={{ something: 'something' }}```

is equivalent to

```
const newValue={ something: 'something' }
// In render
value={newValue}
```

All consumers don't rerender when a Provider rerenders, they rerender when the value of the context changes identity (determined using `Object.is()` which is similar to `===`). Creating a new object for the value in each render forces the value to change identity and rerenders all the consumers.

**Comment by lydell** [comment]
Luckily, I've never had any issues with context. I'm just curious.

But I think this has to do with `shouldComponentUpdate`.

```jsx
<App> {/* A `.setState` in App causes a re-render... */}
  <MyContext.Provider value={{ foo: 1337 }}> {/* ...which causes a new context value here. */}
    <Scu> {/* Let's say this component `shouldComponentUpdate` returns `false`... */}
      <A> {/* ...then this component won't re-render. */}
		<MyContext.Consumer> {/* One would expect the entire subtree below Scu not to re-render... */}
          <B /> {/* ...but both MyContext.Consumer and B does because of the new context value. */}
        </MyContext.Consumer>
      </A>
    </Scu>
  </MyContext.Provider>
</App>
```

Not sure how this works with hooks.

**Comment by threepointone** [comment]
Alex is right, it rerenders because of the new object being passed to context every time.

**Comment by lydell** [comment]
@threepointone That’s not the question, though, is it?

**Comment by lydell** [comment]
@threepointone Can you provide a minimal example where `<Provider value={{something: 'something'}}>` causes unnecessary re-renders? Maybe codesandbox? Bonus points for using hooks.

**Comment by learnitmyway** [comment]
For those of you who ended up here trying to understand why it's a caveat this answer might help https://stackoverflow.com/a/70022607/5955911
