### ISSUE TITLE
[Docs] Why useMemo is a hook?

### ISSUE THREAD

**Issue by everdimension** [reactjs/reactjs.org#1831]
I understand what `useMemo` does, but I don't really understand why it is a hook and why you can't just memoize a call using a "normal" memoization function.

When something is a hook, it kinda implies that this code right here is specific to react state or lifecycles, doesn't it?

It seems that the docs touch a little bit on the reasoning: 
> In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, [...]

Is this the main reason why `useMemo` exists as a hook?

In any case, I believe it will be useful for the docs to explain this better.

Thanks!

**Comment by gaearon** [comment]
It's because memoization is local to this component, in the same way state is local. You don't want an update in one component to invalidate memoization of another component of the same type.

**Comment by ahtee** [comment]
I'll check the docs soon and see. I'm currently doing a binge on the react docs myself and will see if i can offer suggestions for use cases/explanations there.

**Comment by threepointone** [comment]
Closing since there’s a good explanation here.
