### ISSUE TITLE
Unexpected

### ISSUE THREAD

**Issue by cloudrex** [reactjs/reactjs.org#1837]
![image](https://user-images.githubusercontent.com/41349879/54499929-dfc21b80-48ed-11e9-8d9a-7c16c7b03b71.png)

Is that supposed to happen? [Here's the example](https://github.com/reactjs/reactjs.org/blob/master/content/docs/lifting-state-up.md)

**Comment by threepointone** [comment]
You can infinite examples of this kind of bug simply because that’s how numbers work in computers, ha. Closing, but will revisit in the future.
