### ISSUE TITLE
Do hooks suppport typescript well recently?

### ISSUE THREAD

**Issue by yanlee26** [reactjs/reactjs.org#1885]
I have implemented ts in my whole project, sometimes hooks will trigger some ts syntax error, which is hard to fix.So  I wonder how ts was supported in hooks.

**Comment by jordyvandomselaar** [comment]
What error are you getting? We're using TS with hooks as well and all seems to work fine! =)

**Comment by PerfectionCSGO** [comment]
```
//useHover.ts
import { useRef, useState, useEffect } from 'react';

export default function useHover(): [React.RefObject<HTMLDivElement>, boolean] {
  const [value, setValue] = useState(false);

  const ref = useRef<HTMLDivElement>(null);

  const handleMouseOver = () => setValue(true);
  const handleMouseOut = () => setValue(false);

  useEffect(() => {
    const node = ref.current;
    if (node) {
      node.addEventListener('mouseover', handleMouseOver);
      node.addEventListener('mouseout', handleMouseOut);

      return () => {
        node.removeEventListener('mouseover', handleMouseOver);
        node.removeEventListener('mouseout', handleMouseOut);
      };
    }
    return;
  }, [ref.current]);

  return [ref, value];
}
```

Here's an example hook that I use. Works just fine in typescript. However, the only challenge is that it will only work on HTMLDivElments and it becomes a challenge to make it work with HTMLDivElements + HTMLButton elements.

**Comment by yanlee26** [comment]
`js
  // const [routes, setRoutes] = useState(null); // before 
  const [routes, setRoutes] = useState(<></>); // after
// ...
  return <BrowserRouter>{routes}</BrowserRouter>;
`

Well, the initial value I set was not correct, I fixed it now. 
Thanks and I will try and see this cool feature of React !
