### ISSUE TITLE
Maintain scroll position of mobile menus

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#19]
Originally reported by @KyleAMathews via facebook/react/issues/10952

When going quickly through pages on mobile, it'd be really nice if as you scroll down long menus e.g. in docs, if after navigating to the next page and then returning to the menu if the previous scroll position is maintained/restored.

This could be done by by storing the menu scroll position in the layout again and then passing it into the page component on render.

**Comment by KyleAMathews** [comment]
This would also lessen the need to hide subsections of the menu.

**Comment by tsriram** [comment]
Has this been fixed by some other change? I can't seem to reproduce this. Whenever I go back & forth between pages on mobile, it looks to be retaining the scroll position!

**Comment by bvaughn** [comment]
It's possible this was fixed as a result of replacing several of the `<a>` tags with `gatsby-link` links (aka `react-router-dom` links).

**Comment by bvaughn** [comment]
I am also unable to reproduce the behavior originally reported 😄  So I'll close this issue for now.
