### ISSUE TITLE
Broken link in the blog

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#192]
https://reactjs.org/blog/2014/10/16/react-v0.12-rc1.html#react-elements

> We talked about this topic in depth earlier this week. 

Leads nowhere.

**Comment by bvaughn** [comment]
Just to clarify: This task is to fix the broken link to point to `/blog/2014/10/14/introducing-react-elements.html` (eg fix the "introducting" typo)

**Comment by emmafallancy** [comment]
Can I voluntarily take this?

**Comment by bvaughn** [comment]
This issue is all yours< @emmafallancy 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by emmafallancy** [comment]
Yeay!!! Thanks! 🎉

**Comment by brijeshprasad89** [comment]
@emma let me know if you change your mind

**Comment by gaearon** [comment]
Hmm. The issue I see is that the link points to:

https://blog/2014/10/14/introducing-react-elements.html

Which isn't a real URL.

**Comment by emmafallancy** [comment]
@gaearon Yup. There was a typo there. Also, I got question regarding the related matter as well. I've made a PR just now at #193 and a question there too.

**Comment by gaearon** [comment]
Thanks for the PR! I merged it as is but I want to understand two things:

1. Why existing `redirect_from` that you mentioned didn't work. On the old website it seemed to work (and this is why we didn't have this issue earlier).

2. Why, if the website can't find something, it redirects to such a strange URL (with `blog` domain) rather than to our 404 page.

I think we need to keep the issue open until we figure out both of these things. Would you like to continue looking into it?

**Comment by emmafallancy** [comment]
@gaearon yes, I would like to give it a try. Didn't dig further about this just now. Only just found out about the behaviour in question 2. I brought up question 1 is because since we fix the problem for the broken link, was wondering if we ever still need the redirect.

**Comment by emmafallancy** [comment]
@gaearon I've made a PR #194 which leads to the issue in question 2 that you have just now.

**Comment by bvaughn** [comment]
Fixed via #192 and #194
