### ISSUE TITLE
Higher-Order Components

### ISSUE THREAD

**Issue by Learner16** [reactjs/reactjs.org#1938]
Under the explanation of "[Don’t Mutate the Original Component. Use Composition.](https://reactjs.org/docs/higher-order-components.html#dont-mutate-the-original-component-use-composition)"

> The comment shall say : The fact that we're **NOT** returning the original input is a hint that it has been mutated.

```
function logProps(InputComponent) {
  InputComponent.prototype.componentWillReceiveProps = function(nextProps) {
    console.log('Current props: ', this.props);
    console.log('Next props: ', nextProps);
  };
  // The fact that we're not returning the original input is a hint that it has
  // been mutated.
  return InputComponent;
}

// EnhancedComponent will log whenever props are received
const EnhancedComponent = logProps(InputComponent);
```

**Comment by kambleaa007** [comment]
Yes, good catch,
you can check PR,
https://github.com/reactjs/reactjs.org/pull/1989

**Comment by threepointone** [comment]
As pointed out on the PR, the docs are fine
