### ISSUE TITLE
useEffect goes in inifinite loop with React Hooks

### ISSUE THREAD

**Issue by m-nathani** [reactjs/reactjs.org#1941]
React/Redux application goes into an infinite loop on using useEffect with object references..

I am trying render pending todos for my application using `useEffect`.. and passing the array of todos as the second param in `useEffect` ..but why is not checking the values of the object ?

**Container:**
```const mapStateToProps = state => state;
const mapDispatchToProps = dispatch => ({ actions: bindActionCreators(RootActions, dispatch) });
const Home = (props) => {
  const { root, actions } = props;

  useEffect(() => {
    getTodos(actions.loadPendingTodo);
  }, [root.data]);

  return (
    <Segment>
      <Error {...root } />
      <TodoList { ...root } actions={actions} />
  </Segment>
  );
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
```

**Action:**
```
export const loadPendingTodo = () => ({
  type: LOAD_PENDING_TODO,
  data: todoService.loadPendingTodo(),
});

```

**Reducer:**
```
const initialState = {
  initial: true,
  data: [{
    id: 0,
    text: 'temp todo',
    dueDate: new Date(),
    completedDate: '',
    isDeleted: false,
    isCompleted: false,
  }],
  error: false,
  isLoading: false,
  isEdit: false,
};

export default function root(state = initialState, action) {
  switch (action.type) {
    case LOAD_PENDING_TODO:
      return {
        ...state,
        data: [...action.data],
      };
...

    default:
      return state;
  }
}
```

**getTodos Method:**
```
export const getTodos = (loadTodo) => {
  try {
    loadTodo();
  } catch (error) {
    console.log(error); // eslint-disable-line
  }
};
```

**Service:**
```
export default class TodoAppService {
  loadPendingTodo() {
    return store.get('todoApp').data.filter(todo => !todo.isCompleted && !todo.isDeleted);
  }
```

Can anyone please help me out how to resolve this issue.. and there is no official documentation for this case too :/

Moreover changing the `useEffect` to the following works but i want to render on every change

```
  useEffect(() => {
    getTodos(actions.loadPendingTodo);
  }, []);
```

**Comment by gaearon** [comment]
I don't understand what you're trying to do by passing `[root.data]`. Array of dependencies should contain *value whose change should trigger the effect again*.

You're saying "when `root.data` changes, run this effect". Effect runs, changing `root.data`. But you're saying "when `root.data` changes, run this effect". So again, effect runs, changing `root.data`. But you're saying "when `root.data` changes, run this effect". [...]

That's your infinite loop.

For data fetching with React Hooks, read this:

https://codesandbox.io/s/jvvkoo8pq3
https://www.robinwieruch.de/react-hooks-fetch-data/

**Comment by m-nathani** [comment]
> I don't understand what you're trying to do by passing `[root.data]`. Array of dependencies should contain _value whose change should trigger the effect again_.
> 
> You're saying "when `root.data` changes, run this effect". Effect runs, changing `root.data`. But you're saying "when `root.data` changes, run this effect". So again, effect runs, changing `root.data`. But you're saying "when `root.data` changes, run this effect". [...]
> 
> That's your infinite loop.
> 
> For data fetching with React Hooks, read this:
> 
> https://codesandbox.io/s/jvvkoo8pq3
> https://www.robinwieruch.de/react-hooks-fetch-data/

got it :D

**Comment by m-nathani** [comment]
Fixed it by removing the redux actions in `useEffect` that causing it loop and directly setting the data in function from service.. 

```const Home = (props) => {
  const { root, actions } = props;
  return (
    <Segment>
      <Error {...root } />
      <TodoList isEdit={root.isEdit} todo={todoService.loadPendingTodo()} actions={actions} />
  </Segment>
  );
};
```

thanks :)
