### ISSUE TITLE
Improve Composition vs Inheritance

### ISSUE THREAD

**Issue by kambleaa007** [reactjs/reactjs.org#1961]
Page about `So What About Inheritance?` is quiet undigestable.

What about containers, `<Provider>` , `<Router>`  , aren't they Inherited.
Our whole wrapped inside them `<App />`
sending data from parent component through `State` and map them in child as `props`,
Isn't it a inheritance.

**Comment by threepointone** [comment]
No, what you’re describing isn’t inheritance, as the doc says.
