### ISSUE TITLE
Add <link rel="canonical"> tag to all pages

### ISSUE THREAD

**Issue by sophiebits** [reactjs/reactjs.org#1964]
I noticed in a Google search result there is a ?utm_source tagged on this link:

![image](https://user-images.githubusercontent.com/6820/57119358-64da8600-6d1e-11e9-9464-92891408f1cf.png)

I think if we add a `<link rel="canonical">` tag to every page header (with the query-string-less URL), this will be fixed.

**Comment by kambleaa007** [comment]
where do i find configurations for URL Routing??

**Comment by kambleaa007** [comment]
I think its Solved or not reproducing at my end,

![image](https://user-images.githubusercontent.com/19818679/57274908-5394cf00-70ba-11e9-9bec-fe83c3c0266c.png)

**Comment by george-veras** [comment]
Hi @sophiebits, I'd like to have a go on this ;)

**Comment by george-veras** [comment]
Hi @sophiebits , if it is still a problem I'd love to have a go, but seems that @kambleaa007 is right.
