### ISSUE TITLE
[Documentation] - Minor change to description of JSX in Depth.Booleans, Null, and Undefined Are Ignored

### ISSUE THREAD

**Issue by v1690117** [reactjs/reactjs.org#1969]
This section https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored of the documentation describes this peace of code
```javascript
<div>
  {showHeader && <Header />}
  <Content />
</div>
```
in this way:
> This JSX only renders a \<Header /> if showHeader is true:

I believe the correct variant should be:

> This JSX only renders a \<Content/> if showHeader is false.

**Comment by kambleaa007** [comment]
<div>
  {showHeader && <Header />}
  { !showHeader && <Content />}
</div>

**Comment by kambleaa007** [comment]
But if there is no header whats purpose to show content then,

**Comment by v1690117** [comment]
@kambleaa007 Thank you for the answer, but the issue is about incorrect documentation, not how to do such thing.

**Comment by kambleaa007** [comment]
Yeah, I know,
I have made pull request regarding changes, You can review or propose changes in it.
Thanks,
https://github.com/reactjs/reactjs.org/pull/1975

**Comment by v1690117** [comment]
Great! Thank you!

**Comment by yvesgurcan** [comment]
@v1690117 I believe that the wording of the documentation is actually correct. 
The following sentence
> This JSX only renders a <Header /> if showHeader is true:
does not imply anything at all about `<Content />` or even `<div/>` being rendered or not.
In other words, this sentence is only about `<Header />` and its relationship to `showHeader`.
Moreover, the modification you suggested might be misleading as the JSX in question actually renders a `<div/>` with `<Content/>` inside, which is different from only rendering `<Content/>`.

**Comment by v1690117** [comment]
@yvesgurcan Thank you for the answer!

I believe the documentation should be clear enough to prevent misunderstanding.
Current statement is not clear because it's possible to understand the sentence at least in two ways. The word "only" may be interpeted as 
> "only renders a \<Header />, showHeader will not be rendered". 

Or 
> "only renders a \<Header />, \<Content/> will not be rendered".

This is the place where misunderstanding borns.

Maybe my suggestion wasn't clear enough too. Perhaps it's better to use something like this to prevent misleading:
> This JSX only renders only a \<Content/> inside of the \<div> if showHeader is false.

**Comment by yvesgurcan** [comment]
No problem! I see how the phrasing can lead to some confusion. Good luck with your suggestion.

**Comment by v1690117** [comment]
Now it's fine, so I close the issue. Thanks!
