### ISSUE TITLE
"A page wasn't found for /blog/" when mouse move into "Blog" on navigation

### ISSUE THREAD

**Issue by outloudvi** [reactjs/reactjs.org#1984]
When mouse moves in the "Blog" link on the navigation bar, the console says:

```
A page wasn't found for "/blog/"                 loader.js:312:16
```

However, when clicking into this link, the blog shows normally (for me, it jumps to https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html).

Steps to reproduce:
1. Go to https://reactjs.org
2. Put mouse into the area of "Blog" link on the navigation bar
3. Console gives a log

Tested on:
* Firefox Developer Edition 67.0b19
* Chromium 74.0.3729.108

**Comment by mjamilfarooq** [comment]
is that an issue or feature? it seems it jumps to recent blog post. https://reactjs.org/blog/all.html is given in the page to explore all blog posts.

**Comment by george-veras** [comment]
May I fix this one?

**Comment by outloudvi** [comment]
Closing since this is not reproducible now.
