### ISSUE TITLE
Defer loading Babel until it is needed

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#2]
We currently load Babel via CDN (which is nice) but we load it in the `<head>` of the page (which is not so nice). We should only load it on pages that actually use it (eg pages that use the [`CodeEditor`](https://github.com/reactjs/reactjs.org/blob/master/src/components/CodeEditor/CodeEditor.js)).

Check out the [Babel website's REPL](https://github.com/babel/website/tree/master/js/repl) for an example of similar deferred loading.

**Comment by renanpvaz** [comment]
Is it necessary to use a worker or could it be achieved through XHR + eval?

**Comment by bvaughn** [comment]
Worker is totally not necessary (but a nice touch). I built a non-worker based version for Babel REPL initially. (It's there in the Git history if you're curious.)

**Comment by renanpvaz** [comment]
Okay, I'll look into it and then attempt to fix the issue.

**Comment by bvaughn** [comment]
Okay. I've tagged this as "in-progress" then. Please let me know if you decide not to submit a PR and I'll remove that label so someone else can claim the task.

**Comment by renanpvaz** [comment]
@bvaughn  should `docsearch` be loaded the same way?

**Comment by bvaughn** [comment]
Could be pretty cool to just-in-time load Algolia too, yeah. 😄 

I plan to remove it in favor of a client-side search solution like [js-worker-search](https://github.com/bvaughn/js-worker-search) at some point in the future so I hadn't considered it much. That being said, it might take me a long time to get to that so...

**Comment by bvaughn** [comment]
Check out issue #98 for my thoughts on that if you're interested
