### ISSUE TITLE
Broken link in /community/articles

### ISSUE THREAD

**Issue by chandrasd** [reactjs/reactjs.org#2035]
The link to ReactFAQ is broken.
Not sure if it has been updated. Probably need to remove the link.

[React.org articles page](https://reactjs.org/community/articles.html)
[GitHub reference](https://github.com/reactjs/reactjs.org/blob/master/content/community/articles.md)

**Comment by kambleaa007** [comment]
it works

**Comment by chandrasd** [comment]
That's odd. Are you sure this [link](https://reactfaq.site/) is working? Seems like the domain name is expired to me. Could you send some screenshots?

**Comment by kambleaa007** [comment]
![image](https://user-images.githubusercontent.com/19818679/58453421-ad783a00-8138-11e9-99fa-16e9c377192a.png)

**Comment by kambleaa007** [comment]
Yeah, Sorry
![image](https://user-images.githubusercontent.com/19818679/58453444-caad0880-8138-11e9-8eb6-66befc29c0e5.png)
Not working

**Comment by kambleaa007** [comment]
It seems down
[https://reactfaq.site/components/rendering/](url)
