### ISSUE TITLE
useState hook updating state using a callback is not documented

### ISSUE THREAD

**Issue by tomecho** [reactjs/reactjs.org#2039]
Currently the following behavior exists with the useState hook as an undocumented feature.

```
  it("calls function passed to useState", () => {
    let didCall = false;

    const Component = () => {
      const [state, setState] = React.useState(null);
      React.useLayoutEffect(() => {
        setState(() => { didCall = true; });
      }, []);
      return null;
    };

    usingMount(<Component />, wrapper => {
      expect(didCall).toBe(true);
    });
  });
```

The section dedicated to documenting updating state does not mention that if a function is passed to setState it will execute it and set the state to the result. https://reactjs.org/docs/hooks-state.html#updating-state

**Comment by pietmichal** [comment]
It is mentioned here: https://reactjs.org/docs/hooks-reference.html#functional-updates

**Comment by tomecho** [comment]
Looks like someone else got it.  Closing.
