### ISSUE TITLE
reactjs.org\node_modules\sharp: Command failed. Exit code: 1 Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

### ISSUE THREAD

**Issue by AlaEddineLaouir** [reactjs/reactjs.org#2049]

**Comment by ctcuff** [comment]
What version of node are you using? I got this same error on Windows using 12.x but fixed it by downgrading to 10.x, specifically, 10.16.0

**Comment by vksbhandary** [comment]
I got same error after cloning the repo and running `yarn`

`
error /Users/vksbhandary/Desktop/pytorch/reactjs.org/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
`

I am using node version `v12.6.0`, npm version `6.10.2`

**Comment by vksbhandary** [comment]
Fixed the error by using node '10.16.0'

**Comment by wisammechano** [comment]
I am still facing this issue with Node v12.13.0 and the prerequisites state only greater than 8.4.0

**Comment by emielvanseveren** [comment]
same thing here!

**Comment by ahmadrasyidsalim** [comment]
@vksbhandary I thought it can be solved, try remove ```yarn.lock``` and ```node_modules``` and running ```yarn``` again. I've trying on Node v12.14.1

**Comment by threepointone** [comment]
We’ll work on making this better with 12, the current workaround is to use 10.

**Comment by bhattaraibishal50** [comment]
Fixed the error by installing ` brew install vips` in Mac OS M1.

**Comment by afrancht** [comment]
This didn't fix it for me, any suggestions?

**Comment by ddtch** [comment]
non of the answers not helped (( same issue. so tired, can't code for 3 hours for now./
Mac M1 Pro,
`warning " > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
[4/4] 🔨  Building fresh packages...
[-/4] ⠈ waiting...
[-/4] ⠈ waiting...
[-/4] ⠈ waiting...
error /Users/dorado/Desktop/repos/aspect-mobile/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/dorado/Desktop/repos/aspect-mobile/node_modules/sharp
Output:
sharp: Detected globally-installed libvips v8.12.2
`

**Comment by gochev** [comment]
Doesnt work even with node 10.24 on Ubuntu and wsl2.

**Comment by csalmeida** [comment]
I have the following issue, the exit code is `127` instead of `1`:

```
[4/4] 🔨  Building fresh packages...
[-/4] ⠠ waiting...
[-/4] ⠠ waiting...
[3/4] ⠠ sharp
error /Users/username/Projects/my-rn-project/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/username/Projects/my-rn-project/node_modules/sharp
Output:
sharp: Detected globally-installed libvips v8.12.2
sharp: Building from source via node-gyp
/Users/username/.nvm/versions/node/v16.15.0/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 5: ~/.nvm/versions/node/v16.13.2/lib/node_modules/node-gyp/bin/n
```

Using Node `v16.13.2`, unsure of a solution yet but I'll update the thread if I find out.

**Comment by LL782** [comment]
I hit this problem on a Gatsby app on a Mac M1.

Thanks to @bhattaraibishal50 I tried `brew install vips` and got 

```Error: gcc: the bottle needs the Apple Command Line Tools to be installed.```

So I'm now running and even if this doesn't fix everything I'm thankful to have found the command for installing these bits from xcode.

```xcode-select --install```

Hope it helps others

**Comment by awxiaoxian2020** [comment]
I still have this problem on Windows using latest node vesion.

**Comment by Milan-960** [comment]
I also have the same issue with node v16.18.1. if anyone has resolved it please let me know. I have checked everywhere but did not find anything helpful :)

**Comment by csalmeida** [comment]
@Milan-960 could you post your terminal output where the error is displayed, please? If you think it has to do with `libvips` and you're using MacOS [try following the steps @LL782](https://github.com/reactjs/reactjs.org/issues/2049#issuecomment-1319250129) and let us know. :)

**Comment by Milan-960** [comment]
I tried that on my machine and it worked @csalmeida :)

**Comment by elsiosanchez** [comment]
I get the same error after cloning my repository and running `yarn`

![image](https://user-images.githubusercontent.com/45974454/232140587-661dd589-a16b-47b1-8217-a4c3e4c99823.png)
I am using version of `node v16.20.0`, version `npm6.10.2`


The question would be what is the version of `node` with which I can work with `sharp` that does not give me a problem in the installation

**Comment by danish5454** [comment]
Just update your node.
`brew install node`

**Comment by gwontaeyong** [comment]
> I have the following issue, the exit code is `127` instead of `1`:
> 
> ```
> [4/4] 🔨  Building fresh packages...
> [-/4] ⠠ waiting...
> [-/4] ⠠ waiting...
> [3/4] ⠠ sharp
> error /Users/username/Projects/my-rn-project/node_modules/sharp: Command failed.
> Exit code: 127
> Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> Arguments:
> Directory: /Users/username/Projects/my-rn-project/node_modules/sharp
> Output:
> sharp: Detected globally-installed libvips v8.12.2
> sharp: Building from source via node-gyp
> /Users/username/.nvm/versions/node/v16.15.0/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 5: ~/.nvm/versions/node/v16.13.2/lib/node_modules/node-gyp/bin/n
> ```
> 
> Using Node `v16.13.2`, unsure of a solution yet but I'll update the thread if I find out.

after run 'yarn install --verbose' and output show '/sh node-gyp not found'
do install node-gyp 'npm install --global node-gyp'

**Comment by prushotam** [comment]
I was also having same issue , trying out lots of things .....
yarn install --unsafe-perm
This command worked for me well
![Screenshot (1)](https://github.com/reactjs/react.dev/assets/34192747/2e9a33af-5e5a-4f60-98eb-4f641d82f15c)

Other relevant info regarding the solution
OS - WIN10
Installing deps for the cloned repo
