### ISSUE TITLE
Not able to import json files in TSX files

### ISSUE THREAD

**Issue by synckarthik** [reactjs/reactjs.org#2062]
have tried to import the json file in my react application(App.tsx)

[App.tsx

import * as currencies from './currencies.json';](url)

My Json file will look like below structure:

{
"main": {
"numbers": {
"currencies": {
}
}
}
}

While running the application, it throws the below error

(1,1): unused expression, expected an assignment or function call

After further analysis, i have added the typings.d.ts file within src folder

declare module "*.json" {
const value: any;
export default value;
}

Please suggest your solution to resolve this issue

**Comment by MightyRevenge** [comment]
This answer on SO might help you: https://stackoverflow.com/a/49997144/3436164

**Comment by synckarthik** [comment]
Resolved the issue skipping the lint error in json files. Refer the below link
https://stackoverflow.com/questions/55826319/how-to-resolve-the-issue-unused-expression-expected-an-assignment-or-function
