### ISSUE TITLE
reactjs.org not work

### ISSUE THREAD

**Issue by LaFrish** [reactjs/reactjs.org#207]
The site is down.

**Comment by clemmy** [comment]
https://isitdownorjust.me/reactjs-org/ Seems to be working for me.

**Comment by gaearon** [comment]
It works for me too. Can you share screenshot of the browser with DevTools open?

**Comment by bvaughn** [comment]
Hi @LaFrish! I'm sorry to hear that you were having problems with the website. I wonder if it could potentially be related to issue #14?

We'd love to learn more about what you're seeing. If you have the time to send us a screenshot of your developer console, please do. Any error information logged there could help track down the issue.

**Comment by bvaughn** [comment]
I don't think this issue is actionable so I'm going to close it for now. Would still love to learn more about what went wrong though. We'll re-open the issue if more info becomes available!
