### ISSUE TITLE
error trying to run gatsby dev mode

### ISSUE THREAD

**Issue by wilsonrocks** [reactjs/reactjs.org#2076]
I have something I'd like to contribute to the docs about hooks - but I can't get the docs building in dev mode - output below.

Apologies if I'm missing something really obvious!

> react-website@0.0.1 dev /home/james/coding/reactjs.org
> gatsby develop -H 0.0.0.0

success open and validate gatsby-configs - 0.012 s
success load plugins - 0.484 s
success onPreInit - 0.062 s
success initialize cache - 0.012 s
success copy gatsby files - 0.015 s
success onPreBootstrap - 0.022 s
success source and transform nodes - 0.987 s
error UNHANDLED REJECTION

  TypeError: (0 , _graphql.isScalarType) is not a function
  
  - TypeMapper.js:88 TypeMapper.get
    [reactjs.org]/[graphql-compose]/lib/TypeMapper.js:88:76
  
  - TypeMapper.js:608 TypeMapper.typeFromAST
    [reactjs.org]/[graphql-compose]/lib/TypeMapper.js:608:17
  
  - TypeMapper.js:603 TypeMapper.typeFromAST
    [reactjs.org]/[graphql-compose]/lib/TypeMapper.js:603:24
  
  - TypeMapper.js:105 TypeMapper.getWrapped
    [reactjs.org]/[graphql-compose]/lib/TypeMapper.js:105:17
  
  - TypeMapper.js:272 TypeMapper.convertOutputFieldConfig
    [reactjs.org]/[graphql-compose]/lib/TypeMapper.js:272:114
  
  - configAsThunk.js:19 resolveOutputConfigAsThunk
    [reactjs.org]/[graphql-compose]/lib/utils/configAsThunk.js:19:41
  
  - ObjectTypeComposer.js:300 ObjectTypeComposer.getFieldConfig
    [reactjs.org]/[graphql-compose]/lib/ObjectTypeComposer.js:300:58
  
  - toInputObjectType.js:44 fieldNames.forEach.fieldName
    [reactjs.org]/[graphql-compose]/lib/utils/toInputObjectType.js:44:19
  
  - Array.forEach
  
  - toInputObjectType.js:38 toInputObjectType
    [reactjs.org]/[graphql-compose]/lib/utils/toInputObjectType.js:38:14
  
  - ObjectTypeComposer.js:600 ObjectTypeComposer.getInputTypeComposer
    [reactjs.org]/[graphql-compose]/lib/ObjectTypeComposer.js:600:84
  
  - node-interface.js:19 schemaComposer.getOrCreateOTC.tc
    [reactjs.org]/[gatsby]/dist/schema/types/node-interface.js:19:8
  
  - SchemaComposer.js:382 SchemaComposer.getOrCreateOTC
    [reactjs.org]/[graphql-compose]/lib/SchemaComposer.js:382:54
  
  - node-interface.js:7 getOrCreateNodeInterface
    [reactjs.org]/[gatsby]/dist/schema/types/node-interface.js:7:37
  
  - node-interface.js:83 getNodeInterface
    [reactjs.org]/[gatsby]/dist/schema/types/node-interface.js:83:7
  
  - schema-composer.js:18 createSchemaComposer
    [reactjs.org]/[gatsby]/dist/schema/schema-composer.js:18:3
  
  - index.js:44 Object.<anonymous>
    [reactjs.org]/[gatsby]/dist/schema/index.js:44:28
  
  - Generator.next
  
  - new Promise
  

⠋ building schema
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-website@0.0.1 dev: `gatsby develop -H 0.0.0.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-website@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/james/.npm/_logs/2019-06-14T22_02_14_700Z-debug.log

**Comment by wilsonrocks** [comment]
this is my fault - I was having trouble installing yarn, and trying it via npm - hoping it would work, despite the README - apologies!

**Comment by uc-deepak** [comment]
meaning what exactly did you do ?
