### ISSUE TITLE
[Doc] Link within "HOC" page is not found.

### ISSUE THREAD

**Issue by lexiaoau** [reactjs/reactjs.org#2082]
In [HOC page](https://zh-hans.reactjs.org/docs/higher-order-components.html), the link **[阅读更多 关于我们为什么要抛弃 mixins](https://zh-hans.reactjs.org/blog/2016/07/13/mixins-consideration-hazardous.html)** will lead to a "404" page.

May need to change the link to point this English version:  https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html   , if no Chinese version available now.

**Comment by saranshkataria** [comment]
This issue would belong to https://github.com/reactjs/zh-hans.reactjs.org/ instead of here
