### ISSUE TITLE
Clicking on a link doesn't reset scroll if I came from search results

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#209]
I'm on https://reactjs.org/docs/how-to-contribute.html#contribution-prerequisites.

I'm clicking on this:

<img width="577" alt="screen shot 2017-10-25 at 7 20 56 pm" src="https://user-images.githubusercontent.com/810438/32015652-a3f6bd1e-b9b9-11e7-98d4-e07615d43c00.png">

I end up in the middle of the linked page:

<img width="1020" alt="screen shot 2017-10-25 at 7 21 06 pm" src="https://user-images.githubusercontent.com/810438/32015665-ada36f88-b9b9-11e7-98ad-6dc3f33c85ed.png">

Latest Chrome on OS X.

**Comment by gaearon** [comment]
Hmm. It's not so simple.

This only happens if I come to the original section through search results.

For example:

<img width="595" alt="screen shot 2017-10-25 at 7 23 44 pm" src="https://user-images.githubusercontent.com/810438/32015789-0c6146bc-b9ba-11e7-91b1-1dd3a0d9def5.png">

Now if I go to that page, scroll to the bottom, find a link to the next page and click it:

![](https://user-images.githubusercontent.com/810438/32015652-a3f6bd1e-b9b9-11e7-98d4-e07615d43c00.png)

That's when I end up in the middle of the page.

**Comment by abiduzz420** [comment]
This seems like an interesting bug. I would like to fix this bug and shall update soon if any progress is made.

**Comment by bvaughn** [comment]
This issue is all yours, @abiduzz420! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
Thanks @abiduzz420!
