### ISSUE TITLE
Tutorial navigation highlight should update as you scroll

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#21]
When you click on side-nav items, the page scrolls to that section (with 4px blue span in front of the link text). If you scroll manually to those parts, the side-nav doesn't update to show where you're at.

You can see it on a screenshot, **An Interactive Component** should be active.
![](https://i.imgur.com/zooCABr.png)

Originally reported by @vicodinchik via facebook/react/issues/10984

**Comment by jxom** [comment]
Hey @bvaughn! Can I tackle this one? :)

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!
