### ISSUE TITLE
Is React.createElement necessary when rendering function components without JSX?

### ISSUE THREAD

**Issue by jsejcksn** [reactjs/reactjs.org#2110]
I haven't found the answer to this in the documentation, so perhaps someone on the team can answer and it can be added to the docs:

The homepage gives this example component:

![jsx-on-off](https://user-images.githubusercontent.com/868251/60399633-fd2d9500-9b2c-11e9-97c9-35b1779caec9.gif)

Here is the same code (but as a function component) in JSX:

```jsx
function HelloMessage (props) {
  return (
    <div>
      Hello {props.name}
    </div>
  );
}

ReactDOM.render(
  <HelloMessage name="Taylor" />,
  document.getElementById('hello-example')
);
```

And here is that function component without JSX:

```js
function HelloMessage (props) {
  return React.createElement(
    'div',
    null,
    'Hello ',
    props.name
  );
}

ReactDOM.render(
  React.createElement(HelloMessage, {name: 'Taylor'}),
  document.getElementById('hello-example')
);
```

In the non-JSX example, as the first argument to `ReactDOM.render`, it lists

```js
React.createElement(HelloMessage, {name: 'Taylor'})
```

What I want to understand is this: Is it actually necessary to call `React.createElement` again, since it is already in the return value of the component? Is there any effective difference between that and calling the function component directly, like this?

```js
ReactDOM.render(
  HelloMessage({name: 'Taylor'}),
  document.getElementById('hello-example')
);
```

Here is another example with child components:

```js
function ParentComponent (props) {
  return React.createElement(
    React.Fragment,
    null,
    React.createElement(ChildComponentA, {someValue: props.someValueA}),
    React.createElement(ChildComponentB, {someValue: props.someValueB}),
    React.createElement(ChildComponentC, {someValue: props.someValueC})
  );
}

// vs

function ParentComponent (props) {
  return React.createElement(
    React.Fragment,
    null,
    ChildComponentA({someValue: props.someValueA}),
    ChildComponentB({someValue: props.someValueB}),
    ChildComponentC({someValue: props.someValueC})
  );
}
```

**Comment by leblowl** [comment]
> What I want to understand is this: Is it actually necessary to call React.createElement again, since it is already in the return value of the component? Is there any effective difference between that and calling the function component directly, like this?

I am not a React expert, but I hope this helps.

I believe there is a difference. I think that if the parent calls a child as a function, when the parent re-renders, it will always re-render the child (the child function is always called)... So in your last example, part B:
```
function ParentComponent (props) {
  return React.createElement(
    React.Fragment,
    null,
    ChildComponentA({someValue: props.someValueA}),
    ChildComponentB({someValue: props.someValueB}),
    ChildComponentC({someValue: props.someValueC})
  );
}
```

ChildComponentA, B & C will always get re-rendered when the parent re-renders. When you call ChildComponentA as a function, during code evaluation, the function call will simply be replaced with the function's return value.

In your last example, part A:
```
function ParentComponent (props) {
  return React.createElement(
    React.Fragment,
    null,
    React.createElement(ChildComponentA, {someValue: props.someValueA}),
    React.createElement(ChildComponentB, {someValue: props.someValueB}),
    React.createElement(ChildComponentC, {someValue: props.someValueC})
  );
}
```

You are creating React components out of the children, so they are a bit 'smarter' and keep track of the props passed to them... if the parent re-renders, the children will only re-render if their props change.

So I do not think it's always necessary to use `createElement`, but it can lead to better rendering performance in some cases and at the same time, there is some overhead from the extra component object created.

**Comment by jsejcksn** [comment]
@leblowl Thanks for responding, and thank you for the suggestion to cross-post.

**Comment by jsejcksn** [comment]
Answered at https://github.com/facebook/react/issues/16796
