### ISSUE TITLE
Inheritance code example...

### ISSUE THREAD

**Issue by ebgranger** [reactjs/reactjs.org#212]
There's no code example in the Inheritance section. I think it'd be great to show a simple anti-pattern so other devs might have some familiarity with the smell.

**Comment by gaearon** [comment]
I'm generally hesitant to add these because people tend to copy and paste what they see without really reading.

**Comment by ebgranger** [comment]
I can understand that for sure @gaearon. Do you happen to have any links that might show inheritance in React as an anti pattern, and the issues that can arise? 

I feel like I have a decent understanding/appreciation of composition, but I was looking for a more fleshed out example of the plights of inheritance.

**Comment by gaearon** [comment]
```
class Button extends Component {
  render() {
    return <button style={{ color: this.getColor() }} />
  }
  getColor() {
    return "black"
  }
}

class RedButton extends Button {
  getColor() {
    return "red"
 }
}
```

**Comment by bvaughn** [comment]
I don't think we plan to add an anti-pattern example to the website, for the reason Dan mentioned.

There are some sources online that go into greater detail about why composition can be better than inheritance, eg:
* https://en.wikipedia.org/wiki/Composition_over_inheritance
* http://asserttrue.blogspot.ie/2009/02/inheritance-as-antipattern.html
