### ISSUE TITLE
[Docs] Why 'memoized' not 'memorized' ? 

### ISSUE THREAD

**Issue by Mr-Welson** [reactjs/reactjs.org#2124]
I'm confused that 'memoized' is a conventional word or just a spelling mistake ？
Thanks for answering .

**Comment by alexkrolick** [comment]
It's a real word 😄

https://en.m.wikipedia.org/wiki/Memoization

> memoization or memoisation is an optimization technique used primarily to speed up computer programs by storing the results of expensive function calls and returning the cached result when the same inputs occur again.
