### ISSUE TITLE
[Docs] Unable to navigate on Chrome 

### ISSUE THREAD

**Issue by ErickTamayo** [reactjs/reactjs.org#2132]
I'm unable to expand submenus in the docs using 

Chrome Version 75.0.3770.100 (Official Build) (64-bit)
macOS Mojave 10.14.4

![Screen Capture on 2019-07-07 at 20-00-35](https://user-images.githubusercontent.com/4788817/60778008-60519580-a0f2-11e9-99d7-b93af3df7d88.gif)

I have no problems using Safari. No errors in the console.

**Comment by sergii-zhuravel** [comment]
Hi Erick. I have the same Chrome (Version 75.0.3770.100 (Official Build) (64-bit)) on Mac - no any issues.

**Comment by ErickTamayo** [comment]
For some reason, I had javascript disabled on the website...
