### ISSUE TITLE
传值的问题

### ISSUE THREAD

**Issue by jingkaixuan1998** [reactjs/reactjs.org#2141]
越级传值，与兄弟传值

**Comment by hansenwangvip** [comment]
亲，建议您先学会说人话呢。可以看一下【提问的智慧】：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by jingkaixuan1998** [comment]
你什么意思？咋地 你认识人的汉子？还是听不懂？




------------------ 原始邮件 ------------------
发件人: "Hansen Wang"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 晚上7:15
收件人: "reactjs/reactjs.org"<reactjs.org@noreply.github.com>;
抄送: "温文尔雅！"<2798108745@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [reactjs/reactjs.org] 传值的问题 (#2141)




亲，建议您先学会说人话呢。可以看一下【提问的智慧】：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
