### ISSUE TITLE
Component is not been re-rendered when changing state

### ISSUE THREAD

**Issue by afucher** [reactjs/reactjs.org#2143]
I have a component that has property on state that is an object. When I change the state of this property the component is not been updated on the browser.
If I update any other state property, the component is updated and also shows the updated value of the object property on state.

Here is a example to reproduce it:
1. click on button `Increment object`, check that the component on browser did not update
2. click on button `Increment counter`, check that the component show the updated value.

```import React, {useState} from 'react';

function App() {
  let [counter, setCounter] = useState(0);
  let [objectState, setObject] = useState({a: 1})

  const changeObject = () => {
    const updatedObject = objectState;
    updatedObject.a = objectState.a + 1
    setObject(updatedObject);
  }

  return (
    <div>
      <p>{counter}</p>
      <button onClick={() => {setCounter(counter+1)}}>Increment counter</button>
      <button onClick={changeObject}>Increment object</button>
      <p>{objectState.a}</p>

    </div>
  );
}

export default App;
```

**Comment by madhavgaba** [comment]
@afucher  In you function 
<pre>
const changeObject = () => {
    const updatedObject = objectState;  
    updatedObject.a = objectState.a + 1;  
    setObject(updatedObject);  
}
</pre>
The updatedObject is being used as reference, your way of implementing is equivalent to `this.state.objectState.a += 1` which is not the correct way of doing it.
<pre>
const changeObject = () => {  
    const updatedObject = { ...objectState, a: objectState.a + 1 };   
    setObject(updatedObject);  
}
</pre>
I tried running this in my local machine and it works fine for me!
