### ISSUE TITLE
<h1><h1>Array should have a unique key

### ISSUE THREAD

**Issue by 2675569545** [reactjs/reactjs.org#2148]
If the code in JS is as follows：

    let welcomes = [ <h1>我想说其实你很好</h1>,<h1>你自己却不知道</h1> ];
    ReactDOM.render(
        <div>{welcomes}</div>,
        document.getElementById("root")
    )

He needs key, but I don't know how to give it.If it is like map(),I will give he index.But now,I don't know how to do.

**Comment by madhavgaba** [comment]
Since the array is hard coded, `<h1 key={0}>` should work.

**Comment by 2675569545** [comment]
What do you mean by that?
Like this?
    let welcomes = [ <h1 key={0}>我想说其实你很好</h1>,<h1 key={1}>你自己却不知道</h1> ];
    ReactDOM.render(
        <div>{welcomes}</div>,
        document.getElementById("root")
    )
This requires me to add keys to each of them.

**Comment by madhavgaba** [comment]
Yeah you need to add key to each element since your array is static, for every element key can be the corresponding index, `<h1 key={0}>`, `<h1 key={1}>`, should you need to add elements in the future, you can simply make the corresponding index as the key.

**Comment by erasmuswill** [comment]
I'd recommend rather doing this:

```
let welcome = ['text1','text2'].map((value,i)=><h1 key={i}>{value}</h1>);
```
