### ISSUE TITLE
No github repo for create-react-class

### ISSUE THREAD

**Issue by jaredp** [reactjs/reactjs.org#2189]
There's no way to read the create-react-class source without `npm install`ing it and opening your node_modules.

https://www.npmjs.com/package/create-react-class lists the homepage/repo for create-react-class as the general React homepage and repo (https://facebook.github.io/react/ and https://github.com/facebook/react, respectively).

However, I can't find the create-react-class sources in the main React repo; I assume they were deleted.

I actively rely on create-react-class, especially in my legacy projects.  It would be great if the latest version of the code could be moved to its own repo, and npm pointed there.

**Comment by threepointone** [comment]
Here you go! https://github.com/facebook/react/tree/15.6-dev/addons/create-react-class I think we didn't move it into its own repo because we didn't plan on publishing any more updates, but this branch is the source of truth for this package.

**Comment by jaredp** [comment]
Would it be possible to move this to its own repo, and point the npm package at it, to be good open source citizens?

**Comment by zhangenming** [comment]
same question

**Comment by green-coder** [comment]
Same request - the source code hard to find otherwise.

**Comment by gaearon** [comment]
We have no plans to move its into another repo because we don't plan to make changes to it. You're welcome to setup your own repo from https://github.com/facebook/react/tree/15.6-dev/addons/create-react-class if you'd like.
