### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by kazijosh** [reactjs/reactjs.org#219]
Hi there! 

Are there any plans to add translated content? It would be great to have the docs written in more than one language.

**Comment by bvaughn** [comment]
Yup! This is being tracked via issue #82. There's a Crowdin project in-progress for translating, if you'd be interested in helping out.

**Comment by gaearon** [comment]
https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html

**Comment by fjoshuajr** [comment]
Wow @gaearon, almost forgot I filled this issue.
I'm one of the maintainers on the pt-BR 😃

Keep the good work guys! 👌
