### ISSUE TITLE
Broken download link on /docs/installation

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#23]
The link to "download this HTML file" on the [/docs/installation.html](https://reactjs.org/docs/installation.html) page is broken.

This issue was originally reported by @dbnex14 via facebook/react/issues/10994

**Comment by leticiawanderley** [comment]
Can I try to fix this?

**Comment by bvaughn** [comment]
It's all yours!

Please let me know if you decide not to submit a PR and I'll remove the "in-progress" label.

**Comment by yangshun** [comment]
This issue has been fixed by #32

**Comment by bvaughn** [comment]
Thanks!

**Comment by dbnex14** [comment]
Much appreciated
