### ISSUE TITLE
property "og: image: url" cannot be parsed as type "url"

### ISSUE THREAD

**Issue by sato-hirokazu** [reactjs/reactjs.org#2318]
## phenomenon
Since the value "/logo-og.png" specified in property "og: image: url" cannot be parsed as type "url", the object of URL "https://reactjs.org/" (type "website") Is invalid.

## Target URL
https://reactjs.org

## debug-tools 
https://developers.facebook.com/tools/debug/og/object/

**Comment by threepointone** [comment]
Fixed separately, thanks!
