### ISSUE TITLE
Does react has an ECCN?

### ISSUE THREAD

**Issue by otramony** [reactjs/reactjs.org#232]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption. Thanks.

**Comment by bvaughn** [comment]
Hi @otramony,

I don't know the answer to this, but I'll ask internally and get back to you.

**Comment by bvaughn** [comment]
Sorry for the wait.

The applicable ECCN is EAR99.
