### ISSUE TITLE
CSS recommendations?

### ISSUE THREAD

**Issue by kaycebasques** [reactjs/reactjs.org#235]
I'm finding it strange that the site doesn't give any guidance on how to handle styling!

You probably don't enforce any particular approach, but it'd be helpful to explicitly say that, and to provide a list of popular approaches.

**Comment by alexkrolick** [comment]
I added a little bit of styling guidance to the FAQ, which is in PR #43

**Comment by bvaughn** [comment]
Marking this one in progress since @alexkrolick already has PR #43

**Comment by alexkrolick** [comment]
#43 is merged

👀  https://reactjs.org/docs/faq-styling.html

**Comment by bvaughn** [comment]
Cheers
