### ISSUE TITLE
The additionalHooks option of the exhaustive-deps ESLint rule

### ISSUE THREAD

**Issue by vkrol** [reactjs/reactjs.org#2350]
Hello!

I didn't find any mention of that option anywhere. Is the `additionalHooks` option of the `exhaustive-deps` ESLint rule stable enough? If that's so, it's a good idea to document it.

https://github.com/facebook/react/blob/9e64bf18e11828d6b4c0363bff5ed2eca1ccd838/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L32
https://github.com/facebook/react/blob/9e64bf18e11828d6b4c0363bff5ed2eca1ccd838/packages/eslint-plugin-react-hooks/__tests__/ESLintRuleExhaustiveDeps-test.js#L260

**Comment by thecotne** [comment]
it is documented in react repo here https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/eslint-plugin-react-hooks/README.md#advanced-configuration

**Comment by rickhanlonii** [comment]
Hey @vkrol, thanks for submitting. This is documented on the NPM page [here](https://www.npmjs.com/package/eslint-plugin-react-hooks), which is the documentation for the package and is taken from the README linked above.

**Comment by waynebloss** [comment]
In VS Code I'm getting this advice about a `stableHooksPattern` advanced configuration [1] but when I add that to my `.eslintrc.cjs` file and run `eslint .`, I am getting an error [2].

When I switch to using `"additionalHooks": "(usePlatform|useWorkbench)"` in `.eslintrc.cjs` the `eslint .` command works, but then VS Code doesn't work anymore.

[1] 
![image](https://github.com/reactjs/react.dev/assets/623736/ed1f8d43-86aa-4c2f-a10c-e41a57ef4115)

[2] 
> Error: .eslintrc.cjs:
>        Configuration for rule "react-hooks/exhaustive-deps" is invalid:
>        Value {"stableHooksPattern":"usePlatform|useWorkbench"} should NOT have additional properties.

**Comment by waynebloss** [comment]
Clarification - the suggestion `@example` shown above is from my own jsdoc comment. The actual error I'm receiving is that my React Hook is "received a function whose dependencies are unknown". but the code I'm calling is not even passing a function, e.g. `usePlatform("logger", "workbench")`

However, I realize now that this github repo is for the react.dev site and that these notes really don't belong here. Thanks
