### ISSUE TITLE
eslint-plugin-react-hooks release numbering in "Releases" tab

### ISSUE THREAD

**Issue by croraf** [reactjs/reactjs.org#2352]
On https://github.com/facebook/react/releases, `eslint-plugin-react-hooks` release notes are documented, like:
![image](https://user-images.githubusercontent.com/19698636/65028355-38757e00-d93c-11e9-8d38-b766d3ceb32f.png)

But the plugin has different release numbering (v2.0.1 for example) than `react` (v16.9.0). This is not reflected here in release notes.

**Comment by nickmccurdy** [comment]
We might want to add packages/eslint-plugin-react/CHANGELOG.md like we have in the other packages

**Comment by croraf** [comment]
But also this page I screenshot should be fixed.

**Comment by threepointone** [comment]
Curious, why does this matter?

**Comment by nickmccurdy** [comment]
Because you wouldn't be able to easy find the release notes for a particular eslint-plugin-react-hooks version (and vice versa)

**Comment by threepointone** [comment]
Yeah that’s fair. We should do better with this.

**Comment by gunn4r** [comment]
Just chiming in... just saw major release 3.0.0 come through and I am trying to find some release notes so I know what the breaking changes are.

**Comment by houmark** [comment]
I agree that these packages should have their own changelog.

In the meantime, for eslint-plugin-react-hooks, you can look at the history for the directory of the plugin source code here (there seem to be no breaking changes):
https://github.com/facebook/react/commits/master/packages/eslint-plugin-react-hooks

**Comment by gaearon** [comment]
Yeah looking at the commit history in the package folder is the easiest way.

I bumped the major because we cut a version that is stricter and doesn’t let you call Hooks in a class. That can cause false positives, hence a major bump.

https://github.com/facebook/react/commit/d3368beeecb2b51f51814f95f977e8c11900f54e#diff-abcd3df96e981cf0ab8ee6fc2866953c

> We might want to add packages/eslint-plugin-react/CHANGELOG.md like we have in the other packages

I think this is a reasonable suggestion because it is standalone. I’ll take a PR doing this.

**Comment by dominicfraser** [comment]
Changelog has been added here: https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/CHANGELOG.md
