### ISSUE TITLE
React.memo does not act the same as the document mentioned

### ISSUE THREAD

**Issue by PejmanNik** [reactjs/reactjs.org#2359]
Hi in the documentation you mention it shallowly compare complex objects **in the** props object.
but it just shallowly compare the props object.

https://reactjs.org/docs/react-api.html#reactmemo:
>By default it will only shallowly compare complex objects in the props object. If you want control over the comparison, you can also provide a custom comparison function as the second argumen 

I mean by that sentence I expect this prop doesn't cause re-run the render but it does:

```js
const Test = React.memo(...);
<Test simple={1} complex={{ a: 'a', b: 'b' }} />
```

**Comment by threepointone** [comment]
`complex` is a new object in every render, so this does in fact fail a shallow compare.

**Comment by PejmanNik** [comment]
Thank you @threepointone 
So if I memorize the `complex` with `useMemo` and then change `a` prop value it case re-render?

**Comment by alexkrolick** [comment]
Yes, the identity of the inline object assigned to complex changes when you create it inline. Remember it looks like this without JSX:

```js
React.createElement(Text, {simple: 1, complex: {a: 'a', b: 'b'}})
```

**Comment by PejmanNik** [comment]
Am I doing it wrong?

https://jsfiddle.net/PejmanNik/j6p9rhau/

**Comment by threepointone** [comment]
That link 404s, but I hope the explanation is clear.
