### ISSUE TITLE
useEffect with React Native

### ISSUE THREAD

**Issue by tim92109** [reactjs/reactjs.org#2389]
Since I would expect the docs on ReactJS to be compatible with React Native - and these docs are very clearly and detail-written (compared to React Native), it seems like the useEffect hook is specific to ReactJS and the DOM.  But I have my doubts, so I wanted to mention this imperfection in the docs where the primary example of useEffect is used on document.title.  I can think of much, much better and still simple examples to use if this is something that is also a good reference for React Native developers.  Thanks!

**Comment by threepointone** [comment]
I believe the react native docs now use hooks extensively.
