### ISSUE TITLE
Link to Babeljs.io repl incorrect.

### ISSUE THREAD

**Issue by ptrmelko10** [reactjs/reactjs.org#240]
The "See full expanded version" link to babeljs.io in content/tutorial/tutorial.md is not interpreting the html character codes for non-alphanumeric characters correctly in production. The link is working correctly when selected from within the markdown file in the repo.

This is what is loaded into babel in production:
```
<div className%3D"shopping-list">
  <h1>Shopping List for {props.name}<%2Fh1>
  <ul>
    <li>Instagram<%2Fli>
    <li>WhatsApp<%2Fli>
    <li>Oculus<%2Fli>
  <%2Ful>
<%2Fdiv>
```
Product URL snippet: `className%253D%22shopping-list`
Markdown URL snippet: `className%3D%22shopping-list`

Reproduced in:
Google Chrome Version 61.0.3163.100
Google Chrome Version 62.0.3202.75 
Firefox 56.0.2

Work around:
Update the code in babel after following the link.

I can probably take a look at this later unless someone else wants to grab this.

**Comment by gaearon** [comment]
Wanna send a fix?

**Comment by ptrmelko10** [comment]
Sure, I'll take a look over the weekend. Do the markdown files go through some sort of build process  before it hits production?

**Comment by bvaughn** [comment]
Thanks for catching this!

> Do the markdown files go through some sort of build process before it hits production?

I had an idea (mentioned [here](https://github.com/reactjs/reactjs.org/pull/150#discussion_r146117461)) of auto-generating the links during build, but currently they are hard-coded.

**Comment by bvaughn** [comment]
This issue is all yours, @ptrmelko10! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
@ptrmelko10 Have you started on this, by chance? If not I'd like to pick it up. After working on #251 I have a pretty good idea of how we could auto-generate links during build in the way I mentioned.

**Comment by bvaughn** [comment]
I'm going to toss up a PR that's related to this, but a bit broader, just because I'm thinking about it at the moment. I'll CC you on it for discussion! 😄

**Comment by bvaughn** [comment]
Since my PR fixed a couple of additional issues (not just the one mentioned in this issue) I went ahead and merged it. I hope this is okay and I didn't step on your toes, @ptrmelko10. 🙏 Many apologies if I did.

Let's chat more if you have any concerns or follow-up suggestions to the approach I took in #255!

**Comment by ptrmelko10** [comment]
@bvaughn it's all good. I didn't get much time to look this over. I'll review #255 since I figured the problem had something to do with gatsby.
