### ISSUE TITLE
Links in without extension disable navigation

### ISSUE THREAD

**Issue by BookOfGreg** [reactjs/reactjs.org#241]
If you come from [google](https://www.google.co.uk/search?q=react+server+side+rendering&gws_rd=cr&dcr=0&ei=QhP_Wc6sL4mosAfCprgI) on "react server side rendering" you are sent to `https://reactjs.org/docs/react-dom-server` instead of `https://reactjs.org/docs/react-dom-server.html`.

And all links on the page are disabled with this console warning.

<img width="720" alt="screen shot 2017-11-05 at 13 32 46" src="https://user-images.githubusercontent.com/637868/32415211-da196ece-c22d-11e7-98a9-333c4b95ed27.png">

---

Browser: Chrome 62
OS: MacOS 10.12.6

**Comment by bvaughn** [comment]
Interesting. I wonder if this is a known Gatsby issue or if we're misusing it? Possibly related to gatsbyjs/gatsby/issues/1838.

I _think_ Gatsby auto-redirects without extensions. I _don't think_ it's expected that things would break like this in that case.

**Comment by erquhart** [comment]
Note: this is now happening on all pages, regardless of how you come in.

**Comment by emmafallancy** [comment]
@bvaughn if somehow Gatsby couldn't find any resource to the page, any navigation link would not be possible to be click. The click issue is a known bug, especially for page not found. For the redirect issue, I have no clue about it, since I can actually see the page but it is reported as not being able to find the page 😐

**Comment by awayken** [comment]
I just visited https://reactjs.org/docs/react-dom-server and was redirected automatically to https://reactjs.org/docs/react-dom-server.html. Does that mean this issue can be closed?

**Comment by gaearon** [comment]
Probably.

**Comment by BookOfGreg** [comment]
👍 Can no longer reproduce my original issue so it must have been fixed at some point.
