### ISSUE TITLE
Making context official

### ISSUE THREAD

**Issue by drcmda** [reactjs/reactjs.org#243]
After context being in React for such a long time, can someone please remove the "experimental" clause in the React docs as it keeps 3rd party maintainers from allowing us to use it. 

One such case is react-redux, where connect blocks context in order to prevent liability concerns. It forces us to inject objects and propagate down the tree again. https://github.com/reactjs/react-redux/issues/289 Although in this case Dan said it wouldn't be possible to read arbitrary types (though, aren't contextTypes static?), i'm citing this also because of the sentiment.

Context is a highly valuable addition to React and without it some parts would be very hard to realize, or perhaps even impossible. Thousands of 3rd party controls use it at this point. It would be nice to know that it is finally deemed an official part of React without the scary possibility that it might be removed.

**Comment by bvaughn** [comment]
Context has been in React for a long time, but it is still an unofficial API that we generally recommend _against_ using (except in special cases). The team has plans to redesign context eventually- making it a part of the official, supported API- but until we do that, context as it is currently implemented (with its current flaws) will remain experimental.

See related issue facebook/react/issues/9411
