### ISSUE TITLE
Why does the main page of React not give an EXACT INSTALLATION GUIDE for actual developers?

### ISSUE THREAD

**Issue by cyphire** [reactjs/reactjs.org#2437]
Have an advanced option to install React and a page showing all the other things which should be upgraded installed for React.

**Comment by ndresx** [comment]
Doesn't [Create a New React App](https://reactjs.org/docs/create-a-new-react-app.html) cover this part already?

**Comment by cyphire** [comment]
Not really... You really need to wade through the first page react.com, go to the next page then all the content on the left (including Create a New React App) has no hyperlinks.  So you need to look to the right column and then click (Create a new React App), to then go to another page where half way down it shows up.

So for someone who is a developer seeing the web site for the first time it isn't even slightly clear where to go to get going!

At the minimum, put a hyperlink in the Create a new App page in the content section on the left side, not in the right side column.

I shouldn't have to spend 10 min looking through pages of content to just see how to install.

Just my opinion.

**Comment by gaearon** [comment]
This doesn't seem like 10 minutes to me:

![Screen Recording 2019-10-18 at 06 55 PM](https://user-images.githubusercontent.com/810438/67116737-fbb9d280-f1d8-11e9-9987-78b93257d71c.gif)


Is there a particular point where you "fell off"? Thanks.

**Comment by cyphire** [comment]
Hey Dan,

I think that   several JavaScript toolchains
<https://reactjs.org/docs/create-a-new-react-app.html>  isn't a proper
hyperlink to the Create a New React App page (which is on right).  Do you
really think that is intuitive for someone to use?

On the right side you have Add React to a Website & Create a New React
App.  Why not use those two gestalts in the paragraph on left rather than
"add React to an HTML page in one minute" (Which is fine) and "Create a New
React App" vs the "several Javascript Toolchains" hyperlinked verbiage as
it exists?

By the way - huge fan of you and the work you have done!  Kudos.

I promise I'm not knitpicking.  It didn't occur to me that "several
Javascript Toolchains" was the entry point!  If i had noticed the
difference on the right I would have gone there.

Best,

Brian.
_________________________________________
Brian B. Canin    brian.canin@gmail.com

858-945-5601 (cell)
