### ISSUE TITLE
Link to research / researches regarding human computer interaction

### ISSUE THREAD

**Issue by divyanshu013** [reactjs/reactjs.org#2480]
Thanks for rolling out concurrent mode docs!

While going through the docs, in particular [putting research into production section](https://reactjs.org/docs/concurrent-mode-intro.html#putting-research-into-production). There is a mention of research / researches around human-computer interaction. Would it be possible to link to these? Can send a PR if I've the links to research(es).

Thanks!

**Comment by threepointone** [comment]
Nothing that we can link to at the moment since it’s mostly internal to fb. Maybe in the future!
