### ISSUE TITLE
Minimum system requirement for React JS ? 

### ISSUE THREAD

**Issue by hamza5746** [reactjs/reactjs.org#2543]

**Comment by sophiebits** [comment]
Any machine with a code editor and a browser should be able to develop for React. Here's the most barebones way: https://reactjs.org/docs/add-react-to-a-website.html

**Comment by thirusubash** [comment]
> Any machine with a code editor and a browser should be able to develop for React. Here's the most barebones way: https://reactjs.org/docs/add-react-to-a-website.html
Starting the development server...

ok 
trying to run Ec2 t2micro machine instance , i got this 
<--- Last few GCs --->

[18693:0x55da16277ea0]    53844 ms: Scavenge (reduce) 398.6 (409.8) -> 398.0 (410.1) MB, 1.5 / 0.0 ms  (ave                                                                                                                                  rage mu = 0.235, current mu = 0.084) allocation failure
[18693:0x55da16277ea0]    53854 ms: Scavenge (reduce) 398.8 (410.1) -> 398.2 (410.3) MB, 1.7 / 0.0 ms  (ave                                                                                                                                  rage mu = 0.235, current mu = 0.084) allocation failure
[18693:0x55da16277ea0]    53864 ms: Scavenge (reduce) 398.9 (410.3) -> 398.4 (410.6) MB, 1.4 / 0.0 ms  (ave                                                                                                                                  rage mu = 0.235, current mu = 0.084) task


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x55da121c34c4 node::Abort() [/usr/bin/node]
 2: 0x55da1207cf02 node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0x55da123c273a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0x55da123c29c6 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/u                                                                                                                                  sr/bin/node]
 5: 0x55da12561799  [/usr/bin/node]
 6: 0x55da125618dc  [/usr/bin/node]
 7: 0x55da12579d35 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallb                                                                                                                                  ackFlags) [/usr/bin/node]
 8: 0x55da1257a5f4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageC                                                                                                                                  ollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0x55da1257d634 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType,                                                                                                                                   v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0x55da1257d6c9 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType                                                                                                                                  , v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
11: 0x55da12547baf v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::inte                                                                                                                                  rnal::AllocationOrigin) [/usr/bin/node]
12: 0x55da12888140 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isola                                                                                                                                  te*) [/usr/bin/node]
13: 0x55da12c5f919  [/usr/bin/node]
[ec2-user@ip-10-0-100-157 gksvp-com]$




![image](https://user-images.githubusercontent.com/74720300/155933048-9106e15f-d402-4c88-ae2a-2eb977601abd.png)
