### ISSUE TITLE
How to find Docs for Jest, Enzyme, Create-React-App, Shallow()?

### ISSUE THREAD

**Issue by suitcasemedia** [reactjs/reactjs.org#2545]
Im using Create React App and have set up my test files like this:

```
import React from 'react';
import { shallow, configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
```
Then I set up wrapper using shallow() like this:

```
let wrapper;
  beforeEach(() => {
    const defaultProps = {
      color: 'orange',
      value: 17,
      title: 'live services',
      link: 'htttp://google.com'
    };

    wrapper = shallow(<Callout {...defaultProps} />);
  });
```
Im using assertions that I have been using for a while such as

```
expect(wrapper.find('h5').html()).toContain('some title');
expect(wrapper.containsMatchingElement(<Foo />)).toBe(true);
```
These assertions work but i want to find more.

I have no idea where to find the docs for the assertions that are available to me. The assertions I have working so far look a bit like Jasmine assertions in that they are using camel case but the methods are still named differently. https://jasmine.github.io/

I thought I was using jest and enzyme but the assertions are completely different to those in the Enzyme docs https://airbnb.io/enzyme/ For example

`expect(wrapper.find(Foo)).to.have.lengthOf(3);`

Does not work. These methods of find() are not available to my current set up. How do I see what assertions are available to shallow() and shallow.find() with my current setup?

In the Jest Docs I can only find assertions for testing javaScript functions and can't find any methods for traversing and testing Virtual DOM or shadow DOM elements like the ones I have been using( see above) https://jestjs.io/docs/en/jest-object

**Comment by alexkrolick** [comment]
- Enzyme provides the wrapper methods like `.find`, so use their docs for that
- Jest provides expect() and the methods attached to it, such as `expect(x).toHaveLength()`
  - The example you gave `.to.have.lengthOf(3)` are from Chai which is commonly used with Mocha (not Jest, which ships with the Jasmine assertions built in) https://www.chaijs.com/api/bdd/#method_language-chains
