### ISSUE TITLE
Document change request: isMounted antipattern

### ISSUE THREAD

**Issue by styrmani** [reactjs/reactjs.org#2554]
Does it really mean using _isMounted state instead of property?

> An easy migration strategy for anyone upgrading their code to avoid isMounted() is to track the mounted status yourself. Just set a _isMounted property to true in componentDidMount and set it to false in componentWillUnmount, and use this variable to check your component's status.

[ismounted-antipattern](https://github.com/reactjs/reactjs.org/blob/master/content/blog/2015-12-16-ismounted-antipattern.md)

**Comment by danburzo** [comment]
It means setting a property in the JavaScript sense to the component:

```js
class MyComponent extends React.Component {
    componentDidMount() {
        this._isMounted = true;
    }

    componentWillUnmount() {
      this._isMounted = false;
    }
}
```

Using the component state for this purpose would be counter-productive.

**Comment by styrmani** [comment]
Thanks!
