### ISSUE TITLE
Where do I can edit page in my language?

### ISSUE THREAD

**Issue by namnguyen2091** [reactjs/reactjs.org#2582]
I detect a grammar mistake in this page https://vi.reactjs.org/docs/hooks-effect.html and I want to edit this. So, where do I can edit and create pull request by what rule?

**Comment by danielpox** [comment]
Hi! The repo you’re looking for is over at https://github.com/reactjs/vi.reactjs.org/. Check for existing issues or pull requests, and if you can’t find a fix, then go ahead and follow the Prerequisites and Contributing section of the README.md. 🙂
