### ISSUE TITLE
Update documentation to show that className can be object

### ISSUE THREAD

**Issue by knobo** [reactjs/reactjs.org#2591]
Please update the documentation to show that className can be an object, and that react does .toString() on the argument.

**Comment by sophiebits** [comment]
I don't know that I would recommend that practice, but we do have this blog post describing how objects are stringified:

https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Comment by knobo** [comment]
It's for supporting libraries like bem-cn.
