### ISSUE TITLE
Unit test: ReferenceError: InputEvent is not defined or Failed to execute 'dispatchEvent'

### ISSUE THREAD

**Issue by maufarinelli** [reactjs/reactjs.org#2597]
Regarding to Events, I did not find a way to test InputEvent
Consider this codesandbox: https://codesandbox.io/s/mutable-firefly-zpz5e

I took the Toggle example from https://reactjs.org/docs/testing-recipes.html
and I also added another component called Input, which basically is a simple Input text

in Input test, I am trying to dispatch an InputEvent, and I have the following error:
`TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.`
in my project, I was having `ReferenceError: InputEvent is not defined` instead.

Toggle tests dispatch a MouseEvent click and it works (BTW, the test at your page is wrong because initial state is `false`, so the button has `Turn on` label instead :))

I am doing something wrong or there is an issue here?

**Comment by sophiebits** [comment]
These issues are intended for tracking issues related to the documentation. It sounds like you're having trouble understanding how to extend the example in the docs to another situation. I'd suggest asking in one of the community resources at https://reactjs.org/community/support.html, as this isn't the right place.

If you figure out what is wrong and that there is a way to improve the docs, feel free to comment back here or open a new issue.
