### ISSUE TITLE
Documenting best practices around creating component libraries

### ISSUE THREAD

**Issue by o-t-w** [reactjs/reactjs.org#2613]
Because React development is very dominated by Next.js and create-react-app, it can be difficult to know how to proceed without those tools. 

Justin Fagnani listed [best practices for publishing web components to NPM](https://justinfagnani.com/2019/11/01/how-to-publish-web-components-to-npm/). Similar guidance for React components and component libraries would be very useful

**Comment by TransmissionsDev** [comment]
Would love to see this!

**Comment by o-t-w** [comment]
<img width="779" alt="Screenshot 2019-12-17 at 12 16 29" src="https://user-images.githubusercontent.com/29547922/70995191-de658f80-20c7-11ea-88e8-5446ce3ad33d.png">
This is currently all that the docs bother to say - point to some blog post. What is the minimum viable set-up to use React? This is never explained in the docs!

**Comment by sophiebits** [comment]
We typically document how React itself works, rather than trying to catalog best practices for the entire ecosystem. As a result, I am not sure the docs are the right place for this right now. Community blog posts are a great place for this sort of content.

The minimum viable setup for using React is here: https://reactjs.org/docs/add-react-to-a-website.html.

**Comment by o-t-w** [comment]
@sophiebits I agree that the React docs themselves should be neutral about tools rather than attempting to document Webpack _and_ Parcel _and_ Rollup, for example. However, the resource I linked to was a [tool-agnostic guide](https://justinfagnani.com/2019/11/01/how-to-publish-web-components-to-npm/) to some basic best practices. This undoubtedly _would_ be useful for many people so I disagree with this issue being closed. This is the part of React that leaves many people feeling lost and confused.

**Comment by o-t-w** [comment]
For example, how many people even know about this issue?: https://twitter.com/housecor/status/1195753315067297792
