### ISSUE TITLE
Node.js 8 End-Of-Life closing in

### ISSUE THREAD

**Issue by danielpox** [reactjs/reactjs.org#2617]
This project enforces the use of Node.js version `>8.4.0`, however Node.js 8 will reach its ”End-Of-Life” on [December 31, 2019](https://nodejs.org/en/about/releases/). Currently it does not seem like the project runs in any version higher than 8.

What’s the plan forward, as maintenance support for version 8 is dropped?

**Comment by threepointone** [comment]
Why do you say it doesn’t work for version above 8?
