### ISSUE TITLE
Link to Oceanic Next theme has expired

### ISSUE THREAD

**Issue by naveedali8086** [reactjs/reactjs.org#2627]
One link at following page says that the domain has expired.

https://reactjs.org/docs/introducing-jsx.html

Steps:

1. - Go to above URL
2. - Find the text 'Oceanic Next' (in Tips section at bottom) and click
3. - 'Domain has expired' is received as a response.

**Comment by vnoitkumar** [comment]
Given PR for that https://github.com/reactjs/reactjs.org/pull/2636

**Comment by threepointone** [comment]
Closing as fixed
