### ISSUE TITLE
Amazing tutorial - time for hooks?

### ISSUE THREAD

**Issue by uffehellum** [reactjs/reactjs.org#2644]
Thank you for hosting a great tutorial for beginners like me.

Instead of object components, maybe it's time to use react hooks for state?

I pulled out the model objects for Game and Board, and changed the components to use hooks for state instead. To me, this seems more beginner friendly than redux or object components with state.

It requires that the data model is not mutated, so there's some JS grittiness, but the model objects can be unit tested separately.

https://github.com/uffehellum/react-tictactoe-hook

I also wanted to have some best practice of method pairs undo/canUndo, so it's easier to make the UI show which actions are available.

My example is certainly not as polished as your tutorial, I just wanted to offer the suggestion to simplify your tutorial with hooks.

Thanks
Uffe

**Comment by objarni** [comment]
I agree with this almost 3 year old comment; hooks make a much cleaner syntax, without reduces expressivity. Why teach the dated class syntax in the tic-tac-toe-tutorial?

**Comment by eps1lon** [comment]
The main page now has a banner pointing to the [beta docs](https://beta.reactjs.org/) which are written with a hooks-first approach. Remember that those docs are still in beta and some things might be missing. We're actively looking for feedback for the beta docs so if you're looking for docs with hooks in mind, please check https://beta.reactjs.org/ out.
