### ISSUE TITLE
CodePen Examples in Tutorial Not Working

### ISSUE THREAD

**Issue by ofthedove** [reactjs/reactjs.org#2669]
When I follow the link in the tutorial for the "Final Result" or "Starter Code" CodePen examples, the examples do not work and I receive the error:
```
ReferenceError: React is not defined
    at pen.js:115:22
```

I've not used CodePen before, so I'm not sure if this is an issue with their site or with the configuration of the example.

My setup:
Chrome 79.0.3945.88 and Firefox 72.0.1 (same issue in both)
MacOS Mojave 10.14.6

**Comment by classicmatsuo** [comment]
@ofthedove i cant duplicate your error
you're referring to [Starter Code](https://codepen.io/gaearon/pen/oWWQNa?editors=0010) and [Final Result](https://codepen.io/gaearon/pen/gWWZgR?editors=0010), correct?

env:
`Chrome 79.0.3945.117`
`Firefox 72.0.1`
`macOS Mojave 10.14.6`

**Comment by ofthedove** [comment]
Yes, that's correct. Here's a screenshot of what I see in CodePen when I follow the Starter Code link in the tutorial: https://i.imgur.com/X2YpSXT.png
This is what the JS settings look like in CodePen: https://i.imgur.com/yNyhHlC.png

I created these screenshots in Chrome Version 79.0.3945.117

**Comment by classicmatsuo** [comment]
@ofthedove have you tried disabling your browser plugins? 
[known-issues-with-codepen](https://guide.freecodecamp.org/miscellaneous/known-issues-with-codepen/)

**Comment by ofthedove** [comment]
Using incognito mode didn't help, but I think it must be the network I've been using. Once I switched to a different network the error went away. Thanks for helping me troubleshoot!

**Comment by classicmatsuo** [comment]
@ofthedove close issue #2669
