### ISSUE TITLE
Warn about X.PropTypes rather than X.propTypes

### ISSUE THREAD

**Issue by AChaoZJU** [reactjs/reactjs.org#268]
The section  [Requiring Single Child](https://reactjs.org/docs/typechecking-with-proptypes.html#requiring-single-child) provides an API of checking `Requiring Single Child`.
<br>
The example code of this section:
```
import PropTypes from 'prop-types';

class MyComponent extends React.Component {
  render() {
    // This must be exactly one element or it will warn.
    const children = this.props.children;
    return (
      <div>
        {children}
      </div>
    );
  }
}

MyComponent.propTypes = {
  children: PropTypes.element.isRequired
};
```

However, it doesn't work in my code.  It is supposed to print a warning because two children are passed to a component as children. However, there is no warning.

```

import PropTypes from 'prop-types';
import React from 'react'

class MyComponent extends React.Component{
    render(){
        const children = this.props.children;
        return(
            <div>
                {children}
            </div>
        )
    }
}

// more than one child are passed to a component as children
// but there is no warning
function Test(){
    return(
        <MyComponent name='test3'>
            <p>child1</p> 
            <p>child2</p>
        </MyComponent>
    )
}

MyComponent.PropTypes = {
    children:PropTypes.element.isRequired
}

export default Test;
```
Is there any problem in myCode ?
<br>
my environment

- react: v16.0.0
- browser: 62.0.3202.75

**Comment by gaearon** [comment]
`MyComponent.PropTypes` is wrong. It should be `MyComponent.propTypes`.

Maybe we should add a warning for this? Tagging as a good first bug.

**Comment by gaearon** [comment]
Oh. Actually I should file this in React repo.
But the documentation is correct.

**Comment by AChaoZJU** [comment]
@gaearon  thank you for your reply

I should have been more careful.
