### ISSUE TITLE
Documentation about which style numeric values are treated as pixels is missing

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#27]
This change was originally requested by @Kovensky via facebook/react/issues/10418

This used to exist in the React 15 documentation under the Tips section, but mentions to this support are now missing entirely.

The old documentation page: https://github.com/facebook/react/blob/8cac523beaaacfeae179ca14a1d8a46d82892016/docs/tips/06-style-props-value-px.md

This was removed in commit 455d2d1b48e5cdaeac5d0b4fd92b29b4d52bcaec

**Comment by FannyVieira** [comment]
basically it is necessary to add the information of the pixels to this page? https://reactjs.org/docs/dom-elements.html#style

**Comment by Kovensky** [comment]
An important thing that new documentation needs to mention is that, as of React 16, this only applies to _actual_ `number` values. Numeric `string`s used to work (with a warning in React 15), but now they are always passed as-is.
