### ISSUE TITLE
Post data into a api

### ISSUE THREAD

**Issue by harmit001** [reactjs/reactjs.org#2706]
we are posting data into api using react js.

here is the code that we have a write to send json data into the api using react js.

but we are facing cross origin error.

and also our api have a barrier auth so please guide us to pass json data and get response.

**Comment by ayomidebajo** [comment]
Where is the code?

**Comment by alexkrolick** [comment]
This repo is not the best place to get help using the library.
Here is a list of places to get support 😄 : https://reactjs.org/community/support.html
