### ISSUE TITLE
Typo in Context example

### ISSUE THREAD

**Issue by tannaurus** [reactjs/reactjs.org#2723]
Discovered what I believe to be a typo in the context documentation.

You can find it [here](https://github.com/reactjs/reactjs.org/blob/master/examples/context/motivation-solution.js#L39).

<img width="670" alt="Screen Shot 2020-02-07 at 10 11 19 AM" src="https://user-images.githubusercontent.com/25316168/74054129-3e730680-4992-11ea-92a4-6076d83e5e32.png">

The code pictured is referencing `this.context` when it should be `this.contextType`

**Comment by krishna7860** [comment]
I want to take this as My First Contribution 
Right version : 
`render(){
   return<Button theme={this.contextType} />;
}`

**Comment by tannaurus** [comment]
This may have been opened due to a misunderstanding. I'm making my way through the rest of the documentation right now, I'm [reading](https://reactjs.org/docs/context.html#classcontexttype) that 

> The contextType property on a class can be assigned a Context object created by React.createContext(). This lets you consume the nearest current value of that Context type using this.context. You can reference this in any of the lifecycle methods including the render function. 

Perhaps that should be explained (or linked) in/near the pictured block in the issue body.

**Comment by krishna7860** [comment]
Hmm Right this.context explicitly refer to the nearest context
