### ISSUE TITLE
DOM inspector image broken for rendering elements

### ISSUE THREAD

**Issue by janat08** [reactjs/reactjs.org#274]
https://reactjs.org/docs/rendering-elements.html has broken image for dom inspection that is demonstrative at the very bottom.

**Comment by bvaughn** [comment]
There's only 3 `img` elements on the page you listed: One in the header, one in the footer, and one in the body content. All seem to load correctly for me.

<img width="583" alt="screen shot 2017-11-11 at 11 20 28 am" src="https://user-images.githubusercontent.com/29597/32688956-584ac556-c6d2-11e7-9ca3-388e1a81391a.png">

Are you sure this wasn't just a transient network issue? Could you provide any more detail (like what error message you're seeing or what's shown in the network console?)
