### ISSUE TITLE
Are hooks synchronous?

### ISSUE THREAD

**Issue by gajomon** [reactjs/reactjs.org#2748]
I've searched in the docs but didn't found this information. So, hooks are synchronous or asynchronous?

**Comment by gajomon** [comment]
Still no answers :(

**Comment by developerantoniosousa** [comment]
@gajomon hooks are synchronous

**Comment by gajomon** [comment]
Alright, thanks

**Comment by hashinclude72** [comment]
you cant define a hook as `async` because they are not supposed to return a promise. If you do it will result in race conditions. So instead async function inside the hook and then call it.

**Comment by gajomon** [comment]
Alright, I've tried it and you're right, hooks doesn't returned a promise. Thanks
