### ISSUE TITLE
About useState hook

### ISSUE THREAD

**Issue by gajomon** [reactjs/reactjs.org#2753]
Why we need to call the useState function with an arrow function, like in this code:

```
<button onClick={() => setCount(count + 1)}>Click me!</button>
```

Istead of simply:

```
<button onClick={setCount(count + 1)}>Click me!</button>
```

**Comment by developerantoniosousa** [comment]
You should use arrow function (or normal function), because your function only run when someone click on button, else function is run when your component is rendered

**Comment by gajomon** [comment]
That makes sense, haha, thanks.

**Comment by gajomon** [comment]
And is it possible to Update two States with only one function? Actually I'm trying to do this but it isn't working, and I think it is because React isn't rendering the component after the new states are set.

I have a component with a button and this function:

```
onClick={() => {
       arquivar(projeto._id)
}}
```

And this function arquivar has this code:

```
async function arquivar(id) {

        new Promise((resolve, reject) => {
            setArquivado(!arquivado);
            resolve();
        })
        .then(() => {
            const texto = 'Descrição do status:';
            let novoStatus = window.prompt(texto, "");
            novoStatus = novoStatus.toUpperCase();
            setStatus(novoStatus);
            return(novoStatus);
        })
        .then((novoStatus) => {
            var body = {
                cliente,
                nomeProjeto,
                disciplinaMestre,
                numPedido,
                responsavel,
                tipoEngenharia,
                status: novoStatus,
                infoProjetos,
                arquivado: !projeto.arquivado
            };

            console.log('Log 1', status, arquivado);
            return(body);
        })
        .then((body) => {
            // O problema não está na chamada desta função
            onUpdateProjeto(id, body);
        })
        .then(() => {
            console.log('Log 2', status, arquivado);
            decideWhatToDisplay();
        })
        .catch(() => {
            console.log('Ocorreu um erro :(');
        });

    }
```

But when I click in the button and call this function it doesn't re-render the component, so the states doesn't really changes, only if I click in the button again the component re-render :/

**Comment by gajomon** [comment]
This function onUpdateProjeto() is an async function that sends a PUT request to my server running locally to update the data in db.

**Comment by developerantoniosousa** [comment]
@gajomon I think that arquivar function should implements a code different.

Your should run other function when your component was updated use useEffect hook.

See this [part](https://reactjs.org/docs/hooks-effect.html) of documentation for understand as useEffect work

**Comment by gajomon** [comment]
Alright, I'll try this new approach, thanks my friend
