### ISSUE TITLE
React Dev Tools Firefox extension fails to detect React

### ISSUE THREAD

**Issue by jzzcoder** [reactjs/reactjs.org#2770]
React extension version: 4.4.0

Extension reports: "This page does not appears to be using React"

**Comment by bvaughn** [comment]
Bugs about the DevTools extension should be filed on the main React repo where the DevTools source code is maintained: https://github.com/facebook/react/issues

You'll want to provide more information though- which OS, which version of Firefox, and what URL you're using the extension on that you are seeing that message. :smile:

**Comment by bvaughn** [comment]
I suggest just adding the info to https://github.com/facebook/react/issues/17997
