### ISSUE TITLE
Images are not rendering when No Internet Connection

### ISSUE THREAD

**Issue by kondasanthosh30** [reactjs/reactjs.org#2789]
Hi Team,

Need help on one of the use case where we need to render the images when there is no internet.
we need to show the No InterConnection page when there is no internet.But when component is loaded when there is  no internet its not rendering the images since componented loaded for first time.How can i load images to this component in advance and used it for rendering  in UI.

Thanks,
Santhosh

**Comment by CyrusZei** [comment]
I think this is a question for [https://stackoverflow.com/](url) ? 
You can just make an ternary expression on the src ?

Here you should only post bugs and issues
