### ISSUE TITLE
Question: Color scheme used for syntax highlighting

### ISSUE THREAD

**Issue by statico** [reactjs/reactjs.org#279]
The code highlighting theme used on this site is wonderful. I've tried looking for the source but [didn't find much](https://github.com/reactjs/reactjs.org/commits/master/src/theme.js). Is it based on another theme or was it custom made for these docs?

![image](https://user-images.githubusercontent.com/137158/32702098-4800e026-c796-11e7-8bd3-0ade5a4dfc37.png)

**Comment by bvaughn** [comment]
The color scheme is called [Oceanic Next](https://labs.voronianski.com/oceanic-next-color-scheme/) and it was created by @voronianski who was kind enough to let us use it. 😄

**Comment by statico** [comment]
Thank you!
