### ISSUE TITLE
The FAQ page on AJAX and APIs should be refactored to use hooks

### ISSUE THREAD

**Issue by martin-sweeny** [reactjs/reactjs.org#2799]
The FAQ page describing [how to interact with APIs via AJAX](https://reactjs.org/docs/faq-ajax.html) still uses class components. This should probably be updated to use hooks

**Comment by alexkrolick** [comment]
👍 PR welcome to add a hooks version

**Comment by filipe-costa** [comment]
@alexkrolick more than happy to do so.
