### ISSUE TITLE
<a> links appear broken

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#280]
I don't know when this happened, but the "download this HTML file" link on our main Installation page is completely broken.

In particular, `<a>` tag gets immediately auto-closed for some reason:

<img width="729" alt="screen shot 2017-11-12 at 20 24 29" src="https://user-images.githubusercontent.com/810438/32703008-a44d0e80-c7e7-11e7-95f7-e1f1c2c9262f.png">
<img width="264" alt="screen shot 2017-11-12 at 20 25 04" src="https://user-images.githubusercontent.com/810438/32703009-a464fbc6-c7e7-11e7-8e02-bf9272ccbbc9.png">

The source code is:

```md
If you prefer to use your own text editor, you can also <a href="https://raw.githubusercontent.com/reactjs/reactjs.org/master/static/html/single-file-example.html" download="hello.html">download this HTML file</a>, edit it, and open it from the local filesystem in your browser. It does a slow runtime code transformation, so don't use it in production.
```

**Comment by bvaughn** [comment]
I think this is related to a recent Gatsby regression, unfortunately (see gatsbyjs/gatsby/issues/2696). ☹️ I thought I'd patched all spots where it occurred but I guess not.

Looks like it's been fixed upstream ([4b444e3](https://github.com/gatsbyjs/gatsby/commit/4b444e3df1e4e9a76207fab994cb72a7688fac7e)) so maybe we can resolve this by upgrading.

**Comment by bvaughn** [comment]
Hm...it's not broken for me when I run the app locally on head of master with a fresh `yarn install`.

It also doesn't appear to be broken on [reactjs.org/docs/installation.html](https://reactjs.org/docs/installation.html). Maybe you have a bad version cached, @gaearon? We definitely broke in this way recently (because of the issue mentioned) but I downgraded the plug-in that introduced the regression right afterward.

**Comment by xjlim** [comment]
@bvaughn The [workaround](https://github.com/reactjs/reactjs.org/commit/5dfd480fe27c0cffe5f9609600af00a6bc941e5a) has been put forth by Dan.

**Comment by bvaughn** [comment]
Gotcha. I hadn't seen that commit. Thanks Joe.

Other links that are in `<a href...>` format in Markdown also seem to work for me though (locally and on reactjs.org), eg `/docs/thinking-in-react.html` links to "Thinking In React: Step 4"

I still suspect this may have been a caching issue, given that I specifically noticed and fixed this type of thing recently.

**Comment by bvaughn** [comment]
Going to assume this was just a transient issue for Dan.
