### ISSUE TITLE
Export function from React Class

### ISSUE THREAD

**Issue by kottackalsulvin** [reactjs/reactjs.org#2812]
Hi,
I am trying to implement a dapp using react js.In my app.js inside the app class, there is a method that I want to export to another module.I tried many options,but none of them worked for me. In the below code, I want to export username().

**App.js Code**

```
export default class SessionStore {
......
 username () {
    if (!this._user || !this._user.username) return null
    return this._user.username
  }
......
}
```

I am new to reactjs, so please help me to resolve this issue.

**Comment by kottackalsulvin** [comment]
Anyone please help me.

**Comment by threepointone** [comment]
It's not clear why you'd want to export a single method of a class, it would help if you explained your usecase/problem, so I could recommend alternate solutions.

**Comment by kottackalsulvin** [comment]
I need the return value (this._user.username) of username() in another module. How can I get it in another module or js file.

**Comment by Rohitkrops** [comment]
In React data flows downwards. So if the method `username()` is part of a react component class you can pass a reference to it into another module used inside this class. 

But as method `username()` simply returns a value. Catch it's return value once and pass it as a prop to another module.  There can be two cases as you haven't shared, how these components are interacting with each other. 

Case 1. If the module to which you want to pass this return value is used inside the module containing this method you can pass the return value as a prop to another module. 

Case 2. If the module to which you want to pass this return value is used outside the module containing this method you can move this method to a common parent and pass the return value as a prop to both modules.

**Comment by kottackalsulvin** [comment]
@Rohitkrops I want to pass the return value outside the module containing this method. Can you refer some documents(examples) regarding how to do this. I am not too familiar with reactjs.

**Comment by Rohitkrops** [comment]
Can you share your repo or code sample on codesandbox
