### ISSUE TITLE
Typo for onClick prop for Square class component in Tutorial

### ISSUE THREAD

**Issue by pnaranja** [reactjs/reactjs.org#2817]
In https://reactjs.org/tutorial/tutorial.html#lifting-state-up

It mentions changing the Square component to
`
class Square extends React.Component {
render() {
    return (
      <button
        className="square"
        onClick={() => this.props.onClick()}
      >
        {this.props.value}
      </button>
    );
  }
}
`

But this results in the page error: 
> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

To fix this, I had to change the onClick to:
`        onClick={() => this.props.onClick}`

**Comment by threepointone** [comment]
This doesn't sound right. Could you make a codesandbox version that shows the error?

**Comment by pnaranja** [comment]
Sorry I see my typo:
I actually had typed this:
`	     onClick = {this.props.onClick}> `

Which I guess is very similar to 
`	     onClick = {() => this.props.onClick()}> `

I'll close this issue.  Thanks for the attention.
