### ISSUE TITLE
reactjs.org homepage examples are outdated

### ISSUE THREAD

**Issue by slk333** [reactjs/reactjs.org#2833]
The examples are located here:
https://github.com/reactjs/reactjs.org/tree/master/content/home/examples
We can see that they received little to no change since their creation, more than 3 years ago.

There are two problems:

- The examples don't use hooks
- The examples use classes

More generally, reactjs.org introduction largely ignores hooks, while using classes throughout. As a result, **hooks are largely ignored by newcomers.**

Suggestion: the Clock example and the Markdown Editor examples should come in two alternative versions: one using Class, one using function components and useState() and useEffect() hooks.

**Comment by Zeko369** [comment]
I'm already working on this, will have a PR today

**Comment by slk333** [comment]
https://github.com/reactjs/reactjs.org/issues/2874#issuecomment-607930242
