### ISSUE TITLE
Improving Spanish translation

### ISSUE THREAD

**Issue by barisoft** [reactjs/reactjs.org#2843]
URL: 'https://es.reactjs.org/docs/getting-started.html'

In the 'Stay informed' section and just at the end of the first paragraph, where it says 'depreciación', it would make more sense to say 'desactualización'.

En la sección 'Mantente informado' y justo al final del primer párrafo, en donde dice 'depreciación', tendría más sentido que digera 'desactualización'.

**Comment by alexkrolick** [comment]
Thanks for helping translate the React docs! The Crowdin translation project is separate from the reactjs.org repo, so please check out https://crowdin.com/project/react
