### ISSUE TITLE
Can we use functional components in the Tutorial (tic-tac-toe) since create-react-app now generates functional components?

### ISSUE THREAD

**Issue by Souro7** [reactjs/reactjs.org#2851]
The default components generated by create-react-app are functional components. Can we modify the Tutorial (tic-tac-toe) to use the same since it can be confusing for beginners?

The current tutorial has class based components.

**Comment by bootleg-icarus** [comment]
Possible duplication of [#2833](https://github.com/reactjs/reactjs.org/issues/2833) (Outdated examples on homepage)
