### ISSUE TITLE
Course link: project not found

### ISSUE THREAD

**Issue by aaabramov** [reactjs/reactjs.org#2854]
Link: https://reactjs.org/community/courses.html#free-courses

> Glitch: React Starter Kit - A free, 5-part video course with interactive code examples that will help you learn React.

![image](https://user-images.githubusercontent.com/11317222/77250849-47bee680-6c53-11ea-9404-dc57f9613c99.png)

Maybe we should remove this one from courses list?

**Comment by alexkrolick** [comment]
redirect seems to be working now, it went here for me https://glitch.com/glimmer/post/react-starter-kit/

**Comment by aaabramov** [comment]
@alexkrolick agree. Works for me also. Closing.
