### ISSUE TITLE
How to Tie React Hooks to HTML Page

### ISSUE THREAD

**Issue by mitchelln11** [reactjs/reactjs.org#2857]
Hooks look great, but when I try to add them to a local file, I'm getting errors, and it just ignores my new hook. Classes still work just fine.

On an HTML page, **NOT THE CREATE-REACT-APP**, how do you connect your hook to, let's say a div?
```<div id="root"></div>```

And this, below, being the hook itself:
```
import React, { useState } from 'react';

export function Example() {
    const [count, setCount] = useState(0);

    return (
        <div>
            <p>You clicked {count} times</p>
            <button onClick={() => setCount(count + 1)}>
                Click Me
            </button>
        </div>
    );
}
const rootElement = document.getElementById("root");
ReactDOM.render(<Example />, rootElement);
```

Should ReactDOM.render accomplish this?
Are hooks compatible with regular web HTML pages?

What am I missing? It seems very small.
I've updated node and npm.
I've tried changing my js file to .mjs.
I've tried adding type="module" to the script call.
I've tried adding "type" : "module" to the packages.json.

Nothing has worked. Any ideas?
Does my website have to be on a server like I've seen in an article or two?

**Comment by alexkrolick** [comment]
👉  https://reactjs.org/docs/add-react-to-a-website.html

**Comment by mitchelln11** [comment]
I guess I need a server in order to run things locally. I just wish that was mentioned in the documentation.
