### ISSUE TITLE
error close Tag in React document

### ISSUE THREAD

**Issue by ZuccRoger** [reactjs/reactjs.org#2861]
https://zh-hans.reactjs.org/docs/optimizing-performance.html
in this Chinese Document 
here is a error close Tag
please fix it 
<img width="913" alt="截屏2020-03-25上午11 19 57" src="https://user-images.githubusercontent.com/37689108/77498514-ca7db680-6e8a-11ea-822c-4b7559082240.png">

**Comment by brettdewoody** [comment]
This is not an error. The right angle bracket is correctly closing the `<button .... >` tag.
