### ISSUE TITLE
Confused about the comment on AJAX and APIs page

### ISSUE THREAD

**Issue by Allan-Gong** [reactjs/reactjs.org#2868]
on https://github.com/reactjs/reactjs.org/blob/master/content/docs/faq-ajax.md,

in the `fetch` call example:

```
componentDidMount() {
    fetch("https://api.example.com/items")
      .then(res => res.json())
      .then(
        (result) => {
          this.setState({
            isLoaded: true,
            items: result.items
          });
        },
        // Note: it's important to handle errors here
        // instead of a catch() block so that we don't swallow
        // exceptions from actual bugs in components.
        (error) => {
          this.setState({
            isLoaded: true,
            error
          });
        }
      )
  }
```

Can you please elaborate the reason for handling errors in the error callback instead of chained `catch` block ? 

What does it mean by not swallowing exceptions from actual bugs in components ? Is it possible to provide an example ?

I googled it but didn't find anything. Hence this Github issue.

Thanks in advance.

**Comment by alexkrolick** [comment]
Putting the catch after code that calls setState, or other logic in the component, will catch errors originating there instead of just the errors from the fetch
