### ISSUE TITLE
eslint-plugin-react-hooks@3.0.0 changelog/upgrade guide?

### ISSUE THREAD

**Issue by Billy-** [reactjs/reactjs.org#2871]
I noticed a major version of the react hooks plugin was released, however I can't find any changelogs, release notes, upgrade guides etc. What are the breaking changes in this release, and can they be documented somewhere for our viewing pleasure? 😃

**Comment by gaearon** [comment]
I bumped the major because the lint rule is a bit stricter now and won’t let you use Hooks from a class. That’s the only change.

We don’t have a separate change log for it but happy to take a PR that adds it to the package folder.
