### ISSUE TITLE
Put more focus on Hooks

### ISSUE THREAD

**Issue by balazsorban44** [reactjs/reactjs.org#2874]
Hi, I am the main author of the [Hungarian](https://github.com/reactjs/hu.reactjs.org) 🇭🇺 translation pages, and it is now not the first time that I come across statements like this:

> This might seem like a lot to take in at first. Don't rush it! If you're lost in the explanation, look at the code above again and try to read it from top to bottom. We promise that once you try to "forget" how state works in classes, and look at this code with fresh eyes, it will make sense.

On several pages, there seem to be suggestions to that if you would like to get started with Hooks, you should forget classes, although most of the Core Pages _STILL_ heavily focus on classes, and seem to delay introducing Hooks to beginners for whatever reason. In many places, it is suggested somehow, that Hooks are a kind of an experimental API (can't remember where still linking to the RFC), and the community is still working out good practices, and implementing libraries. Hooks have been released for a time now, and speaking from experience, it REDUCES mental load by miles, compared to classes. Not to talk about the many great libraries solely built on Hooks. It may be the time to give more credits to Hooks, and phase out (**meaning to give less focus to,** not remove) **classes** from the docs, and put **Hooks into the spotlight**. 🎣 

Correct me if I am wrong, I have heard several times from highly appreciated React developers, that  Hooks are the future of React, as it is closer to what React is supposed to be.

**Comment by josephrexme** [comment]
I agree with this. I think we can work on tabbed code blocks like I have designed here:

![Screenshot 2020-04-01 20 45 43](https://user-images.githubusercontent.com/5395567/78202458-03ed8d80-745a-11ea-8b1d-6d43e27cb00f.png)

This code is taken from this page https://reactjs.org/docs/forms.html#the-textarea-tag

**Comment by gaearon** [comment]
We plan to rewrite a bunch of docs soon. I don't think we're going to introduce tabs though because the content would need to be different.

**Comment by josephrexme** [comment]
Great, thanks @gaearon ! Is there an issue you'd recommend to follow on the progress of docs rewrite? I will be interested in participating if needed, or just learning from the process.

**Comment by gaearon** [comment]
No issue yet. We might create one when we’re closer to it but it’s unlikely it’ll need contributions early on because it would need to be written holistically end-to-end.

**Comment by Zeko369** [comment]
@gaearon Maybe we could add something like this to the homepage? I have a PR open for that #2838

**Comment by gaearon** [comment]
As I mentioned, we plan to **completely overhaul** the docs for Hooks. We appreciate the PR but this needs to be done holistically so I don't think disjointed individual changes make sense.

**Comment by balazsorban44** [comment]
Thanks for the answer!
