### ISSUE TITLE
The lazy initial state documentation appears contradictory.

### ISSUE THREAD

**Issue by steveharrison** [reactjs/reactjs.org#2876]
The [documentation on lazy initial state](https://github.com/reactjs/reactjs.org/blob/master/content/docs/hooks-reference.md#lazy-initial-state-lazy-initial-state) appears contradictory. If the `initialState` is disregarded after the initial render, then why is a callback function needed for an expensive computation, since it would only run once anyway without a callback, right?

> The initialState argument is the state used during the initial render. In subsequent renders, it is disregarded. If the initial state is the result of an expensive computation, you may provide a function instead, which will be executed only on the initial render:
> 
>```
>const [state, setState] = useState(() => {
>  const initialState = someExpensiveComputation(props);
>  return initialState;
>});
>```

**Comment by alexkrolick** [comment]
Consider:

```
const [state, setState] = useState(() => {
 const initialState = someExpensiveComputation(props);
 return initialState;
});

// same as this

const getInitialState = () => {
 const initialState = someExpensiveComputation(props);
 return initialState;
}
const [state, setState] = useState(getInitialState)

// not the same as this, getInitialState is **called** multiple times
const [state, setState] = useState(getInitialState())
```

**Comment by kpodmasko** [comment]
Am I right that also you can do like that?
``` js
//  if you return state from someExpensiveComputation directly
const [state, setState] = useState(someExpensiveComputation);
```

**Comment by alexkrolick** [comment]
Yes, but note that in the original example the computation references props; that's why it's wrapped in another function.
