### ISSUE TITLE
Side bar for navigation can't be scrolled

### ISSUE THREAD

**Issue by GanongLS** [reactjs/reactjs.org#2883]
I just visited the react js documentation. But there is a problem in the sidebar for subtopic navigation. Please fix it right away, it becomes very difficult to see subtopics if it exceeds screen height.

**Comment by jordanliu** [comment]
Screenshots or instructions how to recreate this?

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/reactjs/reactjs.org/issues/3171
