### ISSUE TITLE
Can I use Suspense in production today? 

### ISSUE THREAD

**Issue by etiennejcharles** [reactjs/reactjs.org#2923]
Based on this: 
https://reactjs.org/docs/concurrent-mode-suspense.html

I shouldn't. 

but it seems like nextjs.org is already relying on it in some of their codebase
https://github.com/zeit/swr/issues/119

Could anyone provide some input?

**Comment by gaearon** [comment]
We do consider any use of Suspense for data fetching experimental today. It happens to work in stable releases to an extent, but it's not a documented stable API, and we may sometimes break it. (We'll try not to though.)
