### ISSUE TITLE
Installation problem on windows 10

### ISSUE THREAD

**Issue by gaelgerard** [reactjs/reactjs.org#293]
Hello, 
I can't install reactjs.org on my localhost with the following message
```
$ yarn dev
yarn run v1.3.2
$ gatsby develop -H 0.0.0.0
success delete html files from previous builds — 0.010 s
success open and validate gatsby-config.js — 0.007 s
success copy gatsby files — 0.060 s
error UNHANDLED EXCEPTION


  Error: error: 127\\?\C:\wamp64\www\reactjs.org\node_modules\sharp\build\Releas
  e\sharp.node

  - module.js:11 require
    internal/module.js:11:18

  - constructor.js:9 Object.<anonymous>
    [reactjs.org]/[sharp]/lib/constructor.js:9:15

  - module.js:11 require
    internal/module.js:11:18

  - index.js:3 Object.<anonymous>
    [reactjs.org]/[sharp]/lib/index.js:3:15

  - module.js:11 require
    internal/module.js:11:18


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.


```
As seen above, I run yarn v1.3.2
node v8.9.1

Does anyone have a solution ?

Thanks in advance
g

**Comment by bvaughn** [comment]
Hi @gaelgerard. Sorry to hear that you ran into some difficulties getting this project running locally. I run into occasional problems with Sharp during installation as well on my Mac.

Unfortunately I'm not in a great position to help you debug these as I'm not familiar with Sharp and I don't have a Windows dev setup. I think you might have a better chance of finding someone who can help with this issue over at [github.com/lovell/sharp](https://github.com/lovell/sharp/).

This isn't a problem specific to reactjs.org- (it's actually a dependency of a dependency)- so I'm going to close this issue. Hope you understand.
