### ISSUE TITLE
What's an example of inheritance?

### ISSUE THREAD

**Issue by ThomasShih** [reactjs/reactjs.org#2932]
Under [the composition vs inheritance](https://github.com/reactjs/reactjs.org/blob/master/content/docs/composition-vs-inheritance.md) blog post I see a few examples of how I would be structuring code personally. However, I still don't understand what react code would look like inheriting? Having an example of what is considered "worse practice" might be good for us beginners to fully understand what to avoid! Thank you in advance! :)

**Comment by alexkrolick** [comment]
Something like this, for example:

```jsx
class ButtonCore extends React.Component {
	handleClick = (e) => {
    	if (typeof this.props.onClick === 'function') {
   			this.props.onClick(e)
    	}
		else {
			alert('button click!')
		}
 	}
}

class ButtonPrimary extends ButtonCore {
  	render() {
		return (
			<button
				{...props}
				onClick={this.handleClick}
				className={'btn btn-primary'}
			/>
		)
	}
}
```

**Comment by ThomasShih** [comment]
Oh. Ew. I see why we don't do that now.

Thank you!
