### ISSUE TITLE
Adding other statically-typed languages

### ISSUE THREAD

**Issue by alfonsogarciacaro** [reactjs/reactjs.org#294]
[This document](https://reactjs.org/docs/static-type-checking.html) explains how to do static type checking with React apps. It mixes a static-type checker for JS (Flow) with Typescript, which is a different language even if still a superset of JS. It maybe worthing to mention other statically-typed languages that compile to JS and are compatible with React, like ReasonML or [F#/Fable](http://fable.io/), which can be used to create React apps for example with [fable-elmish](https://fable-elmish.github.io/react/).

If you are OK with this, I can send a PR to include a Fable mention for you to review.

**Comment by bvaughn** [comment]
I don't think our intentions are to create and maintain an exhaustive list of languages capable of compiling to JavaScript. Flow and TypeScript are the most common and so seemed worth mentioning specifically.

I'll be happy to review a PR that suggests specific changes to our content to be more informative and inclusive, but I also think it's important to keep the React docs focused. I think if we add too many options to sections like this, we might overwhelm people and end up being less effective.

I'm going to close this issue _but_ I'm happy to keep discussing it here and I'll happily review a PR if you'd like to send one in. 😄

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your quick reply @bvaughn, your reasoning makes sense to me :+1: Maybe a short sentence with non-exhaustive samples to let the user know there are other options could be enough? I'll send a PR so you can tell me what you think 😄

**Comment by bvaughn** [comment]
You're welcome! I look forward to reviewing it.
