### ISSUE TITLE
Community menu not visibile fully in the header of site

### ISSUE THREAD

**Issue by TechSaq** [reactjs/reactjs.org#2949]
On the header of [reactjs.org](url), **Community** option is _half-visible_. It is overlapped by adjacent **Search** Box input.
![Screenshot from 2020-05-05 11-02-09](https://user-images.githubusercontent.com/28209930/81037416-4c1c2780-8ec0-11ea-8ee6-77eb93f48c89.png)

**Comment by Judionit** [comment]
Hi,
Think this issue should be closed now
![comm](https://user-images.githubusercontent.com/46365844/82122776-423ad400-979e-11ea-85ac-f1619d747af2.PNG)
