### ISSUE TITLE
Smallest React example?

### ISSUE THREAD

**Issue by dddotsev** [reactjs/reactjs.org#2953]
So I'm a bit new to React and am probably wrong about this. That's why I'm creating an issue instead of straight up making a PR.

But isn't the smallest React example technically this:
```js
ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.querySelector('body')
);
```

Instead of this:
https://github.com/reactjs/reactjs.org/blob/77d3c2fa8e7f8bd26336b652d21336b3d13f682d/content/docs/hello-world.md  (the first paragraph).

I'm not talking about `querySelector` being 1 character shorter than `getElementById`, that's a bit of a technicality and can even be shortened to `document.body`.

What I mean is that you don't expect anything to be in the DOM. You just render everything in the body.

**Comment by kpodmasko** [comment]
Hi! I think it is a good idea, but react has context. So if you render your app in body you will not paste a container for context content as there will not be a space.

**Comment by alexkrolick** [comment]
Typically you don't want to render into the root node because portals and other things can be appended as children of document.body, as well as script tags that you don't want to put into the document head.

**Comment by kpodmasko** [comment]
> will not paste a container for context content as there will not be a space.



> Hi! I think it is a good idea, but react has context. So if you render your app in body you will not paste a container for context content as there will not be a space.

I made a mistake:) not context, portals, of course
