### ISSUE TITLE
Component Life Cycle Methods are called twice

### ISSUE THREAD

**Issue by Sravan2** [reactjs/reactjs.org#2961]
constructor, getDerivedStateFromProps, render methods are called twice and componentDidMount callled once. can any one help me out.

![code](https://user-images.githubusercontent.com/12997317/81437308-946d6b00-9188-11ea-9d4b-93a692803741.PNG)
![console](https://user-images.githubusercontent.com/12997317/81437310-959e9800-9188-11ea-8a37-e062ecbd204c.PNG)

**Comment by gaearon** [comment]
This is expected if your app is running in strict mode. This helps detect unintended side effects (which shouldn’t happen in these methods). https://reactjs.org/docs/strict-mode.html

**Comment by Sravan2** [comment]
But my app is not running in strict mode
