### ISSUE TITLE
Older React version documentation links are broken.

### ISSUE THREAD

**Issue by kartiksharma1607** [reactjs/reactjs.org#2976]
Try going to React 15 documentation [https://react-legacy.netlify.app/docs/hello-world.html](https://react-legacy.netlify.app/docs/hello-world.html)

Go to search, search for `Refs`.

Page takes you to React 16 documentation instead.

**Comment by gaearon** [comment]
Yeah I think it's likely the search only works on the new website.

**Comment by alexkrolick** [comment]
It only works on the current version, I believe, even for old react 16 versions.

**Comment by rickhanlonii** [comment]
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268

**Comment by gaearon** [comment]
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
