### ISSUE TITLE
[docs] Outdated react transition group repo link

### ISSUE THREAD

**Issue by vuki656** [reactjs/reactjs.org#2990]
In the [animation add-ons](https://reactjs.org/docs/animation.html) doc page the links for [react transition group](https://github.com/reactjs/react-transition-group) repo lead to an outdated branch **v1-stable** that is no longer updated.

**Comment by rachelnabors** [comment]
Actually, upon closer inspection, this is an intentional link to help people migrating. The 1.x branch copies this helper's original API. The latest version's API is different, so linking to it would cause confusion.
