### ISSUE TITLE
Some part of document page is not visible.

### ISSUE THREAD

**Issue by devethan** [reactjs/reactjs.org#3014]
![Jun-03-2020 10-55-49](https://user-images.githubusercontent.com/55861805/83587008-eab3ab00-a588-11ea-8df5-20f6ae93e47f.gif)

I was reading [this page](https://reactjs.org/docs/concurrent-mode-suspense.html#start-fetching-early), I couldn't see some part of the page.

There's no problem with github origin sources. Please check it.

**Comment by maxsbelt** [comment]
Same problem. Seems like it happens in all pages in Google Chrome browser (my version is Version 83.0.4103.61 (Official Build) (64-bit) on Mac OS). Firefox and Safari work well.

**Comment by yangshun** [comment]
This happened after 5eeb441. Disabling the grayscale filter on `<div class="css-4zmxiv">` fixes things.

**Comment by gaearon** [comment]
Fixed.
