### ISSUE TITLE
Broken link in tutorial

### ISSUE THREAD

**Issue by lrose07** [reactjs/reactjs.org#3015]
The link titled "See full expanded version." under [Overview > What Is React](https://reactjs.org/tutorial/tutorial.html#what-is-react) points to [this link](https://babeljs.io/repl/#?presets=react&code_lz=DwEwlgbgBAxgNgQwM5IHIILYFMC8AiJACwHsAHUsAOwHMBaOMJAFzwD4AoKKYQgRlYDKJclWpQAMoyZQAZsQBOUAN6l5ZJADpKmLAF9gAej4cuwAK5wTXbg1YBJSswTV5mQ7c7XgtgOqEETEgAguTuYFamtgDyMBZmSGFWhhYchuAQrADc7EA), and leads to a Page Not Found on the BabelJS site.

edit: Further investigation shows that the BabelJS site is currently offline in protest, so that may be the reason.

**Comment by harshilparmar** [comment]
It is working fine now!!

**Comment by QualBean** [comment]
This is working ok.
