### ISSUE TITLE
Bug in documentation.

### ISSUE THREAD

**Issue by OlegBrony** [reactjs/reactjs.org#3022]
I think, you changed colors in documentation by accident. Everything is gray, could you fix it?
![image](https://user-images.githubusercontent.com/19880334/83845360-604a8300-a711-11ea-9681-77319ce1f97a.png)

**Comment by stephenlin35** [comment]
This is intentional.

You can learn more about the cause the React team is supporting: [BlackLivesMatter](https://blacklivesmatters.carrd.co/#educate)

You are also welcome to donate at [Support the Equal Justice Initiative](https://support.eji.org/give/153413/#!/donation/checkout)

**Comment by OlegBrony** [comment]
> This is intentional.
> 
> You can learn more about the cause the React team is supporting: [BlackLivesMatter](https://blacklivesmatters.carrd.co/#educate)
> 
> You are also welcome to donate at [Support the Equal Justice Initiative](https://support.eji.org/give/153413/#!/donation/checkout)

well, sorry, but I don't understand. how is it connected with react or javascript or development at all?

**Comment by sijusamson** [comment]
@OlegBrony its not connected to react or Javascript. I hope you may be aware of the situation in US. So this is basically react community showing their support for the act. :-)

I hope my answer would have helped you.

**Comment by OlegBrony** [comment]
finally you returned the colors. thanks.
