### ISSUE TITLE
What types can `key` prop have?

### ISSUE THREAD

**Issue by MilosChmel** [reactjs/reactjs.org#3023]
Hi,
in my case I have a list of items and I want to add `key` prop, but items do not have ID and using index from `.map((value, index) => ` is not reliable. Do I assume correctly that React uses `===` and I can safely put object into `key` prop?

I was looking in https://reactjs.org/docs/lists-and-keys.html , https://reactjs.org/docs/reconciliation.html#recursing-on-children , https://reactjs.org/docs/react-component.html , https://reactjs.org/docs/glossary.html#keys (using algolia search) and I could not find information I was looking for.

Can You please update documentation with this information:
- supported key type ... if key prop can be only primitive value like `String` or `Number` (examples suggest that, but it is not specified if it is the only case) ... if key prop can be an `object`
- is key compared with `==` or `===`

Thank You :)

**Comment by sijusamson** [comment]
@MilosChmel Well, IMHO keys have a special purpose, it is used by React to identify which items have been changed, are added. So basically it is used to give a unique identification for a element. Now, I wonder why you want to add an object to key prop.

**Comment by eps1lon** [comment]
@MilosChmel Seems like this has been adressed in the meantime. The docs now explicitly mention the type:

> A “key” is a special string attribute you need to include when creating arrays of elements.

-- https://reactjs.org/docs/glossary.html#keys

Note that you can still pass whatever you want to the `key` but the `key` will be converted to a string eventually.
