### ISSUE TITLE
Add breathing space around section links. 

### ISSUE THREAD

**Issue by anasansari157** [reactjs/reactjs.org#3029]
Border touches around Section links (those with ChevronSvg Component) on focus, in the Sidebar menu (Navigation Sidebar)

**Comment by rickhanlonii** [comment]
Hey @anasansari157, just to clarify, are you talking about the left and right padding here?

<img width="256" alt="Screen Shot 2020-07-07 at 10 23 33 PM" src="https://user-images.githubusercontent.com/2440089/86867257-8365ab00-c0a0-11ea-8f9f-6729a7a150b1.png">

If so then yeah it would be nice if the outline wasn't right against the text and cheveron.

**Comment by rickhanlonii** [comment]
@kefimochi volunteered to help with this!

**Comment by kefimochi** [comment]
Fixed in #3090 🔥

**Comment by kefimochi** [comment]
@anasansari157 Fixed in #3090 🔥
