### ISSUE TITLE
Hooks documentation suggestion - talk about options for sharing

### ISSUE THREAD

**Issue by udf2457** [reactjs/reactjs.org#3035]
The docs talk a lot about _"extracting component logic into reusable functions"_ but they singularly fail to address the old chestnut of how to share state between components.

The docs are silent on whether with the advent of hooks, global state managers (e.g. `redux`) are still the only way, or whether there is a smarter, more intelligent way, to share state between components in the hook era.

It would be nice to have some discussion on the topic in the docs (e.g. it would go well next to the _"Tip: Pass Information Between Hooks"_ section).

**Comment by rickhanlonii** [comment]
Hey @udf2457, thanks for the feedback. The docs have a section on [Lifting State Up](https://reactjs.org/docs/lifting-state-up.html#lifting-state-up) for sharing state between components, which is the recommended vanilla React way to share state.
