### ISSUE TITLE
Scrolling through the guides on the right hand panel is broken 

### ISSUE THREAD

**Issue by kusiroll** [reactjs/reactjs.org#3037]
Scrolling through the guides on the right hand panel is broken  on reactjs.org is broken. Please fix

**Comment by threepointone** [comment]
How is it broken exactly? Seems fine here, but maybe I'm missing something.

**Comment by threepointone** [comment]
Closing this issue, happy to reopen if you can explain and/or show a screenshot/gif of what exactly is wrong.
