### ISSUE TITLE
useTransition guidance wrt passing around isPending and general lifecycles

### ISSUE THREAD

**Issue by orestis** [reactjs/reactjs.org#3042]
Hello,

I understand the caveat about using experimental APIs so if you don't want to spend the time feel free to close this issue.

The guidance in useTransition suggests to bake the usage inside the design system, e.g. a Button component.

However, at the same time it's suggested that some stage changes that show a response to user interaction should be outside startTransition so that they render sooner.

I have found myself having to pass around the `startTransition` function inside my event handler functions, so that the event handler function can choose. For example:

```
function updateTab(tabID, startTransition) {
// flush immediately to show user that their click was registered
  setActiveTab(tabID);
// wrap inside transition to keep the old tab content around just a little bit
  startTransition(()=> {
   setTabContent(fetchTabData(tabID));
 })
}
```

----

At a similar note, very often I would like to pass the `isPending` flag to a parent component because the loading indicator shouldn't be inside the Button, but at some other place. I guess I could do that with a `useEffect` that side-effects whenever isPending changes but it feels wrong.

----

Both of these issues are centered around the same point: It's not clear to me from reading the documentation if `useTransition` has a lifecycle attached to it or not. Both cases would go away if a parent component could call `useTransition` just once and construct different event handlers with the same `startTransition` function. Or perhaps it needs to call it once for every Tab component? Keeping track of the `isPending` flag becomes tricky in any case.

Thanks for your time!

**Comment by rickhanlonii** [comment]
Hey @orestis, thanks for the great feedback on this API. As you said, it's experimental and working out use cases like this is part of the reason that the API isn't finalized. I'm going to close this as the documentation isn't the right place to discuss the new API, but feel free to keep the discussion open here or elsewhere.

**Comment by rickhanlonii** [comment]
As for the specific feedback, have you considered doing something like this:

```
function Button({ children, onPrepareClick, onClick }) {
  const [startTransition] = useTransition({
    timeoutMs: 10000
  });

  function handleClick() {
   onPrepareClick();
    startTransition(() => {
      onClick();
    });
  }

  return (
    <>
      <button
        onClick={handleClick}
        disabled={isPending}
      >
        {children}
      </button>
    </>
  );
}
```

That way you're not passing around startTransition and instead you have handlers for _what_ you want to do instead of _how_.

**Comment by gaearon** [comment]
Ideally we’d discuss this in React repo. Mind filing this issue there please?

**Comment by orestis** [comment]
Thanks @rickhanlonii for taking the time, much appreciated. 

@gaearon will do - I didn’t want to take much of your attention at this point, since this is experimental and not a bug per se.
