### ISSUE TITLE
Broken link in tutorial

### ISSUE THREAD

**Issue by Padavan-itbeard** [reactjs/reactjs.org#3047]
Why JSX? {#why-jsx}

React doesn't require using JSX

doesn't require - link 404

**Comment by sijusamson** [comment]
What is this bug ? Please report a bug with full details.

**Comment by Padavan-itbeard** [comment]
Hi,
when you click on the links on the page (which lead to this guide) gives - page not found 404. You can close it, I realized that the links are not intended to be viewed from the Git Hub.

**Comment by sijusamson** [comment]
Please share a screenshot for the same, so that we can investigate further .

**Comment by rickhanlonii** [comment]
Confirmed that the "doesn't require" link on [Why JSX](https://reactjs.org/docs/introducing-jsx.html#why-jsx) works.

Going to close this, but if there's a different link feel free to clarify and we'll re-open.
