### ISSUE TITLE
Discussion required: React Hook useEffect has a missing dependency: 'functionName'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

### ISSUE THREAD

**Issue by sijusamson** [reactjs/reactjs.org#3052]
Hi, 
I went through various articles and posts, but couldn't find a proper answer for my case. 
I have a function **getHumanResourceList** which doesn't depends on any props. 

`  const getHumanResourceList = async () => {`
    `const result = await HumanResource.getHumanResourceList(filters);`
    `if (result.data.success) {`
      `setHumanResources(result.data.data.rows);`
  `  } else {`
    `  toast.error(result.message);`
   ` }`
 ` };`

I am invoking it like this !
`  useEffect(() => {`
   ` getHumanResourceList();`
 ` }, []);`

But i am getting an error. I know we can define the function within **useEffect**, but i want to invoke the **getHumanResourceList** various times, depending on the CRUD functions done by user.

Can anyone help me out here ?

**Comment by vivek12345** [comment]
what is the error?

**Comment by sijusamson** [comment]
Hi @vivek12345, I am getting this **warning** in my dev tool.
**React Hook useEffect has a missing dependency: 'functionName'. Either include it or remove the dependency array react-hooks/exhaustive-deps**

**Comment by vivek12345** [comment]
I tried your code with some modifications here
https://codesandbox.io/s/angry-dawn-5ouvh?file=/src/Comp.js

I don't see any warnings

**Comment by siju-enuke** [comment]
That warning is given by eslint.

**Comment by sijusamson** [comment]
That warning is given by eslint.

**Comment by vivek12345** [comment]
the above codesandbox has eslint enabled

**Comment by sijusamson** [comment]
@vivek12345 Even I tried to reproduce the bug but wasn't successful in codesandbox, so I am closing this.
