### ISSUE TITLE
Release Channels page in the docs doesn't have "Previous article" or "Next article" links

### ISSUE THREAD

**Issue by arnav-aggarwal** [reactjs/reactjs.org#3068]
https://reactjs.org/docs/release-channels.html

Beginners looking to learn React often start from the beginning of the "Getting started" page (https://reactjs.org/docs/getting-started.html) and progress through the pages by clicking "Next article" at the bottom of each page. This page is missing that link as well as the "Previous article" link. It would be very helpful to add this to the bottom of the page to keep it consistent with the rest of the "getting started" pages.

"CDN Links" (https://reactjs.org/docs/cdn-links.html) has a "Next article" link that goes to "Release Channels".

"Hello World" (https://reactjs.org/docs/hello-world.html) has a "Previous article" link that links to "CDN Links".

This chain in the docs is broken and currently difficult for a beginner to navigate.

**Comment by threepointone** [comment]
Landed the PR with the fix, closing this issue. It should reflect on the website in a few minutes, please let me know here if it doesn’t. Thanks @sijusamson!

**Comment by sijusamson** [comment]
> Landed the PR with the fix, closing this issue. It should reflect on the website in a few minutes, please let me know here if it doesn’t. Thanks @sijusamson!

Welcome @threepointone
