### ISSUE TITLE
www.bing.com

### ISSUE THREAD

**Issue by azaruiz** [reactjs/reactjs.org#3074]
www.bing.com

_Originally posted by @azaruiz in https://github.com/reactjs/reactjs.org/issues/3069#issuecomment-651901545_

**Comment by azaruiz** [comment]
Activar

**Comment by azaruiz** [comment]
#3069

**Comment by azaruiz** [comment]
@azaruiz

**Comment by threepointone** [comment]
I'm not sure why you're spamming the issues section. I'm going to lock these issues, but fair warning, if you keep doing this, I"m going to ban your from the project.
