### ISSUE TITLE
link to a github profile returns 404 in the documentation

### ISSUE THREAD

**Issue by nik72619c** [reactjs/reactjs.org#3092]
### Description
On clicking the GitHub profile link for @acdlite returns a 404 under the given section in the react's website:-
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#concurrent-mode-experimental

### Steps to reproduce
- go to the above link
- click on `acdlite`under the bullet point *Fix React.memo components dropping updates when interrupted by a higher priority update (@acdlite in #18091)*
- The 404 page appears

<img width="1280" alt="Screenshot 2020-07-09 at 2 58 44 PM" src="https://user-images.githubusercontent.com/30630904/87022915-c173e380-c1f4-11ea-960d-e3453fe0664b.png">

After clicking:-
<img width="1280" alt="Screenshot 2020-07-09 at 2 59 28 PM" src="https://user-images.githubusercontent.com/30630904/87023038-e5372980-c1f4-11ea-91c5-108c00fa099d.png">

**Comment by nik72619c** [comment]
would like to work on this 🙂

**Comment by rickhanlonii** [comment]
@nik72619c feel free to submit a PR!

I think the markdown for the link is wrong, it's

`[@acdlite](<(https://github.com/acdlite)>)`

but should be:

`[@acdlite](https://github.com/acdlite)`

**Comment by sijusamson** [comment]
> would like to work on this

If you are working on it, let me know. Otherwise I would be happy to raise a PR.

**Comment by nik72619c** [comment]
@sijusamson , I am working on it 🙂

**Comment by nik72619c** [comment]
ref #3094

**Comment by rickhanlonii** [comment]
Nice fix, thanks!
