### ISSUE TITLE
Accessing state in App.js through Context API

### ISSUE THREAD

**Issue by inblack67** [reactjs/reactjs.org#3103]
It's not in the docs so I figured it out on my own. When a user logs in and reload, to persist the state generally we add the load user action in the useEffect hooks in the main App.js. While using Redux, loadUser action can be easily accessed.

App.js
```js
import {lodUser}  from '../actions/auth';
store.dispatch(loadUser());
```

But while using Context API, how to access it? I came up with this solution:-
To access state, wrap the AuthState in index.js so that App.js can access the auth state.
```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import AuthState from './context/auth/AuthState'

ReactDOM.render(
  <React.StrictMode>
    <AuthState>
      <App />
    </AuthState>
  </React.StrictMode>,
  document.getElementById('root')
);
```

Now App.js
```js
  const authContext = useContext(AuthContext);

  const { loadUser } = authContext;

  useEffect(() => {
    loadUser();
  },[])
```

Load User Action
```js
    const loadUser = async () => {
        const token = sessionStorage.getItem('token');

        if(!token){
            dispatch({
                type: ERROR
            })
        }
        setAuthToken(token);

        try {
            const res = await axios('/api/auth'); 

            dispatch({
                type: USER_LOADED,
                payload: res.data.data
            })
            
        } catch (err) {
           console.error(err); 
        }
    }
```

**Comment by rickhanlonii** [comment]
Hey @inblack67, what's the context here?

Are you asking if this is correct or if we can add this to the docs or something else?

**Comment by inblack67** [comment]
@rickhanlonii , the latter. You guys should add this to the docs or else provide a better solution if any.

**Comment by inblack67** [comment]
@rickhanlonii 
#### Pull Request Awaits to be merged.
