### ISSUE TITLE
Issue related to snippet please update it for Inline If-Else with Conditional Operator

### ISSUE THREAD

**Issue by Krishank-Tripathi** [reactjs/reactjs.org#3108]
As per doc if there is issue is doc for a snippet please update it. 
For case of Condition operator for isLogedIn case.
Link : https://reactjs.org/docs/conditional-rendering.html#inline-if-else-with-conditional-operator

Issue in snippet please find it in Attachement & update for the same thank you.
![Screenshot_2020-07-15 Conditional Rendering – React](https://user-images.githubusercontent.com/43090677/87558725-0dcc9100-c6d7-11ea-9bea-eff44ebb5645.png)

Proper Snippet Code

`render() {
  const isLoggedIn = this.state.isLoggedIn;
  return (
    <div>
      {isLoggedIn  ? <LoginButton onClick={this.handleLoginClick} />
      : <LogoutButton onClick={this.handleLogoutClick} /> }
    </div>  );
}`

**Comment by rickhanlonii** [comment]
Hey @Krishank-Tripathi, thanks for flagging.

The current snippet is correct and the recommended snippet is not. In the current snippet, if the user is logged in then we show a logged out button. In the recommended snippet, if the user is logged in then we would show a login button.

But a logged in user does not need to see a login button (they're already logged ini), they need to see a logout button.

Going to close but thanks again for taking a look.
