### ISSUE TITLE
Broken Link on Acknowledgements Page

### ISSUE THREAD

**Issue by mojo706** [reactjs/reactjs.org#3109]
Hi, on the[ acknowledgements ](https://reactjs.org/acknowledgements.html/) page of the website there is a broken link that needs to redirect to [Oceanic Next](https://labs.voronianski.dev/oceanic-next-color-scheme/) Instead of the link that's currently there. 
👋🏾

**Comment by saswatamcode** [comment]
Hi! I took this up and opened a [pull request](https://github.com/reactjs/reactjs.org/pull/3111).
