### ISSUE TITLE
Anchors are hidden underneath the navbar when navigating to them

### ISSUE THREAD

**Issue by claudiopro** [reactjs/reactjs.org#3113]
I noticed that anchor links slide under the navbar. This is similar to https://github.com/facebook/docusaurus/issues/2907 and likely caused by the increase of the height of the navbar caused by the BLM banner.

# Steps to reproduce

1. Create an anchor and a link to the anchor in React docs
2. Publish the website
3. Tap the anchor link

# Expected result
The anchor appears in view at the top of the page

# Actual result
The anchor appears at the top of the page hidden under the navbar

<img width="1392" alt="Screen Shot 2020-07-16 at 9 39 25 PM" src="https://user-images.githubusercontent.com/860099/87715351-8736b300-c7ad-11ea-9ab0-b6b89d8fdb18.png">

**Comment by claudiopro** [comment]
The padding of anchors appears to be set in the Gatsby theme here:

https://github.com/reactjs/reactjs.org/blob/master/src/theme.js#L286-L292

**Comment by rickhanlonii** [comment]
Confirmed, thanks for filing this @claudiopro. Do you want to submit a PR to fix it?

**Comment by harshilparmar** [comment]
@rickhanlonii @claudiopro  Can I try this?

**Comment by rickhanlonii** [comment]
@harshilparmar sure!

**Comment by rickhanlonii** [comment]
@harshilparmar yeah! Let me know if you need any help getting set up.

**Comment by kwaimind** [comment]
Hey, I hope it's ok but I took the liberty of looking into this issue and made a PR with a potential fix.

**Comment by kavin25** [comment]
I have a fix for this. Can I do this?

**Comment by kavin25** [comment]
@claudiopro @rikhanlonii ^

**Comment by kavin25** [comment]
@rickhanlonii

**Comment by eps1lon** [comment]
@kavin25 Go for it :+1:

**Comment by kavin25** [comment]
I am not able to find this component and css for this. I have been able to implement it with inspect element, in chrome though.  I found that there is a markdownremark being passed to markdownpage. The markdownremark comes from a data object, which is passed as props. But I am not able to find where the docs.js component is being called.

 This is my first time, so will be very helpful if someone can help

**Comment by kavin25** [comment]
Nevermind... I managed to do it. Will make a pr in few mins

**Comment by kavin25** [comment]
I am very new to open source. So, can you please tell me what my fork name would be?

Thanks

**Comment by kavin25** [comment]
This is for pushing my code

**Comment by kavin25** [comment]
1. I had forked
2. I cloned the fork repo
3. I made changes
4. I did git add -A && git commit -m "the message here"
5. this is what I'm confused about*( shouldn't i just do git push origin <branch name>)*

@eps1lon

**Comment by kavin25** [comment]
Sorry for disturbing so often. It's my first time. Might get accustomed to it by next time

**Comment by kavin25** [comment]
Have created a PR

**Comment by rickhanlonii** [comment]
Thanks for the fix!
