### ISSUE TITLE
Adding requestAnimation throttling

### ISSUE THREAD

**Issue by alexreardon** [reactjs/reactjs.org#312]
This is a great new resource: https://reactjs.org/docs/faq-functions.html

[This section](https://reactjs.org/docs/faq-functions.html#how-can-i-prevent-a-function-from-being-called-too-quickly-or-too-many-times-in-a-row) states that people can use `throttle` or `debounce` to reduce the amount of times a function is called. There is another alternative that we have been getting great results from: `requestAnimationFrame` throttling:

https://github.com/alexreardon/raf-schd

Rather than sampling on a time basis - you sample based on `requestAnimationFrame`. This lets the browser decide how many times to actually call the function to optimise for render performance.

```js
import rafSchedule from 'raf-schd';

class ScrollListener extends React.Component {
  constructor(props) {
    super(props);
    this.nextFrameId = null;
    this.handleScroll = this.handleScroll.bind(this);
    this.scheduleUpdate = rafSchedule(this.emitUpdate.bind(this));
  }

  handleScroll(e) {
    this.nextFrameId = this.scheduleUpdate({ x: e.clientX, y: e.clientY });
  }

  emitUpdate(point) {
     this.props.update(point);
  }

  componentWillUnmount() {
    cancelAnimationFrame(this.nextFrameId);
  }

  render() {
    return (
      <textarea
        onScroll={this.handleScroll}
      />
    );
  }
}
```

I would be happy to add the technique to the docs if you think it worth while.

Cheers

**Comment by gaearon** [comment]
I've needed this pattern a few times. Let's add it.

**Comment by alexkrolick** [comment]
I also like that there would now be examples for click, change, and scroll, with throttling appropriate to common usage of those events 👍

**Comment by alexreardon** [comment]
Would you like me to raise a PR @gaearon ?

**Comment by gaearon** [comment]
Sure.

**Comment by bvaughn** [comment]
Nice suggestion @alexreardon! And great job getting the ball rolling with this section< @alexkrolick 😄
