### ISSUE TITLE
The prop value with an expression type of SequenceExpression could not be resolved. Please file issue to get this fixed immediately.

### ISSUE THREAD

**Issue by inblack67** [reactjs/reactjs.org#3120]
I was just contributing to the docs a few minutes ago and after running
```sh
yarn check
```
got this warning
 #### "The prop value with an expression type of SequenceExpression could not be resolved. Please file issue to get this fixed immediately." . 
Thought I'd let you know.

**Comment by rickhanlonii** [comment]
Do you mean `yarn lint`?

I get this as well, seems to be an eslint issue. Do you want to upgrade our eslint version to see if it fixes it?

<img width="945" alt="Screen Shot 2020-07-19 at 3 13 39 PM" src="https://user-images.githubusercontent.com/2440089/87883037-80d55080-c9d2-11ea-8abf-ed34a2ad81e5.png">

**Comment by inblack67** [comment]
I meant
```sh
yarn check-all
```
I tried upgrading eslint. No help!

**Comment by nawazeverlane** [comment]
https://github.com/jsx-eslint/jsx-ast-utils/issues/95 could be the issue blocking.

**Comment by nawazkhan** [comment]
https://github.com/jsx-eslint/jsx-ast-utils/issues/95 could be the issue blocking.

**Comment by rrhg** [comment]
[jsx-eslint/jsx-ast-utils#101](https://github.com/jsx-eslint/jsx-ast-utils/pull/101) was merged & should fix this.

**Comment by rickhanlonii** [comment]
@rrhg do you want to submit the PR to upgrade?

**Comment by rrhg** [comment]
I can try. If someone could provide some guidance that would be great. Thanks.

**Comment by rrhg** [comment]
Did some research & if I understand correctly, the 2 dependencies using it are eslint-plugin-react & eslint-plugin-jsx-a11y.

eslint-plugin-react has a newer release tag ([v7.21.4](https://github.com/yannickcr/eslint-plugin-react/tree/v7.21.4)) that updated jsx-ast-utils to 3.0.0 & should fix this.

But for eslint-plugin-jsx-a11y, we have to wait for an active branch ([v6.4.0](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/tree/tag-6.4.0)) to be merged. Apparently it should be ready soon.

**Comment by rickhanlonii** [comment]
Thanks for looking into it @rrhg!

**Comment by webrafaelso** [comment]
Please, fix this asap. GitLab ci/cd keep showing this error message when checking the project

**Comment by webrafaelso** [comment]
Please update this thread if this already fixed. thanks

**Comment by darbandi** [comment]
1.Install eslint-plugin-react-hooks@4.1.2
2.Run yarn eslint src --ext=js,jsx,ts,tsx

fix it

**Comment by rickhanlonii** [comment]
Merged the fix, please let us know if this is still an issue after pulling and re-running `yarn`.

**Comment by samirarezai** [comment]
you need to update react-scripts to solve this problem in package.json :

`"react-scripts": "^5.0.0",`

**Comment by sumantaparida** [comment]
> 1.Install eslint-plugin-react-hooks@4.1.2 2.Run yarn eslint src --ext=js,jsx,ts,tsx
> 
> fix it

Not work
