### ISSUE TITLE
Image has an incorrect aspect ratio

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#314]
Noticed this in https://reactjs.org/docs/lifting-state-up.html#lessons-learned:

<img width="933" alt="screen shot 2017-11-21 at 00 52 42" src="https://user-images.githubusercontent.com/810438/33049102-5b9c5c84-ce56-11e7-9a67-4476f7c438be.png">

Not sure if this is just a single image or if there's a pattern.

**Comment by jyash97** [comment]
Gone through the docs, I think this image is only having this problem because it has been assigned a fixed height of 322px.
![aspectratio](https://user-images.githubusercontent.com/22376783/33057501-5801d1de-ceb1-11e7-83d9-5c2b47941fd0.png)
