### ISSUE TITLE
Uncontrolled input with onChange handler

### ISSUE THREAD

**Issue by sarang-naico** [reactjs/reactjs.org#3195]
I was wondering whether I can use the `input` with the onChange handler without providing any `value`,
when I tried the code it is working fine but I am not sure whether this method is correct or not.
![input](https://user-images.githubusercontent.com/52169146/89902423-0def7c00-dc04-11ea-84a2-c8e1800cf008.PNG)

**Comment by gaearon** [comment]
Yes, this is expected to work.

**Comment by sarang-naico** [comment]
Thank you for the quick reply @gaearon
