### ISSUE TITLE
Footer not being rendered properly

### ISSUE THREAD

**Issue by tanishqdaiya** [reactjs/reactjs.org#3196]
https://reactjs.org/docs/getting-started.html#learn-react
In here it fells like the footer is mixed up. Next Article link is not working

**Comment by saswatamcode** [comment]
The footer seems to be rendered the same way across Docs, Tutorials, Blog and Community. Also the "Next Article" is a label. The link appears below in a much larger font.

**Comment by NaumanMoazzam** [comment]
I think, 'Next Article' should be align left. It confuses me for a second, but I guess it's like a presentation where heading is 'Next Article' & URL is in big fonts.

**Comment by anushri20** [comment]
I would like to work on this issue.
