### ISSUE TITLE
Remove link to CSS-in-JS comparsion site

### ISSUE THREAD

**Issue by necolas** [reactjs/reactjs.org#3214]
Screen: https://reactjs.org/docs/faq-styling.html

The link to a CSS-in-JS comparison site should be removed as it 1) hasn't been maintained for years, 2) doesn't provide much relevant information, 3) we don't actively audit these 3rd party efforts for accuracy

https://github.com/reactjs/reactjs.org/blob/ddbd064d41d719f9ec0c2f6a4227f797a5828310/content/docs/faq-styling.md#what-is-css-in-js-what-is-css-in-js

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/commit/1cc8aa3f033939e15323ff32e8fa1248706ddf92
