### ISSUE TITLE
Invalid hook call error when using React function component from npm package

### ISSUE THREAD

**Issue by theotheruserid** [reactjs/reactjs.org#3229]
I have a React function component, `SimpleComponent`, exported from `library` project and published on GitHub packages. This package is consumed in `consumer` project which simply renders `SimpleComponent`. If `SimpleComponent` is using React hook, it fails to render in `consumer` project and I get the following React hook related error:

```Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

library project: https://github.com/joshigaurava/library
consumer project: https://github.com/joshigaurava/consumer

Both projects use React, TypeScript and webpack. Package.json, TypeScript and webpack configs included.

`library` package version `0.0.1` contains `SimpleComponent` without React hook and it renders and functions fine in `consumer` project.

`library` package version `0.0.2` contains `SimpleComponent` with React hook and it fails to render in `consumer` project.

I see many others a facing similar issue and I have tried various things so far but nothing has worked:
- Ensured that there is a single dependency on `react/react-dom` in consumer project (`npm ls react`, `npm ls react-dom`)
- Ensured none of the issues listed at https://reactjs.org/warnings/invalid-hook-call-warning.html have occurred
- People seem to have solved this issue with `npm link` or symlinks when using `npm file:` in dependencies, but in my case, consumer project is using library project by consuming an npm package and so this doesn't apply
- Foolishly tried exporting `SimpleComponent` in different ways - with or without default etc.

Now I wonder if this has something to do with how webpack is bundling the library project. But I am spending too much time on this issue and any help will be appreciated.

**Comment by gaearon** [comment]
>Now I wonder if this has something to do with how webpack is bundling the library project.

Yes, you are bundling React itself into your library. You can check that by looking at the compiled bundle. The fix is to exclude React. In webpack, you can do this with the `externals` option.

**Comment by theotheruserid** [comment]
> Yes, you are bundling React itself into your library. You can check that by looking at the compiled bundle. The fix is to exclude React. In webpack, you can do this with the `externals` option.

Thank you @gaearon. That was indeed the issue. For anyone stumbling on this issue, following webpack config helped fix it:

```
externals = {
  react: {
    root: "React",
    commonjs2: "react",
    commonjs: "react",
    amd: "react",
    umd: "react",
  },
  "react-dom": {
    root: "ReactDOM",
    commonjs2: "react-dom",
    commonjs: "react-dom",
    amd: "react-dom",
    umd: "react-dom",
  },
};
```
