### ISSUE TITLE
how to set "one time import custom component in one file and usage in every pages & component without import in particular file" ? #19717

### ISSUE THREAD

**Issue by Jatin-Pixer** [reactjs/reactjs.org#3230]
I don't know it is possible or not but i need solution. If you have any suggestion then send us.

Requirement:

I made multiple component such as button, heading and etc.
Require all component is imported and used in pages.
This is simple and right way but i need like set all require component in one file (Ex. **App.js**) and I can use these all component in entire project without import modules in particular file. Is this possible ?

**Comment by eps1lon** [comment]
Duplicate of https://github.com/facebook/react/issues/19717
