### ISSUE TITLE
React copied itself 3 times

### ISSUE THREAD

**Issue by atabariscanalp** [reactjs/reactjs.org#3256]
I suddenly started to get `invalid hook call` error in React and after a little research I found out that I have multiple copies of React (Page loads 3 times and I see 3 React Apps in Redux DevTools [redux](https://i.stack.imgur.com/1jFYZ.png)). So I typed `npm ls react` in my project path and it gave me one React file, I really don't understand how can I delete the other copies. Please help me.

**Comment by eps1lon** [comment]
https://github.com/facebook/react/issues/13991 has a bunch of possible workarounds. If none of these help check out the [community resources](https://reactjs.org/community/support.html)-
