### ISSUE TITLE
Hooks support redux?

### ISSUE THREAD

**Issue by abvg156** [reactjs/reactjs.org#3272]
Hi All,

I am using react version 16.13.1
Can i use redux with hooks in my project which is on banking domain.

**Comment by eps1lon** [comment]
redux hooks should be compatible with any version past 16.8. If you need any more help check out our [community support](https://reactjs.org/community/support.html).

**Comment by abvg156** [comment]
Can I use hook context instead of redux for large project to maintaining state. Also does that hook context support for jest and enzyme test cases
