### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by ibrohim123** [reactjs/reactjs.org#3285]
`{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}`

**Comment by eps1lon** [comment]
For issues related to `create-react-app` please [open an issue in their repository](https://github.com/facebook/create-react-app/issues/new/choose). Don't forgot to provide as much information as possible by filling out their issue template.
