### ISSUE TITLE
When I was in the onClick`s callback, simulating clicking on other elements triggers an additional callback

### ISSUE THREAD

**Issue by Kunoky** [reactjs/reactjs.org#329]
Here's the link ：https://codepen.io/afc163/pen/JOvzZy?editors=0011
`
class NormalLoginForm extends React.Component {
  handleSubmit = (e) => {
    e.preventDefault();
    console.log('click button');
    //模拟点击
     document.getElementById('div').click();
  }
  render() {
    return (
      <div>
        < button onClick={this.handleSubmit} >
          Log in
        </ button >
        <div id='div' onClick={()=>console.log('click div')}>1111</div>
      </div>
    );
  }
}

ReactDOM.render(<NormalLoginForm />, mountNode);`

**Comment by bvaughn** [comment]
It looks like you're trying to report an issue with React. You can do that [here](https://github.com/facebook/react/issues/new). This repo is just for the documentation website.
