### ISSUE TITLE
Anchor links inside of Hooks page not working on fresh reload

### ISSUE THREAD

**Issue by yuanworks** [reactjs/reactjs.org#3313]
On the page https://reactjs.org/docs/hooks-reference.html, anchors are not working consistently.

![image](https://user-images.githubusercontent.com/3508123/95392158-d7e02700-092a-11eb-837f-192bdce7731d.png)

Clicking on any of the anchors when going from google (google: "react hooks"), or opening the page in incognito don't work sometimes. Not sure if it's related to an async script that hasn't loaded. I've seen it happen on and off for the last few days I believe.

Can anyone confirm that they can reproduce it?

**Comment by eps1lon** [comment]
Thanks for the report. I can reproduce it. However, this was already reported in https://github.com/reactjs/reactjs.org/issues/3261 so I'm closing.

**Comment by yuanworks** [comment]
Thank you, sorry for the duplicate 👍
