### ISSUE TITLE
On click on particular section, doesnt takes me to that particular part of the page

### ISSUE THREAD

**Issue by karan-tewari** [reactjs/reactjs.org#3327]
When I go to the https://reactjs.org/docs/hooks-reference.html
and click on the of the following links like useRef, the url becomes https://reactjs.org/docs/hooks-reference.html#useref but doesnt scroll to that part of the page

**Comment by amohapatra123** [comment]
@karan-tewari i checked the issue mentioned but its working fine.

**Comment by eps1lon** [comment]
Thanks for the report. We're tracking this already in #3261
