### ISSUE TITLE
Should I rely on the dependency list check of useEffect hook?

### ISSUE THREAD

**Issue by tranvansang** [reactjs/reactjs.org#3337]
Consider the following code

    useEffect(effect, [v]) // v can be undefined

I want to run the `effect` function **only** after the first render or when `v` changes.

My questions are

1. Do I need to check whether `v` changes in `effect` (with some refs, carefully, to avoid additional deps) ? Or I can rely on react to check the change of values of the dependency list (i.e., the `[v]`).
2. If the answer of 1. is the latter, is this behavior supposed to be changed in the near future? For e.g., when the concurrent mode is released.

From the [official docs](https://reactjs.org/docs/hooks-reference.html#useeffect)

> Conditionally firing an effect
>
> The default behavior for effects is to fire the effect after every completed render. That way an effect is always recreated if one of its dependencies changes.

It says **if** `one of its dependencies changes`, **then**, `an effect is recreated`. However, it does not mention the reverse: an effect is recreated **if and only if** one of its dependencies changes (or after the first render).

I only remember that in the early stage of hook, I read somewhere that the `effect` function can be run in some cases even without `v`'s change, in order to optimize the memory, or in concurrent mode?? I really do not remember exactly and could not find out the source.

It would be very helpful if anyone can tell me how exactly React does, or refer to the related internal source code. I think there would be a special check of the first render, otherwise, when `v` is `undefined` after the first render, `effect` will not run.

If possible I think this question is worth to be added to the [Hooks FAQ](https://reactjs.org/docs/hooks-faq.html) page.

**Comment by gaearon** [comment]
Can you tell more about the use case? We do plan some features that would cause effects to re-fire in some cases more often. However, in those cases, it would usually be _desirable_ for them to re-fire so I want to learn more about the specific case you're describing. What is your effect doing?

**Comment by tranvansang** [comment]
Lets see this example. When users click the "View All"/"View Less" button, we call `toggleViewAll` to toggle the viewAll state, and change documentElement.scrollTop to keep the current scroll position.

```
const [vewAll, setViewAll] = useState()
useLayoutEffect(() => {
  if (currentScrollTop.current === undefined) return
  document.documentElement.scrollTop = currentScrollTop.current
}, [viewAll])
```

```
  const toggleViewAll = () => {
    setViewAll((v) => {
      currentScrollTop.current = v
        ? undefined
        : document.documentElement.scrollTop;
      return !v;
    });
  };
```

I am trying to find more examples. Because of what I asked in the main question, I have been always adding a check by refs in several effect functions where some actions should only be run when the state really changes.

Now I am confused if I should remove all of them and rely on react to do that.

**Comment by tranvansang** [comment]
Other examples

- scroll to top when location.href changes
- pull new resolved data from the server when location.href changes

**Comment by gaearon** [comment]
Hmm. The specific case where we're considering refiring is related to when the component is shown/hidden. Like a way to keep the component mounted but hidden on the screen instead of unmounting when the route changes. I think it would still be desirable to re-fire in this scenario because it matches view "appearing" / "disappearing", like on mount.

**Comment by tranvansang** [comment]
Let me summarize the scenario by the following state machine. We have these states

- (1) unmounted, never rendered
- (2) mounted
- (3) rendered before but currently specially `unmounted`, and hidden instead of unmounted. As you said in the previous comment. This is a new state we never have seen before.

When the state changes
- (1) -> (2): effect fires
- (2) -> (2): dispose fires, then effect fires
- (2) -> (3): dispose fires
- (3) -> (2): effect fires

I think that what you are thinking *desirable* is considering `(1) -> (2)`, `(3) -> (2)` are the same.

Let me think more about this and continue the discussion if I find anything at least in our projects.

**Comment by gaearon** [comment]
(3) -> (3) could happen, this would be a regular update (while it's hidden). To be clear, this is still pretty hypothetical, but it's something we're beginning to experiment with. We wouldn't enable these semantics in old mode in either case, but it might be useful for newer features.

**Comment by tranvansang** [comment]
the idea sounds interesting, I have never been thinking about (3), like maintain an unmounting state of a component. For a very unopinionated project like react, this is a hard decision to choose, IMHO.

Let me share what I am thinking about, and hope that this can help. Regarding what the users consider, when (3) is the current state, about the appearance of the component.

- only (i) The component should be unmounted. Then everything is fine with the effect function, except that the previous states are different (inited, v.s., changed). We have the benefit of a faster re-rendering old component, but more memory consumed.
- only (ii) The component should be mounted. This sounds not good because the dispose function is called unexpectedly.
- can be (i) or (ii)

**Comment by tranvansang** [comment]
In the effect functions, these types of actions are desired

- (a) only run after the first render
- (b) only run after some changes from after the second render

Consider only (i) is the answer for the last comment, after the transition (3) -> (2), (a) is supposed to fire, but none of (a) or (b) fire.

**Comment by tranvansang** [comment]
With the new StrictMode behavior in react 18, useEffect is fired unconditionally in the second render, even though the deps array does not change.

My usecase is below

```javascript
const useData = (params) => {
  useEffect(() => {
    // if data is not available in cache fetch data
    if (store.has(params)) prefetchData(params)
  })
  const initedRef = useRef(false)
  useEffect(() => {
    // if we can rely on the condition that useEffect ONLY fires in the first render or when the deps array changes
    // this implementation works as expected
    if (!initedRef.current) return
    initedRef.current = true
    //refetch data ONLY when params changes
    prefetchData(params)
  }. [params])
}
```

Suppose that the StrictMode's purpose is to make sure that even if the second effect runs, it shouldn't cause any problem.
However, in fact, it causes the hydration to fail, as described in this issue https://github.com/facebook/react/issues/24388.

My current solution is to manually check if the deps array really change before calling `prefetchData(params)` in the second effect.
