### ISSUE TITLE
Documentation links broken on main site's version page

### ISSUE THREAD

**Issue by JustCodin** [reactjs/reactjs.org#3357]
All of the documentation links on 'https://reactjs.org/versions/' are not working.

**Comment by foreverabhi2002** [comment]
@JustCodin links are all working fine.
If you are facing any issue on any of the links then please specify or mention here.

**Comment by sijusamson** [comment]
@foreverabhi2002 go to version 16.8, and click on "Documentation".

**Comment by foreverabhi2002** [comment]
@sijusamson and @JustCodin, Yeah I've got the issue. Thanks for letting me know.

**Comment by foreverabhi2002** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/57245064/102095407-80d66100-3e49-11eb-86ef-1a7480e8e0db.png)

Got this!! the link is not broken the path has been removed and it leads to nowhere check this attachment.
I think it has been removed for purpose.

**Comment by rickhanlonii** [comment]
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268

**Comment by gaearon** [comment]
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
