### ISSUE TITLE
There are errors in the Chinese version of the official website

### ISSUE THREAD

**Issue by ssaylo** [reactjs/reactjs.org#3360]
Official website Chinese version
https://zh-hans.reactjs.org/docs/faq-versioning.html
```
开发环境的警告不会影响你的应用，你的应用在开发环境和生成环境的表现是一致的 —— 唯一的区别是生产环境不会打印出这些警告，并且生产环境的性能更好。（如果你发现了其他的区别，请提交 issue。）
```
shoud be
```
开发环境的警告不会影响你的应用，你的应用在开发环境和生成环境的表现是一致的 —— 唯一的区别是生产环境不会打印出这些警告，并且生产环境的性能更好。（如果你发现了其他的区别，请提交 issue。）
```
**生成环境** should be **生产环境**

**Comment by gaearon** [comment]
Please file an issue (or send a PR!) to the translation repo: https://github.com/reactjs/zh-hans.reactjs.org/

**Comment by ssaylo** [comment]
Got it
