### ISSUE TITLE
Link to a good key={index} danger explanation

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#339]
I liked this article: https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

I think we should link to it from Lists and Keys page for people who want to know why indexes as keys are not safe in some cases, since we often get asked that but it's not essential or easy to explain enough to include in the doc itself.

**Comment by mateoholman** [comment]
I can do a quick revision to the Lists and Keys page and find an appropriate place to insert the link if you would like help.

**Comment by gaearon** [comment]
👍 sounds great

**Comment by mateoholman** [comment]
Ok, added the link where I thought it may best fit in PR #340 😄
