### ISSUE TITLE
Documentation or types incorrect for tabIndex type?

### ISSUE THREAD

**Issue by Ed-Ed** [reactjs/reactjs.org#3408]
If you take a look at the documentation, it uses a string: https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

`<div tabIndex="-1" />      // Just like node.tabIndex DOM API`

But the types state that it should be a number: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts#L1767

`tabIndex?: number;`

**Comment by eps1lon** [comment]
That's a good point, thanks for bringing it up. I believe React is less strict behind the scenes. `readOnly="true"` might work as well. 

Note that "Just like node.tabIndex DOM API" only refers to the casing not the types ("React uses the camelCase convention just like the DOM APIs:"). Though it might help to qualify that statement again to be sure. 

What wording would you think is appropriate here?

**Comment by Ed-Ed** [comment]
> That's a good point, thanks for bringing it up. I believe React is less strict behind the scenes. `readOnly="true"` might work as well.
> 
> Note that "Just like node.tabIndex DOM API" only refers to the casing not the types ("React uses the camelCase convention just like the DOM APIs:"). Though it might help to qualify that statement again to be sure.
> 
> What wording would you think is appropriate here?

Yeah, string and number both work. IMO the docs should match the type, I made a PR for this change: https://github.com/reactjs/reactjs.org/pull/3409

I think the wording is fine, I just copied the code across, including the comment.
