### ISSUE TITLE
Make it clearer we don't necessarily encourage using CSS in JS

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#342]
I saw this more than a few times:

https://twitter.com/chrisrhymes/status/934459780130885632

We probably have some paragraph about inline styles in our docs, and people think it's the only (or even the most common) way of doing styling in React.

We should make it clearer that typically people use normal CSS with React, even though CSS in JS (via different approaches) is possible.

May be a good idea for the FAQ section.

**Comment by gaearon** [comment]
Could also be due to some example code using `style=` just for illustration purposes without realizing people take it seriously.

**Comment by markerikson** [comment]
It's like with the Redux docs.  People see examples and assume that's the "best/right/only" way to do things.

**Comment by jyash97** [comment]
Hey  @gaearon,
Let me give this a try and update you

**Comment by gaearon** [comment]
Here's a specific section that might need an extra explanation. https://twitter.com/chrisrhymes/status/934485220073590785?s=17

**Comment by jyash97** [comment]
#344

**Comment by bvaughn** [comment]
Closed by #344. Some follow-up work via #346 as well.
