### ISSUE TITLE
Bundling/Code Splitting Guide

### ISSUE THREAD

**Issue by thejameskyle** [reactjs/reactjs.org#343]
I think we should be doing a better job encouraging React apps to do code splitting. Would an "Advanced" guide with the following structure be accepted?

- Bundling - What is it?
- Code Splitting - What is it?
- `import()` - Using it to code split
- Libraries:
  - React Loadable - Loading components/error states/etc
  - Other libs?

Most of the page will assume you're using Create React App or have Webpack setup already, it'll mention that you'll need one of the two and link to the Webpack docs.

**Comment by bvaughn** [comment]
That sounds great to me, James. I'd love to see such a PR.

**Comment by gaearon** [comment]
Fixed by https://github.com/reactjs/reactjs.org/pull/348.
