### ISSUE TITLE
Code formatting is not working in official docs

### ISSUE THREAD

**Issue by RRode** [reactjs/reactjs.org#3439]
It seems that code formatting is not working. I tried it in Windows 10 using Chrome (Version 86.0.4240.198) and Firefox (83.0).

![image](https://user-images.githubusercontent.com/2607323/101461407-1ef29480-393b-11eb-9884-3504c201d23e.png)

**Comment by eps1lon** [comment]
The page is currently having trouble loading JavaScript responsible for this functionality. We're already tracking it in https://github.com/reactjs/reactjs.org/issues/3437 with a workaround explained in  https://github.com/reactjs/reactjs.org/issues/3437#issuecomment-740549531
