### ISSUE TITLE
Code examples are never loaded

### ISSUE THREAD

**Issue by RRode** [reactjs/reactjs.org#3440]
Again on Windows 10 using Chrome (Version 86.0.4240.198) and Firefox (83.0).

![image](https://user-images.githubusercontent.com/2607323/101462980-2155ee00-393d-11eb-94f2-d55622008ec6.png)

**Comment by eps1lon** [comment]
The page is currently having trouble loading JavaScript responsible for this functionality. We're already tracking it in https://github.com/reactjs/reactjs.org/issues/3437 with a workaround explained in  https://github.com/reactjs/reactjs.org/issues/3437#issuecomment-740549531
