### ISSUE TITLE
Code blocks are broken

### ISSUE THREAD

**Issue by talkor** [reactjs/reactjs.org#3442]
Steps to reproduce:

1. Go to https://reactjs.org/docs/context.html (there are other pages affected as well).

Current behavior:
- Code blocks are overflowing horizontally.
- Code blocks are missing style and syntax highlighting.
- Also probably the navigation sidebar is missing.

<img width="1547" alt="Screen Shot 2020-12-08 at 15 13 41" src="https://user-images.githubusercontent.com/18269880/101488201-f765f100-3967-11eb-830a-6abdec45d8a8.png">

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/3437#issuecomment-740607814

**Comment by foreverabhi2002** [comment]
Hi, @talkor  and @gaearon, Codeblocks and the sidebar items all fine now. 
You can check.

**Comment by foreverabhi2002** [comment]
@talkor Please close this issue now.

**Comment by eps1lon** [comment]
Should be resolved: https://twitter.com/reactjs/status/1336729989161635842
