### ISSUE TITLE
Sidebar expandable menus are not opening

### ISSUE THREAD

**Issue by talkor** [reactjs/reactjs.org#3443]
Steps to reproduce:
1. Go to https://reactjs.org/docs/getting-started.html
2. Click on any expandable section on the sidebar, for example `API Reference`.

Result:
1. Expandables are not expanded, cannot navigate to any of the sidebar sections.

<img width="1448" alt="Screen Shot 2020-12-08 at 15 17 26" src="https://user-images.githubusercontent.com/18269880/101488656-8bd05380-3968-11eb-8df8-c5ef7b1fbaf3.png">

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/3437#issuecomment-740622093

**Comment by eps1lon** [comment]
Should be resolved: https://twitter.com/reactjs/status/1336729989161635842
