### ISSUE TITLE
Main Page broken link.

### ISSUE THREAD

**Issue by gubareve** [reactjs/reactjs.org#3471]
On the main page in the `A Simple Component` section, the `Babel REPL` text links to <https://babeljs.io/repl/#?presets=react&code_lz=MYewdgzgLgBApgGzgWzmWBeGAeAFgRgD4AJRBEAGhgHcQAnBAEwEJsB6AwgbgChRJY_KAEMAlmDh0YWRiGABXVOgB0AczhQAokiVQAQgE8AkowAUAcjogQUcwEpeAJTjDgUACIB5ALLK6aRklTRBQ0KCohMQk6Bx4gA> which returns a 404.

![img](https://cdn.evang.dev/2020/12/30/firefox_q9HvRA.png)
![img](https://cdn.evang.dev/2020/12/30/firefox_QdDDUF.png)

**Comment by gubareve** [comment]
From what I can tell, the link redirects to `https://babeljs.io/repl/#?presets=reac ...` instead of `https://babeljs.io/repl#?presets=reac ...`.

**Comment by eps1lon** [comment]
Does this still happen to you? Both the link on the main page and the one you posted here work for me.

**Comment by dantehemerson** [comment]
Also, It's working for me

**Comment by gubareve** [comment]
Still not working for me:

https://user-images.githubusercontent.com/24500411/103430419-bd5bc980-4b78-11eb-9356-a4b381ac833a.mp4

**Comment by ThakurBallary** [comment]
It's working as expected.

https://user-images.githubusercontent.com/25402167/103456421-1e6fd280-4d1c-11eb-8f24-9a782c767f03.mp4

**Comment by eps1lon** [comment]
Closing since this is most likely network related. Maybe some corporate firewall or proxy that's interfering?
