### ISSUE TITLE
Improper documentation about accessing Refs using the functional components

### ISSUE THREAD

**Issue by sumitshinde2608** [reactjs/reactjs.org#3476]
ES7 is picking up numbers and people are moving to functional components none of the less but there is no proper reference material to them

**Comment by eps1lon** [comment]
Thanks for the feedback!

Could you explain where you expected to find material for refs on function components and what should be explained for function components specifically?

**Comment by sumitshinde2608** [comment]
I went on to this link: https://reactjs.org/docs/refs-and-the-dom.html
I expected it to have a mention of the fact that to use refs in functional component, you need to do it by using the UseRef hook and also have the boilerplate code to do the same

**Comment by sumitshinde2608** [comment]
If possible, can I contribute to resolving the issue. I am a novice developer and this contribution would mean a lot :)

**Comment by eps1lon** [comment]
> I went on to this link: [reactjs.org/docs/refs-and-the-dom.html](https://reactjs.org/docs/refs-and-the-dom.html)
> I expected it to have a mention of the fact that to use refs in functional component, you need to do it by using the UseRef hook and also have the boilerplate code to do the same

Is this not what https://reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components does?

If you're saying it should come before class components then this'll be most likely fixed with https://github.com/reactjs/reactjs.org/issues/3308

**Comment by sumitshinde2608** [comment]
I meant it to be in the way it has been given in this reference : https://medium.com/javascript-in-plain-english/react-refs-both-class-and-functional-components-76b7bce487b8
