### ISSUE TITLE
unable to get complete folders with npx create-react-app my-app 

### ISSUE THREAD

**Issue by mirzaumersaleem** [reactjs/reactjs.org#3483]
Node version v10.16.0
System : macbook pro MD101

Hey team , I am trying to create react app by following documentation on official page "https://reactjs.org/docs/create-a-new-react-app.html#create-react-app" , after running "npx create-react-app my-app" I got only 3 folders i.e node_modules , package.json , packag-lock.json that's it .

moreover package.json file contains only these lines. No scripts there for start and build 
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1"
  }  
}
 
Kindly look into this.
Thanks

**Comment by rickhanlonii** [comment]
I just ran it and got all the correct files and scripts. If you still get the issue, can you create a bug in the [create-react-app](http://github.com/facebook/create-react-app) repo with more information?
