### ISSUE TITLE
examples with hooks in the main concepts.

### ISSUE THREAD

**Issue by PabloProta** [reactjs/reactjs.org#3485]
Very nice to have examples using classes, but I think it is interesting (in the view of a beginner) to show an alternative using hooks, since it is considered a good practice and for me it was easier to understand.
At the beginning of the walkthrough, specifically in the part of the life cycle and the states, as much as it is expected that you have prior knowledge with classes, it would be good if we already had contact with the hooks, in order to know how to use them , even if succinctly, as an alternative to classes.

**Comment by rickhanlonii** [comment]
Hey @PabloProta, thanks for the suggestion.

We're working on this as part of the new site in https://github.com/reactjs/reactjs.org/issues/3308
