### ISSUE TITLE
Document "props vs state" in FAQ

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#351]
https://twitter.com/CarysMills/status/934908731950759936?s=17 includes two good links that we should have in the FAQ.

**Comment by jyash97** [comment]
@gaearon #341 also based on this

**Comment by bvaughn** [comment]
I've marked this issue in progress since @jyash97 is going to pull it into #341

**Comment by jyash97** [comment]
@bvaughn I have applies the changes in my latest commit #341
