### ISSUE TITLE
Old documentation links are broken

### ISSUE THREAD

**Issue by matyasf** [reactjs/reactjs.org#3514]
Go to https://reactjs.org/versions/
Click any of the old documentation links, e.g. https://reactjs.org/version/16.8 or https://reactjs.org/version/16.3
You'll get a 'page not found' page.

**Comment by rickhanlonii** [comment]
Closing as dupe of https://github.com/reactjs/reactjs.org/issues/3268

**Comment by gaearon** [comment]
Fixed in https://github.com/reactjs/reactjs.org/pull/3516
