### ISSUE TITLE
Document simulating browser events

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#352]
Maybe for the FAQ. It's commonly asked how to simulate events in React. We have Simulate helpers but they only trigger the React events without the browser behavior. In some cases that's not enough. We also have SimulateNative helpers but they're undocumented and I think we should get rid of them (https://github.com/facebook/react/issues/11656).

What we should do IMO is to document how to use browser APIs to dispatch normal browser events. Surprisingly many people have no idea (including myself a few weeks ago). For example: https://github.com/facebook/react/issues/11111#issuecomment-347209267. (It's also commonly missed that the node needs to be in the document for this to work with React.)

**Comment by radubrehar** [comment]
I'm working on this.

**Comment by radubrehar** [comment]
Build preview deployed at https://deploy-preview-375--reactjs.netlify.com

**Comment by eps1lon** [comment]
This should be sufficiently covered by now in [Testing Recipes#events](https://reactjs.org/docs/testing-recipes.html#events).
