### ISSUE TITLE
Out-of-date paths for React and React-DOM UMD builds documented in How to Contribute page

### ISSUE THREAD

**Issue by tsairinius** [reactjs/reactjs.org#3524]
After building react (using either `yarn build` or `yarn build react/index,react-dom/index --type=UMD`), the resulting UMD builds no longer reside at `build/dist/react.development.js` and `build/dist/react-dom.development.js`, which is what is currently documented (see [How to Contribute](https://reactjs.org/docs/how-to-contribute.html)): 

<img width="749" alt="old-path" src="https://user-images.githubusercontent.com/9063787/107836459-101cc980-6d52-11eb-8e31-4f6e540387bb.png">

 The builds now appear to be located at `build/node_modules/react/umd/react.development.js` and `build/node_modules/react-dom/umd/react-dom.development.js`. 

I opened a PR for this issue: https://github.com/reactjs/reactjs.org/pull/3523

**Comment by rickhanlonii** [comment]
Oh yeah nice catch!

**Comment by rickhanlonii** [comment]
Closed by https://github.com/reactjs/reactjs.org/pull/3523
