### ISSUE TITLE
Little typos can be significant to newbies

### ISSUE THREAD

**Issue by jfkquality** [reactjs/reactjs.org#3531]
In the very first sentence of the main content on https://reactjs.org/ there is this typo (in double quotes). Makes the sentence harder to understand. Should "what" be "that"?

'React components implement a render() method that takes input data and returns "what" to display'

**Comment by twalton83** [comment]
Not necessarily, what if the input data is an object, we can't return "that" object to display, but we can tell the component "what" needs to be displayed from that input data.

**Comment by rickhanlonii** [comment]
Thanks for the feedback but I believe "what" is correct here: render returns what you want to display.
