### ISSUE TITLE
When accessing the React project, GPU acceleration leads to 100% CPU usage, resulting in operation delays

### ISSUE THREAD

**Issue by enjoy-wind** [reactjs/reactjs.org#3544]
Visit a React project, then enter a list page, open the chrome task manager, and click the "search" button. At this time, the CPU in the GPU process is 90.4, which causes the action to delay dozens of seconds.
condition:
1. In low-performance machines, such as: computer configuration: 1 core 2G.
2. 2.chrome version: 87.0.4280.88, 72.0.3626.109, 80.0.3987.132. But 71.0.3578.98 is a normal CPU, and there is no delay in user actions.

Environment | Info
antd | 3.26.0
React | 15.6.2
System | win10

**Comment by eps1lon** [comment]
Thanks for the report.

You probably want to file this issue in https://github.com/facebook/react instead. The current repository is strictly used for documentation issues not issues with React itself.

Though before you do please provide more information for your issue. 
Please provide a CodeSandbox (https://react.new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
