### ISSUE TITLE
Inaccurate wording in "Render Props": "instance method"

### ISSUE THREAD

**Issue by JingkangZhang** [reactjs/reactjs.org#3546]
In the chapter "Render Props", in explaining why arrow functions can cause inefficiency with React.PureComponent and the solution to it, the doc says:

> To get around this problem, you can sometimes define the prop as an instance method, like so:
> 
> ```js
> class MouseTracker extends React.Component {
>   // Defined as an instance method, `this.renderTheCat` always
>   // refers to *same* function when we use it in render
>   renderTheCat(mouse) {
>     return <Cat mouse={mouse} />;
>   }

It mentions the word "instance methods" twice, which can be a source of confusion. In JavaScript, an [instance property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#instance_properties) can be a method, which can either be attached to the prototype or not. `renderTheCat` in this case, however, is a [prototype method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#prototype_methods). This may be significant because a prototype method is only defined once on all instances' prototype, as desired in relation to the topic of PureComponent efficiency. 

I can submit a PR if desired.

**Comment by rickhanlonii** [comment]
It's true that in a prototype based language there's no concept of "class" and "instance", but informally "instance" is used in JavaScript to mean an object created using a particular constructor function. A prototype method is an "instance method" in that it is available on class instances created using the `new` keyword where the context within the function via `this` will be the instance of the class. So it's common, and accurate enough, to say that prototype methods are instance methods, and in each case the method is only defined once on the class/prototype.
