### ISSUE TITLE
Can you add the Hooks linting info

### ISSUE THREAD

**Issue by nonopolarity** [reactjs/reactjs.org#3548]
It seems weird that

https://reactjs.org/docs/hooks-rules.html

> We released an ESLint plugin called eslint-plugin-react-hooks that enforces these two rules. You can add this plugin to your project if you’d like to try it:

> This plugin is included by default in Create React App.

> `npm install eslint-plugin-react-hooks --save-dev`

It seems weird that if it is included by default, then why do we need to install it?

Also, could you add the line as to how to invoke the linting?

It seems it is adding the `lint` line:

```
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint src"
```

for the default create-react-app

and to invoke it

```
npm run lint
```

Maybe you can state for the 
```
// Your ESLint configuration
```
it is the file `.eslintrc.js` because somebody may not know or see the format and think it is `package.json`

**Comment by rickhanlonii** [comment]
@nonopolarity it's installed by default in Create React App, which is only one way to use React. For other ways, like in vanilla React apps configured yourself, you'll need these instructions to know how to install it yourself.
