### ISSUE TITLE
Fix Tutorial CodePen to use constructor(props) and super(props)

### ISSUE THREAD

**Issue by samsch** [reactjs/reactjs.org#358]
The CodePen links in the tutorial are missing the props param/arg in constructors.

E.g., this:
```jsx
class Square extends React.Component {
  constructor() {
    super();
    // ...
  }
}
```
Should be replaced with:
```jsx
class Square extends React.Component {
  constructor(props) {
    super(props);
    // ...
  }
}
```
I think this includes all the linked CodePens which use the constructor:
-  https://codepen.io/gaearon/pen/VbbVLg?editors=0010
-  https://codepen.io/gaearon/pen/gWWZgR?editors=0010
-  https://codepen.io/gaearon/pen/gWWQPY?editors=0010
-  https://codepen.io/gaearon/pen/ybbQJX?editors=0010
-  https://codepen.io/gaearon/pen/QvvJOv?editors=0010
-  https://codepen.io/gaearon/pen/gWWZgR?editors=0010
-  https://codepen.io/gaearon/pen/PmmXRE?editors=0010
-  https://codepen.io/gaearon/pen/EmmGEa?editors=0010
-  https://codepen.io/gaearon/pen/EmmOqJ?editors=0010
-  https://codepen.io/gaearon/pen/LyyXgK?editors=0010
-  https://codepen.io/gaearon/pen/KmmrBy?editors=0010

**Comment by gaearon** [comment]
Done, thanks.
