### ISSUE TITLE
State Hook docs don't use functional updates to change state based on a previous state.

### ISSUE THREAD

**Issue by chrisdrifte** [reactjs/reactjs.org#3585]
### Problem

In [Using the State Hook](https://reactjs.org/docs/hooks-state.html), the given example changes state based on a previous state without a functional update.

```jsx
import React, { useState } from 'react';

function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}> // shouldn't this be `setCount(count => count + 1)` ?
        Click me
      </button>
    </div>
  );
}
```

The [Equivalent Class Example](https://reactjs.org/docs/hooks-state.html#equivalent-class-example) also fails to use a functional update against the explicit recommendations of the [state and lifecycle docs](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous).

```jsx
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
  }

  render() {
    return (
      <div>
        <p>You clicked {this.state.count} times</p>
        <button onClick={() => this.setState({ count: this.state.count + 1 })}> // shouldn't this be this.setState( (state) => ...) ?
          Click me
        </button>
      </div>
    );
  }
}
```

Relying on a functional component's local scope to have the most recent state causes subtle, easy to miss bugs under the following conditions:

- Whenever state is updated asynchronously
- Whenever state is updated more than once during a single render
- When using the state setter in a callback, if implementation of the caller becomes asynchronous in future

I've written some (admittedly slightly contrived) [example components](https://codesandbox.io/s/broken-state-changes-88em7?file=/src/index.js:1908-1912) that are all broken because they use `setCount(count + 1)` - but would work fine if they used `setCount(count => count + 1)`.

### Solutions

1. Change the first example in the docs that uses `setCount(count + 1)` to a simpler component that updates state independently of previous state, thereby avoiding the nuance completely.

2. Make an explicit recommendation for functional updates (similar to that found in [State and Lifecycle](https://codesandbox.io/s/broken-state-changes-88em7?file=/src/index.js:1908-1912)) - rather than [just mentioning them](https://reactjs.org/docs/hooks-reference.html#functional-updates) in passing in a completely different place.

3. If the "Equivalent Class Example" is kept, it should probably follow the react doc's own recommendations for updating state.

### Am I wrong?

Part of me wonders if the react docs are written this way for a particular reason, and I'm second guessing myself a little -- so I'd love to hear why I'm wrong about this.

**Comment by eps1lon** [comment]
Thanks for writing this up. 

The [React docs are currently being rewritten](https://github.com/reactjs/reactjs.org/issues/3308) and this particular problem was already mentioned in https://github.com/reactjs/reactjs.org/issues/3308#issuecomment-762823578.

With the new docs this issue should be resolved but leaving this open for visibility i.e. revisit the issue after the new docs launch.

**Comment by eps1lon** [comment]
Closing in favor of https://github.com/reactjs/reactjs.org/issues/3308 which will adress this issue.
