### ISSUE TITLE
How to trigger hook based component from vanilla Javascript DOM script.

### ISSUE THREAD

**Issue by amitshahc** [reactjs/reactjs.org#3592]
Hello,

Can you address this issue using React Hooks?
https://stackoverflow.com/questions/66762339/calling-react-function-based-component-from-vanilla-javascript-dom

**Comment by eps1lon** [comment]
We use this issue tracker for bugs, features etc related to the React docs. Support questions often go unanswered so I encourage you to wait a bit for the answer on StackOverflow or try another support channel listed on https://reactjs.org/community/support.html
