### ISSUE TITLE
Document using "Highlight Updates" in React DevTools

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#360]
As of React 16 it now works correctly and highlights components that re-render. We should mention this in "Optimizing Performance".

**Comment by sanjsanj** [comment]
@gaearon May I pick up this PR please?  I'm very new to open source contributing and would love to start small.  p.s. Huge fan :)

**Comment by gaearon** [comment]
Sure!

**Comment by sanjsanj** [comment]
@gaearon Brilliant, cheers!  Just a few questions:

1 - Is this for the standalone react-devtools node package or the chrome and firefox extension, or both?
2 - Where should it go in the Docs tree?  I've provisionally started it in Advanced Guides > Highlight Updates (Just under Optimizing Performance).
3 - Is this using [Trace React Updates](https://github.com/facebook/react-devtools/issues/335)?  Thereby making the colors listed in that issue accurate?

I assume you want the content to be something like:

- Explain the use case
- How to install and enable
- How to use and interpret

**Comment by sanjsanj** [comment]
@gaearon Ok I've had a go, please have a look when you get the chance, I'm happy to change whatever needs changing - https://github.com/reactjs/reactjs.org/pull/387/files

What it looks like:

![page](https://user-images.githubusercontent.com/4478671/33516401-26e6adc4-d76a-11e7-8eb1-5bfb381c9467.png)

Things to note would be that I've included an animated gif at the top and a link to a relevant blog post and app.

**Comment by sanjsanj** [comment]
Just popping in a direct link to the section, for your feedback when you get a chance

https://deploy-preview-387--reactjs.netlify.com/docs/optimizing-performance.html#visualize-component-updates-with-react-devtools-highlight-updates-feature

Having left it for a week and re-read it I guess I might want to make a couple of tweaks but I'd rather wait to hear your opinion first :)

**Comment by sanjsanj** [comment]
I've consolidated the information about "highlight updates" a little bit further down in the "Avoid Reconciliation" section since it fit more naturally into the workflow there, and trimmed the content a bit to be only what's super-relevant.
