### ISSUE TITLE
Spelling error in documentation (language: Spanish)

### ISSUE THREAD

**Issue by GaboCuba** [reactjs/reactjs.org#3604]
In the link:
https://es.reactjs.org/docs/hooks-reference.html#useref

The accent is missing in the word: "código".

Where it says: ... "Si quieres correr algún codigo cuando React agregue"...
I should say: ..."Si quieres correr algún código cuando React agregue"...

Greetings

**Comment by eps1lon** [comment]
Thanks for the report. You probably want to open this against https://github.com/reactjs/es.reactjs.org instead since that repository is concerned with the spanish translation.
