### ISSUE TITLE
Not a clear mention of React 17 removing Timings from the Chrome Performance tab.

### ISSUE THREAD

**Issue by OndeVai** [reactjs/reactjs.org#3605]
Is there any chance the documentation (https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) can make a note about React 17 no longer using the Timing API from Chrome? It's super confusing to not see it, especially after seeing so many outdated blogs referencing Timings.

**Comment by gaearon** [comment]
Oof, this should've just been completely removed. Want to send a PR removing it and adding a small note that it used to exist?
