### ISSUE TITLE
Update homepage with a step-by-step example

### ISSUE THREAD

**Issue by KarandikarMihir** [reactjs/reactjs.org#3613]
_I'm creating this issue from my mobile. I'll update the issue with standard template in some time _

I want to propose a change to the home page of Reactjs.org website. The to-do app for beginners is filled with too much of code IMO. Can we create a few more steps in it and add things to it incrementally?

We could probably add some animations that look delightful and engaging to the first time users.

**Comment by eps1lon** [comment]
Added as feedback for https://github.com/reactjs/reactjs.org/issues/3308.
