### ISSUE TITLE
Please explain how to properly do scroll restoration as Facebook does with their infinite scrolling.I am tired of getting "Go to stackoverflow" as a reply. Info very unclear there. Atleast add something related to scroll restoration.

### ISSUE THREAD

**Issue by ynsfasttoday** [reactjs/reactjs.org#3625]

**Comment by eps1lon** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html
