### ISSUE TITLE
[RFC]: documents should supplement this usage of useState

### ISSUE THREAD

**Issue by yklydxtt** [reactjs/reactjs.org#3640]
Put a function in setState,the function will be called,but the official document has't recored this usage
Wxample like this:
```js
const [state,setState]=useState(0);
setState(prevValue => prevValue + 1);
```
I hope add this usage  in official document

**Comment by eps1lon** [comment]
Duplicate of https://github.com/reactjs/reactjs.org/issues/3585

**Comment by reza-boroushaki** [comment]
Agree

**Comment by reza-boroushaki** [comment]
Why Closed!

**Comment by reza-boroushaki** [comment]
hey
