### ISSUE TITLE
React 17 for React Native Event Pooling clarification.

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [reactjs/reactjs.org#3654]
This page:
https://github.com/reactjs/reactjs.org/blob/master/content/docs/legacy-event-pooling.md

says React 17 changes Event pooling. the Blog Post link is 404.

Trying to use the Event.nativeEvent of a Pressable in React Native 0.64.2 + React 17 results in:

```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://reactjs.org/link/event-pooling for more information.
```

But that page doesn't contain useful information for React Native.

I'm not sure how to proceed, I just want the co-ordinates of the press event, the absolute simplest of possible cases (except for basic detection _of a click_)

**Comment by eps1lon** [comment]
> the Blog Post link is 404.

On github I could confirm but on the [deployed docs](https://reactjs.org/docs/legacy-event-pooling.html) it works.

> But that page doesn't contain useful information for React Native.

That page is only concerned with React native and React 16. So you should use event.persist in React native if you need the event at a later point. 

Does this clear things up?

**Comment by AlphaJuliettOmega** [comment]
event.persist() works as documented, thank you :)
