### ISSUE TITLE
All React versions are not displayed in fr.reactjs.org/versions

### ISSUE THREAD

**Issue by dimitridumont** [reactjs/reactjs.org#3663]
Hello, all React versions are not displayed in fr.reactjs.org/versions

You can check here: https://reactjs.org/versions/, you have all versions

On french site, versions 17 and later are not displayed: https://fr.reactjs.org/versions/
![image](https://user-images.githubusercontent.com/25826657/116377056-1e3a9c00-a811-11eb-9e0d-a58c4d316807.png)

**Comment by kiragona** [comment]
Hi, going to handle this issue

**Comment by marianna-exelate** [comment]
Please see PR [here](https://github.com/reactjs/fr.reactjs.org/pull/338 )

**Comment by reza-boroushaki** [comment]
Hello

**Comment by reza-boroushaki** [comment]
Salami

**Comment by reza-boroushaki** [comment]
Alo

**Comment by reza-boroushaki** [comment]
Hey

**Comment by reza-boroushaki** [comment]
Nice

**Comment by reza-boroushaki** [comment]
szxzxzx

**Comment by reza-boroushaki** [comment]
Oh

**Comment by reza-boroushaki** [comment]
Howdy

**Comment by shamwela** [comment]
I think this issue is fixed. @harish-sethuraman
