### ISSUE TITLE
Mission Key attribute in list item in the example of list and key

### ISSUE THREAD

**Issue by novamaster-official** [reactjs/reactjs.org#3681]
Hello, I think here is a key attribute is missing in the example of **Correct Key Usage**
link : https://reactjs.org/docs/lists-and-keys.html
```
function ListItem(props) { 
  // Correct! There is no need to specify the key here:
  return <li>{props.value}</li>;
}
```
I think it should be like this
```
function ListItem(props) { 
  // Correct! There is no need to specify the key here:
  return <li key={props.key}>{props.value}</li>;
}
```

**Comment by eps1lon** [comment]
Let's keep the discussion in a single place: https://github.com/reactjs/reactjs.org/pull/3684
