### ISSUE TITLE
Docs regarding setState are in direct conflict with one another

### ISSUE THREAD

**Issue by johncmunson** [reactjs/reactjs.org#3692]
In [Introducting Hooks](https://reactjs.org/docs/hooks-intro.html), and several other places, there is a simple counter example that illustrates how to use the `useState` hook.
```js
function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

However, there happens to be another counter example in the [Hooks API Reference](https://reactjs.org/docs/hooks-reference.html#functional-updates) for `useState`.
```js
function Counter({initialCount}) {
  const [count, setCount] = useState(initialCount);
  return (
    <>
      Count: {count}
      <button onClick={() => setCount(initialCount)}>Reset</button>
      <button onClick={() => setCount(prevCount => prevCount - 1)}>-</button>
      <button onClick={() => setCount(prevCount => prevCount + 1)}>+</button>
    </>
  );
}
```

In this second example, a callback is being passed into the setState function, and the code is accompanied by the following language...
> The ”+” and ”-” buttons use the functional form, because the updated value is based on the previous value.

__This would imply that the first example (which is in a very prominent location in the docs by the way), is actually incorrect and is encouraging an anti-pattern.__

I hope you can see how these two examples are in direct conflict with one another and might be causing confusion in the community!

**Comment by gaearon** [comment]
Yeah, we're addressing this in the ongoing docs rewrite.

**Comment by Aaro247** [comment]
test comment

**Comment by Aaro247** [comment]
hey

**Comment by Aaro247** [comment]
hey

**Comment by Aaro247** [comment]
fe
