### ISSUE TITLE
Top "Get Started" & "Take the Tutorial" links are blocked on screens of width > 1280px

### ISSUE THREAD

**Issue by KyleAMathews** [reactjs/reactjs.org#372]
Not sure what's intercepting the clicks.

**Comment by bvaughn** [comment]
Seems related to a [recent logo SVG change](https://github.com/reactjs/reactjs.org/pull/354#issuecomment-348071051) that I believe was fixed by Sophie via #373.

Please let me know if you're still seeing this and I'll reopen the issue!
