### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by LDSY-wjx** [reactjs/reactjs.org#3720]
在react的文档--高级指引--与第三方库协同--拖动到最下方。
原文：这个技术并不仅限于 Backbone。你可以通过在生命周期方法中订阅其更改并，
修改：这个技术并不仅限于 Backbone。你可以通过在生命周期方法中订阅其更改，
多了一个汉字“并”

**Comment by eps1lon** [comment]
Google translate is telling me it's about a typo in chinese? You probably want to file these issues against https://github.com/reactjs/zh-hans.reactjs.org or https://github.com/reactjs/zh-hant.reactjs.org

**Comment by QC-L** [comment]
Hi, @eps1lon. Can be closed, I've fixed it in [this commit](https://github.com/reactjs/zh-hans.reactjs.org/commit/c51623ab45380c3d30d73d15207af3ff2ed25d65)
