### ISSUE TITLE
issue on create-react-app

### ISSUE THREAD

**Issue by reflycharles123** [reactjs/reactjs.org#3747]
i have got some   7 vulnerabilities after do npx create-react-app, and i think its new in here, 3 moderate and 4 with high status
![vulberabilities](https://user-images.githubusercontent.com/59403484/123099666-fd837100-d464-11eb-8488-b5f7e4fec2b3.png)

**Comment by shreezvevo** [comment]
enter command "npm audit fix" it clearly says there after that you should be good to go :)
