### ISSUE TITLE
Openclassroom courses - dead link

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [reactjs/reactjs.org#3754]
Hello,

The french course in OpenClassroom have change.

**The link here is dead:**
https://fr.reactjs.org/community/courses.html
https://openclassrooms.com/fr/courses/4664381-realisez-une-application-web-avec-react-js

**This is the new link:**
https://openclassrooms.com/fr/courses/7008001-debutez-avec-react

And they have create a Redux course:
https://openclassrooms.com/fr/courses/5511091-organisez-votre-application-avec-la-logique-redux

Thanks

**Comment by dimitri-bourreau** [comment]
Openclassrooms themselves added a redirection so the dead link redirects to the new course. ✨

The link therefore is not dead.

I [proposed a PR](https://github.com/reactjs/fr.reactjs.org/pull/364) to keep the codebase clean, and the course description updated according this new course from Openclassrooms.

**Comment by hug0b** [comment]
Looks like this was solved and can be closed 👍
