### ISSUE TITLE
Remove unnecessary "use strict" directives from source files

### ISSUE THREAD

**Issue by extg** [reactjs/reactjs.org#376]
As per the below discussion, let's remove the unnecessary `use strict` directives scattered throughout the source code (like [here](https://github.com/reactjs/reactjs.org/blob/2bdc003c126475234160e67e52244c42d71755bb/src/components/ButtonLink/ButtonLink.js#L7)).

### Original issue
In each component I saw `use strict;` directive and my question for what, what is a meaning?  
[Spec] declare **"Module code is always strict mode code."**

There is a example of code with strict mode
https://github.com/reactjs/reactjs.org/blob/master/src/components/ButtonLink/ButtonLink.js#L7

[spec]: http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

**Comment by bvaughn** [comment]
Short answer? Maybe just habit.

You're right. ES6 modules are always in strict mode. Our code is run through Babel+Webpack so it can work with browsers that don't support ES6 modules natively though (like Internet Explorer). But I think this process auto-adds the "use strict" directive for code that's declared in modules, so maybe our declaring them in the source too is not necessary?

I'm not positive about this.

**Comment by gaearon** [comment]
Babel 6 automatically adds them *everywhere* regardless of whether it's a module. That behavior is wrong though and I think they plan to fix it in Babel 7.

**Comment by bvaughn** [comment]
Thanks for clarifying, Dan.

I think [Webpack's use-strict plugin](https://github.com/webpack/webpack/blob/5acbe2f72eaa67654904cf8a127c3ed4da12dc99/lib/UseStrictPlugin.js#L26) [also does this](https://github.com/webpack/webpack/blob/master/lib/FunctionModuleTemplatePlugin.js#L18)? I'm unclear on all of the plugins/transforms that might inject this directive. 😄 

It does seem like it's unnecessary to also be declared in our source either way, although I don't think it hurts anything.

**Comment by gaearon** [comment]
As long as we don't ship it a thousand times in the final bundle. :-)

**Comment by bvaughn** [comment]
I'll just convert this issue to removing the unnecessary directives. 😄
