### ISSUE TITLE
The primary branch has been renamed from "master" to "main"

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#3767]
# Renaming `master` branch to `main`

As a part of a broad effort to avoid problematic terminology in our software, we are renaming our default branch from `master` to `main`. We recognize that this is only a small step, but it is an opportunity to make our project and community more welcoming to historically marginalized communities.

## How does this impact my development process?

There should be very little impact. GitHub will surface the branch name change in your fork, if you have one. For new forks, you will automatically have `main` as the default branch.

We encourage the use of feature branches for local development. The only change in practice is changing which branch your feature branch is started from. When sending Pull Requests on GitHub, the target will default to our `main` branch, so there are no changes to make there.

## I have a lot of tools that depend on `master` being the upstream branch name. How can I fix that?

`master` has always been only a default value and a number of projects have used other names for their primary development branch for years. We encourage updating your tooling to instead dynamically determine the branch to use. [This article](https://aj.codes/post/branch-agnostic-git-aliases/) provides insight into how you can do that. Additionally, you can always set up a branch locally of any name to track our `main` branch.

## I'd like to do this for my own projects, do you have any documentation on how this works?

[GitHub has published a guide documenting their tooling.](https://github.com/github/renaming) We recommend reading that and the accompanying documentation.

If you're a Facebook employee looking to do this for a project you maintain, please reach out to the Open Source Team.

## My PR is failing because of `ci/circleci: get_base_build`
This is because the `master` branch has been renamed to `main`, but our Circle CI scripts used to refer to `master` by name. To fix this, just rebase your branch on top of `main` to get the latest version of the Circle CI scripts:
```sh
git fetch origin
git rebase -i origin/main
```

**Comment by smikitky** [comment]
Unfortunately, d456dfb has replaced URLs of **many** external repositories whose default branch is still "master". For example, README.md has this broken link now:

```
as found in the [LICENSE-DOCS.md](https://github.com/open-source-explorer/reactjs.org/blob/main/LICENSE-DOCS.md) file.
```

...because this external repository is using "master".

**Comment by bvaughn** [comment]
My apologies. I scanned the URLs being replaced in an attempt to filter out any that weren't the React repo, but apparently I missed a couple. I'll update them.
