### ISSUE TITLE
Typo Bug in React docs/react-dom.html#render

### ISSUE THREAD

**Issue by iemprashant** [reactjs/reactjs.org#3785]
![Screenshot (384)_LI](https://user-images.githubusercontent.com/53941491/125154621-7af2f500-e178-11eb-9a7f-cc4a233bddec.jpg)
This Brackets typo can be confusing in understanding the rendering function.

**Comment by harish-sethuraman** [comment]
This is not a bug. We are changing the format on the new site. Thanks 😄 .
