### ISSUE TITLE
Netlify checks are stuck or pending on pt-br translation repo

### ISSUE THREAD

**Issue by cezaraugusto** [reactjs/reactjs.org#3799]
Hello all! I'm one of the maintainers of https://github.com/reactjs/pt-br.reactjs.org/. After some recent upstream changes, Netlify checks stopped working and are kept as pending. It seems all Netlify configs for the website are internal, so I'd like to ask for help on that.

[Here is a pull request I did with all the latest changes from react.org](https://github.com/reactjs/pt-br.reactjs.org/pull/532). Not a fix but has the current latest changes from here and is from where I took the screenshot below. Feedback appreciated. 

<img width="688" alt="Screen Shot 2021-07-17 at 16 22 14" src="https://user-images.githubusercontent.com/4672033/126047467-42cb296b-7ca8-4916-96f0-9861204b611a.png">

**Comment by harish-sethuraman** [comment]
I hope this should not be an issue now. Since we have moved our deployments to vercel. 
Closing this issue :)
