### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by kkanekii** [reactjs/reactjs.org#3803]
Will a nice and comfortable dark mode come to the website? i feel that this would boost consumers to your website too

**Comment by shamwela** [comment]
The upcoming documentation has dark mode. (https://beta.reactjs.org) It will replace the current one.

**Comment by shamwela** [comment]
I think this issue is fixed. @harish-sethuraman

**Comment by fw-aaron** [comment]
Long live dark mode! :tada:
