### ISSUE TITLE
additions in contributing.md

### ISSUE THREAD

**Issue by khareyash05** [reactjs/reactjs.org#3834]
I would like to add following things in contributiong.md
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

**Comment by shamwela** [comment]
I think these are mentioned in https://github.com/reactjs/reactjs.org#contributing

**Comment by shamwela** [comment]
@harish-sethuraman I think we can close this.
