### ISSUE TITLE
useState introduction doesn't mention function arguments

### ISSUE THREAD

**Issue by fdevibe** [reactjs/reactjs.org#3846]
On https://reactjs.org/docs/hooks-state.html, there is no mention that passing a function to `useState()` or `setState()` (or whatever the state setting function is named) will actually result in that function being called and the state set based on that, instead of storing the function as the state. Given that functions are first-class in JavaScript, I believe it would be beneficial to mention this to avoid pitfalls. I realize that the tutorial part intentionally is kept simple, but I have to say I found it rather surprising that
```javascript
const [func, setFunc] = useState(f)
```
doesn't behave the same way as
```javascript
const [func, setFunc] = useReducer((state, newState) => newState, f)
```
when `f` is a function.
I for one would find a brief mention of this, with a reference to https://reactjs.org/docs/hooks-reference.html#lazy-initial-state, along the lines of "passing a function to `useState()` is handled specially, see ..." fairly useful.

**Comment by eps1lon** [comment]
Thanks for the suggestion. 

This was already [brought up during the discussion of the new docs](https://github.com/reactjs/reactjs.org/issues/3308#issuecomment-762823578) and should be adressed in those.
