### ISSUE TITLE
Improvement in Docs

### ISSUE THREAD

**Issue by ishanpan** [reactjs/reactjs.org#3863]
Since the release of hooks we are moving towards more of a functional approach in react. Are there any plans in place to update the react docs to include functional programming aspects aswell?
EG: https://reactjs.org/ -> the front page of react. We have a simple component section which uses OOP heavily

**Comment by eps1lon** [comment]
>  Are there any plans in place to update the react docs to include functional programming aspects aswell?

Yes, see https://github.com/reactjs/reactjs.org/issues/3308
