### ISSUE TITLE
broken link at README.md

### ISSUE THREAD

**Issue by adityadees** [reactjs/reactjs.org#3866]
broken link (This site can’t be reached)
[isreacttranslatedyet.com](https://github.com/reactjs/reactjs.org#translation)

**Comment by amanjaingithub** [comment]
What link supposed to be there? Please reply, i will take this issue
Thank you

**Comment by adityadees** [comment]
> What link supposed to be there? Please reply, i will take this issue
> Thank you

go to https://github.com/reactjs/reactjs.org#translation and click [isreacttranslatedyet](https://www.isreacttranslatedyet.com/ )
and you will be redirected to their site, but the server says  `This site can’t be reached`

**Comment by harish-sethuraman** [comment]
This is currently fixed :)
