### ISSUE TITLE
Whenerver i called set State , static getDerivedStateFormProps is called? 

### ISSUE THREAD

**Issue by Hassan-Gilani** [reactjs/reactjs.org#3874]

**Comment by bk973** [comment]
Hello, Hassan sorry that you're going through this. I would like to see some code so that I can help you with this issue.

**Comment by premsai2030** [comment]
hi @Hassan-Gilani, please provide some code....

**Comment by vuhuucuong** [comment]
That is expected behavior, as in the [doc](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) stated
> `getDerivedStateFromProps` is invoked right before calling the render method, **both** on the **initial mount** and on **subsequent updates**

When you call `setState()`, you update the component, thus causing `getDerivedStateFromProps` to be called again

**Comment by shamwela** [comment]
I think this issue is fixed. @harish-sethuraman
