### ISSUE TITLE
Docs should be rewrite in functional components

### ISSUE THREAD

**Issue by ericdevjs** [reactjs/reactjs.org#3878]
Hi,

Most of the people using React uses functional component, I think for that reason the docs should be rewrite for functional components.

I think it is confusing and misleading for people just staring to learn React to teach them class components like if it was what they should use.

Thank you

Eric

**Comment by eps1lon** [comment]
Thanks for the feedback.

This is already part of https://github.com/reactjs/reactjs.org/issues/3308
