### ISSUE TITLE
Dropdown icon next to 'ADVANCED GUIDES' moves below on clicking 'TESTING' or 'CONTRIBUTING' menus

### ISSUE THREAD

**Issue by camperjett** [reactjs/reactjs.org#3891]
Before:<br><img width="338" alt="before" src="https://user-images.githubusercontent.com/84286404/131947984-860155dc-d385-4699-997e-9dea107ab9cb.png">
After:(clicked TESTING menu)<br>
<img width="301" alt="after" src="https://user-images.githubusercontent.com/84286404/131948041-6da1bafe-d2d0-4e49-8ffc-b71eab5071d7.png">
After:(clicking CONTRIBUTING menu)<br>
<img width="275" alt="after 2" src="https://user-images.githubusercontent.com/84286404/131948088-a89051cb-97d7-4b25-8f0d-11abb7d09a23.png">
<br>
_PS: The borders are highlighted using [Pesticide](https://chrome.google.com/webstore/detail/pesticide-for-chrome-with/neonnmencpneifkhlmhmfhfiklgjmloi) extension for chrome_

**Comment by farheen21** [comment]
This is happening with Installation menu as well..
![Screenshot (37)](https://user-images.githubusercontent.com/60287642/132631057-17819c67-d1bd-4973-8e03-e255ce511680.png)

**Comment by camperjett** [comment]
@farheen21 You may work on this the issue.

**Comment by harish-sethuraman** [comment]
I guess this issue is fixed? It is not reproducible for me 🤔

**Comment by shamwela** [comment]
I think this issue is fixed. @harish-sethuraman
