### ISSUE TITLE
Could you add please to the doc that Context is not a state manager?

### ISSUE THREAD

**Issue by romeerez** [reactjs/reactjs.org#3905]
If you use context for everything this will kill performance, as every component will re-render on any change.

Could you please add to the doc https://reactjs.org/docs/context.html that Context is designed only for the data which changes rarely or never?

> Context is designed to share data that can be considered “global” for a tree of React components, such as the current authenticated user, theme, or preferred language. 

Would be great to have a use case examples when not to use it, like:

Context is not designed for frequently changed data, such as keeping form state, API queries state, UI state apart from theme which is changing rarely.

I think that would help a lot of people to avoid performance problems.

**Comment by filipesmedeiros** [comment]
Can you please add a source to this? I've tried to do some research on this but have never come to a nice conclusion.

Why is it bad for rapidly changing state?

**Comment by romeerez** [comment]
@filipesmedeiros article for example: [why react context is not a state manager](https://blog.isquaredsoftware.com/2021/01/context-redux-differences/). Let me explain in my words: imagine 10 variables in context, change one of them and every consumer of context will re-render. Do the same with any state manager - only consumer of specific variable will re-render.

In most of state managers it is solved with selectors, so component is selecting data to subscribe, mobx tracks used properties by itself, and the Context has no such mechanisms.

**Comment by filipesmedeiros** [comment]
@romeerez Context does have those mechanisms. The pattern is to split your context according to the needs of the consumers. Of course it's always a balance, but at the limit, you could split the context into separate providers until they only have 1 primitive value each.

Also very important for reference: https://youtu.be/_ISAA_Jt9kI?t=354

**Comment by filipesmedeiros** [comment]
I have now read most of the article you linked. Hmm I understand the downfalls, but tbh I'm not convinced. I'd much rather make an effort to keep the app architecture simple enough to use contexts, than to be force into Redux-level complexity. But I may be wrong, of course

**Comment by romeerez** [comment]
@filipesmedeiros thank you for responding, I see it's not that easy to convince. Maybe if we had a benchmark showing that Context works 10 times slower than state managers it would help people to realize the problem. I'll try to that and will post here.

We have `n` variables in Context, and every consumer of this Context will re-render on any change, while in state manager the component will be updated only on specific variable change. In real projects there will be hundreds of state variables. 

> you could split the context into separate providers

Does it mean you are suggesting to create one Context per variable? For 100 variables you'll create 100 contexts?

> than to be force into Redux-level complexity

But why Redux? Here is [Redux FAQ](https://changelog.com/posts/when-and-when-not-to-reach-for-redux), and they are not suggesting to use Redux for everything. Most popular doesn't mean it should be a default.

There are plenty other state managers, like mobx, zustand, recoil and others. The fact it may be hard to choose doesn't mean we have to pick Context which is a wrong tool for a state manager. I see this misconception a lot in React community, so I believe the doc should say it explicitly.

> Redux uses Context internally!

Yes, but Redux uses Context on purpose: as a Dependency Injection tool. So does other state managers and lots of React libraries. So the store instance is provided by Context, but it's never updated with Context itself, so no problems described above.

**Comment by romeerez** [comment]
Here I my resultls for [this benchmark](https://github.com/krausest/js-framework-benchmark)

Okay, Context is just a bit slower than other state managers: redux gives 1.8 and context 2.4, we may call it insignificant, not even 2 times slower than redux.

Still, in my opinion, it is important to understand what happens and why it is slower not that much: because in this benchmark there were **just 2** state variables: rows array and selected number, and **just 3** components: main component, RowList for iterating over the list and Row for each row. So I can expect Context to be 10 times slower when you have more variables and more components, the speed will decrease linearly based on that.

Brief small advertisement: [react-jastaman](https://github.com/romeerez/jastaman) (second column on the screenshot) is my lib which is much easier but still performs faster than redux

![image](https://user-images.githubusercontent.com/42248135/134444581-738c9826-af60-4e43-9a80-bbabcb5e937a.png)

**Comment by filipesmedeiros** [comment]
Nice table man!

> So why to use wrong tool when you'll have to rework it later once it will start to be laggy?

Lazy complexity: don't use/do something until you actually need it. It's like https://stackify.com/premature-optimization-evil/ (of course, again, it's not black and white)

As for the results themselves, I believe they make sense. I'd like to see implementations though, just in case eheh the `selected` state variable could be `memo`ed in some way on the consumer if you're really getting to those limits right?

Of course, like the article said, by then you're just recreating redux, but what I don't like about redux is the DX/API, not the performance of functionality.

I'll check jastaman!
