### ISSUE TITLE
Typo in Quickstart

### ISSUE THREAD

**Issue by azimbaig** [reactjs/reactjs.org#3966]
The word visual either has a typo or misplaced and has a typo.
![Screenshot_20211021-211139](https://user-images.githubusercontent.com/5605421/138377649-8f064081-7da0-43dc-8ea9-6bce3280ba20.png)

**Comment by amankalra4** [comment]
Seems this bug has been fixed,
https://beta.reactjs.org/learn#react-uses-javascript

Can someone confirm on this?
