### ISSUE TITLE
[beta] Google translate breaks Sandboxes by translating their contents

### ISSUE THREAD

**Issue by rachelnabors** [reactjs/reactjs.org#3977]
When I use Google Translate to translate a page, it translates the source code and error messages in the sandboxes. Could we make it so the code in the sandbox and the code in the error messages are _not_ translated?

<img width="1024" alt="Screenshot 2021-10-22 at 15 14 15" src="https://user-images.githubusercontent.com/236306/138469529-a4a550bf-3f4f-492f-b8f8-059dc4e580fe.png">

**Comment by gaearon** [comment]
Should be fixed.
