### ISSUE TITLE
 Document tutorial missing one line of code ?

### ISSUE THREAD

**Issue by webkong** [reactjs/reactjs.org#402]
The `tutorial.md` line 1044-1049

```js{6}
jumpTo(step) {
    this.setState({
      stepNumber: step,
      xIsNext: (step % 2) === 0,
    });
  }
``` 

should add `history : this.state.history.slice(0, step + 1)`

to make Doms rerender the history.

**Comment by bvaughn** [comment]
Jeu Denny. Thanks for the suggestion!

This change would erase part of the history though (so that stepping back would discard all later steps). I don't think that's the intent. 😄  It's meant to be more of a "time travel" feature, where you can step backward and forward.

**Comment by webkong** [comment]
Jeu vaughn . Thank you for your answer!
 I finally know the true intentions about that. 😄 
But I think you change the `stepNumber` that also make the history changed, because the code `const history = this.state.history.slice(0, this.state.stepNumber + 1);` in the handleClick function . 😄

**Comment by bvaughn** [comment]
You're right, you could override history if you stepped back and then clicked a different move. Maybe the tutorial could be updated to disallow that
