### ISSUE TITLE
Links are dead

### ISSUE THREAD

**Issue by xfumihiro** [reactjs/reactjs.org#403]
![screen shot 2017-12-08 at 12 35 53 am](https://user-images.githubusercontent.com/12194969/33726374-cf2f0000-dbaf-11e7-9925-4d2c7b10f4c5.png)

**Comment by gaearon** [comment]
Can you still get this if you shift+refresh the page?

**Comment by gaearon** [comment]
Please also provide more details. It's not obvious which link you clicked, on which page you encountered this,e tc.

**Comment by xfumihiro** [comment]
Ah, shift + refresh works.
Thx!

**Comment by gaearon** [comment]
Awesome. There was a bug but it got fixed a few days ago.
