### ISSUE TITLE
[Beta] Solution to JavaScript in JSX with Curly Braces Challenge #3 wrong solution

### ISSUE THREAD

**Issue by jomarrumbawa** [reactjs/reactjs.org#4053]
Hey React team! Thank you for the new docs. As I was going through I noticed that the solution calls for an undefined object property. In the problem it uses **person.imageSize** and then for solution it says to use **person.pictureSize**

[JavaScript in JSX with Curly Braces Challenge #3](https://beta.reactjs.org/learn/javascript-in-jsx-with-curly-braces)

<img width="847" alt="Screen Shot 2021-11-05 at 9 48 34 PM" src="https://user-images.githubusercontent.com/92612838/140598342-5ea37130-d90c-44ce-9e90-91830a993d04.png">

**Comment by gaearon** [comment]
Fixed in f288a83f2, thanks.
