### ISSUE TITLE
React Conf ticket download don't support Chinese

### ISSUE THREAD

**Issue by masonzz** [reactjs/reactjs.org#4078]
I generated a ticket in https://conf.reactjs.org/, but when I download this ticket, I found the Chinese words in my name is not shown correctly.

<img width="600" alt="react-conf-download-Chinese-is-not-supported" src="https://user-images.githubusercontent.com/9844455/140907353-8ce60764-bb36-427b-a960-e924d8f901f0.png">

I don't know is this the right repo I report this issue(I can not find the related repo of https://conf.reactjs.org/)

**Comment by gaearon** [comment]
Oh no, thanks for reporting. Do you mind pasting the characters?

**Comment by masonzz** [comment]
> Oh no, thanks for reporting. Do you mind pasting the characters?

Do you mean `二吉`?

**Comment by gaearon** [comment]
Yeah just so we test them. Thanks.

**Comment by dev-tom-0108** [comment]
I think it comes from context.

**Comment by dev-tom-0108** [comment]
I think it comes from context.

**Comment by dev-tom-0108** [comment]
I think it comes from context.

**Comment by dev-tom-0108** [comment]
I think it comes from context.
