### ISSUE TITLE
Beta site heading breaks when we have special characters

### ISSUE THREAD

**Issue by harish-sethuraman** [reactjs/reactjs.org#4085]
It seems like the link to Sebastian Markbåge's section doesnt work in @gaearon's section.
URL: https://beta.reactjs.org/community/meet-the-team

@lex111 Trying to understand if it occurred because of https://github.com/reactjs/reactjs.org/pull/4043 ? 

How it looks:
<img width="582" alt="Screenshot 2021-11-11 at 10 31 28 AM" src="https://user-images.githubusercontent.com/32865581/141240242-0ccd83ba-2b0b-49bd-9187-d637a7b083e9.png">

**Comment by lex111** [comment]
Thanks for reporting this, it will be fixed in PR #4086.
