### ISSUE TITLE
Docs beta: useRef Stopwatch doesn't stop if you click start twice

### ISSUE THREAD

**Issue by Aidurber** [reactjs/reactjs.org#4096]
I was just browsing the beta docs and playing around with the examples, I came across the useRef stop watch and spotted a bug. 

**Steps**
1. Go view the stop watch: https://beta.reactjs.org/learn/referencing-values-with-refs#example-building-a-stopwatch
2. Click start twice
3. Click stop
4. It doesn't stop

**Comment by dev-tom-0108** [comment]
Thanks so much

**Comment by Aidurber** [comment]
This seems to have been fixed by #4110 closing.
