### ISSUE TITLE
Great content

### ISSUE THREAD

**Issue by yashone7** [reactjs/reactjs.org#4099]
The new new documentation looks great and its emphasis on functional components is the need of the hour, however, It would also be good if examples included for class based components perhaps in a separate section to give learners an option to look at how the library has evolved. The comparison of the lifecycle methods in the class based components and functional components can give an idea on how the concepts have evolved. Now that most of them follow hooks first approach, it may be redundant to include class based components in the new docs, personally I would love to see them for learning point of view and for interview purpose ; )

**Comment by dev-tom-0108** [comment]
Thanks so much. I will try

**Comment by harish-sethuraman** [comment]
The older documentation with the class components will continue to exist even after the complete release of the beta site :) So one can refer between class components and their lifecycle methods as well as the functional component's methods.

**Comment by shamwela** [comment]
I think we can close this now. @harish-sethuraman

**Comment by gaearon** [comment]
I think we'll also have a reference page that documents class components on the new site. As long as they're in the stable API, they should be in the stable documentation.
