### ISSUE TITLE
[Beta] Heading overflows in mobile view

### ISSUE THREAD

**Issue by harish-sethuraman** [reactjs/reactjs.org#4113]
## Problem:
When I use beta.reactjs.org site in my phone (Iphone 12 mini). There is a small breakage in UI in the https://beta.reactjs.org/community/acknowledgements page.

When the heading of the document is small there is no overflow
In normal page:   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In Acknowledgements page
<p>

<img width="325" alt="Screenshot 2021-11-18 at 9 25 20 PM" src="https://user-images.githubusercontent.com/32865581/142453257-86eecf31-0e46-4bce-9573-db68949402b2.png">
<img width="321" alt="Screenshot 2021-11-18 at 9 25 35 PM" src="https://user-images.githubusercontent.com/32865581/142453253-bb727402-cc2f-478d-8afd-90b3fa2e9894.png">
</p>
But when we see for larger heading like Acknowledgements the word introduces a new scroll in the x-axis.

## Solution
Should we consider reducing the heading size a bit for mobile? 
Or shall we break the word and add hypens via CSS? 
Or is there any other suggested way?

**Comment by gaearon** [comment]
Break word seems fine in this case

**Comment by harish-sethuraman** [comment]
Is this fine ? 
Added `word-break: break-all;` and this is the outcome. Is this okay 

<img width="323" alt="Screenshot 2021-11-18 at 11 21 59 PM" src="https://user-images.githubusercontent.com/32865581/142469817-ef2cd615-02e7-4b6b-939a-9e0b02c5d301.png">
