### ISSUE TITLE
Tutorial render recreates the button each time

### ISSUE THREAD

**Issue by yecril71pl** [reactjs/reactjs.org#4124]
Could you modify the [tutorial](content/tutorial/tutorial.md) to create each button object only once and only replace its _content_ upon press?  Or, if that is not a good idea, could you at least say why?  I feel confused and have a WTF feeling while reading this.

**Comment by gaearon** [comment]
This is not how React works. In React, the JSX you return is a lightweight description of the tree, so no DOM elements are actually being "recreated".

The beta version of the new docs has a deeper dive on this: https://beta.reactjs.org/learn/preserving-and-resetting-state. Let me know if this helps!

**Comment by yecril71pl** [comment]
I was told that React has a shadow DOM and from what I can see, the shadow button is being recreated by `render`.  I did not mean that the HTML button is being recreated.  Similarly, in another place, you say that a lambda function is being recreated for the handler and that this is suboptimal.

**Comment by gaearon** [comment]
Sorry, I don't know what you're asking. The whole point of React is to be able to write code that just describes the UI _now_ and not think about _how_ to update it. What you're describing is imperative UI programming, and it's indeed how it works ... without React. If you prefer the imperative approach, I suggest to not use React at all, and use DOM APIs directly.

See also this page from new (beta) docs: https://beta.reactjs.org/learn/reacting-to-input-with-state

**Comment by yecril71pl** [comment]
I understand from what you said that React controls may be constructed and assigned to variables but modifying their properties, even if technically possible, is not supported.  I must have missed this information in the initial exposition.
