### ISSUE TITLE
MarkDown Comments appear as texts in the site

### ISSUE THREAD

**Issue by harish-sethuraman** [reactjs/reactjs.org#4125]
In the following page https://beta.reactjs.org/community seems like the content broke. 
<img width="917" alt="Screenshot 2021-11-26 at 10 13 37 AM" src="https://user-images.githubusercontent.com/32865581/143527949-cc552cb2-bf6f-47af-a3f3-aab93f98d857.png">

How? 
Seems like the heading id inside of the comment causes this.

https://github.com/reactjs/reactjs.org/blob/0057efa12c1aa2271ef80d7a84d622732bdfa85c/beta/src/pages/community/index.md?plain=1#L23

Tried removing the heading id and seems like it fixed the issue. I also tried commenting that line separately as well (It also breaks).

Shall I remove the ID `{/*popular-discussion-forums*/}` for now? 
But if I do so we might actually run the generate-ids in the pre commit and that will add the Id again. 

Or shall I change it as normal text so that we don't generate ID for it? 

cc: @wooorm

**Comment by wooorm** [comment]
maybe it works if you for now turn `## Popular Discussion Forums {/*popular-discussion-forums*/}` -> `Popular Discussion Forums` as a quick workaround?

**Comment by harish-sethuraman** [comment]
Yep will change it into normal text instead of heading for now. Thanks.
