### ISSUE TITLE
Spelling mistake in the page

### ISSUE THREAD

**Issue by NikhilAndola** [reactjs/reactjs.org#4130]
Correct the spelling of skim = skip in the ( A Brief Interlude: Props vs State ) paragraph on page Thinking in React.
Thank you,
Nikhil

**Comment by NikhilAndola** [comment]
Change it ASAP.

**Comment by harish-sethuraman** [comment]
There are no spelling mistake in skim. It actually is a valid word and means `The action of reading something quickly so as to note only the important points`.

Closing this issue.
