### ISSUE TITLE
[Beta] Markup problem in the "Converting HTML to JSX" section

### ISSUE THREAD

**Issue by thanosades** [reactjs/reactjs.org#4131]
I was going through the [Writing markup with JSX](https://beta.reactjs.org/learn/writing-markup-with-jsx#converting-html-to-jsx) section and noticed an example that's missing multiple ending` </li>` tags.

Given that the line above the following example states that "Suppose that you have some (perfectly valid) HTML:" I'm proposing that
```
<h1>Hedy Lamarr's Todos</h1>
<img 
  src="https://i.imgur.com/yXOvdOSs.jpg" 
  alt="Hedy Lamarr" 
  class="photo"
>
<ul>
    <li>Invent new traffic lights
    <li>Rehearse a movie scene
    <li>Improve the spectrum technology
</ul>
```

Should be changed into
```
<h1>Hedy Lamarr's Todos</h1>
<img 
  src="https://i.imgur.com/yXOvdOSs.jpg" 
  alt="Hedy Lamarr" 
  class="photo"
>
<ul>
    <li>Invent new traffic lights</li>
    <li>Rehearse a movie scene</li>
    <li>Improve the spectrum technology</li>
</ul>
```

**Comment by gaearon** [comment]
It is valid HTML to leave out some closing tags, including `</li>`.
https://css-tricks.com/some-html-is-optional/
