### ISSUE TITLE
Feature request: API reference

### ISSUE THREAD

**Issue by mwisnicki** [reactjs/reactjs.org#4145]
Can React project publish actual API reference that is organized by function/class (like jsdoc) rather than flat tutorial pages as it is right now. Also rename current "API Reference" to "tutorial".

I find that looking up information about specific items is very hard due to lack of structure and also I rarely find the answers I seek (the documentation is not very exhaustive). Most of the time I have to resort to use Google and even then I sometimes fail (e.g. #4144).

**Comment by mwisnicki** [comment]
Or at least just improve the layout of the pages to have more structure. Perhaps the navigation tree on the left could expand to include every documented element as children and highlight the current one.

I'm talking about pages such as:
- https://reactjs.org/docs/react-api.html
- https://reactjs.org/docs/hooks-reference.html

**Comment by dev-tom-0108** [comment]
Thanks so much

**Comment by matheusanmo** [comment]
+1. 
The docs are hard to navigate as a newcomer to React trying to go below the surface. For instance: having the API Reference point you _back_ to the Main Concepts is not fun. Ironically, the Main Concepts and Advanced Guides do not link to the API Reference.
Also many examples still use **class** components + magic methods (`render`, `constructor`, `setState` etc), which I've been told are obsolete. Looking around for documentation and examples for **function** components + hooks specifically is painful.
Having the section on Hooks totally separated from the rest of the docs felt somewhat misleading too. There is not even a page on Hooks under Advanced Guides. 
The guides themselves feel helpful and well written, but the contents and structure of the Docs page need attention.

**Comment by mwisnicki** [comment]
Yes, it seems it is going in the direction I've asked for.

**Comment by harish-sethuraman** [comment]
I'll close this issue since we are currently adding API references. Feel free to leave any suggestions regarding the new docs in https://github.com/reactjs/reactjs.org/issues/3308
