### ISSUE TITLE
create a new react app exception raised by following destructions at https://reactjs.org/docs/create-a-new-react-app.html

### ISSUE THREAD

**Issue by Bazmundi** [reactjs/reactjs.org#4147]
Running Node.js v17.2.0, npm/npx comes up as 8.2.0.  Attempting to setup react app with destructions at: https://reactjs.org/docs/create-a-new-react-app.html  

Under the heading "Create React App".   

```
npx create-react-app my-app
cd my-app
npm start
```

Running in Windoze(aka Windows) 10.  Fresh first-time install of create-react-app function itself (so that process also pulled in react 17.0.2).  The result when I try running the freshly created app is an exception!  So I understand what the exception is trying to tell me but why is setting up all dependencies and their paths not covered by the react app setup?     This is just the npx create-react-app version of "hello world" right?   So should it not pull everything in it needs and set everything up?      

Full insult at: https://pastebin.com/czGkpX1K.   Not to mention the apparently contradictory information at the end of the app creation https://pastebin.com/m9mr2EYP, and yes the same error is raised by darn yarn start as dang blasted npm start.😆 

So, currently it appears the instructions may work for Node >= 14.0.0   <17.2.0 and npm >= 5.6 <8.2.0.

So, currently it appears the instructions should illuminate on `yarn start` option to remove confusion.

**Comment by dev-tom-0108** [comment]
Thanks

**Comment by rhgolakiya** [comment]
`rm -rf node_modules package-lock.json
`
Try this once time after again install all node modules and start your app. I also got the same error and Using the above my app worked properly.

**Comment by gaearon** [comment]
We can’t help without a reproducing case unfortunately.
