### ISSUE TITLE
Callback after setState.

### ISSUE THREAD

**Issue by elvn5** [reactjs/reactjs.org#4148]
Now I use functional components in my react projects, but previos on class based components I can pass second arg to setState - a callback that will be called after render. How can I implement the same behavior on functional based component?

**Comment by dev-tom-0108** [comment]
Thanks so much

**Comment by arghyab0** [comment]
I believe the functionality that you're looking for can be achieved using the `useEffect` hook.

Here's an example:

```jsx
const [state, setState] = useState({ name: "Michael" });

const isFirstRender = useRef(true);

useEffect(() => {
  if (isFirstRender.current) {
    isFirstRender.current = false; //toggle flag after first render/mounting
    return;
  }
  doSomethingAfterStateUpdate(); //callback that will be called after every state change
}, [state])
```

### Custom hook -
 
Alternatively, you can use this custom hook from [here](https://github.com/the-road-to-learn-react/use-state-with-callback#usage).

```jsx
import { useStateWithCallbackLazy } from 'use-state-with-callback';

const [count, setCount] = useStateWithCallbackLazy(0);

setCount(count + 1, () => {
   afterSetCountFinished(); //callback that will be called after every state change
});
```

**Comment by elvn5** [comment]
> I believe the functionality that you're looking for can be achieved using the `useEffect` hook.
> 
> Here's an example:
> 
> ```js
> const [state, setState] = useState({ name: "Michael" });
> 
> const isFirstRender = useRef(true);
> 
> useEffect(() => {
>   if (isFirstRender.current) {
>     isFirstRender.current = false; //toggle flag after first render/mounting
>     return;
>   }
>   doSomethingAfterStateUpdate(); //callback that will be called after every state change
> }, [state])
> ```
> 
> ### Custom hook -
> Alternatively, you can use this custom hook from [here](https://github.com/the-road-to-learn-react/use-state-with-callback#usage).
> 
> ```js
> import { useStateWithCallbackLazy } from 'use-state-with-callback';
> 
> const [count, setCount] = useStateWithCallbackLazy(0);
> 
> setCount(count + 1, () => {
>    afterSetCountFinished(); //callback that will be called after every state change
> });
> ```

Thanks a lot, I used to use this solution, but always want to use native support of lazy render.
