### ISSUE TITLE
Weird state binding bug

### ISSUE THREAD

**Issue by Crunchyman-ralph** [reactjs/reactjs.org#4152]
Hey guys, this is my first issue so please let me know if I am missing something.

So I am using functional components and using `useState` and `SWR` together. 
I use a useEffect hook to watch for changes in `dataOfFunnel` and when there is a change, I set the state as the new data fetched.
but the problem is that when I change the state, `dataOfFunnel` is also affected as if they were bonded together.

here is a snippet of my code:
````js
const {
        data: dataOfFunnel,
        dataLoading: initialFunnelLoading,
        isValidating: isInitialFunnelValidating
    } = getFromBackend<Funnel>(sharedConstants.routeToGetFunnelWithID, { funnelID: funnelId });
const [triggerSystem, setTriggerSystem] = useStateAsReducer<TriggerSystem>(null);

useEffect(() => {
                setTriggerSystem((previousTriggerSystem) => {
                    return { ...dataOfFunnel.result.triggerSystem}
                });
    }, [dataOfFunnel]);
````

**Comment by Crunchyman-ralph** [comment]
Seems like I found an answer to my question.

Doing this seemed to fix my issue:
````js
setTriggerSystem(JSON.parse(JSON.stringify(dataOfFunnel.result.triggerSystem)))
````

but I would have loved this to be enough:
````js
setTriggerSystem({...dataOfFunnel.result.triggerSystem}) 
````

**Comment by dev-tom-0108** [comment]
Thanks so much

**Comment by Crunchyman-ralph** [comment]
> Thanks so much

were you also having this issue?

**Comment by shamwela** [comment]
This repository is for the React's website (https://reactjs.org). For React issues, please go to https://github.com/facebook/react/issues

**Comment by shamwela** [comment]
@gaearon I think we can close this issue now.
