### ISSUE TITLE
Explanation: Get previous state

### ISSUE THREAD

**Issue by alexalannunes** [reactjs/reactjs.org#4153]
Hello.
I'm reading the React Documentation and there is a topic that I didn't understand very well
https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state

```javascript
function Counter() {
  const [count, setCount] = useState(0);

  const prevCountRef = useRef();
  useEffect(() => {
    prevCountRef.current = count;
  });
  const prevCount = prevCountRef.current;

  return <h1>Now: {count}, before: {prevCount}</h1>;
}
```
Demo:

https://codesandbox.io/s/get-previous-state-ref--hook-faq-w0f3k?file=/src/App.js

I'd like a better explanation about this. Kind, how it's works?. Thanks

**Comment by SalmaQueen** [comment]
I will catch you up tonight please... text me on whatsapp. thank you

**Comment by alexalannunes** [comment]
I already have the answer
https://stackoverflow.com/questions/70268060/explanation-get-previous-state
