### ISSUE TITLE
Documentation needs to be rewritten to be Hooks-first

### ISSUE THREAD

**Issue by michaeltrollan** [reactjs/reactjs.org#4158]
The majority of people are using hooks when writing react. But the documentation still has hooks as a separate add-on. 

Ideally, the documentation would be rewritten to be hooks first.

**Comment by harish-sethuraman** [comment]
Have you visited https://beta.reactjs.org/?
It is being re-written with hooks and is a work in progress.

**Comment by SalmaQueen** [comment]
yeah and am really so in love with the upcoming documentation for react
https://beta.reactjs.org/ .. I can't wait for it. :)

**Comment by michaeltrollan** [comment]
Ooh that's perfect! Can't wait for that to be finished.
