### ISSUE TITLE
Docs of setState hook showcase usage that might lead to bugs

### ISSUE THREAD

**Issue by kriim** [reactjs/reactjs.org#4170]
URL: https://reactjs.org/docs/hooks-state.html

Example from the docs:
```
import React, { useState } from 'react';

function Example() {
  // Declare a new state variable, which we'll call "count"  const [count, setCount] = useState(0);
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

When toggling values or incrementing counters, I think people should be encouraged to use the `setState` variant that takes an function as argument.

So here:
```
setCount((prevCount) => prevCount + 1)
```

We just ran into a bug caused by this today. And having this as the first bit of documentation might to lead to more bugs like this as people might assume it's safe to use `setState` like this.

I get that the functional argument might be too advanced for the initial docs of `setState`, but maybe then the counter might not be the best example to use.

Update:
Or linking to here might help? https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

**Comment by shamwela** [comment]
This is explained in the new documentation. (https://beta.reactjs.org/apis/usestate#updating-state-based-on-the-previous-state)
![image](https://user-images.githubusercontent.com/62544170/154528890-53f4e96b-f550-4f18-a086-10959c1e0035.png)

The new documentation will replace the current one soon.

**Comment by kriim** [comment]
nice, thanks for the update

**Comment by shamwela** [comment]
Happy to help. 👋
