### ISSUE TITLE
Chapter 2 overview: Adding interactivity, Index may be out of bounds of array

### ISSUE THREAD

**Issue by DaYePython** [reactjs/reactjs.org#4177]
🐛 In the "Chapter 2 overview: Adding interactivity", If you press "next"13 times, the index is out of bounds of "sculptureList".

**Comment by harish-sethuraman** [comment]
We had a [PR](https://github.com/reactjs/reactjs.org/pull/4122) addressing this. 


https://github.com/reactjs/reactjs.org/pull/4122#issuecomment-979090483
