### ISSUE TITLE
Error on node 16.13.1

### ISSUE THREAD

**Issue by m6code** [reactjs/reactjs.org#4180]
I got this error after running yarn (v1.22.17) on a Windows with node v16.13.1 installed.

error react-website@0.0.1: The engine "node" is incompatible with this module. Expected version "12.x.x || 14.x.x || 15.x.x". Got "16.13.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by harish-sethuraman** [comment]
Can you try with any of these node versions?  `"12.x.x || 14.x.x || 15.x.x"`

**Comment by m6code** [comment]
Thank you. I found a fix for it - I added 16.x.x to the package.json file 
`"engines": {`
    `"node": "12.x.x || 14.x.x || 15.x.x || 16.x.x",`
    `"yarn": "^1.3.2"`
  `},`
