### ISSUE TITLE
ERROR in Plugin "react" was conflicted between "package.json » eslint-config-react-app » C:\Users\asus\desktop\google-clone\node_modules\eslint-config-react-app\base.js" and "BaseConfig » C:\Users\asus\Desktop\google-clone\node_modules\eslint-config-react-app\base.js".

### ISSUE THREAD

**Issue by Shobit1502** [reactjs/reactjs.org#4186]
Recently get this error. plz let me know how to fix this.

**Comment by HusseinHamidani** [comment]
There is a conflict in the casing

C:\Users\Ruben|desktop\reactapp\test.... whereas the nodemodules is looking for C:\Users\Ruben|Desktop\Reactapp\test....

This is a windows specific problem, and previously react would have run the app regardless of this difference. Not anymore it seems.

The solution I used was to locate the folder and open with code; that ensures that the path matches directly with what is stored in node modules

**Comment by SouzaWesley** [comment]
Open the package.json and type `ctrl + save` and it disappears.

**Comment by pnrede366** [comment]
> Open the package.json and type `ctrl + s` and it disappears.

thanks

**Comment by Adecodess** [comment]
hi all i am having this error in production , locally when I press ctrtl + s, it disappears but when I refresh the page it comes back

**Comment by NickersWeb** [comment]
Have the same issue...

**Comment by harish-sethuraman** [comment]
Can you file an issue in this repo https://github.com/facebook/create-react-app linking this issue ?

This problem likely seems to be with create react app.


This repo is for documentation site of react.

**Comment by shreyash510** [comment]
delete package.json and install again

**Comment by Kenramiscal1106** [comment]
> Recently get this error. plz let me know how to fix this.

Are you using bash? Because bash doesn't care about the letter case of the path. This can be fixed by changing the path of your project in bash

`cd `
`cd [project path]`

**Comment by tekeoglan** [comment]
> > Recently get this error. plz let me know how to fix this.
> 
> Are you using bash? Because bash doesn't care about the letter case of the path. This can be fixed by changing the path of your project in bash. **You must reference** the exact case of the path of your project
> 
> Example: Documents is not equal to documents Documents must be also Documents
> 
> `cd ` `cd [project path]`

You are right. I had the same issue when executing 'npm start' command on bash then i switched back to cmd the error has gone. Thank for your point.

**Comment by calmb** [comment]
> hi all i am having this error in production , locally when I press ctrtl + s, it disappears but when I refresh the page it comes back

same here.

**Comment by kdany25** [comment]
i have same issue. i do ctr+s but when i refresh it comes back

**Comment by johannes67890** [comment]
I had some trouble with this as well. What I did to fix it was to upgrade nodejs to V.16. I found the bug while on V.15.
I don't know if that is the core solution, but that is how I fixed it.

**Comment by SATYAM1548** [comment]
johannes67890 bro this worked thanks alot.

**Comment by igortas** [comment]
> I had some trouble with this as well. What I did to fix it was to upgrade nodejs to V.16. I found the bug while on V.15. I don't know if that is the best solution, but that is how I fixed it.

I'm on 16.x version... I've killed my app with setting monorepo and manually installed react-scripts and then problem started... react-scripts start command also starts the tests...

**Comment by enderandpeter** [comment]
Ran into this problem today and it turned out that the `esLintConfig` setting I had for `extends: [react-app]` was conflicting with the settings from the `eslint-config-react-app` package. Removing the `esLintConfig` resolved the issue.

**Comment by igortas** [comment]
> Ran into this problem today and it turned out that the `esLintConfig` setting I had for `extends: [react-app]` was conflicting with the settings from the `eslint-config-react-app` package. Removing the `esLintConfig` resolved the issue.

try to update setupTests.ts with this import statement: import @types/jest. I've tried this also on monorepo w/ Lerna with --hoist option turned and it works for me

**Comment by briandgomez** [comment]
I got the same issue. You can try using:
C:\Users\asus\Desktop\google-clone\node_modules\eslint-config-react-app\base.js 
instead of 
C:\Users\asus\desktop\google-clone\node_modules\eslint-config-react-app\base.js 
That's what worked for me using git bash on my windows computer

**Comment by kdany25** [comment]
hello me all i did was to update the babel-eslint  and u also updated .eslintrc and it worked for me

**Comment by igortas** [comment]
Also other solution is to set skip flag before star script: `DISABLE_ESLINT_PLUGIN=true`, in case u have custom .eslintrc file

**Comment by karthikuppalapati** [comment]
I too had the same issue. I am using Visual Studio Code. 

 E:\React-Projects\playground\test-7>.  Here test-7 is my project folder created using create-react-app. The folder playground actually starts with a capital p instead of small p in my laptop. I changed playground to Playground it worked!!!

E:\React-Projects\Playground\test-7> This the changed version of my folder name

**Comment by ceyhun-yildiz** [comment]
I am using Bash and I have changed desktop to Desktop on my path and it works without the error now

**Comment by ShawnNJH** [comment]
inside your package.json, delete the following

"eslintConfig": {
"extends": [
"react-app",
"react-app/jest"
]
},

**Comment by Kenramiscal1106** [comment]
Still didn't work

**Comment by samyarkd** [comment]
> instead of "saving" your package.son everytime you make an update, go to your package.json and delete the following
> 
> "eslintConfig": { "extends": [ "react-app", "react-app/jest" ] },
> 
> Cheers! :)

workerd for me

**Comment by d1joseph** [comment]
For those looking for the open issue - https://github.com/facebook/create-react-app/issues/11825

**Comment by SuzieZUMO** [comment]
Recreate your projects in lower case. Solution name case doesn't matter. 
Renaming project names won't help (perhaps renaming folder names to lower case would, I didn't try).

**Comment by EddisonM** [comment]
This is the solution:

Use the correct App path location.

For example if u are in C:\users\cyber\documents\juego_gabriel> and run "npm start", u get the next error:
![image](https://user-images.githubusercontent.com/98683128/151690648-1678a56b-823e-46cf-be9a-069b7d7ca481.png)

To fix it follow these steps:
1. Locate your project folder location
![image](https://user-images.githubusercontent.com/98683128/151690767-4766f499-3589-40f0-8862-9e1b405d756a.png)
2. Copy that path and paste in your VS Code PS Terminal (run "cd [path]")
![image](https://user-images.githubusercontent.com/98683128/151690805-40f4e2e3-24c4-4e5b-9044-6ba1152f1943.png)
3. Run "npm start"

Done...!!!

**Comment by tiagocorreiia** [comment]
The problem is Windows PowerShell.
I don't recommend Windows PowerShell.
Make a download the last version of Powershell from Microsoft Store and will works fine

![2022-02-01](https://user-images.githubusercontent.com/7349208/152041643-4bed2845-fafb-4461-95ac-f5ca19b23558.png)
.

**Comment by Nacer-MEDIOUNI** [comment]
Try to uninstall your current node.js and reinstall it. It worked for me!

**Comment by kukovisuals** [comment]
Open PowerShell as Administrator

**Comment by wevertonbezzera013** [comment]
> Open the package.json and type `ctrl + s` and it disappears.

GOD

**Comment by prettygenius** [comment]
I got the same error  apparently I was using the wrong path Desktop was capitalized so use cd Desktop NOT cd desktop I re ran npm start and  it worked for me! Thanks guys

**Comment by ninzacoder** [comment]
> There is a conflict in the casing
> 
> C:\Users\Ruben|desktop\reactapp\test.... whereas the nodemodules is looking for C:\Users\Ruben|Desktop\Reactapp\test....
> 
> This is a windows specific problem, and previously react would have run the app regardless of this difference. Not anymore it seems.
> 
> The solution I used was to locate the folder and open with code; that ensures that the path matches directly with what is stored in node modules

saved me a lot of hair you did.

**Comment by NarayanBavisetti** [comment]
It is just because of the capital letter used in the location of the file path. That's it. check it and make all the folder name to lowercase.

**Comment by phoique** [comment]
I get this error when I update my packages on my Macbook. With ctrl s the error went away but was coming back. It was fixed when I deleted node_modules and yarn.lock and created it again with yarn install.

**Comment by OldTechnique** [comment]
Issues is simple. exit terminal cd the correct path. when u cd'd u cd'd with the wrong case.

**Comment by yaowang908** [comment]
I'm putting in my two cents, for me, the problem is a space in the path, remove the space, everything works.

**Comment by bkincz** [comment]
I stumbled across this issue when using a custom .eslintrc with a fresh CRA (react-scripts v5.0.0) project.

I resolved this by removing `"root": true` from my .eslintrc.

This is my .eslintrc at the moment while using CRA (react-scripts v5.0.0):
```
{
    "env": {
        "browser": true,
        "es2021": true,
        "jest": true
    },
    "extends": [
        "plugin:react/recommended",
        "plugin:react/jsx-runtime",
        "plugin:prettier/recommended",
        "standard"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": ["react", "@typescript-eslint"],
    "settings": {
        "react": {
            "version": "detect"
        }
    },
    "globals": {
        "React": true,
        "google": true,
        "mount": true,
        "mountWithRouter": true,
        "shallow": true,
        "shallowWithRouter": true,
        "context": true,
        "expect": true,
        "jsdom": true,
        "JSX": true
    },
    "rules": {
        /* Rules go here */
    },
    "overrides": [
        {
            "files": ["*.ts", "*.tsx"],
            "parserOptions": {
                "ecmaVersion": 12,
                "project": ["./tsconfig.json"]
            }
        }
    ]
}
```

Hopefully this helps.

**Comment by Code-with-Fizza** [comment]
> Still didn't work

**Comment by Code-with-Fizza** [comment]
> Remove the following code from package.json ...it worked for me

"eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },

**Comment by dendoink** [comment]
> Open the package.json and type `ctrl + s` and it disappears.

Great thanks !

**Comment by Blind2k** [comment]
Saving the files over and over again is not a solution.
In my case, the application's local source directory had capital letters.
Changed to lower case, and it works smoothly.

**Comment by gaearon** [comment]
This repository is for the React website. There is no relation between the topic you are discussing and the React website. If you have an issue with some plugin, please file it in the repo with that plugin. Thanks!
