### ISSUE TITLE
Meta or Facebook Open Source?

### ISSUE THREAD

**Issue by bharadwajduggaraju** [reactjs/reactjs.org#4194]
![image](https://user-images.githubusercontent.com/69485164/146871985-767d6aec-84bd-41c8-ba1b-273879adb9d1.png)
 
Similar to this issue: https://github.com/facebook/react-native-website/issues/2893, because Facebook open source is now meta open source, is this logo still valid? Or should it be changed to match the new logos on the meta open-source website? This applies to https://reactjs.org if you scroll to the bottom. If this is invalid, feel free to close this issue, I just wanted to bring it up.

**Comment by bharadwajduggaraju** [comment]
Oh, and I just realized that the copyright was updated. So, my only wondering is about the image.

**Comment by mr-vaibh** [comment]
can you assign it to me?

**Comment by gaearon** [comment]
There is no need to do anything. The new site doesn't have the logo anyway.
