### ISSUE TITLE
Working on React Core contribution

### ISSUE THREAD

**Issue by vitaliemiron** [reactjs/reactjs.org#4206]
All your files have a .js extension, and you use typescript syntax. 

Could you explain how you are working ?

Do you have a particular configuration for your IDE ?

Why is it organized in this way ?

**Comment by harish-sethuraman** [comment]
React repo uses flow for type checking. You can read more about flow here https://reactjs.org/docs/static-type-checking.html#flow  and here https://flow.org/en/docs/react/

**Comment by harish-sethuraman** [comment]
Closing this issue :)
