### ISSUE TITLE
Imported object written in pascal case

### ISSUE THREAD

**Issue by haydaralrikabi** [reactjs/reactjs.org#4211]
In the following document: https://reactjs.org/docs/test-renderer.html
Why the following import was written in pascal case?
```import TestRenderer from 'react-test-renderer'; // ES6```

**TestRenderer** is supposed to be a pure JS function (or is it not), and it can be written in camel case or in small letters.

Is it a React convention or what?

**Comment by ansh-ag** [comment]
TestRenderer is not a function, its a wrapper, that has a bunch of method that one can access. So it should be Pascal I think. See - https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-test-renderer/src/ReactTestRenderer.js

**Comment by ansh-ag** [comment]
> In the following document: https://reactjs.org/docs/test-renderer.html Why the following import was written in pascal case? `import TestRenderer from 'react-test-renderer'; // ES6`
> 
> **TestRenderer** is supposed to be a pure JS function (or is it not), and it can be written in camel case or in small letters.
> 
> Is it a React convention or what?
TestRenderer is not a function, its a wrapper, that has a bunch of method that one can access. So it should be Pascal I think. See - https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-test-renderer/src/ReactTestRenderer.js

**Comment by ansh-ag** [comment]
> In the following document: https://reactjs.org/docs/test-renderer.html Why the following import was written in pascal case? `import TestRenderer from 'react-test-renderer'; // ES6`
> 
> **TestRenderer** is supposed to be a pure JS function (or is it not), and it can be written in camel case or in small letters.
> 
> Is it a React convention or what?

TestRenderer is not a function, its a wrapper, that has a bunch of method that one can access. So it should be Pascal I think. See - https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-test-renderer/src/ReactTestRenderer.js

**Comment by haydaralrikabi** [comment]
Sorry, it was a typo on my part.
I meant that **TestRenderer** is supposed to be a pure JS "object" (not a function).
I checked it out through:
```console.log(TestRenderer.constructor.name) // Object```
That made me think, why an object is written in Pascal case.

**Comment by haydaralrikabi** [comment]
For reference, it is a naming convention in JavaScript that explains why **TestRenderer** is imported using PascalCase.

According to "[Airbnb Javascript Style Guide](https://github.com/airbnb/javascript#naming--PascalCase-singleton)":

> Use PascalCase when you export a constructor / class / singleton / function library / bare object.

**Comment by harish-sethuraman** [comment]
Thanks for catching up and clarifying :)
