### ISSUE TITLE
The sandcodebox in section wrapping-setstate-in-a-transition cannot work properly.

### ISSUE THREAD

**Issue by daweilv** [reactjs/reactjs.org#4231]
[The sandcodebox](https://codesandbox.io/s/musing-driscoll-6nkie) in section [wrapping-setstate-in-a-transition](https://reactjs.org/docs/concurrent-mode-patterns.html#wrapping-setstate-in-a-transition) cannot work properly.

![image](https://user-images.githubusercontent.com/7405300/150630539-c7349372-5e3d-4988-9d75-d9032e46d797.png)

**Comment by gaearon** [comment]
Like noted at the top of the page, it's outdated anyway. We'll likely be deleting these pages soon in favor of a more up-to-date reference.

**Comment by daweilv** [comment]
> Like noted at the top of the page, it's outdated anyway. We'll likely be deleting these pages soon in favor of a more up-to-date reference.

got it. close the issue
