### ISSUE TITLE
Certificate problem on reactjs.org

### ISSUE THREAD

**Issue by keggum** [reactjs/reactjs.org#4241]
There is a problem with the certificate configuration on reactjs.org documentation site. Error in Chrome says "ERR_SSL_VERSION_OR_CIPHER_MISMATCH", see screen shot below. The same error is present on the new beta-site. 

Due to the security policy setup on our corporate computers this problem results in reactjs.org being blocked, and our development team not being able to access the React documentation while coding, which of course is quite annoying. 
Hopefully there is an easy fix for this problem on your end!

![image](https://user-images.githubusercontent.com/98458651/151147560-b285761b-9534-47a5-9a3d-8e6b429de5ac.png)

**Comment by PhilipSada** [comment]
Just testing graphql api

**Comment by habarahonaa** [comment]
Hello! This doesn't seem to be a problem on the documentation server. Instead an antivirus policy or outdated web browser could cause this error. The server supports the latest TLS version and the certificate is valid :) Greetings!

**Comment by gaearon** [comment]
I was not able to reproduce this either.

**Comment by habarahonaa** [comment]
Yep! It seems it is an issue on their side

**Comment by keggum** [comment]
Thank you for checking!
I can't see how it would be an antivirus or web browser issue on our end. But we were able to add an exception for your site to our security policy, so we have access again now anyways :)
