### ISSUE TITLE
redirect-to-codepen Redirects to Empty Codepen

### ISSUE THREAD

**Issue by Labnann** [reactjs/reactjs.org#4243]
Codepen gives an empty pen instead of one with codes when getting redirected from  /redirect-to-codepen

Tested links are found in these pages: 
[Rendering Elements](https://reactjs.org/docs/rendering-elements.html)
[Introducing JSX](https://reactjs.org/docs/introducing-jsx.html)
[Hello World](https://reactjs.org/docs/hello-world.html)

Examples of some not working links:

https://reactjs.org/redirect-to-codepen/rendering-elements/update-rendered-element
https://reactjs.org/redirect-to-codepen/introducing-jsx
https://reactjs.org/redirect-to-codepen/hello-world

**Comment by harish-sethuraman** [comment]
This issue seems like a duplicate of 
- https://github.com/reactjs/reactjs.org/issues/4227
Closing this duplicate issue to track there

**Comment by harish-sethuraman** [comment]
The links are fixed now. 😄
