### ISSUE TITLE
Incorrect class property reference in Context docs

### ISSUE THREAD

**Issue by haelmj** [reactjs/reactjs.org#4274]
In the return statement of the `ThemedButton` component, `this.contextType` should be assigned to the `theme` prop for the `Button` component instead `this.context` is assigned.

https://github.com/reactjs/reactjs.org/blob/84742f0b0b41c1c02db03586adfc2faad93a8b9e/examples/context/motivation-solution.js#L37
https://github.com/reactjs/reactjs.org/blob/84742f0b0b41c1c02db03586adfc2faad93a8b9e/examples/context/motivation-solution.js#L39

**Comment by haelmj** [comment]
This was actually misunderstood and is the correct implementation. Closing this now...

**Comment by saiy2k** [comment]
This is actually confusing. Relationship between 'contextType' and 'this.context' could be better explained
