### ISSUE TITLE
react v 16 documentation is missing

### ISSUE THREAD

**Issue by badbabykosh** [reactjs/reactjs.org#4347]
no links for any prior React versions documentation is working

**Comment by gaearon** [comment]
Yeah, this is a problem. We're tracking this in https://github.com/reactjs/reactjs.org/issues/3927.

**Comment by gaearon** [comment]
Actually that's not where that issue is. Where is it?...

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/4306 is the right issue.

**Comment by rickhanlonii** [comment]
This is finally fixed: [16.react.dev](https://16.react.dev) redirects to [16.reactjs.org](https://16.reactjs.org).

See https://github.com/facebook/react/issues/24802#issuecomment-2887567501 for more context.

_Note: it might take a bit for DNS to fully propagate._
