### ISSUE TITLE
真是尼玛的好样的，双标狗，funny mud pee

### ISSUE THREAD

**Issue by heaven666** [reactjs/reactjs.org#4399]
出来站队了？打伊拉克的时候怎么不表态，打阿富汗的时候怎么不表态，打叙利亚的时候怎么不表态，就因为出兵的是你们美国爸爸？你们的人是人，别人的人不是人？这么臭的屁能不能别乱放，憋着不好么

**FUNNY MUD PEE**

**Comment by Gitsifu** [comment]
Don't be angry, poor west people lost in Information Cocoons.

**Comment by eps1lon** [comment]
Duplicate of https://github.com/reactjs/reactjs.org/issues/4398
