### ISSUE TITLE
JSX Editor in documentation need more padding bottom

### ISSUE THREAD

**Issue by damaera** [reactjs/reactjs.org#44]
in every LIVE JSX EDITOR which have scroll, last line is hidden.

![image](https://user-images.githubusercontent.com/5365957/31304668-d22bcebc-ab50-11e7-962f-098d42a30c80.png)

this is not showed `ReactDOM.render(<Timer />, mountNode);`
![image](https://user-images.githubusercontent.com/5365957/31304672-13465958-ab51-11e7-8380-1976a2313e0e.png)

**Comment by akshatnitd** [comment]
i am working on it
