### ISSUE TITLE
Add Social Banner with "Support for DONBASS. US stop delivering missiles to the battlefield for the sake of humanity."

### ISSUE THREAD

**Issue by nyepi-3055** [reactjs/reactjs.org#4429]
Donbass was part of Ukraine in south-eastern,where has been shelled by Ukraine since 2014.
A French journalist released a documentary called Donbass in 2017: https://www.youtube.com/watch?v=6Oh-IE2zmJc

So why not add Donbass?selective vocalization?Double standard?
I will give you one slogan:The people in Donbass lives matter!

Before delete this issue.Please [tell me why](https://www.youtube.com/watch?v=F_N6s4u3uvk) the world is so dirty?Why so-called open source community is so ridiculous?And which rule indicates that my issue is in violation?

**Comment by hmmhmmhm** [comment]
Why do you think it will be deleted? Go ahead find an official account sponsoring Donbas and create a PR.

Currently, Russia is bombing Ukrainian civilians, and economic fundraising related to Russia is blocked by U.S. economic sanctions, so it is questionable whether we can legally find a channel that only sponsors civilians.

Wouldn't it be better to proceed to create PR not just arguing if you think this is humanitarian aid and you can prove it...?

**Comment by nyepi-3055** [comment]
>Why do you think it will be deleted? Go ahead find an official account sponsoring Donbas and create a PR.

A pr about 'no politics in open source project' is deleted. It could be closed. Why delete it?

>so it is questionable whether we can legally find a channel that only sponsors civilians.

Russian civilians(students,musicians,athletes,scientists,journalists and even cats) are sanctioned by US and European countries, they are innocent too. Do you think Meta will aids these people? No,it is not political correctness. Instead, facebook mutes Russia civilians.

>Wouldn't it be better to proceed to create PR not just arguing if you think this is humanitarian aid and you can prove it...?

If somebody tell me 'support Donbass' pr will be merged.I would love to pr.

I think the react.js project just becomes a tool to help Meta do 'political correctness'. Many Open source projects not controlled by companies choose to be neutral. A react coreteam member said:
>**It is true that we have not responded to every humanitarian disaster. There is no single objective threshold of scale, and we’ve only started doing these banners recently. However, this is not a zero-sum activity.** First, we are only a single project, and there are other projects which may choose different causes (or not support any causes at all). Second, getting the message out about one crisis does not hurt people affected by a different crisis. This is why the “whataboutism” is mostly a **distraction**, and we will not spend time seriously entertaining it.'

I want to ask:  Why only support Ukraine, this is not a zero-sum activity, many civilians are still suffering from past wars, it's not too late to help them. 
What kind of disaster would you entertain? Prohibiting a country's civilians from speaking on facebook would be considered as a humanitarian disaster?Musicians banned from performing, students expelled from universities, athletes banned from competing would be considered as a humanitarian disaster?Would react stand with them?

**Comment by nyepi-3055** [comment]
'Political correctness' is a humanitarian disaster.
They selectively help others, and the main purpose of their help is to cater to political positions. They deliver humanitarian aid while delivering ammunition to the battlefield. They do political propaganda while blocking other countries' media. Nice job

**Comment by nyepi-3055** [comment]
@xcatliu

**Comment by hmmhmmhm** [comment]
> "US stop delivering missiles to the battlefield".For the sake of humanity.

You initially insisted on a support PR for the Donbas area and wanted to write it down on this issue. But you can't even provide a normal charity event URL and only say what you want to say. You don't even know what humanitarian support means, and you're only showing political messages. Blaming others without providing the right information for the issue is a waste of other people's time.

I checked whether there was a practical support event for the Donbas area for nearly two hours because of you, and confirmed that there was no such event. How do you participate in this if you don't have a support event and a legitimate humanitarian support route?

It is foolish to create an issue that asserts the impossible in order to criticize others.

> They selectively help others, and the main purpose of their help is to cater to political stance. They deliver humanitarian aid while delivering ammunition to the battlefield. They do political propaganda while blocking other countries' media. Nice job.

You don't deserve to say this. Unless you present at least a few proper promotions for support events. And you're trying to convey a very political message. I don't think you know the meaning of humanitarian support.

> Russian civilians(students,musicians,athletes,scientists,journalists and even cats) are sanctioned by US and European countries, they are innocent too. Do you think Meta will aids these people? No,it is not political correctness. Instead, facebook mutes Russia civilians.

> What kind of disaster would you entertain? Prohibiting a country's civilians from speaking on facebook would be considered as a humanitarian disaster?Musicians banned from performing, students expelled from universities, athletes banned from competing would be considered as a humanitarian disaster? Would react stand with them?

It's an issue that has nothing to do with React. Don't talk about political ideas. It's frustrating to see that you can't even make a proper judgment on what humanitarianism is and just try to convey your political message.

> I want to ask: Why only support Ukraine, this is not a zero-sum activity, many civilians are still suffering from past wars, it's not too late to help them.

> A pr about 'no politics in open source project' is deleted. It could be closed. Why delete it?

So register the PR of the charity event you want to apply for in that area. Persuade others. It is not good to only criticize without making a reasonable suggestion. And check what you wrote in PR, I don't know what you wrote, but I guess it was spamming or not proper.

**Comment by drinkjava2** [comment]
To hmmhmmhm:  Don't you think talk humanitarianism in open source project is weird? if you really care about talk humanitarianism and politics in this discuss,  below video and links will give you some new viewpoints:
https://vimeo.com/178871166
https://www.163.com/dy/article/H14GKAIA055271RL.html
https://www.kunlunce.com/ssjj/guojipinglun/2022-03-03/159304.html
https://hotqiqi.com/archives/321585

**Comment by hmmhmmhm** [comment]
Human rights issues are not political, and if simple humanitarian
support is political, it denies most of modern society.

You are trying to make this a political issue, but this is a humanitarian aid issue,
and I don't know your intention to argue that this is political.

See, most front-end library teams or individuals are doing the
same thing as humanitarian support campaigns on this issue.

- React ( https://github.com/reactjs/reactjs.org/pull/4397 )
- Svelte ( https://github.com/sveltejs/sites/pull/308 )
- Angular ( https://twitter.com/angular )
- Vue ( https://twitter.com/vuejsamsterdam/status/1498639014592663552 )
- Node.js ( https://github.com/nodejs/nodejs.org/pull/4450 - Withdrawal due to the possibility of supporting military organizations. )
- Jest ( https://github.com/facebook/jest/pull/12532 )

**Comment by Im-Kevin** [comment]
Where were you during the Iraq Syria war

**Comment by Im-Kevin** [comment]
Choose sexual humanitarianism?

**Comment by hmmhmmhm** [comment]
@Im-Kevin 
Create a PR that can solve the issues you are talking about. It is important to make the team respond to other issues. Don't block other campaigns under the pretext of that.

**Comment by Im-Kevin** [comment]
Why support Ukraine, not help the Ukrainian people

**Comment by Im-Kevin** [comment]
Support Ukraine is a political issue, and helping the Ukrainian people is humanitarian

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/156966861-f1781c90-2134-42d7-bb3f-51619f6b6fca.png)
Can I understand this as weapons? If so, is it humanitarian or military assistance

**Comment by Im-Kevin** [comment]
@hmmhmmhm This is humanitarianism?

**Comment by hmmhmmhm** [comment]
@Im-Kevin
That's what I said. Other existing issues misunderstood the point very differently.
If you want to withdraw this campaign, you should not talk about support from the Donbas area, but rather argue whether there is any possibility of military support or misuse.

However, what you pointed out is wrong and misinformation, misleading the facts. 

> "United Help Ukraine (UHU) is working to provide life-saving individual first aid kits (IFAKs containing blood-stopping bandages and tourniquets) and other emergency medical supplies to the front lines."
https://www.facebook.com/UnitedHelpUkraine.org/posts/5000623900004699

Do you think individual aid kits is a weapon? I hope you will recall how much medical supplies are needed in a country where the medical system has collapsed. There are very limited medical support measures that can be provided in countries where combat is underway and bombing is taking place even to doctors.

**Comment by Im-Kevin** [comment]
So, is this help aimed at soldiers or civilians

**Comment by Im-Kevin** [comment]
In addition, whether we can add help to the unemployed people in Russia caused by sanctions, they are not wrong

**Comment by Im-Kevin** [comment]
Sometimes starvation is more terrible

**Comment by hmmhmmhm** [comment]
![medical-kit](https://user-images.githubusercontent.com/38493722/156970825-ae388f6a-1553-4077-849e-2444e550d84b.png)

> Can I understand this as weapons?

Medical kits are not weapons. If you think bandages or hemostatic rods are weapons, YES you can blame them, but you shouldn't blame people this way. What would be the least abused way to send to Ukraine? If you think there is something that can be least abused, suggest it to them.

> "UNICEF Sponsorship List - Procurement of -First Aid kits, IFAK kits & Survival kits"
https://www.ungm.org/Public/Notice/146921

As you claim, if medical supplies are weapons, UNICEF becomes an organization exporting weapons.

**Comment by hmmhmmhm** [comment]
> Sometimes starvation is more terrible

Yes, that's right. Food support is also being provided. But the most important thing is to save the injured, so they have to solve this first. Likewise, groceries are likely to be provided to soldiers. All humanitarian assistance poses a potential risk of being looted in the middle and not reaching civilians. Nevertheless, it cannot deny that is are on the way to save civilians.

**Comment by Im-Kevin** [comment]
Can I understand that the Ukrainian government forces will seize these materials? If so, should we write them down and attract the attention of Ukraine and the international community to ensure that the materials can help civilians, not the army

**Comment by nyepi-3055** [comment]
Musicians banned from performing, students expelled from universities, athletes banned from competing ist not a humanitarian disaster.OMG.

**Comment by hmmhmmhm** [comment]
>should we write them down and attract the attention of Ukraine and the international community to ensure that the materials can help civilians

Good. There's progress in our conversation. I agree with this view of yours.

>Musicians banned from performing, students expelled from universities, athletes banned from competing is not a humanitarian disaster. OMG.

Is it related to the content of humanitarian aid? I think you need to explain in more detail how you can link this.

**Comment by drinkjava2** [comment]
> Human rights issues are not political, and if simple humanitarian support is political, it denies most of modern society.    
 Human rights are 100% politics, lots of countries be invaded because of one reason:"poor human rights".

> You are trying to make this a political issue, but this is a humanitarian aid issue, and I don't know your intention to argue that this is political.    
humanitarian is not like "We stand to XXX", That's 100% politics.

> See, most front-end library teams or individuals are doing the same thing ......  
That's not a reason. My dog eat dog food, so I eat d.. ...?

**Comment by hmmhmmhm** [comment]
@drinkjava2 

Then to summarize your opinion,

1. medical kits are weapons
2. human rights issues are all 100% political issues
3. many development teams are eating dog food...?

I can't agree with your these opinion. I can't see medical kits as weapons, can't see human rights issues politically, and I can't sarcastic other teams' campaigns like that.

**Comment by drinkjava2** [comment]
> @drinkjava2
>     1. medical kits are weapons
medical kits are medical kits
>     2. human rights issues are all 100% political issues
Yes
>     3. many development teams are eating dog food...?
metaphor

**Comment by nyepi-3055** [comment]
campaign: a series of planned activities that are intended to achieve a particular social, commercial or political aim

**Comment by nyepi-3055** [comment]
Thanks for reminding me.
If I don't know svelte before,I would have thought svelte was a ukrainian government website 
![image](https://user-images.githubusercontent.com/97597220/156961193-b9d91675-0f85-4678-a119-8e8ce86d6454.png)
ridiculous

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/156981174-acde7258-eb09-4e4b-a0b0-5eb91330fe7d.png)
Svelte' political orientation is really ridiculous

**Comment by nyepi-3055** [comment]
@hmmhmmhm would say: 
>You only say what you want to say. You don't even know what humanitarian support means, and you're only showing political messages. 
You don't deserve to say this. Unless you present at least a few proper promotions for support events. And you're trying to convey a very political message. I don't think you know the meaning of humanitarian support.

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/156986237-34dd2a93-0c03-4616-8fc4-725aebf8eadc.png)
Russia is bring Ukraine love and peace, just like TIME said

**Comment by hmmhmmhm** [comment]
@nyepi-3055 
I didn't get an answer from you. and this is react repo,
not a svelte repo. why don't you intentionally answer what I'm saying?

> Is it related to the content of humanitarian aid? I think you need to explain in more detail how you can link this.

**Comment by Im-Kevin** [comment]
We should oppose all military assistance under the pretext of humanitarian assistance. All military assistance will not end the war, but make the war more intense
@hmmhmmhm

**Comment by hmmhmmhm** [comment]
> Russia is bring Ukraine love and peace, just like TIME said

This behavior is a harmful political message what I've talking about. Why do you disturb the community with political messages by breaking the order of the community and spamming it as if asking others for political neutrality?

> We should oppose all military assistance under the pretext of humanitarian assistance. All military assistance will not end the war, but make the war more intense

If you give them bandages and medical kits, do they assassinate the Russians with bandages? Why do you give other reasons for this when you just don't want humanitarian support?

Just simply say that you don't want humanitarian support so that everyone can understand. Your opinion, which does not want to reduce the killing of civilians, is really political and contrary to the values of the nonviolent humanitarian world that most societies aim for.

**Comment by Im-Kevin** [comment]
I didn't seem to say that I didn't want to reduce the killing of civilians. I just said that military assistance should not be carried out

**Comment by Im-Kevin** [comment]
The open source software community is contributed by many international people, and no one wants these contributions to end up in their own country

**Comment by nyepi-3055** [comment]
If you give Russians bandages and medical kits, do they assassinate the Ukrainian with bandages?

**Comment by Im-Kevin** [comment]
The open source software community is contributed by many international people. No one wants these contributions to harm their country in the end

**Comment by Im-Kevin** [comment]
I think assistance to civilians should be provided, but military assistance should not be provided. That is a matter for the country. A neutral open source community should not be allowed to make political tendencies

**Comment by Im-Kevin** [comment]
If one day, the open source community you have contributed has harmed the interests of your country, will you still think like this

**Comment by hmmhmmhm** [comment]
>  I just said that military assistance should not be carried out

Is medical kit support is a military support? What is the military support you are talking about?

**Comment by Im-Kevin** [comment]
> ![image](https://user-images.githubusercontent.com/15227529/156981174-acde7258-eb09-4e4b-a0b0-5eb91330fe7d.png) Svelte' political orientation is really ridiculous
@hmmhmmhm 
Like these
And it should not indicate the political orientation of an open source community

**Comment by hmmhmmhm** [comment]
@Im-Kevin 
Is this where we talk about with the svelte?

**Comment by Im-Kevin** [comment]
If the medical package support for the Ukrainian army is not military assistance, why not provide assistance to Russia

**Comment by Im-Kevin** [comment]
I was just making my point

**Comment by Im-Kevin** [comment]
I believe Russian soldiers also need these medical kits

**Comment by hmmhmmhm** [comment]
> If the medical package support for the Ukrainian army is not military assistance, why not provide assistance to Russia

Have civilian victims occurred in Russia? Most civilian victims occur in Ukraine area.

> I believe Russian soldiers also need these medical kits

This is really a political message and no one has asked for your political opinion.

**Comment by Im-Kevin** [comment]
> Have civilian victims occurred in Russia? Most civilian victims occur in Ukraine area.
> > I'm talking about medical assistance to the Ukrainian army

**Comment by Im-Kevin** [comment]
> Have civilian victims occurred in Russia? Most civilian victims occur in Ukraine area.

I'm talking about medical assistance to the Ukrainian army

**Comment by hmmhmmhm** [comment]
@Im-Kevin 
> "370 CAT tourniquets and 220 Celox Z-Folded gauzes already on the way to Ukraine - going to our hardworking volunteers in Lviv and Mykolaiv. Total cost $19,513. These meds save lives!"

Emergency relief kits are delivered directly to Ukrainian civilians.
Why are you saying that you should support the Russian army?

**Comment by SekiBetu** [comment]
> > If the medical package support for the Ukrainian army is not military assistance, why not provide assistance to Russia
> 
> Have civilian victims occurred in Russia? Most civilian victims occur in Ukraine area.
> 
> > I believe Russian soldiers also need these medical kits
> 
> This is really a political message and no one has asked for your political opinion.

https://rusvesna.su/news/1645720241
https://vimeo.com/202792798
This is what Ukraine did for eight years before this war started, for 8 years
I want to donate to Russia to avenge them.

**Comment by Im-Kevin** [comment]
This is just a metaphor. Please don't take it out of context

**Comment by hmmhmmhm** [comment]
@SekiBetu 
No one is talking about revenge except you.
People here don't seem to agree with you either.
What do you really think humanitarian support is?

**Comment by Im-Kevin** [comment]
Please answer the question positively and don't intercept some articles

**Comment by SekiBetu** [comment]
> @SekiBetu No one is talking about revenge except you. People here don't seem to agree with you either. What do you really think humanitarian support is?

humanitarian support means buy more weapons for Ukraine to kill peoples in Donbass

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/156990946-f573d1d1-090f-41d8-b6a8-24aa15d0d536.png)

**Comment by Im-Kevin** [comment]
I've never said I support Russia. It's just a metaphor

**Comment by Im-Kevin** [comment]
I just think the open source community should remain neutral

**Comment by hmmhmmhm** [comment]
> humanitarian support means buy more weapons for Ukraine to kill peoples in Donbass

So... Do you use bandages as a weapon? At least no one in React Repo is asking to send weapons.

> I've never said I support Russia. It's just a metaphor

<img width="481" alt="스크린샷 2022-03-07 오후 5 01 09" src="https://user-images.githubusercontent.com/38493722/156991178-e09d584f-584e-4998-b2c5-138ced691432.png">

You said it very similarly. If there is civilian damage in Russia and there is an event to sponsor it, just create a PR.
I think this can be the best answer to satisfy everyone's opinions.

**Comment by Im-Kevin** [comment]
Can you only see part of the text

**Comment by hmmhmmhm** [comment]
@Im-Kevin 

So what do you want in full part of the text?
...Support for Russian civilians? If so, I agree.
Let's find such a campaign to resolve the dispute.

But I looked for something similar for hours yesterday, but I couldn't find it.

**Comment by Im-Kevin** [comment]
The community should not support Ukraine, but help the Ukrainian people

**Comment by Im-Kevin** [comment]
These are two different attitudes

**Comment by hmmhmmhm** [comment]
So all you want is to change the message?

**Comment by Im-Kevin** [comment]
Yes

**Comment by hmmhmmhm** [comment]
Let's make a PR that adds a phrase to the message, at least I'll agree with it.

**Comment by Im-Kevin** [comment]
"Helping the Ukrainian people (this behavior does not mean agreeing with the political position of either party)"
Would it be better

**Comment by hmmhmmhm** [comment]
@Im-Kevin too long, can you shorten the message?

**Comment by Im-Kevin** [comment]
Sorry, my English is poor. You can think about it

**Comment by hmmhmmhm** [comment]
```jsx
const bannerText = 'Support civilians in Ukraine area 🇺🇦 ';
const bannerLink = 'Help Provide Humanitarian Aid to civilians in Ukraine area.';
```
@Im-Kevin  @nyepi-3055 
How about doing it like this?

**Comment by Im-Kevin** [comment]
I think it's good

**Comment by Im-Kevin** [comment]
I think it would be better if UA could be deleted

**Comment by hmmhmmhm** [comment]
```
const bannerText = 'Support civilians in war 🇺🇦 ';
const bannerLink = 'Help Provide Humanitarian Aid to civilians in war.';
```
@Im-Kevin  @nyepi-3055 
Is it okay now?

**Comment by Im-Kevin** [comment]
Good

**Comment by hmmhmmhm** [comment]
Good, as agrees, I will edit an message with this.

**Comment by MrRamoun** [comment]
I think you can add Syria too.

**Comment by hmmhmmhm** [comment]
@MrRamoun 
很好。正在寻找与叙利亚有关的捐赠活动。
正在寻找联合国儿童基金会等，如果提出这样的链接，将有助于日后添加意见。
以后要添加创建可长期运营的Banner栏的请求，请给予帮助。

**Comment by nyepi-3055** [comment]
@hmmhmmhm I can find that you really love react.js.
But the fact is that react it controlled by Meta, not by community. It's the reason why there is no discussion in #4397
On the contrary, the php community is free to discuss, even if they have different opinions. https://externals.io/message/117187
And I don't think there will be banners supporting other regions in the future, unless Meta wants to

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/4433#issuecomment-1060759889
