### ISSUE TITLE
Suggest: invent new opensource license: "MIT stand for Ukraine"  and "MIT stand for Donbass"

### ISSUE THREAD

**Issue by drinkjava2** [reactjs/reactjs.org#4430]
To solve political issues, open source projects should think of use "politicized opensource license", like "Apache 2 stand for Ukraine", "MIT stand for Donbass", "GPL stand for Russia"..., make people easier to choose opensource software by license. without confusion and argue. Currently these is no a mechanism to remind the political attitude of  opensource projects, it may cause big lost for projects in one day they have to kick out the "wrong politic attitude software". 
And of cause this react project need switch to "MIT stand for Ukraine" license.

**Comment by drinkjava2** [comment]
Here I give a rough idea of "politicized opensource license":
1. One project can only choose one "politicized opensource license", it's not allowed to release conflict versions for same project.
2. On website, user manual and documents, politic banners, comments, articles should no conflict with author's all released "politicized opensource license"
3. Other rules follow normal opensource license like MIT/GPL/Apache...

**Comment by hmmhmmhm** [comment]
I think you don't know what is the MIT license is or you're sarcastic.
Again, since you mentioned it, the license does not depend on the region.

If you want anything in the open-source community, do not be sarcastic, create pull request, and discuss it in practice.
Do you have a web link to humanitarian assistance in the Donbas area?

And do you have a reference to prove that this does not violate US remittance sanctions and is delivered only to civilians for humanitarian purposes?

**Comment by drinkjava2** [comment]
I meant to invent a new license instead of use MIT license itself. Everyone can write a open source license, if you don't agree, you have right not to use the software.
The thing is as this project already involved politics, why we don't put it on the table to talk? what's the right place to store politics context? source code or user manual? or on website banner which just above the docs and tutorial? no, no, no, these are all not right places, we need find a standard place to store political contexts, there is no better place other than license, as every opensource project have a license. 
I don't stand on Ukraine or Donbass, but only gave a good suggestion for the technical issue "Where to put political context in open source project?", hope from now we can set a good example to others projects who want to add politics into their open source projects.

**Comment by hmmhmmhm** [comment]
It's a really basic concept, but humanitarian support is not political.
Modern society would have worsened if humanitarian aid was banned according to political views.
Do you think it is political to help the injured or orphans who have no place to rest?

And back to the original topic, you can't use the name MIT, GPL in anyway.
Because you don't belong to MIT or GPL, and the license you tampered with is not made by MIT.
According to your argument, it does not comply with the Copyleft basic concept,
so it cannot be considered based on the license you are based on.

The arguments you suggest can lead to great political disputes and poison the open-source ecosystem.

**Comment by phasedarray** [comment]
> It's a really basic concept, but humanitarian support is not political. Modern society would have worsened if humanitarian aid was banned according to political views. Do you think it is political to help the injured or orphans who have no place to rest?
> 
> And back to the original topic, you can't use the name MIT, GPL in anyway. Because you don't belong to MIT or GPL, and the license you tampered with is not made by MIT. According to your argument, it does not comply with the Copyleft basic concept, so it cannot be considered based on the license you are based on.
> 
> The arguments you suggest can lead to great political disputes and poison the open-source ecosystem.

Obviously it's sarcastic. But according his original  logic(NOT talking about whether it's humanitarian aid),
the owner-organization of MIT/GPL is supposed to  create an extended MIT/GPL license for those who have political stand. The political-stand restrictions may be the preconditions of terms of MIT or GPL. Precondition could be something like 'You need to have same political stand if you want to modify and redistribute your code' and it could also comply with copyleft.

**Comment by hmmhmmhm** [comment]
@phasedarray 
Is it intended to prevent the use of projects according to political views? Please understand that the React team's issue has never been a political issue. 

If you use a different name, there will be no problem. ( If it's right to discriminate against licenses by region )

**Comment by drinkjava2** [comment]
> the owner-organization of MIT/GPL is supposed to create an extended MIT/GPL license for those who have political stand. 
Glad to know. 

>Is it intended to prevent the use of projects according to political views? Please understand that the React team's issue has never been a political issue.
Yes they don't like political issues but React team bind political stand on React doc and tutorial on their website. Can I understand by this way they want to prevent the use of this project to whom disagree their political views?

**Comment by hmmhmmhm** [comment]
@drinkjava2 

> React team bind political stand on React doc and tutorial on their website.

1. Why is humanitarian aid a political position? 

2. Does it also seem political for UNICEF to help conflict areas?

> Can I understand by this way they want to prevent the use of this project to whom disagree their political views?

3. When did React team's block the use?

**Comment by drinkjava2** [comment]
Q1 and Q2:
Stand for XXX, it's politics,  
Provide Humanitarian Aid to Ukraine, it's humanitarian 
Bind together: Stand for XXX & Provide Humanitarian Aid,  it's still politics.

Q3: 
That's the problem I want to solve, team said: "we don't like some person, but we welcome you to use our software", that's so wired, why not just put on table and write this attitude in license?

**Comment by hmmhmmhm** [comment]
@drinkjava2 
经过长时间的讨论，在经过多数同意后，以中立的信息修改了react主页上的文章。 希望把政治上可能被误解的信息改善为更好的善意信息，并帮助制定所有人都需要的解决方案。https://github.com/reactjs/reactjs.org/pull/4438

让我们创造一个更好的 React.js，让社区朝着更好的方向发展。

**Comment by gaearon** [comment]
https://github.com/reactjs/reactjs.org/issues/4433#issuecomment-1060759889
