### ISSUE TITLE
This community can close. 这个社区可以洗洗睡了，Meta要介入政治却拒绝社区讨论政治

### ISSUE THREAD

**Issue by drinkjava2** [reactjs/reactjs.org#4440]
Title translate: This community can close. Meta insist to involve politics but refuse to discuss politics.

To  gaearon:
Before you close or delete this issue,  please see below 2 links and rethink if it's too early to involve politics:
https://vimeo.com/178871166  
https://www.youtube.com/watch?v=6Oh-IE2zmJc 
 
>People in Ukraine are in the middle of a severe humanitarian crisis. According to UN, a million of people have become refugees this week. It is widely reported that many people, including kids, are sheltering in basements, traveling in freezing temperatures, and are short on supplies. This is why we would like to encourage everyone using React to help those in need.     

To support humanitarian, the standard words should be "Provide Humanitarian Aid to Ukraine", not "Support Ukraine & Provide Humanitarian Aid to Ukraine".  See, I'm a Chinese but I have better English understanding than you. You are not standing on humanitarian, but on politics.
 
>However, this is not a zero-sum activity. First, we are only a single project, and there are other projects which may choose different causes (or not support any causes at all). Second, getting the message out about one crisis does not hurt people affected by a different crisis. This is why the “whataboutism” is mostly a distraction, and we will not spend time seriously entertaining it.    

Yes it's not zero-sum activity, if you stand on "Support Ukraine" politic attitude, will hurt people who died in Donbass in last 8 years.

>You are free to suggest other causes to support in the future. However, spamming the repo with duplicate issues and comments is disruptive. This violates the GitHub the terms of service, and GitHub will be removing this type of content. There is nothing more we would like to say on this at this point, so we will be locking this issue.    

1)It's not spamming, it's HUUUUUUUUUUUUUUUUUUUUUGE political conflict. community has decided to keep neutral, but Meta decide to involve politics, I don't think community can keep calm and continue work on this project until find a solution, in Chinese there is a idiom "道不同不相为谋" ，means if people have conflict politic views they can not work together. 
2)If Meta insist  involve politics, and community insist to keep neural, could you quit this community and stop pollute this community with your politic issues? you only represent yourselves politic views , not community's. 
3)Violates the GitHub the terms of service? -- Think who first invoke this topic? Meta decide to introduce politic and put politic slogan in source code, why you want forbid community to discuss politics? it's not "political right", and it's double standard.
4)As I said before, if Meta insist involve politics, better to revise the project license to "Politicized MIT license", this is more clear to tell users to kick out "Conflict Political Views Software" from business projects.

**Comment by gaearon** [comment]
We have already said everything we wanted to say on this topic at this moment in https://github.com/reactjs/reactjs.org/issues/4433#issuecomment-1060759889. There's nothing more we want to add at this point.
