### ISSUE TITLE
"Is this page useful?" is partially hidden (https://beta.reactjs.org)

### ISSUE THREAD

**Issue by RinatValiullov** [reactjs/reactjs.org#4447]
The block with reviews "Is this page useful?" is partially hidden (https://beta.reactjs.org). What can create an unpleasant UX in my opinion.

My system:

_Google Chrome: 99.0.4844.51 (Official Build) (64-bit)
OS: Windows 10 Version 20H2_

Screenshot and gif:

![image](https://user-images.githubusercontent.com/9755333/157413511-a4853f20-201e-4129-84cc-ea3e9479f86f.png)

![WOYCoC7smR](https://user-images.githubusercontent.com/9755333/157413974-ada385c6-d025-4b1a-9529-0743ed143569.gif)

**Comment by harish-sethuraman** [comment]
This issue is fixed now 😄
