### ISSUE TITLE
Update egghead's how to contribute to oss url

### ISSUE THREAD

**Issue by immanu10** [reactjs/reactjs.org#4492]
how to contibute doc has old dead egghead link. egghead.io has new version and url changed.

Can i make this quick change? this will be my first os contribution.

**Comment by harish-sethuraman** [comment]
Feel free to send PR. Try using global search of the link in the repo and try updating the link.

**Comment by harish-sethuraman** [comment]
Thanks for the PR

**Comment by immanu10** [comment]
Thanks. I'm very happy, my first OS contribution got merged.
