### ISSUE TITLE
The setState furnction from useState should be in the dependency array when called from within useEffect

### ISSUE THREAD

**Issue by ellertsmari** [reactjs/reactjs.org#4506]
As talked about [here](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528) and explained in [this](https://dennyscott.io/use-effect-dependency-array/) article. The setState function from the useState hook should be in the dependency array when it is called from useEffect. This is not done in the documentation. The clearest example is probably from [the hooks-faq](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies) where this example is given:

![image](https://user-images.githubusercontent.com/1809316/160502177-e510f4f0-11b0-4545-85c1-e3dd74166b9d.png)

**Comment by klarstrup** [comment]
It doesn't have to be. The second value from useState, the setter, is stable. It never changes and thus is redundant to put in the dependency array. See the `Note` in this section: https://reactjs.org/docs/hooks-reference.html#usestate

**Comment by gaearon** [comment]
^ that's correct. So you can add it for consistency but it doesn't really matter one way or another.
