### ISSUE TITLE
"next" footer links don't pull title from source

### ISSUE THREAD

**Issue by alexkrolick** [reactjs/reactjs.org#451]
Instead of pulling the title attribute from `next` target in nav metadata, the link generator seems to just strip the file extension and `-`. This looks weird if the title is different than the title generated from the link.

https://github.com/reactjs/reactjs.org/blob/184a7ef9476c524df0ff82362257c02bfbe8698d/src/templates/components/NavigationFooter/NavigationFooter.js#L89

EDIT: found an existing TODO for this 😄 

https://github.com/reactjs/reactjs.org/blob/184a7ef9476c524df0ff82362257c02bfbe8698d/src/components/MarkdownPage/MarkdownPage.js#L125-L132

**Comment by raunofreiberg** [comment]
@alexkrolick Is there someone working on it already? If not, I'd love to take a crack at it.

**Comment by alexkrolick** [comment]
Sure, it's all yours @raunofreiberg

**Comment by raunofreiberg** [comment]
Gave it a shot at #688. Would appreciate it if you took a look :-) @alexkrolick
