### ISSUE TITLE
there are two same change in React 18 ChangeLog

### ISSUE THREAD

**Issue by wcly** [reactjs/reactjs.org#4522]
https://github.com/facebook/react/releases/tag/v18.0.0

![image](https://user-images.githubusercontent.com/23275036/160746261-c0c54538-ff99-4598-b8d5-89332ae704b6.png)

**Comment by gaearon** [comment]
Oops. Want to send a PR for committed changelog.md and the upgrade post on the website?

**Comment by harish-sethuraman** [comment]
Hey thanks for letting us know. I've fixed this. Thanks :)

**Comment by wcly** [comment]
Right，I should do that next time. @gaearon
