### ISSUE TITLE
“Support Ukraine 🇺🇦“ link doesn’t work on mobile

### ISSUE THREAD

**Issue by tomayac** [reactjs/reactjs.org#4524]
Support Ukraine 🇺🇦
[Help Provide Humanitarian Aid to Ukraine.](https://opensource.fb.com/support-ukraine)

![585E8474-D48C-42CA-9992-D1B238F7029C](https://user-images.githubusercontent.com/145676/160770777-b871474e-3ba7-44ff-8e95-c8fec30c33a3.png)

The link goes to `https://opensource.fb.com/support-ukraine` → `https://m.facebook.com/fundraisers/explore/search/charities/?query=ukraine`, but search for fundraisers doesn’t seem to work on mobile. Search works fine on desktop.

**Comment by 01114941702** [comment]
هل عمل فيسبوك 
doaaabdul87@gmail.com 
01114941702
222333444 
دعاء الصم

**Comment by tomayac** [comment]
It’s been a couple of months now. The behavior still is the same. Since the limitation seems to be that fundraisers can’t be searched for on mobile, maybe the next best thing is to link to a search for pages: https://m.facebook.com/search/pages/?q=fundraiser%20for%20ukraine&source=filter&isTrending=1.

**Comment by gaearon** [comment]
Sorry. I know this sucks. The team working on this product has not been able to prioritize this. And we can’t / it’s a bit late to get approval for a different link. We’ll make sure to not run into the same mistake in the future but it is what it is.
