### ISSUE TITLE
Using of import causing "cannot use import statement outside a module"

### ISSUE THREAD

**Issue by amansani15** [reactjs/reactjs.org#4529]
I followed the tutorial of how to add react to a website. Everything is working as expected until the end of the documentation. The problem occurs when I try to add any import statements within the code. Below are the steps to reproduce:

[https://reactjs.org/docs/add-react-to-a-website.html](url)

**Steps:**
1. Follow all the steps given in the above link
2. Sample import statement or library which I used is 'victory charts' 
    **npm install victory** or
    **npm install victory --save-dev**
3. Now you see the library is installed in node modules section. Then I added import statement **import { VictoryPie, VictoryAnimation } from 'victory';** within the js file [https://gist.githubusercontent.com/gaearon/c8e112dc74ac44aac4f673f2c39d19d1/raw/09b951c86c1bf1116af741fa4664511f2f179f0a/like_button.js](url)
4. This is the error I am getting after adding import statement **Uncaught SyntaxError: Cannot use import statement outside a module**

Could anyone please guide me how I can add import statement successfully when I add react to a website. Any inputs are highly appreciated. Thank you

**Comment by gaearon** [comment]
Hi! You should ask `victory` maintainers for instructions for how to use their library as a `<script>` tag.

**Comment by gaearon** [comment]
It might be that if `victory` is published in ES Modules format, there's some way to import it directly. I don't know how for sure. Otherwise, you might need to set up a bit more involved build process with a bundler.

**Comment by amansani15** [comment]
Victory is one example which I tried. I assume it must be the same thing with any import statement within the js files [[https://gist.githubusercontent.com/gaearon/c8e112dc74ac44aac4f673f2c39d19d1/raw/09b951c86c1bf1116af741fa4664511f2f179f0a/like_button.js](https://github.com/reactjs/reactjs.org/issues/url)](url)

**Comment by amansani15** [comment]
Thank you for recommendations, I will look into it.

**Comment by gaearon** [comment]
I discussed with the team a bit and we should probably update the website instructions to suggest the second approach. Might take a bit of time to get that updated though.

**Comment by amansani15** [comment]
Thank you, I appreciate that.
