### ISSUE TITLE
Need note for react-redux users about React 18

### ISSUE THREAD

**Issue by ariccio** [reactjs/reactjs.org#4534]
It seems that the new concurrent rendering behavior does NOT play nice with react-redux 7.x. Upgrading broke my whole app :)

[The react-redux team seem to know about this](https://github.com/reduxjs/redux-toolkit/releases/tag/v1.8.1): 

> Note: If you are now using React 18, we strongly recommend using [the React-Redux v8 beta instead of v7.x!](https://github.com/reduxjs/react-redux/releases/tag/v8.0.0-beta.3). v8 has been rewritten internally to work correctly with React 18's Concurrent Rendering capabilities. React-Redux v7 will run and generally work okay with existing code, but may have rendering issues if you start using Concurrent Rendering capabilities in your code.

Upgrading to that beta fixes all that was broken for me. I'd recommend adding a note to the documentation, maybe the [`How to Upgrade to React 18` page](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html), to note this.

**Comment by gaearon** [comment]
My guess is your app has StrictMode on. The upgrade post mentions this. If you disable StrictMode I’d expect v7 to work for you as well. Can you check this please?

**Comment by ariccio** [comment]
Yes, I have strictmode on, and I have already checked to see if removing it fixes the problem - it does! Except that is still surprising (and incorrect?) behavior, hence why I went ahead and upgraded to the v8 react-redux.

**Comment by gaearon** [comment]
Yeah. Upgrading is good, but I’d expect many other libraries will run into the same issue with Strict Mode initially so that’s the part that needs to be more prominent.

**Comment by ariccio** [comment]
Yup! Not a huge deal, I just always try to make sure that nobody else has to waste the same five minutes I do when I see a little thing like this.

Maybe it was 30. *Shh* :)

**Comment by ShayanAbedi** [comment]
had the same issue and upgrading `react-redux` to `7.2.8` got it fixed. thanks!
