### ISSUE TITLE
Following 'Add React to a Website' gives 'not supported' error

### ISSUE THREAD

**Issue by adwilk** [reactjs/reactjs.org#4547]
After following the code samples on the [Add React to a Website](https://reactjs.org/docs/add-react-to-a-website.html ) guide (using v18 `.development.js` scripts) there is a warning in the browser console:

> Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".
printWarning @ react-dom.development.js:73
error @ react-dom.development.js:47
createRoot$1 @ react-dom.development.js:29540
(anonymous) @ (index):32

I don't see any obvious way to import react-dom/client from unpkg.

**Comment by gaearon** [comment]
This is a bug: https://github.com/facebook/react/issues/24221. We're looking at it but might take a week to fix.

You can ignore it.

**Comment by harish-sethuraman** [comment]
Closing this as it has been fixed in the react repo 
- https://github.com/facebook/react/issues/24221
