### ISSUE TITLE
Clarification regarding IE11 compatibility in React 18, while using React 17 behaviour

### ISSUE THREAD

**Issue by orestis** [reactjs/reactjs.org#4560]
Hello, in the React 18 announcement I can read:

> In this release, React is dropping support for Internet Explorer, which is [going out of support on June 15, 2022](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge). We’re making this change now because new features introduced in React 18 are built using modern browser features such as microtasks which cannot be adequately polyfilled in IE.

I'd like to ask for a clarification. If we upgrade to React 18 but don't adopt React 18 mode (ie, stick with React.render), are those "modern browser features" still used?

The reason is that we will also drop support for IE11 on June 15, but we'd like to upgrade React 18 earlier than that. However, we can't use two different versions in our package.json. 

After 15 June, we'd like to be able to prompt IE11 users to upgrade, i.e. if the browser is IE11, we use React.render to show a message, otherwise use React.createRoot to load the actual application.

**Comment by gaearon** [comment]
We expect that `ReactDOM.render` should work with IE11. We haven't added or removed IE-related code in those codepaths so should be ok.
