### ISSUE TITLE
The link to React Conf 2021 Videos is broken

### ISSUE THREAD

**Issue by mhsiungw** [reactjs/reactjs.org#4561]
The link to React Conf 2021 Videos is broken in the [Caution quote field](https://17.reactjs.org/docs/concurrent-mode-reference.html).

The link should be changed from http://localhost:8000/blog/2021/12/17/react-conf-2021-recap.html to https://youtu.be/8dUpL8SCO1w .

**Comment by gaearon** [comment]
Thanks, deploying a fix.
