### ISSUE TITLE
Unable to reproduce React 18 SSR example

### ISSUE THREAD

**Issue by morsmodr** [reactjs/reactjs.org#4565]
I am looking for guidance in doing React SSR without a framework. I tried to recreate the sandbox linked in react working group /37 discussion. But for some reason I am not able to get a simple app working.

Here is the CodeSandbox
https://codesandbox.io/s/flamboyant-resonance-megd2o?file=/src/Main.js

Note, I am using React18 production version and webpack 5, vs the e.g. which uses React-18-alpha version and webpack 4
https://codesandbox.io/s/kind-sammet-j56ro?file=/src/App.js

Not sure what I am missing here

**Comment by gaearon** [comment]
Try changing onCompleteShell to onShellReady. It was renamed.

**Comment by morsmodr** [comment]
Yep, that worked! Thanks :)

**Comment by gaearon** [comment]
Can you remind me where we link to this sandbox?

**Comment by morsmodr** [comment]
https://github.com/reactwg/react-18/discussions/37

![Screen Shot 2022-04-08 at 10 13 27 AM](https://user-images.githubusercontent.com/7231256/162490166-c10b22ab-2ca5-4624-a28b-8fbc7e8d712a.png)

^^ One of the places, there are other places within this page where it is referenced
