### ISSUE TITLE
update the codepen code "index.js" in tutorial for react18

### ISSUE THREAD

**Issue by awxiaoxian2020** [reactjs/reactjs.org#4569]
I'm a React beginner. when I use the given examples in [tutorial](https://reactjs.org/tutorial/tutorial.html) , it warns "ReactDOM.render is no longer supported in React 18. Use createRoot instead. ". I think we can update "index.js" to give a better experience for beginners.

==================================================================================
![image](https://user-images.githubusercontent.com/69554233/162738033-383e6e8b-8fa3-4663-b4cd-2bad03f21161.png)

==================================================================================

![image](https://user-images.githubusercontent.com/69554233/162738196-bce3bdd4-75a2-47f4-b8fa-c234d5247ef4.png)

==================================================================================

![react-issue](https://user-images.githubusercontent.com/69554233/162601324-7bf8687d-3e36-4998-b65a-913e29ef2a90.png)
.

**Comment by harish-sethuraman** [comment]
Thanks for reporting. Can you please share where you found this codepen link? (the page's actual link) ?

**Comment by awxiaoxian2020** [comment]
> Thanks for reporting. Can you please share where you found this codepen link? (the page's actual link) ?

[JS code here](https://codepen.io/gaearon/pen/oWWQNa?editors=0010) in [react tutorial](https://reactjs.org/tutorial/tutorial.html).

**Comment by harish-sethuraman** [comment]
I'm not getting `ReactDOM.render is no longer supported in React 18. Use createRoot instead.` for the codepen you have provided? Can you share a screenshot please?

**Comment by awxiaoxian2020** [comment]
> I'm not getting `ReactDOM.render is no longer supported in React 18. Use createRoot instead.` for the codepen you have provided? Can you share a screenshot please?

I use it in "Local Development Environment" , following the tutourial. It shows in the browser console. I'm busy now.  I'll give a screenshot later.

However, I think we shouldn't use the "React.render" as it said. it could not depend on where it repeats.

**Comment by awxiaoxian2020** [comment]
Hi, you can see, when I use the js file, it warns in the browser console.

![react](https://user-images.githubusercontent.com/69554233/162733791-dcf5b43e-533e-4cdc-8d64-464f6765070c.png)

I have given the original source file in [my repo](https://github.com/awxiaoxian2020/react-issue). @harish-sethuraman

**Comment by harish-sethuraman** [comment]
Did you use Create react app for local development? If so we might want to fix this cra’s repo for it to use newer syntax.

**Comment by harish-sethuraman** [comment]
Got it thanks for clarifying.  
cc: @gaearon we might want to either include updated codepen or add the code snippet in the docs itself instead of using a codepen link.

**Comment by capncrockett** [comment]
I am having similar issues. I setup the session with 
```npx create-react-app my-app
cd my-app
npm start```

When using the tutorial snippets they don't work. They also don't match the CodePen examples, which do in fact work. 

I might be missing something as I'm new to React and JS for that matter. Are there any specific instructions for setting up a local environment for the step-by-step tutorial? I believe there was for the tic-tac-toe one.

**Comment by awxiaoxian2020** [comment]
> I am having similar issues. I setup the session with
> 
> ```
> npx create-react-app my-app
> cd my-app
> npm start
> ```
> 
> When using the tutorial snippets they don't work. They also don't match the CodePen examples, which do in fact work.
> 
> I might be missing something as I'm new to React and JS for that matter. Are there any specific instructions for setting up a local environment for the step-by-step tutorial? I believe there was for the tic-tac-toe one. Thanks.

You can click the "optional" button to get the step-by-step tutorial as the image and replace the default file with the provided codepen code by copy and paste. I think you will get the performance.
![re1](https://user-images.githubusercontent.com/69554233/163656846-8a993df7-951e-4ccb-92b1-e71c32a21870.png)

**Comment by capncrockett** [comment]
Thanks @awxiaoxian2020 
I have done the tic-tac-toe tutorial actually. Are you saying to use that base code and then copy/paste the CodePen code into it? My comment was more focused on the fact that the step-by-step tutorial and the CodePen code do not match.

**Comment by awxiaoxian2020** [comment]
> Thanks @awxiaoxian2020 I have done the tic-tac-toe tutorial actually. Are you saying to use that base code and then copy/paste the CodePen code into it? My comment was more focused on the fact that the step-by-step tutorial and the CodePen code do not match.

It seems to match on my side. Could you use screenshots of code or performance to provide more details? I think you can also submit a new issue.

**Comment by capncrockett** [comment]
If you think I should I'm happy to open a new issue. This one just seemed like the same as mine.

Here's the links I'm referring to. It goes on for a bit like this. As a beginner I got really confused with the rendering portion.

https://codepen.io/gaearon/pen/edyBaE?editors=1010
https://reactjs.org/docs/rendering-elements.html#rendering-an-element-into-the-dom
![Screenshot from 2022-04-20 09-48-16](https://user-images.githubusercontent.com/71466450/164282373-eb3c2d88-8630-441a-8637-9357751bff0c.png)

Let me know if you think I should start a new ticket.

**Comment by gaearon** [comment]
I'm not sure I understand the discussion here. Yes, there is an issue that CodePens need to be updated. I will do this after we get 18.1 out because unfortunately there's another false positive warning in 18 that would fire anyway if we did it now.

**Comment by capncrockett** [comment]
@gaearon Apologies. I guess I wasn't totally sure this was being addressed. Consider me no longer confused. Thanks for the clarification!

**Comment by gaearon** [comment]
Ah your issue is clear, I think there was just confusion down the line. But yeah we'll definitely fix this soon!

**Comment by awxiaoxian2020** [comment]
> If you think I should I'm happy to open a new issue. This one just seemed like the same as mine.
> 
> Here's the links I'm referring to. It goes on for a bit like this. As a beginner I got really confused with the rendering portion.
> 
> https://codepen.io/gaearon/pen/edyBaE?editors=1010
> https://reactjs.org/docs/rendering-elements.html#rendering-an-element-into-the-dom
> ![Screenshot from 2022-04-20 09-48-16](https://user-images.githubusercontent.com/71466450/164282373-eb3c2d88-8630-441a-8637-9357751bff0c.png)
> 
> Let me know if you think I should start a new ticket.

It seems that you have a wrong link, I'm busy now, I will give more details later.But I think you should check this link first.
[correct link here](https://codepen.io/gaearon/pen/oWWQNa?editors=0010)

**Comment by awxiaoxian2020** [comment]
> @awxiaoxian2020 I see where the confusion is. You're looking at the [tic-tac-toe](https://reactjs.org/tutorial/tutorial.html) tutorial. I'm looking at the [step-by-step](https://reactjs.org/docs/hello-world.html) tutorial.

So the problem have solved?

**Comment by capncrockett** [comment]
Sounds like they're on it, yes. With the next update they will change the CodePen code to match the tutorials.

**Comment by awxiaoxian2020** [comment]
> Sounds like they're on it, yes. With the next update they will change the CodePen code to match the tutorials.

I don't think there are mismatching. The tic-tac-toe tutorial matches the game code and the step-by-step tutorial matches the normal code. What dismatching you said. Could you give more details. In https://github.com/reactjs/reactjs.org/issues/4569#issuecomment-1104175313 I think the two imgs are matching. They are both talk about the code on the basic "hello world", not the tic-tac-toe game.

**Comment by awxiaoxian2020** [comment]
#4630 closes the issue. :)
