### ISSUE TITLE
I can feel some abnormality in Rendering List Section

### ISSUE THREAD

**Issue by stymsaw** [reactjs/reactjs.org#4586]
https://beta.reactjs.org/learn#rendering-lists

There's some **weird behavior in scrolling** in the **Rendering List** section.

**Comment by awxiaoxian2020** [comment]
It repeated.

**Comment by harish-sethuraman** [comment]
Would you like to look into the issue?

**Comment by nigiiro-taro** [comment]
What exactly do you mean by weird behavior?
Scrolling but no response?

**Comment by awxiaoxian2020** [comment]
> What exactly do you mean by weird behavior? Scrolling but no response?

![issue](https://user-images.githubusercontent.com/69554233/164189052-b171dace-c383-4cf4-9327-e2212e3766a0.gif)

like this.

**Comment by awxiaoxian2020** [comment]
?I test all cases. They have the same behavior in other anchor links. Is it normal?

**Comment by stymsaw** [comment]
> What exactly do you mean by weird behavior? Scrolling but no response?

when i scroll the screen on that section, the screen automatically get sticks to a position

**Comment by stymsaw** [comment]
https://user-images.githubusercontent.com/85004499/164248375-2b5d2e0d-f6a1-4213-8718-a25e16a0cef7.mp4

**Comment by stymsaw** [comment]
Can u guys see how abruptly the screen goes up upon scrolling in this section?

**Comment by gaearon** [comment]
I'm unable to reproduce. What's your system/browser/etc? Thanks!

**Comment by stymsaw** [comment]
> 

windows 11 / chrome

can u see the problem in the video?

I'm not sure, maybe it's only happening with my system.

**Comment by nigiiro-taro** [comment]
hmm, I'm unable to reproduce too.
(Mac M1, chrome)
https://user-images.githubusercontent.com/63572812/164483930-86da0ef1-3b69-482d-9495-a3f58c40b77b.mov

**Comment by yadunandanbhat** [comment]
unable to reproduce! might be some browser issue???

**Comment by stymsaw** [comment]
If none Of you can't reproduce the problem then I guess this problem is only specific to my machine only.
