### ISSUE TITLE
Tutorial "Tic-Tac-Toe" allows move editing while viewing history

### ISSUE THREAD

**Issue by fullreboot** [reactjs/reactjs.org#4603]
Currently the official tutorial allows you to overwrite a game's move while viewing the historical moves of a tic-tac-toe game. There's a simple fix that can be included to disallow 'editing' of moves while viewing a game's history.

I intended to edit the readme with the fixes, however it will also need to include new codepen changes/links.

For the last part of the tutorial you can edit the if statement in the `handleClick` method of the `Game` class like so. This will stop anyone from changing historical game edits.

```js
this.state.stepNumber != this.state.history.length -1
```

```js
handleClick(i){
      const history = this.state.history.slice(0, this.state.stepNumber + 1);
      const current = history[history.length - 1];
      const squares = current.squares.slice();

      if(this.state.stepNumber != this.state.history.length -1 || calculateWinner(squares) || squares[i]){
        return;
      }
      squares[i] = this.state.xIsNext ? 'X' : 'O';
      this.setState({
        xIsNext: !this.state.xIsNext,
        history: history.concat([{
          squares: squares,
        }]),
        stepNumber: history.length
      });
    }
```

**Comment by fullreboot** [comment]
Created a pull request with tutorial.md edits here:

https://github.com/reactjs/reactjs.org/pull/4604

**Comment by smikitky** [comment]
I believe the current behavior is intentional. See my comment [here](https://github.com/reactjs/reactjs.org/pull/4605#issuecomment-1110907722).

**Comment by fullreboot** [comment]
I commented on the pull request as well but it appears I missed the last paragraph. It seems this functionality was intentional after all
