### ISSUE TITLE
The "Support Ukraine 🇺🇦" banner should disappear when scrolling

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [reactjs/reactjs.org#4619]
# The point of this banner
The reason the banner exists is to help people notify that there is a way to help Ukraine people.
However, making them permanent is not helping as it can intefere with the reading.

# The problem
1. Scrolling through contents is very hard to do because of the banner
2. Reading the contents are harder as the banner takes up to 10% to 50% of the existing mobile page
3. If people first look at the banner, they will either help or not help and they won't be likely to change their mind as they scroll through the contents. 

# How to fix
I believe it is right to make the banner disappear when scrolling through contents like [React Native Website](https://reactnative.dev). Comparing two websites, the website looks much better without the banner when scrolling.

# Clarification
I am not stating that the banner should be removed, only suggesting it should disappear when scrolled.
It is much more better to learn when the banner is not present every time in computers. phones, and ipads.

# Screenshots comparison
![react](https://user-images.githubusercontent.com/78584173/166144378-ea336606-1c78-41f6-8875-bed9d8f9b652.png)
![reactfixed](https://user-images.githubusercontent.com/78584173/166144415-51c9a773-2e15-4cd6-bdf0-30d73d0adcfd.png)

**Comment by nurbashanghai** [comment]
I would like to work on this issue, let me raise a PR

**Comment by HyunseungLee-Travis** [comment]
> I would like to work on this issue, let me raise a PR 

If you do, please mention it in this issue.

**Comment by nurbashanghai** [comment]
yes, im currently working on it, will raise pr later today

**Comment by nurbashanghai** [comment]
https://github.com/reactjs/reactjs.org/pull/4713 this is my pull request

**Comment by HyunseungLee-Travis** [comment]
Works perfectly.

**Comment by Rayanysilva12777** [comment]
![Uploading SAVE_20220529_155236.jpg…]()

**Comment by Rayanysilva12777** [comment]
Eu

**Comment by Rayanysilva12777** [comment]
Quero ver meus arquivos messa foto

**Comment by HyunseungLee-Travis** [comment]
Please upload the picture again and use english, please for the majority.

**Comment by Rayanysilva12777** [comment]
I need to see . behold I need to see my files for this photo

**Comment by aniket1010** [comment]
is someone working on this issue?

**Comment by harish-sethuraman** [comment]
Yes there are already two PRs for this issue.

**Comment by harish-sethuraman** [comment]
closed by https://github.com/reactjs/reactjs.org/pull/5002
