### ISSUE TITLE
 React Site for Koreans

### ISSUE THREAD

**Issue by wayne-kim** [reactjs/reactjs.org#466]
Hi, I am Wayne Kim and a ordinary college student in Korea.

I want to create a React site for Koreans.

I will fork this project and then translate all docs into Korean.

I would appreciate making this fork easier to access.
https://github.com/wayne-kim/reactjs.org

or
I would appreciate it if you could create a space for this project.

**Comment by gaearon** [comment]
Please don’t fork. We’ve already set up a translation project. Ping @eriknakagawa and ask for contribution permissions:

https://github.com/facebook/react/issues/8063#issuecomment-324976057

Thanks!
