### ISSUE TITLE
Accordion component doesn't work properly in left navigation pane

### ISSUE THREAD

**Issue by prakhargupta1** [reactjs/reactjs.org#4670]
I am reading the docs on laptop and once the Accordion is expanded, then on clicking the down arrow icon it doesn't collapse back.

<img width="536" alt="Screenshot 2022-05-22 at 1 26 36 AM" src="https://user-images.githubusercontent.com/92228082/169667145-78fde99e-3b8f-470a-a8c8-772a2e628e6e.png">
.

**Comment by harish-sethuraman** [comment]
This is an expected behaviour it is not collapsible.
