### ISSUE TITLE
Is there a problem in add-react-to-a-website.md?

### ISSUE THREAD

**Issue by awxiaoxian2020** [reactjs/reactjs.org#4684]
It seems that there is context only for react17 not supported react18.
See the issue https://github.com/reactjs/zh-hans.reactjs.org/pull/835 and https://github.com/reactjs/zh-hans.reactjs.org/pull/810

> But in the tutorial, the link of cdn is react 17, and in the archive file, it is also react 17, is there someone who forgot to update these things
> 
> _Originally posted by @JINZhao2000 in https://github.com/reactjs/zh-hans.reactjs.org/pull/810#discussion_r867502563_

I'm a beginner and I'm not checking what happened in the `createRoot()` usage for this tutorial.

I only think the issue should be solved here.

**Comment by gaearon** [comment]
See https://github.com/reactjs/zh-hans.reactjs.org/pull/810#issuecomment-1136288335.
