### ISSUE TITLE
[Beta] eslint plugin causes Sandpack to re-render once a second

### ISSUE THREAD

**Issue by justjake** [reactjs/reactjs.org#4686]
While working on autocompletion and hover tooltips for the Sandpack editor component `<CustomPreset>`, I noticed the editor re-renders about once a second. The immediate cause is that the linter in `useSandpackLint` is called repeatedly, and that calls `setState(newLintResults)`, which triggers the React render. Vanilla Sandpack components don't exhibit the same non-stop linting behavior.

Commenting out `setLintErrors` in `useSandpackLint` stops the re-rendering, *and* stops the repeated calls to the linter function.

Video below showing the re-render issue in the production build:

https://user-images.githubusercontent.com/296279/170279821-c4680d69-e67b-4f48-923c-aa4351830d0a.mp4

I think this is a cycle, where mounting SandpackCodeEditor triggers an initial lint, which then sets state and does another re-render, triggering another lint, etc. I wrapped the inner `<SandpackCodeEditor>` in a `React.memo` component which avoids some jank in the editor interior, but doesn't stop the re-rendering:

```typescript
const MemoCodeEditor = React.memo(
  React.forwardRef<CodeEditorRef, CodeEditorProps>((props, ref) => {
    const {extensions, ...rest} = props;

    // Conspire to re-mount SandpackCodeEditor if extensions change.
    // Allows lazy-loading extensions.
    // Content changes are preserved, selection state/caret position is not.
    const keyRef = React.useRef(0);
    const prevExtensions = React.useRef(extensions);
    if (prevExtensions.current !== extensions) {
      keyRef.current++;
    }
    prevExtensions.current = extensions;

    // Only called once.
    console.log('MemoCodeEditor', keyRef.current, extensions);

    return (
      <SandpackCodeEditor
        ref={ref}
        key={keyRef.current}
        {...rest}
        extensions={extensions}
      />
    );
  })
);

MemoCodeEditor.displayName = 'MemoCodeEditor';
```

Perhaps one of the other Sandpack components needs to be `React.memo`?

**Comment by gaearon** [comment]
cc @danilowoz I think the extensions are being "reapplied" even if nothing changed, leading to this

**Comment by gaearon** [comment]
Concretely, `extensionsMap` is inline by default:
https://github.com/codesandbox/sandpack/blob/6507288cdc0c79d666274bea8200cd0683e46b4b/sandpack-react/src/components/CodeEditor/CodeMirror.tsx#L113

So it always triggers the effect.

I think ideally you'd remove the dependencies and instead explicitly diff the array with a ref to make sure it only triggers when there's actual change in the list.
