### ISSUE TITLE
[Beta] the site just hangs when I put alert() in code editor

### ISSUE THREAD

**Issue by kashsbd** [reactjs/reactjs.org#4692]
when I was solving the challenges in the beta site, the site hangs if I put alert() in the code editor.

<img width="1022" alt="Screenshot 2022-05-26 at 12 34 36 PM" src="https://user-images.githubusercontent.com/10044283/170433029-ae470d5d-e563-421b-b24c-fa771570c89e.png">

**Comment by gaearon** [comment]
you need to press "OK" in the alert, right? this is how alert works.
