### ISSUE TITLE
[Beta] Learn > Queueing a Series of State Updates > "Challenge 1 of 2: Fix a request counter" Code Fails

### ISSUE THREAD

**Issue by AlecSchneider** [reactjs/reactjs.org#4704]
Code for Challenge 1 of 2: Fix a request counter on bottom of [Learn > Queueing a Series of State Updates ](https://beta.reactjs.org/learn/queueing-a-series-of-state-updates) fails (even solution code) when button is clicked.

Error:
```
Runtime Exception
App.js: regeneratorRuntime is not defined (3:41)

  1 | import { useState } from 'react';
  2 | 
> 3 | export default function RequestTracker() {
                                               ^
  4 |   const [pending, setPending] = useState(0);
  5 |   const [completed, setCompleted] = useState(0);
  6 | 
  ```
  

  Looks to be around the async button onClick event handler
![Screen Shot 2022-05-27 at 5 53 34 PM](https://user-images.githubusercontent.com/6561589/170793837-651b336a-2a57-4f75-835b-133609756666.png)

This is on Chrome with uBlock Origin running

**Comment by harish-sethuraman** [comment]
I hope this should be fixed now. Please re open if this is still occurring. Thanks
