### ISSUE TITLE
Why am I getting the following error message?

### ISSUE THREAD

**Issue by jsteave** [reactjs/reactjs.org#4729]
Why am I getting the following error message and what does it mean?

Plugin "react" was conflicted between "package.json » eslint-config-react-app » C:\alura\front-end\react\parte1-fundamentosdereact\alura-studies\node_modules\eslint-config-react-app\base .js" and "BaseConfig » C:\Alura\Front-end\React\Parte1-FundamentosDeReact\alura-studies\node_modules\eslint-config-react-app\base.js".

**Comment by gaearon** [comment]
Because one path says `Front-end` and another says `front-end`. Use all lowercase for folders (and when using them in terminal) to avoid issues like this.

**Comment by jsteave** [comment]
@[gaearon](https://ittutoria.net/error-plugin-react-was-conflicted-between-package-json-eslint-config-react-app/) thank you for your response

**Comment by gaearon** [comment]
No prob! Just for reference, the error isn't coming from React itself but from some tooling you use. Possibly ESLint.
