### ISSUE TITLE
Proposal to change the download icon in the sandbox UI

### ISSUE THREAD

**Issue by siva-kannan3** [reactjs/reactjs.org#4735]
In the sandbox UI, the download button has an icon which is usually preferred for a dropdown, so I am proposing to put a valid download icon in place of that.

Present UI:
--
<img width="245" alt="image" src="https://user-images.githubusercontent.com/60533560/173178655-55e629fa-59cd-4dec-af92-8c11366ab88c.png">

The proposed download icon should be similar to this:
--
<img width="48" alt="image" src="https://user-images.githubusercontent.com/60533560/173178605-ae47a95a-c08a-4174-8738-b9dc03ab9ccd.png">

**Comment by harish-sethuraman** [comment]
Yea I agree as well. May be @gaearon can we get a different icon for download?

**Comment by gaearon** [comment]
cc @lebo any thoughts?

**Comment by lebo** [comment]
yeah, I agree. I can take this on next week.
