### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by yousefelgoharyx** [reactjs/reactjs.org#4737]
I'm working on making the beta version of react multi-directional to facilitate translating the docs to Arabic and other languages that use RTL layout
My question is how the translation process works to start on translating the Arabic version right after I do a pull request for multi-directional layouts

**Comment by gaearon** [comment]
Thanks! Please see https://github.com/reactjs/reactjs.org/issues/4135 for the discussion on translating new docs.
