### ISSUE TITLE
[React Beta Docs] SandpackConsole stops updating after switching files

### ISSUE THREAD

**Issue by JohnDaly** [reactjs/reactjs.org#4768]
I noticed this behavior when playing with the second Challenge of the "You Might Not Need an Effect" post.

The `SandpackConsole` component will update as you toggle the "Show only active todos" control. It will stop updating if you view the `todos.js` file in the viewer however.

Video showing the issue:

https://user-images.githubusercontent.com/1719443/175179998-6f3c5484-27d2-4bf1-b887-5c562a9fe515.mov

There doesn't appear to be a way to recover it, other than refreshing the page.

**Comment by gaearon** [comment]
Wanna look into it? Could be either our bug or something on the Sandpack side.

**Comment by JohnDaly** [comment]
I think this is a bug in Sandpack, but I'll explain what I've found here.

The [`listen` function](https://github.com/codesandbox/sandpack/blob/62b9bb1585008fd65a97cc5707be4955ae4c6737/sandpack-react/src/contexts/sandpackContext.tsx#L516) from `useSandpack` can take in a `clientId` string as an argument. If a Sandpack client has been initialized when `listen` is called, then the listener function gets attached to that client.

In the other cases (e.g. there is no client present, or if a `clientId` is not provided), the listeners are added to 2 different queues: `queuedListeners` and `unsubscribeQueuedListeners`.

If the unsubscribe function of a listener without a `clientId` is called, it will [cause all of the listeners in `unsubscribeQueuedListeners` to be cleared](https://github.com/codesandbox/sandpack/blob/62b9bb1585008fd65a97cc5707be4955ae4c6737/sandpack-react/src/contexts/sandpackContext.tsx#L568).

The problem I'm seeing, appears to occur when [this `unsubscribe` function](https://github.com/codesandbox/sandpack/blob/62b9bb1585008fd65a97cc5707be4955ae4c6737/sandpack-react/src/components/CodeEditor/CodeMirror.tsx#L409
) runs. It causes all listeners in the `unsubscribeQueuedListeners` queue to unsubscribe, because there was no `clientId` given.

I'm not sure if something can be done in the `reactjs.org` repo. I do think that the Sandpack code should be updated to always include a `clientId` for its internal listeners, to prevent bugs like this.

It looks like the `Preview` component in `Sandpack` [uses a random ID as a clientId](https://github.com/codesandbox/sandpack/blob/62b9bb1585008fd65a97cc5707be4955ae4c6737/sandpack-react/src/components/Preview/index.tsx#L133), so perhaps a similar approach is needed for `CodeMirror`?

@danilowoz What do you think the right approach should be here?

**Comment by danilowoz** [comment]
Fixed on #4778, so this issue can be closed
