### ISSUE TITLE
What is the right way to lift states(multiple states) up?

### ISSUE THREAD

**Issue by sadeghhosseini** [reactjs/reactjs.org#482]
I read the "Lifting State Up" chapter of the docs. I have multiple states in one component which need to be shared with the parent component. Is lifting state up by passing a changeHandlerStateName method(a changeHandler method defined for each state separately) as prop to child(Like what is done in "lifting state up" chapter of reactjs's docs) a right way to achieve sharing the states of child with parent?

**Comment by alexkrolick** [comment]
Yes, that's a fine approach! 

BTW in the future you may want to ask these types of questins on StackOverflow or [Reactiflux](https://www.reactiflux.com/), there are a lot of people there willing to help with specific use cases.
