### ISSUE TITLE
Tutorial about constructing react component not aligned with the recommended way

### ISSUE THREAD

**Issue by drewyh999** [reactjs/reactjs.org#4837]
Hi team,

The react tutorial on your website mainly tells people like me to build react components in the "Class" way instead of the recommended function component way which sometimes brings trouble to React newcomers like me since I've been creating react components classes. Still, once I decided to add libraries like the react-router v6 and other latest stuff, they all presumed that I was coding the project using the functional component way and it takes a long time and change all of my code. I suggest this could be an issue?

Best 

Dominique

**Comment by harish-sethuraman** [comment]
You might want to have a look at beta.reactjs.org site . The new site is written with functional components.
