### ISSUE TITLE
Accessibility add link name

### ISSUE THREAD

**Issue by Arhell** [reactjs/reactjs.org#4855]
https://reactjs.org/tutorial/tutorial.html
![Screenshot_1](https://user-images.githubusercontent.com/26163841/182031220-9fb51b60-bbd3-4974-aa15-d44075c52b00.png)

**Comment by eps1lon** [comment]
That link is excluded from the accessibility tree via `aria-hidden`. We don't need a name in those cases as far as I know.

If there is an a11y issue could you elaborate what concrete issue users would encounter?

**Comment by Arhell** [comment]
> That link is excluded from the accessibility tree via `aria-hidden`. We don't need a name in those cases as far as I know.
> 
> If there is an a11y issue could you elaborate what concrete issue users would encounter?

As written in the application

An accessible name is a word or phrase coded in a way that assistive technologies can associate it with a specific user interface object. Assistive technologies can then refer to the object by name, not just by type. When a link doesn’t have an accessible name, people who use assistive technologies have no way of knowing its purpose.

i fixed it here https://github.com/reactjs/reactjs.org/pull/4856

before
![Screenshot_1](https://user-images.githubusercontent.com/26163841/182253873-de0713e0-c629-4861-920a-cea49279d907.png)

after fix
![Screenshot_2](https://user-images.githubusercontent.com/26163841/182254056-8600fa52-c523-46a1-8f40-5e60b299479d.png)

**Comment by eps1lon** [comment]
> When a link doesn’t have an accessible name, people who use assistive technologies have no way of knowing its purpose.

The referenced link is not part of the accessibility tree at the moment. Giving it a name has no effect on assistive technology. 

Could you show what issues real users of assistive technology are experiencing without using 3rd party tools? These can have false-positive failures which seems like it's the case here. Or at least explain what specific tool you're using.

**Comment by Arhell** [comment]
> > When a link doesn’t have an accessible name, people who use assistive technologies have no way of knowing its purpose.
> 
> The referenced link is not part of the accessibility tree at the moment. Giving it a name has no effect on assistive technology.
> 
> Could you show what issues real users of assistive technology are experiencing without using 3rd party tools? These can have false-positive failures which seems like it's the case here. Or at least explain what specific tool you're using.

I use Accessibility Insights for Web
Unfortunately, I can't test it any other way.
