### ISSUE TITLE
Spelling error in beta documentation

### ISSUE THREAD

**Issue by KoninMikhail** [reactjs/reactjs.org#4895]
on page: https://beta.reactjs.org/learn/keeping-components-pure#where-you-can-cause-side-effects

at text: When you need to “change things,” you’ll usually want to do it in an event handler. 

Please change comma position.

**Comment by harish-sethuraman** [comment]
Would you like to send a PR?

**Comment by KoninMikhail** [comment]
sorry, I didn't understand the acronym PR

**Comment by KoninMikhail** [comment]
> Would you like to send a PR?

Im dont find file for PR ) this was my first action before creating the issue

**Comment by KoninMikhail** [comment]
> Would you like to send a PR?

created
