### ISSUE TITLE
The 'const [title, setTitle] = useState('');' at the beginning of the TravelPlan component is redundant

### ISSUE THREAD

**Issue by CassieRan** [reactjs/reactjs.org#4896]
**Challenge 2 of 4: Fix a broken packing list** at the [choosing-the-state-structure](https://beta.reactjs.org/learn/choosing-the-state-structure#challenges) page, the `const [title, setTitle] = useState('');` at the beginning of the TravelPlan component is redundant

**Comment by harish-sethuraman** [comment]
Would you like to send a PR to remove it?

**Comment by CassieRan** [comment]
@harish-sethuraman done
