### ISSUE TITLE
Switch ES version type in react docs

### ISSUE THREAD

**Issue by mewc** [reactjs/reactjs.org#4907]
![Screen Shot 2022-08-17 at 11 16 55 am](https://user-images.githubusercontent.com/15105417/185013370-aade1f60-4cf9-4a60-b456-2098346d98de.png)

let us switch the ES version type

```
export default function App() {
  return <h1>Hello, world!</h1>;
}
```

then ES6
```
const App = () => (return <h1>Hello, world!</h1>)
export default  App;
```

https://beta.reactjs.org/apis/render

**Comment by eps1lon** [comment]
Since these are all subjective nits that don't seem to alter or clarify the original meaning, I'm going to close. But thanks for your suggestions.
