### ISSUE TITLE
"Chosing the State Structure" red dot example growing infinite

### ISSUE THREAD

**Issue by Cova14** [reactjs/reactjs.org#4956]
The red dot cursor example (Group related state) on the "Choosing the State Structure" section can grow the white container infinitely.

Steps to reproduce: 
- Go to: https://beta.reactjs.org/learn
- Click on "Managing State" -> "Choosing the State Structure" on the sidebar
- Scroll down to the "Group related state" example (red dot example)
- Place your cursor at the bottom of the white section, move it up, and at the bottom again

You can make that section grow as much as you want by repeating the last step

See attached example

Uploading Grabación de pantalla 2022-09-01 a la(s) 13.01.08.mov…

**Comment by gaearon** [comment]
Yeah, I've seen this. Doesn't seem like there's any harm to it.
