### ISSUE TITLE
Add link to beta docs

### ISSUE THREAD

**Issue by k4a-l** [reactjs/reactjs.org#4962]
The Beta docs  is very useful and should be linked from the main site, even if it is in progress now.
Similar comments: https://github.com/reactjs/reactjs.org/issues/3308#issuecomment-1125199765_

I have implemented this experimentally in a forked repository.
- [repository](https://github.com/k4a-dev/reactjs.org/tree/feature-add-beta-link)
- [hosting](https://reactjs-84etzl2ue-k4a-dev.vercel.app/docs/getting-started.html)

---

![](https://i.imgur.com/x9SWRsf.png)

1. adding a link in the header section in parallel with the existing link
2. inserted at the top of Markdown

1 is natural, but it is not so obvious that some people may not notice it.
2 is easy to see, but may be obtrusive since it is inserted on all pages as well. 2 is inserted as a component, but it may be better to just put it in Getting Started markdown.

Anyway, I would like to put the link in any way I can.
If you have any good ideas on where to add it, wording, etc., please make suggestions.

**Comment by gaearon** [comment]
we plan to add a link soon

**Comment by k4a-dev** [comment]
@gaearon 
Oh, that would be great!
I'll leave this issue for now.
