### ISSUE TITLE
Include a link from 16 blog post to 15.5

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#50]
16 blog post doesn't mention how to run codemods. By now many people forgot.

We should either mention it, or link to the 15.5 post that mentions it.

**Comment by gaearon** [comment]
It's worth calling out again in **Upgrading** section.

**Comment by jxom** [comment]
Agreed!

**Comment by xjlim** [comment]
I will work on this.

**Comment by bvaughn** [comment]
@xjlim Looks like a PR #52 has already been submitted for this.

Maybe check out some of our other ["good first issues"](https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that don't have an "in progress" label yet?

**Comment by bvaughn** [comment]
Resolved via #52
