### ISSUE TITLE
Incorrect path on How to Contribute page

### ISSUE THREAD

**Issue by iansu** [reactjs/reactjs.org#508]
In the "Development Workflow" section of the "How to Contribute" page the instructions for using `yarn link` refer to the wrong path. The instructions say to navigate to `~/path_to_your_react_clone/build/packages/react` but there is no `packages` directory inside of `build`. I believe this should be `node_modules` instead.

Happy to submit a PR if this is actually an error.

**Comment by gaearon** [comment]
Please do, we indeed renamed it.
