### ISSUE TITLE
Is it necessary to call `unmountComponentAtNode` if the component's container is removed?

### ISSUE THREAD

**Issue by wearhere** [reactjs/reactjs.org#509]
The React-Backbone integration guide [says](https://reactjs.org/docs/integrating-with-other-libraries.html#embedding-react-in-a-backbone-view)

> It is important that we also call `ReactDOM.unmountComponentAtNode()` in the remove method so that React unregisters event handlers and other resources associated with the component tree when it is detached.
>
> When a component is removed from within a React tree, the cleanup is performed automatically, but because we are removing the entire tree by hand, we must call it this method.

However, back in September I got [conflicting information](https://stackoverflow.com/a/46551232/495611) from the [#react-internals](https://discordapp.com/channels/102860784329052160/148818842779385856) Discord channel: 

> the objects are cleaned up automatically, but you might want to remove any event listeners that you create that aren't linked to React objects

And the React-Backbone example in the integration guide does not show any such event listeners—it's pretty much exactly the same as the example I presented to #react-internals.

Can you clarify whether `unmountComponentAtNode` must be called before removing the component's container, or no?

**Comment by gaearon** [comment]
Please see my answer: https://stackoverflow.com/a/48198011/458193

**Comment by wearhere** [comment]
Thanks for the speedy response @gaearon !
