### ISSUE TITLE
[Beta] DocSearch Title Gets Escaped

### ISSUE THREAD

**Issue by Huxpro** [reactjs/reactjs.org#5116]
<img width="360" alt="Screen Shot 2022-09-25 at 5 21 52 PM" src="https://user-images.githubusercontent.com/5563315/192166170-dc41d212-8797-4abf-adbd-ea4819d1d372.png">

`Fragment (<>...</>)` became `Fragment (&lt;&gt;...&lt;/&gt;)`

**Comment by albertkol** [comment]
Anyone working on this already or may I give it a shot?

**Comment by harish-sethuraman** [comment]
Feel free to send PR

**Comment by albertkol** [comment]
I wish I had a more elegant solution for this. But I could not get DocSearch to not escape the title.

**Comment by azotamiota** [comment]
Has this been resolved? I may give a try if it isn't perfect still.

**Comment by arafatiqbal** [comment]
Has this been taken care of with the above PR? Or can I give it a try?

**Comment by VishalHaswani** [comment]
This issue seems to **have been fixed**.
Not sure which commit is responsible for the fix.

Here's a screenshot of the current state:
![image](https://user-images.githubusercontent.com/53693352/210877841-cda9ea3a-6796-44f2-9c08-98e8260c4247.png)

**Comment by gaearon** [comment]
maybe Algolia fixed this?

**Comment by harish-sethuraman** [comment]
Yes I remember someone from algolia posting it in a PR asking the person to send a fox to their repo instead of ours.
