### ISSUE TITLE
Caveat when passing an instance method as render prop.

### ISSUE THREAD

**Issue by dtinth** [reactjs/reactjs.org#514]
https://github.com/reactjs/reactjs.org/blob/6efa02d16c265881edc6eb2df1ca15951806a615/content/docs/render-props.md#L302-L331

@mjackson 

There is an important caveat here:

If `renderTheCat` uses `this.props` or `this.state`, when a new prop is received or state changes, the `Mouse` component will not be re-rendered.

Here is an example:

```js
class Mouse extends React.PureComponent {
  // Same implementation as above...
}

class MouseTracker extends React.Component {
  constructor(props) {
    super(props);
    this.renderTheCat = this.renderTheCat.bind(this);
    this.state = { name: getRandomCatName() };
  }
  renderTheCat (mouse) {
    return <Cat name={this.state.name} mouse={mouse} />;
  }
  render() {
    return (
      <div>
        <h1>Move the mouse around!</h1>
        <Mouse render={this.renderTheCat} />
        <button onClick={() => this.setState({ name: getRandomCatName() })}>
          Change cat name
        </button>
      </div>
    );
  }
}
```

Here’s a [CodePen](https://codepen.io/dtinth/pen/goKLMz) for testing.

When you click the “Change cat name” button, the `Cat` will not receive a new `name` until you move the mouse again.

The reason is that `Mouse`, being a `PureComponent`, requires that all props passed to it to be immutable to function correctly. This means **all functions passed to should be pure** (not depending on any mutable state).

Since `renderTheCat()` depends on `this` (the `MouseTracker` instance), and a `MouseTracker` instance is stateful (`this.props` and `this.state` can change over time), this essentially makes the `renderTheCat()` function **impure.**

## Recommendation

> To get around this problem, you can **sometimes** define the prop as an instance method, like so:

In the docs, I find the word *“sometimes”* to be not helpful. We should be specific when it is okay to create an instance method. As a rule of thumb, **do not pass mutable data to PureComponent.** This means the render prop may not use `this.state` or `this.props`. Otherwise, we need to generate a new function each time a relevant prop/state changed.

> In cases where you cannot bind the instance method ahead of time in the constructor (e.g. because you need to close over the component's props and/or state) **you should extend `React.Component` instead.**

Unfortunately, the `MouseTracker` already extends `React.Component`.

`Mouse` extends `PureComponent` to not cause wasteful re-renders when the state and props are unchanged, so we shouldn’t put the fault on `Mouse` — It’s `MouseTracker` who passed an impure function to `Mouse`, breaking the requirement for `PureComponent`.

The `Mouse` component may even come from a 3rd party library. In this case you cannot make it extend `Component` instead of `PureComponent` without forking it.

A solution that does not cause any wasteful re-renders would be to create another `PureComponent` that takes **only** the relevant data (and may contain only the relevant state, if applicable) and generates a new render prop function every time it gets re-rendered:

```js
class MouseCat extends React.PureComponent {
  render () {
    const renderTheCat = mouse => (
      <Cat name={this.props.name} mouse={mouse} />
    );
    return <Mouse render={renderTheCat} />;
  }
}
```

- Since we create a new `renderTheCat` function each render, `Mouse` will receive a new `render` function each time `MouseCat` gets re-rendered.

    - During the lifetime of that `renderTheCat` function, `this.state` and `this.props` is guaranteed not to change (otherwise the component will re-render and a new `renderTheCat` function gets created, ending the lifetime of the old function). Therefore, we can consider `renderTheCat` function “pure” even though it uses `this.props` or `this.state`.

- Since `MouseCat` is a `PureComponent`, it will only be re-rendered when the relevant props changed.

    - Therefore, a new `renderTheCat` function gets created **only** when `this.props.name` changed, minimizing wasteful function creations.

Here is [a CodePen demonstrating the solution](https://codepen.io/dtinth/pen/XVYNMd). Note that all components are `PureComponent`.

**Comment by mjackson** [comment]
> Unfortunately, the MouseTracker already extends React.Component.

I meant that `Mouse` should just extend `React.Component` instead of `React.PureComponent`, not `MouseTracker`. I'll clarify.

The recommendation that you're making here puts us right back where we started, passing a new function to `<Mouse render>` on each render, and thus triggering a re-render (assuming `Mouse` extends `React.PureComponent`). So I don't believe it's very helpful.

**Comment by dtinth** [comment]
@mjackson 

> The recommendation that you're making here puts us right back where we started, passing a new function to <Mouse render> on each render, and thus triggering a re-render (assuming Mouse extends React.PureComponent). So I don't believe it's very helpful.

“Passing a new function on each render” **is not inherently bad.**

We need to factor in how often the component that passes the render prop gets re-rendered as well. To make my point clear, please let me elaborate:

For the sake of example, let’s assume that:

- A `MouseTracker` allows changing the name of `Cat`.

- A `MouseTracker` **also displays a stopwatch**, which causes it to re-render every 1 second.

- A `Mouse` extends `PureComponent`. Therefore we must pass a `render` prop when the cat name changed. Otherwise, `Mouse` will not re-render with the latest cat name.

- However, if the cat name is not changed, we should not pass a new `render` prop, as will not cause any change in the rendered interface. Passing a new `render` prop in this case is considered inefficient.

**Where we started:**

- (Assumption:) A `MouseTracker` re-renders every 1 second.

- Since `MouseTracker.render` creates a new `renderTheCat` function on every render, `Mouse` receives a new `render` prop and also re-renders every 1 second.

- Result:

    ✅ `Mouse` gets a new function whenever the cat name changed (correct).
    ❌ `Mouse` also gets a new function every 1 second, even if the cat name is unchanged (inefficient).

**With instance methods:**

- Now `Mouse` receives the same function every time.

- Result:

    ❌ `Mouse` does not get a new function when the cat name changed (incorrect behavior).
    ✅ `Mouse` does not have to re-render every 1 second (efficient).

**The recommendation:**

- `MouseTracker` renders a `MouseCat`, passing the `name`.

- MouseCat passes a new `renderTheCat` function to `Mouse` every render. **But this is OK!**

- Here’s why: Since `MouseCat` extends `PureComponent`, **it will not be re-rendered unless the `name` prop changes.**

- Therefore, `Mouse` receives a new function **only** when the cat name changed.

- Result:

    ✅ `Mouse` gets a new function whenever the cat name changed (correct).
    ✅ `Mouse` does not have to re-render every 1 second (efficient).

Conclusion: **Passing a new function on every render is fine,** if we make sure the component passing the render prop does not re-render when unnecessary.

**Comment by ayush000** [comment]
@dtinth @mjackson 
One way to enforce that the render function is always pure would be to pass a functional component instead.

```jsx
const TheCat = ({mouse}) => (
  <Cat mouse={mouse} />
);

class MouseCat extends React.PureComponent {
  render () {
    return <Mouse render={TheCat} />;
  }
}
```

Mouse will pass the required props to TheCat component

This would prevent you from using `MouseCat`'s `this.state` inside `renderTheCat` render method and hence prevent an error prone approach (i.e. where you pass an instance method as render prop and use `this.state` of parent component in that instance method).
