### ISSUE TITLE
Strict mode making newbie like me get confused on debugging.

### ISSUE THREAD

**Issue by Misheelajil** [reactjs/reactjs.org#5155]
https://stackoverflow.com/a/60619061/12658561
I think there should be mention of this on doc so newbies like me who understand things by  following every line of code by debugging 
 wont get confused why things not going way it was written.

**Comment by gaearon** [comment]
I believe in the beta docs this is mentioned many times. Where would you like to see it?

**Comment by Misheelajil** [comment]
Oh it was mentioned in API many times. I have only finished quick start guess I should have made feedback after checking out API as mentioned in Using hooks part. I had troubles understanding hooks in main website documentation with added impression of not finding mention of strict mode after finishing quick start part in this Beta website so I had erroneous impression.  Sorry for making inadequate issue.

**Comment by gaearon** [comment]
We try to keep the Quick Start very focused so I'm not sure it fits well there. If you have thoughts on other Beta docs part where it would be good to emphasize, let me know!
