### ISSUE TITLE
Update react-component.html for React 16.2's improved fragment support

### ISSUE THREAD

**Issue by edmorley** [reactjs/reactjs.org#518]
Hi!

React 16.2.0 [improved support for fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html), and #392 added some documentation in this repo for them.

However I've spotted another reference to fragments that is still using the array syntax - that I think should probably be updated too?
https://reactjs.org/docs/react-component.html#fragments

**Comment by clemmy** [comment]
Yes, documentation updates would be very welcome PRs. In the past, the array syntax was also called fragments, so there's a bit of mismatch in the documentation.
