### ISSUE TITLE
Why the render () function is executed twice in react 18.2

### ISSUE THREAD

**Issue by weishengzel** [reactjs/reactjs.org#5206]
Why the render () function is executed twice in react 18.2

**Comment by Tillytaly** [comment]
It's probably happening because of the strict mode. If you go to your main index.jsx/index.tsx file you'll probably find something like this:

```
const root = ReactDOM.createRoot(
  document.getElementById("root") as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
The strict mode around App component causes the second rerender, however it only happens in development mode.
