### ISSUE TITLE
React CDN link is not stable

### ISSUE THREAD

**Issue by xJkit** [reactjs/reactjs.org#5217]
The CDN link for production-ready, minified version of react 18:

https://unpkg.com/react@18/umd/react.production.min.js

![CleanShot 2022-10-28 at 19 32 21](https://user-images.githubusercontent.com/18704345/198577563-22cd9ff7-79de-4cb6-a19a-7d6e725ae5c3.jpg)

**Comment by diegoquintanauala** [comment]
Hi, we hosted this file in our private storage. (workaround)
This error occurs when the exact version of the package is not specified and only the major version is placed.

💋

**Comment by eps1lon** [comment]
The CDN is provided by unpkg.com not React. Seems like other people are experiencing issues as well. Closing in favor of https://github.com/mjackson/unpkg/issues/343
