### ISSUE TITLE
[Beta] [Bug] Reacting to a input with State : pressing the submit button shows an error

### ISSUE THREAD

**Issue by JeelRajodiya** [reactjs/reactjs.org#5241]
If you look at [this page](https://beta.reactjs.org/learn/reacting-to-input-with-state#step-1-identify-your-components-different-visual-states) when I click the **submit** button it shows the following error `Plugin loader react-refresh/babel not found`

![image](https://user-images.githubusercontent.com/63534268/200030530-af35e010-f487-4f05-8b64-5ee9c3445c11.png)

This error also appears in **Deep Dive Section**  of that page
![image](https://user-images.githubusercontent.com/63534268/200030975-8198aa4c-a9f8-4ae8-b69b-4e7d9d579bce.png)

**Comment by harish-sethuraman** [comment]
@danilowoz I think this is being emitted from sandpack? WDYT
