### ISSUE TITLE
Runtime Error In The Example.

### ISSUE THREAD

**Issue by Pannu786** [reactjs/reactjs.org#5258]
In (ADDING INTERACTIVITY-State: A Component's Memory) _https://beta.reactjs.org/learn/state-a-components-memory_  section example is throwing runtime error after the last page is called which is page 12.   

This error pops up after you click next on page 12.

**Runtime Error
App.js: Cannot read properties of undefined (reading 'name') (18:22)

  15 |         Next
  16 |       </button>
  17 |       <h2>
> 18 |         <i>{sculpture.name} </i> 
                             ^
  19 |         by {sculpture.artist}
  20 |       </h2>
  21 |       <h3>  **

**Comment by harish-sethuraman** [comment]
I hope this clarifies 😅  https://github.com/reactjs/reactjs.org/issues/3308#issuecomment-1038641042
