### ISSUE TITLE
The documentation on "Refs and the DOM" wrong states (in multiple places) that you cannot use refs in a functional components

### ISSUE THREAD

**Issue by sonic1981** [reactjs/reactjs.org#5286]
This isn't true, functional components have the [`useRef` hook](https://reactjs.org/docs/hooks-reference.html#useref)

**Comment by sonic1981** [comment]
I've knocked up a quick MR to address this https://github.com/reactjs/reactjs.org/pull/5285

**Comment by PMudra** [comment]
Please note that documentation page might be obsolete after the beta docs are released. See [Accessing another component’s DOM nodes](https://beta.reactjs.org/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes).

I think the old documentation is not completely untrue: Functional components do not support the `ref` attribute out of the box. We'd have to wrap the functional component inside a `forwardRef` call to enable it.

`useRef` is not needed to make that happen but might be used to store the ref passed to the functional component.

**Comment by eps1lon** [comment]
Documentation is correct considering exact wording. See https://github.com/reactjs/reactjs.org/pull/5285#pullrequestreview-1248154616 for more context
