### ISSUE TITLE
Add direct access links for 'deep dive' parts in Beta (proposal)

### ISSUE THREAD

**Issue by ibarapascal** [reactjs/reactjs.org#5304]
as title

In our Beta documentation, sometimes we found the 'deep dive' parts really helpful, then we want to refer to it and share it with others, but there is no link for that part of the content to access directly.

For example

within https://beta.reactjs.org/learn/reusing-logic-with-custom-hooks

>Keep your custom Hooks focused on concrete high-level use cases

---

<img width="1302" alt="スクリーンショット 2022-11-30 12 48 39" src="https://user-images.githubusercontent.com/30466424/204703207-71762685-dc87-4934-9f18-0544323a4a5b.png">

**Comment by gaearon** [comment]
Yeah. We need to make them all links. It might require a bit of effort but I’m not sure. Would you like to try? It would be very helpful.

**Comment by ibarapascal** [comment]
@gaearon Made a small try on that, and it works, please have a look
