### ISSUE TITLE
[Beta] The description of the comparison of dependencies could be inaccurate

### ISSUE THREAD

**Issue by ibarapascal** [reactjs/reactjs.org#5305]
here: https://beta.reactjs.org/apis/react/useContext#caveats

>Passing something via context only works if `SomeContext` that you use to provide context and `SomeContext` that you use to read it are exactly the same object, as determined by a === comparison

As mentioned above in the docs, we are using [Object.is()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) to compare, and as mentioned inside the link **it's not actually equal with `===`** (or determined by, although in the vast majority it is).

>Object.is() is also not equivalent to the [===](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) operator.

---

Proposal to change to:

>Passing something via context only works if `SomeContext` that you use to provide context and `SomeContext` that you use to read it are exactly the same.

**Comment by ibarapascal** [comment]
not a remarkable point at this moment so I'd just close it now

**Comment by gaearon** [comment]
let's change it to Object.is in the text, as in other places
