### ISSUE TITLE
`useTransition` explanation 

### ISSUE THREAD

**Issue by alexlbr** [reactjs/reactjs.org#5314]
The [Caveats](https://beta-reactjs-org-git-usetransition-fbopensource.vercel.app/apis/react/useTransition#starttransition-caveats) section of `useTransition` says "useTransition is a Hook, so it can only be called outside components or custom Hooks.". I think it should say "useTransition is a Hook, so it can only be called __inside__ components or custom Hooks."

**Comment by girishsontakke** [comment]
@alexlbr I think this issue is closed now.
