### ISSUE TITLE
Searching for "contenteditable" in React Docs Beta yields zero results, while the old React Docs website works just fine.

### ISSUE THREAD

**Issue by meglio** [reactjs/reactjs.org#5317]
When I search for "contenteditable" in the React Docs Beta, zero results are shown:

![image](https://user-images.githubusercontent.com/282177/205525525-0689c782-314c-47a3-88bd-ea26dbde9c5b.png)

The old website is much better:

![image](https://user-images.githubusercontent.com/282177/205525587-04ca4660-8fa9-4aa3-a354-d597a6b194b7.png)

Also, if you ask me, I find the React Docs Beta much less easier to read because:
- the search is worse
- there are no colored secions that ease reading the page (the whole page background is white)
- I can't expand sidebar menu sections wihtout causing the navigation
- the code blocks are barely distinguishable from the text now because you just made all UI elements have very similar white-ish color.

It is a degradation overall.

**Comment by harish-sethuraman** [comment]
Hey Thanks for filing an issue, How ever right now there is no such reference for the word `contenteditable` inside the API reference of new docs. That is why you were not able to see it.

**Comment by meglio** [comment]
By this, do you mean the API reference of new docs is incomplete?

**Comment by gaearon** [comment]
We haven't landed the page with HTML attributes yet. (This will probably be one of the last ones we'll add.)

>By this, do you mean the API reference of new docs is incomplete?

Yes, as mentioned here: https://beta.reactjs.org/#how-much-content-is-ready

>there are no colored secions that ease reading the page (the whole page background is white)
>the code blocks are barely distinguishable from the text now because you just made all UI elements have very similar white-ish color.

It's hard to respond to feedback where you group unrelated things as a single issue. If you have problems with colors, please file a separate issue and show some examples of where you find it difficult to read. The current design of the beta docs has been more or less the same for a year, so to be honest this is a bit late for this kind of feedback. However, we'll be happy to iterate on the visual appearance after the switchover given that the feedback is constructive and you provide some screenshots to illustrate the problems.

>I can't expand sidebar menu sections wihtout causing the navigation

Yeah, people sometimes complain about this. We might redesign the nav at some point now that we finalized the content structure, and we'll take this feedback into account next time we do this.

I'll close this as the main issue here (`contenteditable` stuff) will get fixed once we actually write that page.
