### ISSUE TITLE
Please remove the class component description from the tutorial.

### ISSUE THREAD

**Issue by YusukeSuzuki** [reactjs/reactjs.org#5336]
This is just a request and I am not going to get into a detailed discussion. I am also writing this issue using DeepL because I am not fluent in English, which is one of the reasons why I can't discuss it in detail.

I am new to front end and React is my first real framework to use. I am writing code while reading tutorials.

https://ja.reactjs.org/docs/components-and-props.html

React has a function component and a class component, and I designed my screen using the class component, thinking that the class component would be appropriate since it has a state. However, the more I looked into it, the more I learned that various explanations and libraries are written based on the assumption that only function components are used.

Perhaps I need to rewrite the many class components I have written into function components.

If React is going to support practically only function components, then the tutorial should either remove the class component statement or strongly discourage the use of class components.

**Comment by gaearon** [comment]
The new docs use function components.
https://beta.reactjs.org

We haven’t ported the Tutorial to the new docs yet but we will soon.
