### ISSUE TITLE
Module not found: Error: Package path . is not exported from package

### ISSUE THREAD

**Issue by mikeycrystal** [reactjs/reactjs.org#5377]
Trying to create a login page using firebase. Gives me this error in development. Not sure how to fix it, I suspect it has something to do with the node_modules, but not sure what to alter.

<img width="975" alt="Screenshot 2022-12-17 at 2 26 19 PM" src="https://user-images.githubusercontent.com/108841529/208268174-c0af7708-692f-4322-ac0d-250b1a0a21e0.png">

Repository: https://github.com/mikeycrystal/wride-app

**Comment by shamwela** [comment]
This repository is for the React documentation website. For React issues, please go to https://github.com/facebook/react/issues
Thanks.
