### ISSUE TITLE
Code Editor layout broken for smaller screen sizes

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#54]
Not sure when this happened but it looks like our CSS got a little broken:
![screen-shot-2017-10-07-at-9 22 41-am](https://user-images.githubusercontent.com/29597/31309836-be93dfb6-ab41-11e7-83f2-71ee127a254c.png)

![screen-shot-2017-10-07-at-9 24 49-am](https://user-images.githubusercontent.com/29597/31309837-be96138a-ab41-11e7-89da-446d0fc6b9a4.png)

**Comment by thomasyimgit** [comment]
Can I work on this?

And just want to make sure:

1. the top-right and bottom-right radius are misssing
2. the gap should not appear

Is that right? @bvaughn Thanks for your explanation!

**Comment by bvaughn** [comment]
Hey @thomasyimgit ! Sorry I didn't see this until now but PR #58 was submitted 5 hours ago with a fix. Thanks though! Maybe another issue?

**Comment by thomasyimgit** [comment]
@bvaughn That's alright, I'll see what I can help with others.
