### ISSUE TITLE
beta.reactjs.org "Try out some challenges" code box deleting/adding random words

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [reactjs/reactjs.org#5405]
in beta.reactjs.org's docs, I was testing out some of its challenges and one of them was just to create your own component, but after typing a few words, it deletes them and adds some random letters or deletes the entire code completely... 

https://user-images.githubusercontent.com/83801755/209589196-2718a0d8-4e90-4bc1-b170-1db7b8f7654e.mp4

**Comment by gaearon** [comment]
This looks quite strange! I can't reproduce this. Can you share more info — OS version, browser version? Do you have any extensions?
