### ISSUE TITLE
Typo in Tic-Tac-Toe Tutorial

### ISSUE THREAD

**Issue by moeido** [reactjs/reactjs.org#5412]
<img width="885" alt="Screen Shot 2022-12-26 at 12 12 45 pm" src="https://user-images.githubusercontent.com/14045891/209791654-6355cc9d-b9ab-457a-aa37-83ba89341d45.png">

You have a typo here. This should be handleClick and not handleSquareClick
URL: https://beta.reactjs.org/learn/tutorial-tic-tac-toe

**Comment by aimunhidden485** [comment]
Can I fix this issue?

**Comment by gaearon** [comment]
sure, feel free to send a PR!

**Comment by gaearon** [comment]
I fixed it myself for now, thanks!

**Comment by aimunhidden485** [comment]
@gaearon  okay but I was facing an issue saying fatal: 'reactjs/reactjs.org' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by mwelwankuta** [comment]
looks like you didn't Fork the repository
