### ISSUE TITLE
Missing files in the "challenges" on page: extracting-state-logic-into-a-reducer

### ISSUE THREAD

**Issue by mingamellsIDBS** [reactjs/reactjs.org#5454]
Working through the doc and got to:
https://beta.reactjs.org/learn/extracting-state-logic-into-a-reducer
and about to try the challenges, but the refered to files are not present in neither the challenge nor the solution.

**Comment by gaearon** [comment]
Can you please be more specific — which files are missing? Mind taking a screenshot? Thanks!

**Comment by yousefelgoharyx** [comment]
Maybe he's referring to challenge 4. The file explorer doesn't show `Chat.js` and `ContactList.js`

**Comment by yousefelgoharyx** [comment]
![Screenshot_2023-01-10-03-28-50-485_com.android.chrome.jpg](https://user-images.githubusercontent.com/30435916/211441391-b8b49e43-e219-4479-bd46-2a94b1b64ae9.jpg)

Here's a screenshot

**Comment by mingamellsIDBS** [comment]
![image](https://user-images.githubusercontent.com/117197715/211528936-4a22fa48-cbc9-4394-8bcb-30262583d3cc.png)
Having seen the screenshot from @yousefelgoharyx, I see this is the first page of the docs so far, and I have been through a lot of them, where the filenames are not listed above the editor box, but are in a (very subtle) dropdown!  My pardon, for missing this, but perhaps indicates a usability defect.

**Comment by gaearon** [comment]
Ah I see. Yeah maybe it could be clearer. We use the dropdown when all the names don't fit.
