### ISSUE TITLE
[beta] Meet the team page's "next page" link should not exist but links to "https://reactjs" instead

### ISSUE THREAD

**Issue by mattcarrollcode** [reactjs/reactjs.org#5476]
### Summary
On the beta docs [meet the team page](https://beta.reactjs.org/learn/meet-the-team) the footer indicates the "next" page in the section is the blog but it actually links to "https://reactjs". You can see the issue in this screenshot where the URL in the bottom left shows that the "blog" link, actually links to "https://reactjs":

![screenshot of issue](https://i.imgur.com/ErumzqI.png)

### Investigation
The DocsPageFooter component that displays the fault link is used by the [MarkdownPage component](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/Layout/MarkdownPage.tsx) which calls the [`useRouteMeta` hook](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/Layout/useRouteMeta.tsx#L58) to get the `nextRoute` prop. The `useRouteMeta` hook uses the `SidebarContext` to get information on the current page and other pages in the same section. The sidebar data for the learn section is in the `sidebarLearn.json` file.

### The root of the problem
The [community route in sidebarLearn.json](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/sidebarLearn.json#L193) has 3 pages but the blog is not in the route list for the community path. [The blog is a separate non-community section without any routes](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/sidebarLearn.json#L208)

This likely means the issues is with the JSON in sidebarLearn.json or the logic of [`getRouteMeta`](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/Layout/useRouteMeta.tsx#L78) that [`useRouterMeta`](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/Layout/useRouteMeta.tsx#L58)  uses to parse the sidebarLearn.json to determine what pages are in what section. It seems like the logic used to create links in the sidebar itself works correctly as seen in this screenshot where the blog can be seen as its own section separate from community:

![blog separate from community section](https://i.imgur.com/ll4lv6L.png)

All of the above points to a bug in the logic of [`getRouteMeta`](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/Layout/useRouteMeta.tsx#L78) that attempts to extract the URL from blog as a "next page" for the "meet the team" page and does so incorrectly leading to a "next page" with a name of "blog" and link of "https://reactjs"

### Recommended fix
Fix [`getRouteMeta`](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/Layout/useRouteMeta.tsx#L78) to account for the JSON structure [at the end of sidebarLearn.json](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/sidebarLearn.json#L208). Alternatively, since this issue does not seem to appear elsewhere (e.g. the [Installation section](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/sidebarLearn.json#L11)) in `sidebarLearn.json` adding [a `routes` attribute of `[]` to the `blog` route object in the `learn` routes](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/sidebarLearn.json#L208), may also solve the issue

**Comment by harish-sethuraman** [comment]
Would you like to send a PR if it solves the issue?

**Comment by girishsontakke** [comment]
Hi, @harish-sethuraman and @mattcarrollcode I think the [removeFromLast](https://github.com/reactjs/reactjs.org/blob/a08caba2f1424d52930cb5af7c7ecbe8081d12c3/beta/src/components/DocsFooter.tsx#L46) function call is causing this issue. If there is no other use case for this function call then we can remove it to fix this issue.

**Comment by shanpriyan** [comment]
> Would you like to send a PR if it solves the issue?

I remember there was an existing PR related to this issue

**Comment by harish-sethuraman** [comment]
I think this is also the same issue https://github.com/reactjs/reactjs.org/issues/5273 and it even has a fix.

**Comment by gaearon** [comment]
fixed in https://github.com/reactjs/reactjs.org/commit/b8dcdf4f4ffd5c7d663488a0ceca6787b806adbc
