### ISSUE TITLE
i have already authorized Vercel to deploy but why is the check still failing?

### ISSUE THREAD

**Issue by KarkiAnmol** [reactjs/reactjs.org#5484]
i have already authorized Vercel to deploy but why is the check still failing?

_Originally posted by @KarkiAnmol in https://github.com/reactjs/reactjs.org/issues/5479#issuecomment-1399243787_

**Comment by yousefelgoharyx** [comment]
I think this issue is irrelevant to this repo

**Comment by harish-sethuraman** [comment]
Only the owners of repo can authorize deployment. Although the users see the authorize button you will not be able to authorize it. https://twitter.com/harishkumar_s_s/status/1592496496150482944?s=20&t=cyafM5Z9OgxgEOwaR7QxOQ.
