### ISSUE TITLE
Sidebar active category not collapsing onClick (toggle) 

### ISSUE THREAD

**Issue by adeldueast** [reactjs/reactjs.org#5488]
Hi, I don't know if this was made on purpose, but collapsing a category in the sidebar (new beta docs) by clicking on the active category doesn't do work. I have to click on an other category for the active category to collapse.

**Comment by gaearon** [comment]
Yeah, that's intentional. We know it's a bit confusing and might revisit in the future, but this is more like a navigation link than a toggle.
