### ISSUE TITLE
[Beta] Text highlighting mismatch in the 'hydrate#usage' section

### ISSUE THREAD

**Issue by vladdoroniuk** [reactjs/reactjs.org#5505]
In [this](https://beta.reactjs.org/reference/react-dom/hydrate#usage) section, shouldn't it be highlighted in the opposite way, so `React component` corresponds to `<App />` and `browser DOM node` corresponds to `document.getElementById('root')`?

![image](https://user-images.githubusercontent.com/69749436/214914550-8d113bb6-6047-4dad-beb4-bc5ef7d1c7a5.png)

**Comment by gaearon** [comment]
thanks
