### ISSUE TITLE
Minor UI Issue in the sidebar -fold/unfold icon on the website not folding back

### ISSUE THREAD

**Issue by dgupta0** [reactjs/reactjs.org#5513]
Hi, 

The topics in the sidebar are not folding back when I press the fold/unfold button in the website.

Following is the screenshot-

<img width="301" alt="Screenshot 2023-01-28 at 1 31 16 PM" src="https://user-images.githubusercontent.com/108337465/215254725-a023297b-4a45-40e7-a7f9-4d1ecd14a077.png">

Thanks,

**Comment by shanpriyan** [comment]
This is the expected behavior, you need to click on the any other section to close this

**Comment by dgupta0** [comment]
Oh, yeah! Thanks :)
