### ISSUE TITLE
error while using import

### ISSUE THREAD

**Issue by jo777750** [reactjs/reactjs.org#5542]
bebel version6.26.0 installed as per react docs :install babel-cli@6 babel-preset-react-app@3
chrome rendering html error:
![error](https://user-images.githubusercontent.com/66462046/216651199-331a5919-d81e-4bda-9594-02f2cb673841.png)

```
{/*test.js*/}
import { useState } from 'react';

const root10 = ReactDOM.createRoot(document.getElementById('Xy'));
const element10 = <Pile />; 
root10.render(element10);

 function Pile() {
  return (
    <img
      src="https://i.imgur.com/QIrZWGIs.jpg"
      alt="Alan L. Hart"
    />
  );
}
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Test Page-React</title>
  </head>
  <body>
<link rel="icon" type="./x-icon" href="./favicon.ico">

<h3>https://beta.reactjs.org/learn/describing-the-ui</h3>
<h4>https://transform.tools/html-to-jsx</h4>  
<h5>https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules</h5>


<div id="Xy"></div>

    <!-- Load  React. -->
    <!-- Note: if deploying, replace "development.js" with "production.min.js". -->
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
  <!-- Load your React component. -->
 <script type="module" src="test.js"></script>

  
  </body>
</html>
```

**Comment by gaearon** [comment]
Like I mentioned in another issue you filed, **you can't expect to use syntax like `import` and `export` in the browser directly like you're trying to do right now.** We use it throughout the docs because in a practical way, most apps using React will put components in different files. But if you want to keep using this syntax, you need to use a bundler.

I agree we need to make this clearer in the docs, but this isn't specific to React — you'll run into this problem with every other library if you try to use `import` and `export` in your code.

**Comment by gaearon** [comment]
What you can do instead is write `React.useState`.

**Comment by jo777750** [comment]
(by the way i havent used bundler before) ..so please send me some links
regarding the bundler aspect you mentioned so that I can try..Thanks

**Comment by jo777750** [comment]
React.useState worked ...thanks a lot ..example below  

```
test.js


const root2 = ReactDOM.createRoot(document.getElementById('buton'));
const element2 = <MyApp />; 
root2.render(element2);

function MyButton() {
	  const [count, setCount] = React.useState(2);

   function handleClick() {
    setCount(count + 3);
  }

  return (
    <button onClick={handleClick}>
      Clicked {count} times
    </button>
  );
}

export default function MyApp() {
  return (
    <div>
      <h1>Welcome to my app777</h1>
      <hr />
      <MyButton />
    </div>
  );
}
```
index.html

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Test Page-React</title>
  </head>
  <body>
<link rel="icon" type="./x-icon" href="./favicon.ico">
<div id="buton"></div>
    
    
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
  
 <script type="module" src="test.js"></script>
</body>
</html>
```

```
