### ISSUE TITLE
[Documentation] Translation

### ISSUE THREAD

**Issue by GuillaumeUnice** [reactjs/reactjs.org#555]
Hi,

Is there a possibility concerning a community translation?
I'll be glad to translate the documentation in French and Italian.

Thanks in advance

**Comment by koba04** [comment]
@GuillaumeUnice Translation project is here.

* https://crowdin.com/project/react

See also:

* https://github.com/reactjs/reactjs.org/issues/82

**Comment by GuillaumeUnice** [comment]
Nice, thanks have a good day ;)
