### ISSUE TITLE
Document update

### ISSUE THREAD

**Issue by 2362605576** [reactjs/reactjs.org#5609]
When will the Chinese document be updated,I want to learn.
'https://beta.reactjs.org/' ,

**Comment by harish-sethuraman** [comment]
Closing as there is already an issue for tracking this https://github.com/reactjs/reactjs.org/issues/4135

**Comment by awxiaoxian2020** [comment]
@2362605576 you can visit https://beta.react.jscn.org for the time being. :)

**Comment by awxiaoxian2020** [comment]
@harish-sethuraman And [the vercel for zh-hans](https://github.com/reactjs/zh-hans.reactjs.org/deployments/activity_log?environment=Production+%E2%80%93+zh-hans.reactjs.org) seems to fail. Could you please have a look? :) (I'm a maintainer but I have no access for it)
