### ISSUE TITLE
Getting error via running repo locally

### ISSUE THREAD

**Issue by jayk-gupta** [reactjs/reactjs.org#5628]
I followed the steps as given in readme file but while running the  **yarn dev** command I got this error.
***
error react-website@0.0.1: The engine "node" is incompatible with this module. Expected version "12.x.x || 14.x.x || 15.x.x || 16.x.x". Got "18.14.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
***

So how do I resolve it and run it locally?

**Comment by harish-sethuraman** [comment]
Your node version seems to be 18 but the project is expecting lesser than that. If you have node version manager. Then you can try nvm use 16 to use node version 16.

**Comment by jayk-gupta** [comment]
I did that now new error:
***
PS G:\React app\reactjs.org> yarn dev
yarn run v1.22.19
$ gatsby develop -H 0.0.0.0
'gatsby' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by harish-sethuraman** [comment]
You have not installed the dependencies. Please follow the instructions in the readme.

**Comment by jayk-gupta** [comment]
okay, will try again.
thanks!
