### ISSUE TITLE
controlled component link

### ISSUE THREAD

**Issue by FannyVieira** [reactjs/reactjs.org#57]
when clicking on the hyperlink of controlled components the page of [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html) redirects to https://reactjs.org/docs/forms.html the correct would not be https://reactjs.org/docs/forms.html#controlled-components?

**Comment by gaearon** [comment]
Seems like the whole article is about controlled components, isn't it?

**Comment by FannyVieira** [comment]
yes, yes, I just thought it would make more sense if I went to the specific section
