### ISSUE TITLE
Update Gatsby to fix iOS Safari freeze when swiping to navigate

### ISSUE THREAD

**Issue by rutzfutz** [reactjs/reactjs.org#589]
Your site is using an old version of Gatsby that is affected by [this issue](https://github.com/gatsbyjs/gatsby/issues/2842) that causes swipe navigations in iOS Safari to freeze the browser for 2-6s.

I implemented a workaround for this iOS Safari bug in the upstream component [scroll-behavior](https://github.com/taion/scroll-behavior/pull/129) and @KyleAMathews updated Gatsby's dependencies to use the updated version.

I suggest that you redeploy your site using the latest Gatsby version to fix this bug.

**Comment by gaearon** [comment]
Do you mind sending a PR with version bump?

**Comment by rutzfutz** [comment]
Hmm, if I read your package.json correctly, a version bump actually shouldn't be necessary as you depend on "gatsby": "^1.9.135". The current Gatsby version is 1.9.181, so it's still within your semver range. You just need to redeploy the site using the latest packages matching your current package.json.

**Comment by gaearon** [comment]
We use yarn. I think the lockfile version is probably earlier.

**Comment by rutzfutz** [comment]
Oh, I see. I'm afraid I won't be able to help you with the version bump then. I just found and fixed the mentioned bug, but I haven't used yarn yet and currently don't have the time to learn a new tool. Sorry!

**Comment by gaearon** [comment]
Either way, thanks for reporting.

**Comment by rutzfutz** [comment]
You're welcome!
