### ISSUE TITLE
Browser screen update on componentDidMount?

### ISSUE THREAD

**Issue by farskid** [reactjs/reactjs.org#595]
The docs indicates that, if you call `setState` in `componentDidMount`, this will trigger a new rendering , but updates the state before the moment browser updates it in screen. So typically this means that we're gonna have two renders, but won't see the intermediate data in the view.

IMO, this should happen when you call `setState` in a synchronous manner. If for instance, you call `setState` in a callback, it shouldn't update before browser screen update.

Should the docs be updated and be more specific on using sync `setState`?

### Sync Update:

```js
componentDidMount() {
  this.setState({
    key: value
  });
}
```

### Async Update:

```js
componentDidUpdate() {
  fetch('some_path_here')
    .then(result => {
      this.setState({ result })
    })
}
```

**Comment by gaearon** [comment]
I don't understand what you're asking. Can you describe what you expected, and what you saw?

**Comment by farskid** [comment]
Docs say:
>If you call setState in componentDidMount, this will trigger a new rendering , but updates the state before the moment browser updates it in screen.

Is that happening for calling setState in a sync way or does it happen no matter how you call setState?

I know that if you directly use setState in componentDidMount, it triggers a new render. but you can't see the intermediate state between these two renders, because React guarantees to put content into the DOM only after the second render has finished.

Is this waiting for second render happening even if I use setState in a callback? after an async process is done? in a setTimeout for example?

**Comment by gaearon** [comment]
>Is this waiting for second render happening even if I use setState in a callback? after an async process is done? in a setTimeout for example?

No, there's no way React could know that you're "waiting" for setState. Even if it could, it would be bad to make UI unresponsive. Show a loading indicator if the data is not ready yet.

In the future we will add a feature that lets you do this more automatically. It's not ready yet though. (Pun unintentional.)

Hope this helps!
