### ISSUE TITLE
[Documentation] - React.Children.map fragments behaviour

### ISSUE THREAD

**Issue by bsalex** [reactjs/reactjs.org#607]
This section of the documentation states:

> If children is a keyed fragment or array it will be traversed: the function will never be passed the container objects.

But actually, a fragment is passed as a child to the function and it is not traversed:

https://jsbin.com/niyajos/edit?html,console

**Comment by athaax** [comment]
There have been a several releases since this issue was raised. Is it on the roadmap to get fixed?

**Comment by wnayes** [comment]
The documentation was changed to match reality just recently (https://github.com/reactjs/reactjs.org/commit/9cd366714197809ebb5356b9cdb46c9417372b25)
