### ISSUE TITLE
Is there a way to disable outside scroll when scrolling in the live editor

### ISSUE THREAD

**Issue by thomasyimgit** [reactjs/reactjs.org#61]
In the Live JSX editor, when you scroll to the bottom of the code and continue scrolling, the whole page actually gets scrolled, which is annoying because right at this time you are focusing on the content of the editor, but the scrolling page may make you lose your concentration and unable to find where you were looking at.

![image](https://user-images.githubusercontent.com/13282699/31312586-f0737412-ab94-11e7-8444-7ff8a3971183.png)

**Comment by bvaughn** [comment]
This is default browser-scrolling behavior. I don't think we should change it. Changing it might make it difficult for smaller screens like phones to scroll past live code snippets. 😄

**Comment by thomasyimgit** [comment]
@bvaughn Hmm, yeah the tradeoff is truly the concern. Thanks for your explanation!

**Comment by bvaughn** [comment]
No problem!
