### ISSUE TITLE
Application for Proofreader for React Localization in Tagalog

### ISSUE THREAD

**Issue by ergiegonzaga** [reactjs/reactjs.org#613]
Hi sir,
Good day, I am asking for your permission to allow me to be a proofreader of the translation in Tagalog.

I'll be waiting fot your response ,
Thank you and More Power.

**Comment by alexkrolick** [comment]
Thanks for volunteering to help with translation! There is an active Crowdin translation project that you can join in here: https://crowdin.com/project/react/tl#

🇵🇭 😄

**Comment by ergiegonzaga** [comment]
Hi sir, I will help with the translatuon sir but please approved me as a proofreader for the tagalog translation sir.

Thank you and More Power.

**Comment by alexkrolick** [comment]
The Crowdin translation project is separate from the reactjs.org repo, so please refer to the guidelines over there.
