### ISSUE TITLE
React Native test documentation says import react native is required

### ISSUE THREAD

**Issue by Billy-** [reactjs/reactjs.org#614]
[This documentation](https://facebook.github.io/jest/docs/en/tutorial-react-native.html) shows `import 'react-native'` in all examples and at the end remarks: 
> Currently it is required to require react-native before loading the test renderer

I am not importing react-native in my tests and they seem to work fine. Is this a case of outdated documentation, or am I missing something?

Cheers :beers:

**Comment by gaearon** [comment]
I think it’s outdated and not necessary anymore. Feel free to send a PR to Jest docs to remove this
