### ISSUE TITLE
Thinking In React example loads CodePen script multiple times

### ISSUE THREAD

**Issue by danielsbird** [reactjs/reactjs.org#62]
The [Thinking in React](https://github.com/reactjs/reactjs.org/blob/master/content/docs/thinking-in-react.md) doc has three embedded CodePens and each of them load the same script: [one](https://github.com/reactjs/reactjs.org/blame/master/content/docs/thinking-in-react.md#L65), [two](https://github.com/reactjs/reactjs.org/blame/master/content/docs/thinking-in-react.md#L110), [three](https://github.com/reactjs/reactjs.org/blame/master/content/docs/thinking-in-react.md#L136). 

Loading CodePen's script once is enough to make all the pens on that page work.

**Comment by bvaughn** [comment]
Thanks for pointing this out. Looks like a great first-task for someone!

**Comment by ishankbahl** [comment]
Hey @bvaughn, made a pull request for this.
