### ISSUE TITLE
Request for a proofreader at CrowdIn

### ISSUE THREAD

**Issue by vacilagodzila** [reactjs/reactjs.org#624]
Hello, I've been contributing with spanish translations to React's Crowdin page and I was wondering if it was posible I could join the spanish proofreading team for this project. You can check my activity on the React project [here](https://crowdin.com/profile/vacilagozila/activity).

Cheers!

**Comment by alexkrolick** [comment]
Thanks for helping translate the React docs! The Crowdin translation project is separate from the reactjs.org repo, so please refer to the guidelines over there.

https://crowdin.com/project/react
