### ISSUE TITLE
Formatting Issue on Fragments Page

### ISSUE THREAD

**Issue by shahzaibkhalid** [reactjs/reactjs.org#629]
On Fragments Page, enlist in Advanced Guides in React Docs, (ref. https://reactjs.org/docs/fragments.html) there's a formatting issue as highlighted in the attached image screenshot.
<img width="1397" alt="screen shot 2018-02-20 at 9 17 07 pm" src="https://user-images.githubusercontent.com/18225515/36435608-e6327674-1683-11e8-9aeb-3492c11084ab.png">

**Comment by gaearon** [comment]
Seems intentional but I agree it looks silly in a sentence. Please send a PR with your suggestion?

**Comment by shahzaibkhalid** [comment]
Yes sure. I will send a PR.

**Comment by shahzaibkhalid** [comment]
@gaearon Please review the PR.

**Comment by harish-sethuraman** [comment]
![Screenshot 2022-01-02 at 11 45 12 AM](https://user-images.githubusercontent.com/32865581/147867806-5dc8512e-9c87-49d8-9f18-50f0b633f99e.png)
Seems like the text has been changed and the issue is no longer reproducible. Sorry for the late turnaround time.

Thanks 😄
