### ISSUE TITLE
The features scroll horizontally on mobile on landing page

### ISSUE THREAD

**Issue by akshatnitd** [reactjs/reactjs.org#66]
It should be responsive and be placed vertically on mobiles for sake of better UX.

![screenshot_20171008-200114-1](https://user-images.githubusercontent.com/12656846/31317725-c256631c-ac63-11e7-9bfc-85c194829fdf.jpg)
@gaearon Can I work on it ?

**Comment by bvaughn** [comment]
The horizontally scrolling features section is intentional.

cc @joecritch

**Comment by joecritch** [comment]
Yep, this is intentional, to prevent such a longer page on mobile. It's just an alternative design pattern to the standard stacking of elements.

(Off topic, but ideally, we have a different design pattern than stacking for the live code examples, such as sticky tabs?)

**Comment by bvaughn** [comment]
Thanks for confirming Joe! I'm going to close this issue for now as "working as designed" then 😄
