### ISSUE TITLE
Inconsistent titles for "Previous article" and "Next article"

### ISSUE THREAD

**Issue by GloverDonovan** [reactjs/reactjs.org#678]
Currently, `NavigationFooter.js` uses a nasty hack to get the title of an article based on the link URL instead of the actual title in the file. This causes titles like "CDN Links" to be parsed as `cdn links` (with another hack of `text-transform: capitalize;` as an attempt to properly capitalize it, ironically).

Screenshot 1: "CDN Links" and "Introducing JSX"
![https://i.imgur.com/TthaxC5.jpg](https://i.imgur.com/TthaxC5.jpg)

Screenshot 2: "Typechecking with PropTypes" and "Refs and the DOM"
![https://i.imgur.com/LFuFsd8.jpg](https://i.imgur.com/LFuFsd8.jpg)

**Comment by alexkrolick** [comment]
https://github.com/reactjs/reactjs.org/issues/451 😄

**Comment by GloverDonovan** [comment]
Sorry for the duplicate. Is there any reason why a hack was even used in the first place? Other parts of the website get the title just fine, so I don't see why the same logic can't be used here as well.

**Comment by alexkrolick** [comment]
Not sure, it looks like the component structure would have to change somewhat to accept more data or have the title and URL pre-computed and passed down as new props.

**Comment by raunofreiberg** [comment]
@alexkrolick duplicate of #451 which has been fixed. Can close this.

**Comment by GloverDonovan** [comment]
Thanks for fixing this! Closing.
