### ISSUE TITLE
i want to user &::after{} and @keyframes progress{} css property in css inlineStyle

### ISSUE THREAD

**Issue by nafisahmedkhan9** [reactjs/reactjs.org#699]
i Have used like below:
const style = {
    position: 'relative',
    overflow: 'hidden',
    width: '50%',
    height: '40px',
    background: '#f3f3f3',
    '&::after':{
        content: '',
        position: 'absolute',
        top: '0',
        left: '0',
        width: '100%',
        height: '100%',
        background: 'linear-gradient(90deg,#f3f3f3,#fbfbfb,#f3f3f3)',
        animation: 'progress 1s ease-in-out infinite',
    },
    '@keyframes progress':{
        '0%': {
                transform: 'translate3d(-100%, 0, 0)',
            },
        '100%': {
                transform: 'translate3d(100%, 0, 0)'
            }
    }
}

**Comment by gaearon** [comment]
This is an issue tracker for React docs. Please ask your question on a relevant support forum. Thanks!

**Comment by nafisahmedkhan9** [comment]
This is also issue. You can check. It is not working
