### ISSUE TITLE
Add minimum required Node version to create-react-app docs

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#70]
This issue was originally reported by @kyamaguchi81 via facebook/react/issues/10324

### Text of original issue

Please list [You’ll need to have Node >= 6 on your machine.]
before the description in [npm install -g create-react-app],
In [Creating a New Application] of the document https://facebook.github.io/react/docs/installation.html.

Because you want to know the required version before running the command

**Comment by dance2die** [comment]
I will work on this issue.

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by dance2die** [comment]
Thank you @bvaughn 
Struggling to set up the environment but it's part of the fun~

**Comment by bvaughn** [comment]
Please feel free to leave feedback about where you struggled in case it helps us improve the contributing docs.

**Comment by dance2die** [comment]
I will create an issue and work on it later on (regarding `node-gyp` failing to build)

**Comment by dance2die** [comment]
I was finally able to get it up and running but had a lot of trouble on Windows.

Below is the steps required to get the environment running on Windows 10.

1. Get `node-gyp` working using this [documentation](https://github.com/nodejs/node-gyp#on-windows).
2. Installed following commands globally
``` bash
yarn global add prettier
yarn global add flow-bin

```
3. `yarn check-all` doesn't work on windows. So I had to run each command separately one by one.
```bash
prettier --config .prettierrc --write "{flow-typed,plugins,src}/**/*.js"
yarn lint
yarn flow

```
`yarn check-all` failed because of the single quotes used in the prettier command.
Instead of 
`prettier --config .prettierrc --write '{flow-typed,plugins,src}/**/*.js'`
I had used double quotes around `{flow-typed,plugins,src}/**/*.js`
`prettier --config .prettierrc --write "{flow-typed,plugins,src}/**/*.js"`

**Comment by sw-yx** [comment]
i def think Windows setup is something that should be part of the docs for contributors. too easy for devs to just assume everyone has macs

**Comment by bvaughn** [comment]
> i def think Windows setup is something that should be part of the docs for contributors. too easy for devs to just assume everyone has macs

There were no such assumptions. I just have a Mac myself and I wrote the docs so...I wrote what I know. We certainly welcome contributions to the contributing docs to improve the instructions for Windows users! ❤️

If you'd be willing to commit the changes you needed to make via a PR, @dance2die, and tag me on it- I'd be happy to merge it.

**Comment by dance2die** [comment]
Thank you @bvaughn 
I will add a tag you and add the link to your comment in PR comment.

**Comment by bvaughn** [comment]
Closed via #89

**Comment by dance2die** [comment]
I've created a detailed blog entry on how to setup the environment on Windows 10.
https://www.slightedgecoder.com/2017/10/15/setting-reactjs-org-environment-open-source-contribution/

**Comment by bvaughn** [comment]
@dance2die Your write-up says:

> Now install following two NPM packages globally.
> ```
> yarn global add prettier
> yarn global add flow-bin
> ```

Why is this necessary? Both `prettier` and `flow-bin` are declared as project dependencies in `package.json` and so should be installed within the project.

Also, you should be able to update the "Problem2" section now since your PR has been merged. (Thanks!)

**Comment by dance2die** [comment]
@bvaughn 

>> Now install following two NPM packages globally.

>Why is this necessary? 

You are right. I've just tried it after globally removing `prettier` & `flow-bin`.
Both commands were not found for some reason on computer at home but works fine on different machine.

Thank you, Brian. I will update the blog~

**Comment by bvaughn** [comment]
Sweet! Ping me once it's updated and I'll tweet a link to it.

**Comment by dance2die** [comment]
@bvaughn 
Thank you, Brian.

I've updated the blog and renamed `Problem 2 -...` to **Verify that the site works**

**Comment by bvaughn** [comment]
Cool.  Thanks!
