### ISSUE TITLE
Add clarity to Tutorial step 3

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#71]
This issue was originally reported by @hori031617 via facebook/react/issues/10323

### Text of original issue:

I tried tutorial.

> 3. Delete all files in the src/ folder of the new project.

I think that good example code here.
For example `rm -f src/*`
Because, I had a misunderstanding remove src directory.

Thank you.

**Comment by tricinel** [comment]
Hmmm...if we do this, perhaps it'd be worth doing for all those steps, `rm -f src/*` for step 3, `touch src/index.css`, `touch src/index.js` and even have `npm install -g create-react-app`

**Comment by bvaughn** [comment]
Would you like to work on this task, @tricinel ?

**Comment by tricinel** [comment]
@bvaughn, love to. There is however this open PR here: https://github.com/reactjs/reactjs.org/pull/154/files. I thinking the textual addition is good, but if you think it's a good idea, then I can add the shell commands as well.

Let's do it.

**Comment by tricinel** [comment]
@bvaughn, done. Let me know what you think.
