### ISSUE TITLE
setState's undocumented/secret behavior?

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [reactjs/reactjs.org#716]
The documenentation makes clear that setState is asynchronous. But in the following example:
https://codesandbox.io/s/5op4z3myl
I click "Click here (onClick1)", it print to console like this:
```
onClick1:
before setState
value = 0
after setState
value = 0
render
```
Which is expected, but when i click "Click here (onClick2)", it print to console:
```
onClick2:
before setState (render function will be run)
value = 0
render
after setState
value = 9999 🡰 9999 right after setState
```
The setState call in setTimeout callback actually changes this.state and even more, it triggers render function **synchronously**?
Is this a bug or a secret feature? If this is a feature, it should be documented.

**Comment by gaearon** [comment]
It's an implementation detail and will change in the future.
https://stackoverflow.com/questions/48563650/does-react-keep-the-order-for-state-updates/48610973#48610973
