### ISSUE TITLE
"Updating state based on props" in "Update on Async Rendering" not clear

### ISSUE THREAD

**Issue by maulberto3** [reactjs/reactjs.org#749]
Hi. 

**Context**: According to the said [blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#updating-state-based-on-props), two code snippets are shown: _before_ (typical componentWillReceiveProps method use to update state due to new props values) and _after_ (the new React 16.3 recommended way of doing it using static getDerivedStateFromProps method).

**Problem**: the two code snippets are not directly comparable as the first one **explicitly** updates state, while the other one doesn't. Therefore, it's not 100% clear to the reader the new React 16.3 recommended way of updating state due to new props values using static getDerivedStateFromProps method.

**Suggested Solution**: To edit/complement the _after_ code snippet to **explicitly** update state due to the new props values using the componentDidUpdate method, as in the same blog post it's mentioned _"(...) Together with componentDidUpdate, this new lifecycle_ [getDerivedStateFromProps] _should cover all use cases for the legacy componentWillReceiveProps."_.

**Comment by gaearon** [comment]
`getDerivedStateFromProps` alone is sufficient in that example.

The earlier wording suggests that *some* (other) use cases for `componentWillReceiveProps` can be solved with `componentDidUpdate` instead (for example, executing side effects). It doesn’t mean you always have to use both. We’re happy to take PRs that make that wording clearer.
