### ISSUE TITLE
Document how to pass args to event handlers

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#75]
This issue was originally reported by @StokeMasterJack via facebook/react/issues/9685

A similar issue was reported by @Frazer via facebook/react/issues/8065

### Text of original issue #9685

Inside a loop it is common to want to pass a param to an event handler:

```
<button onClick={(event) => this.deleteRow(23)}>Delete Row</button>
<button onClick={this.deleteRow.bind(this,23)}>Delete Row</button>
```

That would be a good thing to add to this doc page:

https://facebook.github.io/react/docs/handling-events.html

Also, how to pass args without triggering a re-render in the child component (i.e. creating a new function every time).

**Comment by sw-yx** [comment]
will work on this

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by alexkrolick** [comment]
This topic was also been suggested for the FAQ in #29, so I included some comments in PR #43 ([diff](https://github.com/reactjs/reactjs.org/pull/43/files?short_path=e475a67#diff-e475a6732d0a9962daab40c49d5f41cb)).

It might be a good idea to merge the docs on this subject, or link from one to the other.

**Comment by Frazer** [comment]
I think @hedgerh suggestion should also be included.

<button name='23' onClick={this.deleteRow}>Delete Row</button>

deleteRow (e) {
  // do some action to (e.target.name)
}

**Comment by alexkrolick** [comment]
@Frazer added to the FAQ version of this topic: https://github.com/reactjs/reactjs.org/pull/43/commits/b2ef5ff1737b339df61d135d39bf0a9e22869775

**Comment by alexkrolick** [comment]
Closed by #81 I think

**Comment by gfortaine** [comment]
@StokeMasterJack @bvaughn There is also a third way through currying (see [How to pass variables to a function reference?](https://stackoverflow.com/a/50631170), thx @esthercuan)  👍 

```javascript
deleteRow = id => event => {
    console.log('row ${id} deleted');
 }

<button onClick={this.deleteRow(23)}>Delete Row</button>
```

**Comment by Frazer** [comment]
Thanks for the interesting example. This creates a copy of the function
every time it is rendered, so I'm guessing wouldn't be good when
performance is an issue.

**Comment by sw-yx** [comment]
how many times do we need to have this debate in react.

**Comment by bvaughn** [comment]
@Frazer The overhead of creating a function during render is rarely a performance problem. We do it all the time to add event handlers, map arrays, etc. The new hooks API also makes heavy use of this pattern for hooks like `useEffect` and `useMemo` (which require creating a function every render, even if it's not called every render).

When it _can_ be a problem is when it breaks memoization and causes a performance sensitive subtree of your application to re-render when it would otherwise not have re-rendered. This is something [the DevTools Profiler UI](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) can help you identify and fix though.
