### ISSUE TITLE
usage with portals

### ISSUE THREAD

**Issue by begoat** [reactjs/reactjs.org#757]
I read the doc related to [portals](https://reactjs.org/docs/portals.html).
I wonder in [this example](https://codepen.io/gaearon/pen/jGBWpE) why should we use portals instead of directly use redux to store the counting of the click event.
Could u explain the importance and some use cases about the Portals?
Thanks in advance. :)

**Comment by alexkrolick** [comment]
- Redux is not part of React.

- From the doc:

> A typical use case for portals is when a parent component has an overflow: hidden or z-index style, but you need the child to visually “break out” of its container. For example, dialogs, hovercards, and tooltips.
