### ISSUE TITLE
Add "Static Type Checking" section to docs

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#76]
This concern was originally raised by @barbu110 via facebook/react/issues/9684

Refer to the discussion on that thread for more backstory.

The outcome of that discussion is: Create a new guide called "Static Type Checking" that shows how to use React from Flow and TypeScript and describes main API definitions.

**Comment by ishankbahl** [comment]
Hi @bvaughn , I would like to work on this one.

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by ishankbahl** [comment]
@bvaughn 
Just saw that entire API reference has been added to the flow website 
( https://flow.org/en/docs/react/types/ ). Is this guide necessary now or not?

**Comment by bvaughn** [comment]
This issue originally covered TypeScript as well as Flow.

Looks like TypeScript also has a [brief introduction to TypeScript + React](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html) on their site.

Maybe it's okay to have a minimal section for Flow and TypeScript integration and then link to the official docs pages for more details?

**Comment by ishankbahl** [comment]
@bvaughn  made a PR for this two days back.

**Comment by bvaughn** [comment]
Closed by #189

Thanks Ishank!
