### ISSUE TITLE
[docs] confusing statement about "state"

### ISSUE THREAD

**Issue by pensierinmusica** [reactjs/reactjs.org#762]
Hi,

[The section about `state` in the docs](https://github.com/reactjs/reactjs.org/blob/master/content/docs/reference-react-component.md#state) contains a confusing statement:

> The state is user-defined, and it should be a plain JavaScript object. If you don’t use it in `render()`, it shouldn’t be in the state. For example, you can put timer IDs directly on the instance.

What does "If you don’t use it in `render()`, it shouldn’t be in the state" mean? The state shoulnd't be in the state? What is the subject of the sentence? I find the sentence confusing, possibly we can improve it.

Thx, cheers!

**Comment by gaearon** [comment]
Probably some kind of bad copy paste. Fixed in cf7329d6bdf129be0731471625b8c06abb76b3a8.

**Comment by pensierinmusica** [comment]
@gaearon awesome, thx!
