### ISSUE TITLE
[docs] add else statement to introducing jsx documentation

### ISSUE THREAD

**Issue by unluisco** [reactjs/reactjs.org#778]
Hi, I think that in the code below at:
https://github.com/reactjs/reactjs.org/blob/master/content/docs/introducing-jsx.md#jsx-is-an-expression-too
```
function getGreeting(user) {
  if (user) {
    return <h1>Hello, {formatName(user)}!</h1>;
  }
  return <h1>Hello, Stranger.</h1>;
}
```
should be a else statement, because if `user` is true, the function will return two h1 elements.

**Comment by alexkrolick** [comment]
A function can only return once. The pattern of conditionally returning is called an "early return" or "short-circuit". The rest of the function isn't executed.
