### ISSUE TITLE
Blank value also making a alert on submit

### ISSUE THREAD

**Issue by impratikprtk** [reactjs/reactjs.org#779]
In this given code, alert function is also working with a empty string or with white spaces.

//A small change

     handleSubmit(event) {
        if(this.state.value==""){
            alert("you did't enter anything");
        }
        else {
            alert('A name was submitted: ' + this.state.value);
        }

        event.preventDefault();
    }

**Comment by alexkrolick** [comment]
Looks like you're referencing https://github.com/reactjs/reactjs.org/blob/3ed5a51eeb92a2a34f615d04d2b3c5a6b74e4d51/content/docs/forms.md#controlled-components

I think keeping the examples minimal is the best way to demonstrate the APIs, even if you would add some extra validation in real life.
