### ISSUE TITLE
Better document/explain the importance of keys

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#79]
Related issues:
* facebook/react/issues/9260
* facebook/react/issues/8410 reported by @bondarewicz

cc @ajcumine who submitted a PR to the old docs repo

**Comment by ajcumine** [comment]
I'll start working on this later today

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by raunofreiberg** [comment]
Should probably close this issue and adjust the labels, seeing as it was resolved. @bvaughn

**Comment by bvaughn** [comment]
Thanks for closing.

I don't think any label changes are required. :)
