### ISSUE TITLE
Passing theme via context

### ISSUE THREAD

**Issue by carpben** [reactjs/reactjs.org#793]
In the section https://reactjs.org/docs/context.html#when-to-use-context an example for the use of context is given, in which the value of theme is passed down. 
In my opinion it raises a very relevant issue - where should constants be held, and how should they be passed in a React application. Normally a theme will not change through out the life of an application, and therefore within the application should be considered a constant. Of course there can be exceptions. So if it is a constant, should it really be passed down to children components as a prop? When we pass a prop to a component, doesn't it have a certain price - listening for changes in those props? 
If there is no significant price, then I guess it makes sense to pass our consts via context and not from the outside.

**Comment by gaearon** [comment]
If it is always a constant, you can import it from a module.

In case of theme, UIs often let you change the theme so that's why we use it as an example for context.

Hope this helps!
