### ISSUE TITLE
Netlify previewed site search bar behaviour.

### ISSUE THREAD

**Issue by johneas10** [reactjs/reactjs.org#818]
Is the search bar in the deploy-preview site supposed to search and redirect to reactjs.org? Or stay within the previewed version?

For example:
[A previewed version from netlify](https://deploy-preview-817--reactjs.netlify.com)
If you use the search bar in the link above and click on a suggested link, it will redirect you to reactjs.org. Not the documentation your PR is relevant to.

**Comment by alexkrolick** [comment]
duplicate of #803
