### ISSUE TITLE
getDerivedStateFromProps state mutability

### ISSUE THREAD

**Issue by ziel5122** [reactjs/reactjs.org#821]
In converting the lifecycle methods of a few Components from willReceiveProps to getDerivedStateFromProps a couple of questions came up that I wish would have been in the docs more explicitly:

 - Does returning anything non-null from getDerivedStateFromProps result in a render?
 - is it safe to mutate and even return prevState?

I was able to conclude that the answer to both is yes, but more clarification about what React does with what the method returns could be useful.

**Comment by gaearon** [comment]
>Does returning anything non-null from getDerivedStateFromProps result in a render?

It results in the normal React rendering flow: `shouldComponentUpdate` -> `render` -> `componentDidUpdate`. As usually, `shouldComponentUpdate` can prevent rendering.

>is it safe to mutate and even return prevState?

It is **not** safe to mutate `prevState`. The method must be pure. You can return `prevState` but that seems equivalent to returning `null`.

**Comment by ziel5122** [comment]
Thank you for clarifying!
