### ISSUE TITLE
Keep componentWillReceiveProps lifecycle method as safe

### ISSUE THREAD

**Issue by yairopro** [reactjs/reactjs.org#822]
Hi
In [your post about adding "UNSAFE_" prefix to some method names](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), you tried to cover the most common use cases to prevent using those methods.
Here's a use case I don't know how to migrate:

Let's say we have a component `<ProductView />` to display a product. It receive as props:

1. `productId` :  the product's to fetch and display. 
2. `onBuyClicked` : callback to event like when the user click on a 'buy' button.

As you can see, the `productId` prop is **critic**. By critic, I mean that the component has to reset its state, and restart to fetch data to display **a completely different product.** It has to cancel the fetching promise, and restart a new one.
While the `onBuyClicked` prop isn't critic at all. If its value change, nothing in the component's behavior has to change. It should display the same product.

That's why the `componentWillReceiveProps` method is so important. Because inside of it, it's possible to compare critic old props with new ones, and decide the component behavior, if it need to reset the state, because a critic prop was changed, or not, and then doing nothing.

**Comment by gaearon** [comment]
Can you explain how this is different from this example? I think it does what you just described.

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change

**Comment by yairopro** [comment]
You're are right, I didn't see this example.
Thanks this close the issue.

But I don't get it. This isn't logic to set props into state.

**Comment by gaearon** [comment]
I don’t understand what you’re asking then. If you could show your code I can show how to convert it.

**Comment by yairopro** [comment]
My first question was:
**How to check previous `props` without `componentWillReceiveProps(props)`?**

With [this example](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change) you gave me, you already answered it. The answer was:
**Store props into state, so you will be able to compare them inside the `static getDerivedStateFromProps(nextProps, prevState)` function**.

This answer makes me close the issue.

Now I'm asking another question:
**Why do we need to store `props` into `state`? This isn't intuitive/logic/normal.** Props are from parent component, while state is from internal behavior. This difference allowed us to develop in a really nice and clean way.

**Comment by gaearon** [comment]
You can read the discussion here: https://github.com/reactjs/rfcs/pull/40. It contains several reasons why that wouldn’t work well.

In any case you shouldn’t be using `getDerivedStateFromProps` very often. There will also be better data fetching APIs coming in the future but in order to ship them we need to migrate people away from `componentWillReceiveProps` first.

**Comment by gaearon** [comment]
We posted more specific recommendations. **In most cases you don’t need `getDerivedStateFromProps` because there are better alternatives.** Check out this post for more details:

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html
