### ISSUE TITLE
Failed To Create New Project With create-react-app

### ISSUE THREAD

**Issue by chandrabudiman** [reactjs/reactjs.org#826]
Here is the error : 
Please help. Thanks in advance

![issue1](https://user-images.githubusercontent.com/32405147/38986072-843213b8-43f5-11e8-92f0-93cfa2205208.png)

**Comment by gaearon** [comment]
The error message says the request has timed out. There's nothing we can do—it's a problem with your internet connection. Try again later or on another network.

**Comment by chandrabudiman** [comment]
@gaearon .. 
That's right. The main problem is internet speed connection. 
.
I met the problem when my download speed is around 3 - 4 mbps or below.. 
.
When my download speed is about 17 mbps, the problem is solved.. 
.
Thanks gaearon
