### ISSUE TITLE
One scenarios of `componentWillReceiveProps `

### ISSUE THREAD

**Issue by huarse** [reactjs/reactjs.org#828]
```js
class Editor extends React.Component {
    constructor(props) {
        super(props);
        // ... init state ..

        // init field
        this.formField = new Field();
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.visible && !this.props.visible) {
            this.initData(nextProps);
        }
    }

    initData(props) {
        const {editData} = props;
        // 1. setState by new editData
        // ...
        // 2. reset field values
        this.formField.setValues({
            username: editData.username,
            // ...
        });
    }
}
```

The `Field` is a form manager component, it should reinit after `Editor` component shown.

In this case, I'm not sure how to migrate to new lifecycles

**Comment by voliva** [comment]
I think your case is this one: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#side-effects-on-props-change

So you would move your init logic on `componentDidUpdate`

**Comment by huarse** [comment]
@voliva But I think it's not a good practice to `setState` in `componentDidUpdate` lifecycle, and I'am afraid it's too late to reset form field in `componentDidUpdate`

**Comment by voliva** [comment]
Yep, this new lifecycle stuff is also confusing for me...

Taking a look at #819 diagram, maybe it'd be better to use `getSnapshotBeforeUpdate(prevProps, prevState)`? In there you have access to previous state/props + current state/props (through `this`), and looks suitable as long as you don't `setState` inside.

Wait, you mentioned
>  I think it's not a good practice to `setState` in `componentDidUpdate`

In the case you need to set the state based on props, it's `getDerivedStateFromProps`, but as it's a static method and you don't have access to previous props, you have to store those props you want to watch in your state. I know, it's also confusing for me. Something similar to this example: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change

(Note that it's the first week I'm trying these new lifecycle methods, so please don't take my answer as someone with good experience....)

**Comment by huarse** [comment]
@voliva much thx for suggesting, I decision to use `UNSAFE_componentWillReceiveProps`, and replace it later.

**Comment by gaearon** [comment]
The problem is the mutation.

Instead of having `this.formField` as a field you mutate in the instance, put it into the state, and treat it as immutable. When you want to change it, make a copy (and return it from `getDerivedStateFromProps`).

It’s hard to say more without seeing the full code but that’s the basic strategy. Mutation in `componentWillReceiveProps` will not work in async mode.
