### ISSUE TITLE
Keyed fragments are not traversed in React.Children.map function

### ISSUE THREAD

**Issue by niksajanjic** [reactjs/reactjs.org#829]
https://reactjs.org/docs/react-api.html#reactchildrenmap

Per documentation keyed fragments should be traversed in React.Children.map function. In React 16.3.2 they are not for which I created this issue:

https://github.com/facebook/react/issues/12662

But they closed the issue with the explanation that it is intentional. So please update the documentation.

**Comment by danburzo** [comment]
I think the docs have been updated here: https://github.com/reactjs/reactjs.org/commit/9cd366714197809ebb5356b9cdb46c9417372b25

**Comment by niksajanjic** [comment]
Great, thanks.
