### ISSUE TITLE
[Documentation] - Explain the componentDidCatch doesn't work with SSR (React 16 renderToString)

### ISSUE THREAD

**Issue by welll** [reactjs/reactjs.org#833]
The page [Error Handling in React 16](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) doesn't mention anything about SSR (Server Side Rendering).

After hours investigating, I found this issue (https://github.com/facebook/react/issues/10442) explaining that it is a known limitation.

That being said, I would like to write one documentation block at the `Error Handling in React 16` page about this known limitation for SSR.

I'm opening this up as a place to discuss it.

**Comment by welll** [comment]
Hi folks 👋, I would like create the PR addressing it, should I do? Any thoughts?

**Comment by overlookmotel** [comment]
The main docs [here](https://reactjs.org/docs/error-boundaries.html) now explicitly state "Error boundaries do not catch errors for... Server side rendering".

So I think this issue can be closed.

**Comment by welll** [comment]
Thanks @overlookmotel , you are right, looks like the docs were updated
