### ISSUE TITLE
Improve documentation for input type=file

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#86]
This issue was originally reported by @kevinsimper via facebook/react/issues/3981

Nowhere on the react documentation is there a reference on how to handle `<input type="file"/>`

It is a speciel field that can not be serialized, and I think it deserve some kind of mention, maybe just a link to some other resource or if it is just like a normal input, just saying that.

I think it might be worth mentioning eg you can't actually programmatically set the value of a file input which is a pretty big deal- it means you're more susceptible to issues with reconciliation. You can only read. You also have to read from `node.files` which is just how those work even outside React, but still might be worth mentioning.

**Comment by vishalvrv9** [comment]
Hello is this issue still open and can I take this up? This is referenced to issue#218 (which is also open)
Sorry I am a little lost (new to open source contributions) but I think I can do this. Thanks.

**Comment by bvaughn** [comment]
This issue is all yours, @vishalvrv9! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
Resolved via #323

Thanks @vishalvrv9 !
