### ISSUE TITLE
New Context API information are not clear enough

### ISSUE THREAD

**Issue by keul** [reactjs/reactjs.org#867]
Referencing to https://reactjs.org/docs/context.html#reactcreatecontext

Spent some time with a little test of new context API and fall into this error: https://stackoverflow.com/questions/49949099/react-createcontext-point-of-defaultvalue

The fact that `defaultValue` is used only when there's no Provider must be more highlighted in documentation in my opinion.
Also: I don't get why `value` is not required as property for `Provider`s.

**Comment by alexkrolick** [comment]
Does this clear things up @keul https://github.com/reactjs/reactjs.org/pull/868?

**Comment by keul** [comment]
@alexkrolick yes, absolutely. 👍
