### ISSUE TITLE
Improve documentation for React.Children.only

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#87]
This issue was originally reported by @jimfb via facebook/react/issues/4424

Please refer to the original issue for the related discussion thread.

My understanding of the outcome is that the docs and the implementation are slightly misaligned. The docs currently say:
> Returns the only child in `children`. Throws otherwise.

This is somewhat ambiguous though with regard to how it handles an array with only 1 child element. The [actual implementation](https://github.com/facebook/react/blob/4131af3e4bf52f3a003537ec95a1655147c81270/src/isomorphic/children/onlyChild.js#L29-L35) uses a [helper method](https://github.com/facebook/react/blob/4131af3e4bf52f3a003537ec95a1655147c81270/src/isomorphic/classic/element/ReactElement.js#L373-L379) to verify that the child is an object (eg not in an array).

Let's add some clarification to the docs about exactly what this method does.

**Comment by renatoselenica** [comment]
Can I take this one? If no one else is working on it right now.

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by renatoselenica** [comment]
#118 I just submitted a pull request on it.

**Comment by bvaughn** [comment]
No problem @renatoselenica.

For future reference, if your pull request description says something like "Fixes #87" then GitHub will automatically link the 2 and close the issue when the PR is merged.
