### ISSUE TITLE
Make React available as a global object on the website

### ISSUE THREAD

**Issue by glixlur** [reactjs/reactjs.org#890]
Sometimes the user wants to experiment with the React API in console when browsing the docs. Since the website already loads React, it’d be nice to also make it a global variable.

**Comment by welll** [comment]
@glixlur , I didn't get your point. Why the `developer` will try to run React by the console?

For libraries like lodash (https://lodash.com/docs/4.17.10), it makes sense IMHO. However, for React, I can not see the benefit.

**Comment by danburzo** [comment]
I agree that there isn't much you can do with a global React variable in the console. You can try http://jscomplete.com/repl for a quick React scratchpad, that's what I use to test out various things.
