### ISSUE TITLE
Todo example scroll

### ISSUE THREAD

**Issue by damaera** [reactjs/reactjs.org#91]
it looks so weird when I add so many todo items 
![image](https://user-images.githubusercontent.com/5365957/31324620-b30ec3e2-acde-11e7-9342-3f4fd955c58a.png)

maybe it should have a scroll in the right panel

**Comment by bvaughn** [comment]
I think this is caused by a `max-height` style on the inner `<pre>` rather than the outer `<div>`. I noticed this at some point and thought, "that doesn't look right" and then forgot to look further. 😅

**Comment by satiewaltz** [comment]
I'll look into this!

**Comment by damaera** [comment]
btw, i'm working on it

**Comment by satiewaltz** [comment]
@damaera Ah sorry - I didn't see you make a note about it. Carry on 👍!

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!
