### ISSUE TITLE
Clarification needed in React documentation for props.children

### ISSUE THREAD

**Issue by mcjazzyfunky** [reactjs/reactjs.org#914]
In the official React documentation of [React.Children](https://reactjs.org/docs/react-api.html#reactchildren) you can read that ```this.props.children``` is an "opaque data structure".

It's really not easy to understand what exactly is meant by "opaque".
Could you please replace the word "opaque" with some better explanation?

Please check the following:
https://github.com/facebook/react/pull/6018/files/91223423410f107ff83a8a6ce3158c488247292f?short_path=ef51787#diff-ef51787305cfed62f6f564284762d4de

Many thanks in advance.

**Comment by estepanov** [comment]
Hey @mcjazzyfunky,

Based on the discussion in the same PR you linked to, it seems like alternative explanations have been tried but not settled on. I would love to prepare a PR for this but I am not as knowledgable as the people who already debated this topic in the PR you referenced. 

Maybe I could just elaborate on the nature of "opaque" in relation to `this.props.children` to help you out instead. Please forgive me if this is of no help or if you already knew this. 

The documentation refers to `this.props.children` as being opaque, or to put it another way: "not able to be seen through." My *assumption* is that the docs are trying to explain that just simply referencing `this.props.children` in a component will not show you to know what the children are. Like in this example we have no way to see what the children are, we just pass the node(s) directly:

```JavaScript
<ComponentExample>
    {this.props.children}
</ComponentExample>
```

That is not entirely true however as you can manipulate *some* things about the node or nodes passed as props children by using `React.Children` and `React.cloneElement` [(example)](https://learn.co/lessons/react-this-props-children).

**Comment by js-works** [comment]
The expression _'this.props.children is an "opaque data structure"'_ sounds like the type of "prop.children" was an "opaque data type" as described in https://en.wikipedia.org/wiki/Opaque_data_type.

But if you look at
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts
```props.children``` is defined as type ```ReactNode``` which itself is defined as

```type ReactNode = ReactChild | ReactFragment | ReactPortal | string | number | boolean | null | undefined```

This is far away from being an "opaque data type".
That's why that sentence in question is really very misleading.
Why not just get rid of that word "opaque" completely and tell that ```props.children``` is of a union type which implies that its concrete type can vary depending on the situation?
Union types and opaque data types are just something completely different....

**Comment by mcjazzyfunky** [comment]
The expression _'this.props.children is an "opaque data structure"'_ sounds like the type of "prop.children" was an "opaque data type" as described in https://en.wikipedia.org/wiki/Opaque_data_type.

But if you look at
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts
```props.children``` is defined as type ```ReactNode``` which itself is defined as

```type ReactNode = ReactChild | ReactFragment | ReactPortal | string | number | boolean | null | undefined```

This is far away from being an "opaque data type".
That's why that sentence in question is really very misleading.
Why not just get rid of that word "opaque" completely and tell that ```props.children``` is of a union type which implies that its concrete type can vary depending on the situation?
Union types and opaque data types are just something completely different....
