### ISSUE TITLE
Load dynamic translation with componentWillMount() lifecycle 

### ISSUE THREAD

**Issue by slim-hmidi** [reactjs/reactjs.org#922]
I'm using the lifecycle `componentWillMount()` to load dynamic translations using `i18next`:
```
class App extends Component {
  constructor(props) {
    super(props)
  }
  componentWillMount(){
    if (!(this.props.i18n.hasResourceBundle('fr', 'category')
    && this.props.i18n.hasResourceBundle('en', 'category'))
    && this.props.categories.length > 0) {
      const categories = {
        fr: {},
        en: {},
      };
      this.props.categories.forEach((result) => {
        categories.fr = Object.assign(
          categories.fr,
          { [result.id]: result.type.fr },
        );
        categories.en = Object.assign(
          categories.en,
          { [result.id]: result.type.en },
        );
      });
      this.props.i18n.addResourceBundle('fr', 'category', categories.fr);
      this.props.i18n.addResourceBundle('en', 'category', categories.en);
  }

}
```

When I update the react from `v16.2.0` to `16.4.0` I tried to use `componentDidMount()` instead of `componentWillMount()` but the translations of field `category` did not be loaded initially and the `TexField` which contains the category was empty. When I press the button and change the language the `TextField` contained the category will be filled by the value.
I put the code in the `constructor` , then I got the translation when the data where loaded initially without changing the language.
Does it a good practice to put the code of `translation` in the constructor?

**Comment by gaearon** [comment]
If translations are loaded asynchronously they wouldn't be ready by the time first render happens anyway.

If they are loaded synchronously, yes, either constructor or a helper you can call from `render` method would work.
