### ISSUE TITLE
Request to source code of conference live demo

### ISSUE THREAD

**Issue by nairihar** [reactjs/reactjs.org#935]
HI, Is there any source from this talk?

https://github.com/reactjs/reactjs.org/blob/master/content/blog/2018-03-01-sneak-peek-beyond-react-16.md

**Comment by gaearon** [comment]
Not yet because it depends on some internal builds with patches over bugs. I think we can release something when it’s more ready though.

**Comment by nairihar** [comment]
Thanks

**Comment by sw-yx** [comment]
@nairihar meanwhile check https://github.com/sw-yx/async-react-future for community code along :)

**Comment by nairihar** [comment]
@sw-yx Thanks a lot :)
