### ISSUE TITLE
[New Use Case] getDerivedStateFromProps

### ISSUE THREAD

**Issue by franklixuefei** [reactjs/reactjs.org#969]
I recently discovered a new use case for `getDerivedStateFromProps`.

Consider the following code snippet

```jsx
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      values: [],
      prevValue: ''
    };
  }

  static getDerivedStateFromProps(nextProps, prevState) {
    if (nextProps.value !== prevState.prevValue) {
      const values = uniq([...prevState.values, nextProps.value]);
      return {
        values,
        prevValue: nextProps.value
      };
    }
    return null;
  }

  render() {
    return (
      <ControlledComponent // this is a third party component with controlled props.
        values={this.state.values}
        onClick={(someValue) => {
          const values = getValuesFromSomeValue(someValue); // some function that returns an array of `value` by `someValue`
          this.setState({values});
        }}
        onValuesChange={(values) => {
          values = uniq([...values, this.props.value]);
          this.setState({values});
        }} />
    );
  }
}
```

In this case, I don't see how I can get rid of `getDerivedStateFromProps` easily without extra rendering. This is primarily an example of "constructing" the state from two places -
1. parent props
2. child component

Also, I could make `values` controlled prop by exposing `values`, but in my case, it doesn't really make sense to expose them, because `values` is computed based on `value`, and the outside world should not have any knowledge on that. I only want to expose `value`.

Any suggestions on how I can get rid of `getDerivedStateFromProps` here, or this is just another use case of this method?

**Comment by gaearon** [comment]
Can you describe in more practical terms what you're trying to do? i.e. what is that component, what are those values, why do you combine them, etc.

**Comment by franklixuefei** [comment]
@gaearon Sure.

Originally, my scenario is that I have a side menu component, where I have a list of menu items. Each item can either be a simple menu item, or a group containing a list of child menu items (we will call them **menu item groups** from now on), so on so forth.

```
----------------------------
Menu Item 1
----------------------------
Menu Item Group 1 ^
----------------------------
Menu Item 3
----------------------------
Menu Item 4
----------------------------
Menu Item Group 2  v
----------------------------
    Menu Item Group 3 v
----------------------------
        Menu Item 5
----------------------------
```

In this component, I keep a local state to remember which menu item groups are expanded. `expand: number[]`. Whenever I click on a menu item group, I will first extract its id, then merge it with the `expand` array. So as you can see, I will call `setState` here on the merged `expand` array. (**first source of truth**).

```ts
interface ISideMenuListState {
  // holds a list of menu item ids indicating they are expanded.
  expand: number[];
  prevSelectedItem: IMenuItem | null; // for comparing the current one with the previous in `getDerivedStateFromProps`
}
```

And then, imagine that I have a set of nested menu items like this:

```
----------------------------
Menu Item Group 1  v
----------------------------
    Menu Item Group 2 v
----------------------------
        Menu Item 3
----------------------------
```
And I hooked up the **react router** so that when I specify the url that corresponding to the content of `Menu Item 3`, then all the "ancestors" of `Menu Item 3` will be expanded. (Imagine that initially, `Menu Item Group 1` is collapsed, like this: `Menu Item Group 1 ^`).

So, the way it works is:
1. When the url is submitted, the component will receive a new prop representing the `MenuItem` related to the content that corresponds to the url.
2. In `getDerivedStateFromProps()`, I will extract the id of that item, and walk up the ancestor path to get a list of ancestor ids of that item. (**second source of truth**)
3. I will merge this list with `expand` and return the new state.

```ts
export interface ISideMenuListProps {
  onItemClick: (item: IMenuItem) => void;
  readonly menuItems: Array<IMenuItem | IMenuItemGroup>;
  selectedItem?: IMenuItem;
}
```

```jsx
  static getDerivedStateFromProps(
    nextProps: ISideMenuListProps & WithStyles<classList>,
    prevState: ISideMenuListState
  ): Partial<ISideMenuListState> | null {
    if ((nextProps.selectedItem && nextProps.selectedItem.id) !==
        (prevState.prevSelectedItem && prevState.prevSelectedItem.id)) {
      const ancestorIds = SideMenuList.getAncestorIds(nextProps.selectedItem); // gets the ancestor ids of the passed item
      return {
        expand: ancestorIds,
        prevSelectedItem: nextProps.selectedItem
      };
    }
    return null;
  }
```

As you can see, I have two source of truths, which is not ideal. I wonder if you have any suggestions on how to optimize away the second source of truth? I think probably this can be another case of optimization in that blog...

Thanks!

**Comment by gaearon** [comment]
What should happen when you navigate back and forward between pages? Do you want to preserve the expansion state, and always *expand more* items? Do you ever want to collapse items on navigating "Back"? What if some items were already toggled, do you want to touch those?

I think that if you really want every navigation to "accumulate" the expansion state (as you do with `union`) then this is a reasonable use case for `getDerivedStateFromProps`.
