### ISSUE TITLE
Remove hard-coded HTML/CSS from index.md

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#97]
(This is a tech debt clean-up issue from the legacy Jekyll docs site.)

The [`docs/index.md`](https://github.com/reactjs/reactjs.org/blob/master/content/index.md) file currently contains a lot of HTML- complete with attributes and class names. This file should contain only (or at least predominantly) markdown syntax. We should remove as much of the HTML as possible and instead convert it to regular markdown.

There are 2 things to be aware of while cleaning up this markdown file:
1. The layout of the home page uses horizontal scrolling for the top section. This is not achievable with regular markdown.
1. The bottom sections each have a live code example that ties into the `home.js` template (see below).

The [`templates/home.js`](https://github.com/reactjs/reactjs.org/blob/master/src/templates/home.js) template makes this situation a little more complex, since it currently uses some of the inline HTML elements from `index.md` to mount examples (eg `<div id="helloExample"></div>`). It might be acceptable to leave _only_ these mount nodes in the file and remove all else.

It might also be nice to break index down into a couple of files, although this would also require:
1. Moving `home.js` from [templates](https://github.com/reactjs/reactjs.org/tree/master/src/templates) to [pages](https://github.com/reactjs/reactjs.org/tree/master/src/pages) and creating a graphql query to load these files
2. Updating [`gatsby-node.js`](https://github.com/reactjs/reactjs.org/blob/master/gatsby-node.js) to ignore the files (so they aren't turned into standalone pages. (We have [a similar check](https://github.com/reactjs/reactjs.org/blob/89cf6d20d6dce1db6f3a273795e3f1041d37c55c/gatsby-node.js#L74-L77) for the error decoder page.)

Making Home a page instead of a template would also provide a nice solution for the horizontal scrolling problem mentioned above.

Also, `mountCodeExample` currently does some [really hacky stuff](https://github.com/reactjs/reactjs.org/blob/42372b24473913fef65146b2ec70e0817076e25f/src/utils/mountCodeExample.js#L16-L28). Making Home a page instead of a template could help us move some of that hackiness out and simplify things like showing a placeholder while pre-loading Babel (#2).

Please feel free to chat with @bvaughn if you decide to pick up this issue.

**Comment by yangshun** [comment]
@bvaughn I would like to take up this task

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
Note that PR #100 may have some impact on your work-in-progress @yangshun. Just an FYI.

I also updated the description to call out the hackiness in `mountCodeExample` more explicitly.

**Comment by yangshun** [comment]
Got it. Thanks for the heads up!

**Comment by bvaughn** [comment]
This issue has been resolved via #150 and some follow up commits. Thanks again to @yangshun for your help!

**Comment by yangshun** [comment]
You're welcome! Sorry this took so long too 😓 Thanks for the follow up work (which made up the bulk of the PR actually 😂 )

**Comment by bvaughn** [comment]
No problem 😁 I'm pretty happy with the resulting solution so yay for us
