### ISSUE TITLE
Clarify Node version required for development

### ISSUE THREAD

**Issue by raunofreiberg** [reactjs/reactjs.org#971]
Currently the docs state:

`Node: install version 8.4 or greater`

I went ahead and naively ran `yarn dev` while using Node 10.3 (also tried with version >= 9), figuring that it should work as the docs stated. I only got it working with 8.4.0 so far after testing a few versions of Node.

Is this a fault on my end or are the docs invalid in assuming that it should work with newer versions?

Stack of the errors being produced with newer version:
![image](https://user-images.githubusercontent.com/23662329/41346821-7a57a68c-6f10-11e8-954d-a4848ca3b16a.png)

**Comment by alexkrolick** [comment]
Yeah that's what broke CI recently - we should reflect that in package.json
