### ISSUE TITLE
Question: How can I better use or get around using getDerivedStateFromProps for this situation?

### ISSUE THREAD

**Issue by bsara** [reactjs/reactjs.org#980]
I was reading [the docs on `getDerivedStateFromProps`](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) and it suggested that `If your use case falls outside of these patterns, please share it with us on GitHub...`. So, here I am.

Here is my situation:

I have a `Card` component that is collapsible. It is a a `CollapseIcon` which, when clicked, toggles the `collapsed` state of `Card`. However, I need to allow other components that may use `Card` to specify `collapsed` as a prop if the want to (but it's not a required prop). The first code snippet below shows a basic version of what `Card` would look like:

```jsx
class Card extends Component {
  static propTypes = {
    collapsed: PropTypes.bool,
    ...
  };

  state = {
    collapsed: this.props.collapsed
  };

  render() {
    <div>
      <CollapseIcon onClick={() => this.setState({ collapsed: !this.state.collapsed })} />
      <Collapsible collapsed={this.state.collapsed}>
        ...
      </Collapsible>
    </div>
  }
}
```

The only way that I can come up with to ensure that both the prop and the state values can be honored *(without requiring a parent component to completely control any owned `Card` components via a `onToggleCollapsed` callback, I want to avoid this if I can)* is to do the following:

```jsx
class Card extends Component {
  static propTypes = {
    collapsed: PropTypes.bool,
    ...
  };
  
  static getDerivedStateFromProps(props, state) {
    const derivedState = {
      deriveCollapsedFromProps: true
    };
    
    if (props.hasOwnProperty('collapsed') && state.deriveCollapsedFromProps) {
      derivedState.collapsed = props.collapsed;
    }
    
    return derivedState;
  }

  state = {
    collapsed: this.props.collapsed,
    
    deriveCollapsedFromProps: true
  };

  render() {
    <div>
      <CollapseIcon onClick={() => this.setState({ collapsed: !this.state.collapsed, deriveCollapsedFromProps: false })} />
      <Collapsible collapsed={this.state.collapsed}>
        ...
      </Collapsible>
    </div>
  }
}
```

However, I can forsee some instances where this still wouldn't work properly, plus it seems a bit overkill for what I'm trying to accomplish.

**Any suggestions or thoughts on how I can better use `getDerivedStateFromProps` or get around using it entirely given the restraints that I've explained above?**

Thanks.

**Comment by gaearon** [comment]
I think the desire to *both* let people supply it via props *and* allow it to be uncontrolled inevitably leads to a conflict: if two values disagree, which one wins? No matter which answer your pick, it can be counter-intuitive to your users.

>it suggested that If your use case falls outside of these patterns, please share it with us on GitHub...

To be fair, your question seems to be about the exact patterns discussed in that blog post, to which we provided two recommended solutions:

* either [make your component fully controlled](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-controlled-component) (taking `collapsed` as a prop only)
* or make it [fully uncontrolled](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key), using a `key` to reset the internal state if necessary

In your case using a key to reset the state would probably produce unintended side effects ("collapsing" a card probably doesn't imply losing its internal state in most UIs) so making it controlled would probably be best. This means you'd always respect the props, and the component using the card would have to always provide it with `collapsed` and `onCollapsedChange` props.

If the card is used in many places, it might make sense to fist write a controlled version, and then also provide a thin wrapper over it (e.g. `<Card.Uncontrolled>`) that just renders `Card` and keeps a boolean internal state to avoid boilerplate in other components. Then, whenever you realize you actually *need* to control it, you swap out `<Card.Uncontrolled>` for `<Card>`.

Hope this helps!

**Comment by bsara** [comment]
@gaearon thank you so much for the response...and for the great speed of your response too. This is all very helpful information, I particularly love the idea of having both a controlled and uncontrolled version when the uncontrolled behavior is needed. It's quite a simple and elegant solution really. Thanks again for the help.
