### ISSUE TITLE
Context docs FUD

### ISSUE THREAD

**Issue by callumlocke** [reactjs/reactjs.org#982]
I want to use Context API, but I'm put off by this:

> **Note**
> Don’t use context just to avoid passing props a few levels down. Stick to cases where the same data needs to be accessed in many components at multiple levels.

It just tells me not to use it, without saying why. And it doesn't tell me how to decide what counts as "many components" or "multiple levels". It's very off-putting.

Can it be rephrased to clarify the potential downsides I might run into? (Is the issue just that Context brings its own complexity, which should be weighed up against the complexity of prop-plumbing, or are there other downsides?)

**Comment by gaearon** [comment]
Going to close this -- if you have other ideas please send a PR!
