### ISSUE TITLE
Render props examples with height: 100% doesn't work well in some of the use cases

### ISSUE THREAD

**Issue by juanmaguitar** [reactjs/reactjs.org#986]
In the [Render props](https://reactjs.org/docs/render-props.html) page some of the components in the examples (`Mouse` fro example) use a `height: 100%` that is not working for the children components that have set a `position: "absolute`

Changing this value from `height: 100%` to `height: 100vh` would solve the issue

Example in action: https://codesandbox.io/s/00yr3lvy8p

**Comment by threepointone** [comment]
fixed by https://github.com/reactjs/reactjs.org/pull/987
